'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_ProjectListTree

    '''<summary>
    '''LTprojectName_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTprojectName_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTprojectCompletion_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTprojectCompletion_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTprojectStatus_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTprojectStatus_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTprojectDeadline_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTprojectDeadline_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''THroles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents THroles As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''LTprojectRoles_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTprojectRoles_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''THmyCompleteness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents THmyCompleteness As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''LTmyCompletion_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmyCompletion_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBprojectActions_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBprojectActions_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPTcontainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTcontainer As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''TDfooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TDfooter As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SPNcommands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPNcommands As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LNBtoggleProjectStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBtoggleProjectStatus As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBtoggleProjectRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBtoggleProjectRoles As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBtoggleProjectCommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBtoggleProjectCommunity As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''DVpagerBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpagerBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTpageBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTpageBottom As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''PGgridBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PGgridBottom As Global.Comunita_OnLine.UC_PagerControl

    '''<summary>
    '''LTstatusContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTstatusContent As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTstatuslight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTstatuslight As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassManager As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassResource As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassByDeadline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassByDeadline As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassByCommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassByCommunity As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTitemCssClassCommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTitemCssClassCommunity As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTitemCssClassDeadline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTitemCssClassDeadline As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LThasdeadline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LThasdeadline As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTnodeadline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTnodeadline As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassContinueTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassContinueTop As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassContinueBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassContinueBottom As Global.System.Web.UI.WebControls.Literal
End Class
