'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_TaskInfo

    '''<summary>
    '''MLVtaskInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVtaskInfo As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWsettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWsettings As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LItaskGeneralSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LItaskGeneralSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTtaskGeneralSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtaskGeneralSettings As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LItaskAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LItaskAttachments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTtaskAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtaskAttachments As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBactivityStartDate_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityStartDate_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivityStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityStartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivityEndDate_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityEndDate_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivityEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityEndDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivityName_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityName_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivityDuration_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityDuration_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivityDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityDuration As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DVdeadline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdeadline As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBactivityDeadLine_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityDeadLine_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivityDeadLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityDeadLine As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DVdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBactivityDescription_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityDescription_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivityDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DVnote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVnote As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBactivityNote_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityNote_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivityNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityNote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DVmanagerComplation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVmanagerComplation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBactivityCompletion_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityCompletion_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivityCompletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityCompletion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DVstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVstatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBactivityCompletionStatus_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityCompletionStatus_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivityCompletionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityCompletionStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DVmyCompletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVmyCompletion As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBmyActivityCompletion_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBmyActivityCompletion_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBmyActivityCompletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBmyActivityCompletion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TXBmyCompletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBmyCompletion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DVassignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVassignments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBactivityCompletionResources_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivityCompletionResources_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LTactivityResourceAssigned_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTactivityResourceAssigned_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTactivityResourceCompletion_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTactivityResourceCompletion_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''THcompletionAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents THcompletionAction As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''RPTresourcesCompletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTresourcesCompletion As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''VIWmessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWmessage As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LTmessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmessage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BTNconfirmTaskCompletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNconfirmTaskCompletion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNsaveTaskDialogSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNsaveTaskDialogSettings As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''HYPcloseTaskDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPcloseTaskDialog As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LTcssClassManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassManager As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassResource As Global.System.Web.UI.WebControls.Literal
End Class
