'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_SkinEdit

    '''<summary>
    '''LBskinName_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBskinName_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TXBskinName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBskinName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LNBsaveSkinName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBsaveSkinName As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LBskinId_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBskinId_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LTskinId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTskinId As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TBSSkinEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBSSkinEdit As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''MLVskinEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVskinEdit As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWcss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWcss As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''CTRLcss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLcss As Global.Comunita_OnLine.UC_SkinCSS

    '''<summary>
    '''VIWimages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWimages As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''CTRLimages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLimages As Global.Comunita_OnLine.UC_SkinImages

    '''<summary>
    '''VIWmainLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWmainLogo As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''CTRLmainLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmainLogo As Global.Comunita_OnLine.UC_SkinHeadLogo

    '''<summary>
    '''VIWfootLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWfootLogo As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''CTRLfootLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLfootLogo As Global.Comunita_OnLine.UC_SkinFootLogo

    '''<summary>
    '''VIWfootText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWfootText As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''CTRLfootText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLfootText As Global.Comunita_OnLine.UC_SkinFootText

    '''<summary>
    '''VIWassociation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWassociation As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''CTRLassociation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLassociation As Global.Comunita_OnLine.UC_SkinAssociation
End Class
