'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_EditUrlItemsHeader

    '''<summary>
    '''LTdefaultWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTdefaultWindow As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcloseScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcloseScripts As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTplaceholderdScript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTplaceholderdScript As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CTRLscripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLscripts As Global.Comunita_OnLine.UC_OpenDialogHeaderScripts

    '''<summary>
    '''LTscript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTscript As Global.System.Web.UI.WebControls.Literal
End Class
