'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_SelectUsers

    '''<summary>
    '''MLVusers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVusers As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWsessionTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWsessionTimeout As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBsessionTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsessionTimeout As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VIWlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWlist As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''DVselectors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVselectors As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DVdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MLVfilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVfilters As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWemptyFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWemptyFilters As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''VIWportalFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWportalFilters As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBprofileOrganizationFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBprofileOrganizationFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLorganizations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLorganizations As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBprofileAuthenticationTypeFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBprofileAuthenticationTypeFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLauthenticationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLauthenticationType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBsearchProfileByFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsearchProfileByFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLsearchProfileBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLsearchProfileBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXBprofileValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBprofileValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBprofileStatusFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBprofileStatusFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLprofileStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLprofileStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBprofileTypeFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBprofileTypeFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLprofileType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLprofileType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBprofileAgencyFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBprofileAgencyFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLprofileAgencies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLprofileAgencies As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''VIWcommunityFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWcommunityFilters As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBsearchSubscriptionsByFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsearchSubscriptionsByFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLsearchSubscriptionsBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLsearchSubscriptionsBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXBsubscriptionValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBsubscriptionValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBsubscriptionStatusFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsubscriptionStatusFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLsubscriptionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLsubscriptionStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBcommunityRoleFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcommunityRoleFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLcommunityRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLcommunityRole As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DVcommunityProfileFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVcommunityProfileFilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBcommunityProfileTypeFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcommunityProfileTypeFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLcommunityProfileType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLcommunityProfileType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DVagencyProfileFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVagencyProfileFilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBcommunityAgencyFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcommunityAgencyFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLcommunityAgencies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLcommunityAgencies As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DVletters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVletters As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CTRLalphabetSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLalphabetSelector As Global.Comunita_OnLine.UC_AlphabetSelector

    '''<summary>
    '''BTNapplyFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNapplyFilters As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DVpagerTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpagerTop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DVpageSizeTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpageSizeTop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBrecordsForPageTop_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrecordsForPageTop_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLpageSizeTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLpageSizeTop As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RPTprofiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTprofiles As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''DVpageSizeBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpageSizeBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBrecordsForPage_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrecordsForPage_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLpageSizeBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLpageSizeBottom As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PGgrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PGgrid As Global.Comunita_OnLine.UC_PagerControl

    '''<summary>
    '''DVcommands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVcommands As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BTNreviewSelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNreviewSelection As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNcancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNcancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNselect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNselect As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DVpreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpreview As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBpreviewDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBpreviewDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLmessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmessages As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''TXBsearchInPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBsearchInPreview As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNapplyPreviewFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNapplyPreviewFilters As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CTRLpreviewAlphabetSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLpreviewAlphabetSelector As Global.Comunita_OnLine.UC_AlphabetSelector

    '''<summary>
    '''RPTpreviewItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTpreviewItems As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''DVpagerPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpagerPreview As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PGgridPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PGgridPreview As Global.Comunita_OnLine.UC_PagerControl

    '''<summary>
    '''BTNcloseUserSelectionPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNcloseUserSelectionPreview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNconfirmSelectionEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNconfirmSelectionEdit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNconfirmSelectionEditAndInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNconfirmSelectionEditAndInsert As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''VIWnoPermission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWnoPermission As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBnoPermission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBnoPermission As Global.System.Web.UI.WebControls.Label
End Class
