'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_FolderSelector

    '''<summary>
    '''HDNselectedIdFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDNselectedIdFolder As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''BTNupdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNupdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LBselectFolderPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBselectFolderPath As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPTchildren control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTchildren As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''LTitemCssClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTitemCssClass As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTselectedItemCssClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTselectedItemCssClass As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTunselectableItemCssClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTunselectableItemCssClass As Global.System.Web.UI.WebControls.Literal
End Class
