'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources.RadImageEditor
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Dialogs
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.RadImageEditor.Dialogs", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color.
        '''</summary>
        Friend Shared ReadOnly Property AddText_Color() As String
            Get
                Return ResourceManager.GetString("AddText_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The color of the text to add.
        '''</summary>
        Friend Shared ReadOnly Property AddText_ColorToolTip() As String
            Get
                Return ResourceManager.GetString("AddText_ColorToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Current Color is {0}).
        '''</summary>
        Friend Shared ReadOnly Property AddText_CurrentColorText() As String
            Get
                Return ResourceManager.GetString("AddText_CurrentColorText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Font Family.
        '''</summary>
        Friend Shared ReadOnly Property AddText_FontFamily() As String
            Get
                Return ResourceManager.GetString("AddText_FontFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The font family of the text to add.
        '''</summary>
        Friend Shared ReadOnly Property AddText_FontFamilyToolTip() As String
            Get
                Return ResourceManager.GetString("AddText_FontFamilyToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Font Size.
        '''</summary>
        Friend Shared ReadOnly Property AddText_FontSize() As String
            Get
                Return ResourceManager.GetString("AddText_FontSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The size of the text to add.
        '''</summary>
        Friend Shared ReadOnly Property AddText_FontSizeToolTip() As String
            Get
                Return ResourceManager.GetString("AddText_FontSizeToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pick Color.
        '''</summary>
        Friend Shared ReadOnly Property AddText_PickColorToolTip() As String
            Get
                Return ResourceManager.GetString("AddText_PickColorToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your text here....
        '''</summary>
        Friend Shared ReadOnly Property AddText_SampleText() As String
            Get
                Return ResourceManager.GetString("AddText_SampleText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert Text.
        '''</summary>
        Friend Shared ReadOnly Property AddText_Title() As String
            Get
                Return ResourceManager.GetString("AddText_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply.
        '''</summary>
        Friend Shared ReadOnly Property BrightnessContrast_ApplyBtn_Text() As String
            Get
                Return ResourceManager.GetString("BrightnessContrast_ApplyBtn_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply the selected brightness/contrast levels to the image.
        '''</summary>
        Friend Shared ReadOnly Property BrightnessContrast_ApplyBtn_ToolTip() As String
            Get
                Return ResourceManager.GetString("BrightnessContrast_ApplyBtn_ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset.
        '''</summary>
        Friend Shared ReadOnly Property BrightnessContrast_ResetBtn_Text() As String
            Get
                Return ResourceManager.GetString("BrightnessContrast_ResetBtn_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset the changes so far.
        '''</summary>
        Friend Shared ReadOnly Property BrightnessContrast_ResetBtn_ToolTip() As String
            Get
                Return ResourceManager.GetString("BrightnessContrast_ResetBtn_ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brightness/Contrast.
        '''</summary>
        Friend Shared ReadOnly Property BrightnessContrast_Title() As String
            Get
                Return ResourceManager.GetString("BrightnessContrast_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a value between -100 and 100.
        '''</summary>
        Friend Shared ReadOnly Property Brightness_TxtBoxToolTip() As String
            Get
                Return ResourceManager.GetString("Brightness_TxtBoxToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actual Size.
        '''</summary>
        Friend Shared ReadOnly Property Common_ActualSize() As String
            Get
                Return ResourceManager.GetString("Common_ActualSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply.
        '''</summary>
        Friend Shared ReadOnly Property Common_Apply() As String
            Get
                Return ResourceManager.GetString("Common_Apply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge the drawn figure with the main canvas.
        '''</summary>
        Friend Shared ReadOnly Property Common_AppyDrawToolTip() As String
            Get
                Return ResourceManager.GetString("Common_AppyDrawToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Best Fit.
        '''</summary>
        Friend Shared ReadOnly Property Common_BestFit() As String
            Get
                Return ResourceManager.GetString("Common_BestFit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property Common_Cancel() As String
            Get
                Return ResourceManager.GetString("Common_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Constrain Proportions?.
        '''</summary>
        Friend Shared ReadOnly Property Common_ConstrainProportions() As String
            Get
                Return ResourceManager.GetString("Common_ConstrainProportions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Decrease.
        '''</summary>
        Friend Shared ReadOnly Property Common_Decrease() As String
            Get
                Return ResourceManager.GetString("Common_Decrease", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A file with a name same as the target already exists!.
        '''</summary>
        Friend Shared ReadOnly Property Common_FileExists() As String
            Get
                Return ResourceManager.GetString("Common_FileExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Height.
        '''</summary>
        Friend Shared ReadOnly Property Common_Height() As String
            Get
                Return ResourceManager.GetString("Common_Height", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Increase.
        '''</summary>
        Friend Shared ReadOnly Property Common_Increase() As String
            Get
                Return ResourceManager.GetString("Common_Increase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert.
        '''</summary>
        Friend Shared ReadOnly Property Common_Insert() As String
            Get
                Return ResourceManager.GetString("Common_Insert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Left.
        '''</summary>
        Friend Shared ReadOnly Property Common_Left() As String
            Get
                Return ResourceManager.GetString("Common_Left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot write to the target folder!.
        '''</summary>
        Friend Shared ReadOnly Property Common_MessageCannotWriteToFolder() As String
            Get
                Return ResourceManager.GetString("Common_MessageCannotWriteToFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected file could not be deleted because the application did not have enough permissions. Please, contact the administrator..
        '''</summary>
        Friend Shared ReadOnly Property Common_NoPermissionsToDeleteFile() As String
            Get
                Return ResourceManager.GetString("Common_NoPermissionsToDeleteFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property Common_OK() As String
            Get
                Return ResourceManager.GetString("Common_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overwrite if file exists?.
        '''</summary>
        Friend Shared ReadOnly Property Common_OverwriteExisting() As String
            Get
                Return ResourceManager.GetString("Common_OverwriteExisting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Position.
        '''</summary>
        Friend Shared ReadOnly Property Common_Position() As String
            Get
                Return ResourceManager.GetString("Common_Position", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set.
        '''</summary>
        Friend Shared ReadOnly Property Common_Set() As String
            Get
                Return ResourceManager.GetString("Common_Set", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drag to change the value.
        '''</summary>
        Friend Shared ReadOnly Property Common_SliderDrag() As String
            Get
                Return ResourceManager.GetString("Common_SliderDrag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Swap Width and Height.
        '''</summary>
        Friend Shared ReadOnly Property Common_SwapWidthHeight() As String
            Get
                Return ResourceManager.GetString("Common_SwapWidthHeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Top.
        '''</summary>
        Friend Shared ReadOnly Property Common_Top() As String
            Get
                Return ResourceManager.GetString("Common_Top", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transform.
        '''</summary>
        Friend Shared ReadOnly Property Common_Transform() As String
            Get
                Return ResourceManager.GetString("Common_Transform", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to URL.
        '''</summary>
        Friend Shared ReadOnly Property Common_Url() As String
            Get
                Return ResourceManager.GetString("Common_Url", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Width.
        '''</summary>
        Friend Shared ReadOnly Property Common_Width() As String
            Get
                Return ResourceManager.GetString("Common_Width", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to X.
        '''</summary>
        Friend Shared ReadOnly Property Common_X() As String
            Get
                Return ResourceManager.GetString("Common_X", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Y.
        '''</summary>
        Friend Shared ReadOnly Property Common_Y() As String
            Get
                Return ResourceManager.GetString("Common_Y", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a value between -127 and 127.
        '''</summary>
        Friend Shared ReadOnly Property Contrast_TxtBoxToolTip() As String
            Get
                Return ResourceManager.GetString("Contrast_TxtBoxToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aspect Ratio.
        '''</summary>
        Friend Shared ReadOnly Property Crop_AspectRatio() As String
            Get
                Return ResourceManager.GetString("Crop_AspectRatio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Aspect Ratio.
        '''</summary>
        Friend Shared ReadOnly Property Crop_AspectRatioToolTip() As String
            Get
                Return ResourceManager.GetString("Crop_AspectRatioToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crop.
        '''</summary>
        Friend Shared ReadOnly Property Crop_Button() As String
            Get
                Return ResourceManager.GetString("Crop_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crop Image.
        '''</summary>
        Friend Shared ReadOnly Property Crop_Title() As String
            Get
                Return ResourceManager.GetString("Crop_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color:.
        '''</summary>
        Friend Shared ReadOnly Property DrawCircle_Color() As String
            Get
                Return ResourceManager.GetString("DrawCircle_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Current color is {0}).
        '''</summary>
        Friend Shared ReadOnly Property DrawCircle_CurrentColorText() As String
            Get
                Return ResourceManager.GetString("DrawCircle_CurrentColorText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fill Color:.
        '''</summary>
        Friend Shared ReadOnly Property DrawCircle_FillColor() As String
            Get
                Return ResourceManager.GetString("DrawCircle_FillColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line size:.
        '''</summary>
        Friend Shared ReadOnly Property DrawCircle_LineSize() As String
            Get
                Return ResourceManager.GetString("DrawCircle_LineSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set line size.
        '''</summary>
        Friend Shared ReadOnly Property DrawCircle_LineSizeToolTip() As String
            Get
                Return ResourceManager.GetString("DrawCircle_LineSizeToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PickColor.
        '''</summary>
        Friend Shared ReadOnly Property DrawCircle_PickColor() As String
            Get
                Return ResourceManager.GetString("DrawCircle_PickColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pick Fill Color.
        '''</summary>
        Friend Shared ReadOnly Property DrawCircle_PickFillColor() As String
            Get
                Return ResourceManager.GetString("DrawCircle_PickFillColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Draw Circle.
        '''</summary>
        Friend Shared ReadOnly Property DrawCircle_Title() As String
            Get
                Return ResourceManager.GetString("DrawCircle_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color:.
        '''</summary>
        Friend Shared ReadOnly Property DrawRectangle_Color() As String
            Get
                Return ResourceManager.GetString("DrawRectangle_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Current color is {0}).
        '''</summary>
        Friend Shared ReadOnly Property DrawRectangle_CurrentColorText() As String
            Get
                Return ResourceManager.GetString("DrawRectangle_CurrentColorText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fill Color:.
        '''</summary>
        Friend Shared ReadOnly Property DrawRectangle_FillColor() As String
            Get
                Return ResourceManager.GetString("DrawRectangle_FillColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line size:.
        '''</summary>
        Friend Shared ReadOnly Property DrawRectangle_LineSize() As String
            Get
                Return ResourceManager.GetString("DrawRectangle_LineSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set line size.
        '''</summary>
        Friend Shared ReadOnly Property DrawRectangle_LineSizeToolTip() As String
            Get
                Return ResourceManager.GetString("DrawRectangle_LineSizeToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PickColor.
        '''</summary>
        Friend Shared ReadOnly Property DrawRectangle_PickColor() As String
            Get
                Return ResourceManager.GetString("DrawRectangle_PickColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pick Fill Color.
        '''</summary>
        Friend Shared ReadOnly Property DrawRectangle_PickFillColor() As String
            Get
                Return ResourceManager.GetString("DrawRectangle_PickFillColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Draw Rectangle.
        '''</summary>
        Friend Shared ReadOnly Property DrawRectangle_Title() As String
            Get
                Return ResourceManager.GetString("DrawRectangle_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose image extension.
        '''</summary>
        Friend Shared ReadOnly Property Export_ChooseExtension() As String
            Get
                Return ResourceManager.GetString("Export_ChooseExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download Image.
        '''</summary>
        Friend Shared ReadOnly Property Export_ClientRadioText() As String
            Get
                Return ResourceManager.GetString("Export_ClientRadioText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Name.
        '''</summary>
        Friend Shared ReadOnly Property Export_FileNameLabel() As String
            Get
                Return ResourceManager.GetString("Export_FileNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter File Name.
        '''</summary>
        Friend Shared ReadOnly Property Export_FileNameToolTip() As String
            Get
                Return ResourceManager.GetString("Export_FileNameToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Image on Server.
        '''</summary>
        Friend Shared ReadOnly Property Export_ServerRadioText() As String
            Get
                Return ResourceManager.GetString("Export_ServerRadioText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Image.
        '''</summary>
        Friend Shared ReadOnly Property Export_Title() As String
            Get
                Return ResourceManager.GetString("Export_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flip None.
        '''</summary>
        Friend Shared ReadOnly Property Flip_None() As String
            Get
                Return ResourceManager.GetString("Flip_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flip.
        '''</summary>
        Friend Shared ReadOnly Property Flip_Title() As String
            Get
                Return ResourceManager.GetString("Flip_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply.
        '''</summary>
        Friend Shared ReadOnly Property HueSaturation_ApplyBtn_Text() As String
            Get
                Return ResourceManager.GetString("HueSaturation_ApplyBtn_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply the selected hue/saturation levels to the image.
        '''</summary>
        Friend Shared ReadOnly Property HueSaturation_ApplyBtn_ToolTip() As String
            Get
                Return ResourceManager.GetString("HueSaturation_ApplyBtn_ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset.
        '''</summary>
        Friend Shared ReadOnly Property HueSaturation_ResetBtn_Text() As String
            Get
                Return ResourceManager.GetString("HueSaturation_ResetBtn_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset the changes so far.
        '''</summary>
        Friend Shared ReadOnly Property HueSaturation_ResetBtn_ToolTip() As String
            Get
                Return ResourceManager.GetString("HueSaturation_ResetBtn_ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hue/Saturation.
        '''</summary>
        Friend Shared ReadOnly Property HueSaturation_Title() As String
            Get
                Return ResourceManager.GetString("HueSaturation_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a value between 0 and 360.
        '''</summary>
        Friend Shared ReadOnly Property Hue_TxtBoxToolTip() As String
            Get
                Return ResourceManager.GetString("Hue_TxtBoxToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert Image.
        '''</summary>
        Friend Shared ReadOnly Property InsertImage_Title() As String
            Get
                Return ResourceManager.GetString("InsertImage_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to URL of an Image to Insert (example http://domain.com/img.png).
        '''</summary>
        Friend Shared ReadOnly Property InsertImage_UrlTxtToolTip() As String
            Get
                Return ResourceManager.GetString("InsertImage_UrlTxtToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color:.
        '''</summary>
        Friend Shared ReadOnly Property Line_Color() As String
            Get
                Return ResourceManager.GetString("Line_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Current color is {0}).
        '''</summary>
        Friend Shared ReadOnly Property Line_CurrentColorText() As String
            Get
                Return ResourceManager.GetString("Line_CurrentColorText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line size:.
        '''</summary>
        Friend Shared ReadOnly Property Line_LineSize() As String
            Get
                Return ResourceManager.GetString("Line_LineSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set line size.
        '''</summary>
        Friend Shared ReadOnly Property Line_LineSizeToolTip() As String
            Get
                Return ResourceManager.GetString("Line_LineSizeToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PickColor.
        '''</summary>
        Friend Shared ReadOnly Property Line_PickColor() As String
            Get
                Return ResourceManager.GetString("Line_PickColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Draw Line.
        '''</summary>
        Friend Shared ReadOnly Property Line_Title() As String
            Get
                Return ResourceManager.GetString("Line_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a value between 0 and 100%.
        '''</summary>
        Friend Shared ReadOnly Property Opacity_TextboxToolTip() As String
            Get
                Return ResourceManager.GetString("Opacity_TextboxToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opacity.
        '''</summary>
        Friend Shared ReadOnly Property Opacity_Title() As String
            Get
                Return ResourceManager.GetString("Opacity_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color:.
        '''</summary>
        Friend Shared ReadOnly Property Pencil_Color() As String
            Get
                Return ResourceManager.GetString("Pencil_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Current color is {0}).
        '''</summary>
        Friend Shared ReadOnly Property Pencil_CurrentColorText() As String
            Get
                Return ResourceManager.GetString("Pencil_CurrentColorText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line size:.
        '''</summary>
        Friend Shared ReadOnly Property Pencil_LineSize() As String
            Get
                Return ResourceManager.GetString("Pencil_LineSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set line size.
        '''</summary>
        Friend Shared ReadOnly Property Pencil_LineSizeToolTip() As String
            Get
                Return ResourceManager.GetString("Pencil_LineSizeToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PickColor.
        '''</summary>
        Friend Shared ReadOnly Property Pencil_PickColor() As String
            Get
                Return ResourceManager.GetString("Pencil_PickColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pencil.
        '''</summary>
        Friend Shared ReadOnly Property Pencil_Title() As String
            Get
                Return ResourceManager.GetString("Pencil_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print.
        '''</summary>
        Friend Shared ReadOnly Property Print_Button() As String
            Get
                Return ResourceManager.GetString("Print_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print Image.
        '''</summary>
        Friend Shared ReadOnly Property Print_Title() As String
            Get
                Return ResourceManager.GetString("Print_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please do not delete this string..
        '''</summary>
        Friend Shared ReadOnly Property ReservedResource() As String
            Get
                Return ResourceManager.GetString("ReservedResource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resize.
        '''</summary>
        Friend Shared ReadOnly Property Resize_Button() As String
            Get
                Return ResourceManager.GetString("Resize_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Percentage.
        '''</summary>
        Friend Shared ReadOnly Property Resize_Percentage() As String
            Get
                Return ResourceManager.GetString("Resize_Percentage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Percentage of original Width x Height [0,100%].
        '''</summary>
        Friend Shared ReadOnly Property Resize_PercentageToolTip() As String
            Get
                Return ResourceManager.GetString("Resize_PercentageToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preset Sizes.
        '''</summary>
        Friend Shared ReadOnly Property Resize_PresetSizes() As String
            Get
                Return ResourceManager.GetString("Resize_PresetSizes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Preset Width x Height.
        '''</summary>
        Friend Shared ReadOnly Property Resize_PresetSizesToolTip() As String
            Get
                Return ResourceManager.GetString("Resize_PresetSizesToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resize.
        '''</summary>
        Friend Shared ReadOnly Property Resize_Title() As String
            Get
                Return ResourceManager.GetString("Resize_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a rotation angle.
        '''</summary>
        Friend Shared ReadOnly Property Rotate_DropDownToolTip() As String
            Get
                Return ResourceManager.GetString("Rotate_DropDownToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rotate.
        '''</summary>
        Friend Shared ReadOnly Property Rotate_Title() As String
            Get
                Return ResourceManager.GetString("Rotate_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a value between -100 and 100.
        '''</summary>
        Friend Shared ReadOnly Property Saturation_TxtBoxToolTip() As String
            Get
                Return ResourceManager.GetString("Saturation_TxtBoxToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download Image.
        '''</summary>
        Friend Shared ReadOnly Property Save_ClientRadioText() As String
            Get
                Return ResourceManager.GetString("Save_ClientRadioText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Name.
        '''</summary>
        Friend Shared ReadOnly Property Save_FileNameLabel() As String
            Get
                Return ResourceManager.GetString("Save_FileNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter File Name.
        '''</summary>
        Friend Shared ReadOnly Property Save_FileNameToolTip() As String
            Get
                Return ResourceManager.GetString("Save_FileNameToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Image on Server.
        '''</summary>
        Friend Shared ReadOnly Property Save_ServerRadioText() As String
            Get
                Return ResourceManager.GetString("Save_ServerRadioText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Image.
        '''</summary>
        Friend Shared ReadOnly Property Save_Title() As String
            Get
                Return ResourceManager.GetString("Save_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zoom to 100%.
        '''</summary>
        Friend Shared ReadOnly Property Zoom_ActualSizeToolTip() As String
            Get
                Return ResourceManager.GetString("Zoom_ActualSizeToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fit image in editable area.
        '''</summary>
        Friend Shared ReadOnly Property Zoom_BestFitToolTip() As String
            Get
                Return ResourceManager.GetString("Zoom_BestFitToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a value between 0 and 100%.
        '''</summary>
        Friend Shared ReadOnly Property Zoom_TextboxToolTip() As String
            Get
                Return ResourceManager.GetString("Zoom_TextboxToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zoom.
        '''</summary>
        Friend Shared ReadOnly Property Zoom_Title() As String
            Get
                Return ResourceManager.GetString("Zoom_Title", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
