'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_MessageEdit

    '''<summary>
    '''MLVcontrol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVcontrol As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWsessionTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWsessionTimeout As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''VIWeditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWeditor As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''DVtitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVtitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTmessageEdit_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmessageEdit_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CTRLmessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmessages As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''DVtemplateSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVtemplateSelector As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBinuseTemplate_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBinuseTemplate_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLtemplateSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLtemplateSelector As Global.Comunita_OnLine.UC_TemplateMessageAssociation

    '''<summary>
    '''DVmailSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVmailSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CTRLmailSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmailSettings As Global.Comunita_OnLine.UC_MailSettings

    '''<summary>
    '''CTRLlanguageSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLlanguageSelector As Global.Comunita_OnLine.UC_ContentTranslationSelector

    '''<summary>
    '''CTRLtranslator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLtranslator As Global.Comunita_OnLine.UC_ContentTranslator

    '''<summary>
    '''BTNdeleteCurrentTranslation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNdeleteCurrentTranslation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNtemplateMessagePreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNtemplateMessagePreview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNselectRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNselectRecipients As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DVpreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpreview As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CTRLmailpreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmailpreview As Global.Comunita_OnLine.UC_MailMessage

    '''<summary>
    '''BTNcloseMailMessageWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNcloseMailMessageWindow As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''VIWusersSelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWusersSelection As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''CTRLrecipientsMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLrecipientsMessages As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''DVmanualSelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVmanualSelection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTrecipientManualSelection_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTrecipientManualSelection_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DVmailRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVmailRecipients As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RPTrecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTrecipients As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''DVinternalRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVinternalRecipients As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTrecipientSelection_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTrecipientSelection_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CTRLcallUsersSelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLcallUsersSelection As Global.Comunita_OnLine.UC_SelectCallUsersForMessageService

    '''<summary>
    '''BTNbackToMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNbackToMessage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNsendMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNsendMessage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''VIWmessageSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWmessageSent As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LTmessageSentInfos_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmessageSentInfos_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CTRLmessageSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmessageSent As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''BTNbackToRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNbackToRecipients As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNnewMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNnewMessage As Global.System.Web.UI.WebControls.Button
End Class
