'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_TemplateSelector

    '''<summary>
    '''LTidentifier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTidentifier As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MLVcontent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVcontent As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWselector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWselector As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''DDLtemplates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLtemplates As Global.lm.Comol.Core.BaseModules.Web.Controls.ExtendedDropDown

    '''<summary>
    '''HYPpreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPpreview As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''VIWsessionTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWsessionTimeout As Global.System.Web.UI.WebControls.View
End Class
