'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_TemplatesList

    '''<summary>
    '''MLVlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVlist As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWempty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWempty As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''VIWlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWlist As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''DVtitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVtitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTtitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DVaddButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVaddButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HYPaddTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPaddTemplate As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPaddObjectTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPaddObjectTemplate As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPaddPersonalTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPaddPersonalTemplate As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''CTRLmessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmessages As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''LBtemplateNameFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtemplateNameFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TXBtemplateName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBtemplateName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNfilterTemplates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNfilterTemplates As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DVdisplayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdisplayType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBtemplateDisplayFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtemplateDisplayFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RBLdisplayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBLdisplayType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RPTtemplates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTtemplates As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''DVpagerBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpagerBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTpageBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTpageBottom As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''PGgridBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PGgridBottom As Global.Comunita_OnLine.UC_PagerControl
End Class
