'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TokenValidation

    '''<summary>
    '''LTredirect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTredirect As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTexternalWebLogon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTexternalWebLogon As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTtitleTokenValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtitleTokenValidation As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MLVtokenValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVtokenValidation As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWvalidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWvalidation As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBvalidationInfo_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBvalidationInfo_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBvalidationInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBvalidationInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VIWinvalidToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWinvalidToken As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''SPNmessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPNmessages As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTtaxCodeDuplicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtaxCodeDuplicate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTinvalidToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTinvalidToken As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTtokenSupportInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtokenSupportInfo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTtokenUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtokenUrl As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''VIWdebug control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWdebug As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBstartValidationOn_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBstartValidationOn_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBstartValidationOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBstartValidationOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPTattributes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTattributes As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''LBcalculatedMac_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcalculatedMac_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBcalculatedMac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcalculatedMac As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBtokenResult_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtokenResult_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBtokenResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtokenResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBendValidationOn_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBendValidationOn_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBendValidationOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBendValidationOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VIWerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWerror As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LTmessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmessage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TMvalidationTimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TMvalidationTimer As Global.System.Web.UI.Timer

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.Authentication
        Get
            Return CType(MyBase.Master, Comunita_OnLine.Authentication)
        End Get
    End Property
End Class
