'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WizardUserProfileEnd

    '''<summary>
    '''LTstartPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTstartPage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTbackToLoginPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTbackToLoginPage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTshibbolethLogon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTshibbolethLogon As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTexternalWebLogon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTexternalWebLogon As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTtitleWizardCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtitleWizardCompleted As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTmessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmessage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.Authentication
        Get
            Return CType(MyBase.Master, Comunita_OnLine.Authentication)
        End Get
    End Property
End Class
