'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AssignSubmissionWithNoEvaluation

    '''<summary>
    '''MLVsettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVsettings As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWempty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWempty As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBnocalls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBnocalls As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VIWsettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWsettings As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''CTRLsteps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLsteps As Global.Comunita_OnLine.UC_WizardEvaluationCommitteesSteps

    '''<summary>
    '''HYPbackTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPbackTop As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''BTNassignToSubmissionsWithNoEvaluationTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNassignToSubmissionsWithNoEvaluationTop As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CTRLmessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmessages As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''LBdisplayStartupInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdisplayStartupInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MLVassignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVassignments As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWsingleCommitteeAssignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWsingleCommitteeAssignments As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''RPTassignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTassignments As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''VIWmultipleCommitteeAssignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWmultipleCommitteeAssignments As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''RPTsubmissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTsubmissions As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''HYPbackBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPbackBottom As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''BTNassignToSubmissionsWithNoEvaluationBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNassignToSubmissionsWithNoEvaluationBottom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DVconfirmAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVconfirmAction As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBdefaultConfirmDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdefaultConfirmDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPTconfirmItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTconfirmItems As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''BTNcloseConfirmInEvaluationSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNcloseConfirmInEvaluationSettings As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNconfirmInEvaluationSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNconfirmInEvaluationSettings As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AjaxPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AjaxPortal)
        End Get
    End Property
End Class
