'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da uno strumento.
'     Versione runtime: 2.0.50727.42
'
'     Le modifiche a questo file possono causare un comportamento non corretto e verranno perse
'     se il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class EditorHandler
	Protected WithEvents aspnetForm As System.Web.UI.HtmlControls.HtmlForm
End Class
