'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EPCertificationList

    '''<summary>
    '''LBserviceCertificationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBserviceCertificationList As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MLVcertificationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVcertificationList As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWcertificationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWcertificationList As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBfilterStartDateTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBfilterStartDateTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RDPStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RDPStartDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''LBfilterEndDateTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBfilterEndDateTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RDPEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RDPEndDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''LBfilterCertificateTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBfilterCertificateTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLCertificateFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLCertificateFilters As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBfilterCommunityRoleTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBfilterCommunityRoleTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLRolesFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLRolesFilters As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BTNupdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNupdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CHBshowall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHBshowall As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LBcertificateNameHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcertificateNameHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBparticipantsStatHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBparticipantsStatHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPTcertifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTcertifications As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''TRempty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRempty As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LBLempty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLempty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VIWerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWerror As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBerror As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AjaxPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AjaxPortal)
        End Get
    End Property
End Class
