(function(b,a){a(["./kendo.core","./kendo.data"],b);
})(function(){(function(a,K){var t=window.kendo,j=t.support.browser,w=t.Observable,y=t.data.ObservableObject,x=t.data.ObservableArray,E={}.toString,f={},B=Array.prototype.slice,m=t.Class,s,A=a.proxy,L="value",C="source",r="events",l="checked",p=true,k="change";
(function(){var O=document.createElement("a");
if(O.innerText!==K){s="innerText";
}else{if(O.textContent!==K){s="textContent";
}}try{delete O.test;
}catch(P){p=false;
}})();
var g=w.extend({init:function(O,P){var Q=this;
w.fn.init.call(Q);
Q.source=O[0];
Q.parents=O;
Q.path=P;
Q.dependencies={};
Q.dependencies[P]=true;
Q.observable=Q.source instanceof w;
Q._access=function(R){Q.dependencies[R.field]=true;
};
if(Q.observable){Q._change=function(R){Q.change(R);
};
Q.source.bind(k,Q._change);
}},_parents:function(){var P=this.parents;
var Q=this.get();
if(Q&&typeof Q.parent=="function"){var O=Q.parent();
if(a.inArray(O,P)<0){P=[O].concat(P);
}}return P;
},change:function(Q){var P,O,R=Q.field,S=this;
if(S.path==="this"){S.trigger(k,Q);
}else{for(P in S.dependencies){if(P.indexOf(R)===0){O=P.charAt(R.length);
if(!O||O==="."||O==="["){S.trigger(k,Q);
break;
}}}}},start:function(O){O.bind("get",this._access);
},stop:function(O){O.unbind("get",this._access);
},get:function(){var S=this,R=S.source,O=0,P=S.path,Q=R;
if(!S.observable){return Q;
}S.start(S.source);
Q=R.get(P);
while(Q===K&&R){R=S.parents[++O];
if(R instanceof y){Q=R.get(P);
}}if(Q===K){R=S.source;
while(Q===K&&R){R=R.parent();
if(R instanceof y){Q=R.get(P);
}}}if(typeof Q==="function"){O=P.lastIndexOf(".");
if(O>0){R=R.get(P.substring(0,O));
}S.start(R);
if(R!==S.source){Q=Q.call(R,S.source);
}else{Q=Q.call(R);
}S.stop(R);
}if(R&&R!==S.source){S.currentSource=R;
R.unbind(k,S._change).bind(k,S._change);
}S.stop(S.source);
return Q;
},set:function(Q){var P=this.currentSource||this.source;
var O=t.getter(this.path)(P);
if(typeof O==="function"){if(P!==this.source){O.call(P,this.source,Q);
}else{O.call(P,Q);
}}else{P.set(this.path,Q);
}},destroy:function(){if(this.observable){this.source.unbind(k,this._change);
if(this.currentSource){this.currentSource.unbind(k,this._change);
}}this.unbind();
}});
var q=g.extend({get:function(){var R=this.source,Q=this.path,P=0,O;
O=R.get(Q);
while(!O&&R){R=this.parents[++P];
if(R instanceof y){O=R.get(Q);
}}return A(O,R);
}});
var D=g.extend({init:function(P,O,Q){var R=this;
g.fn.init.call(R,P,O);
R.template=Q;
},render:function(P){var O;
this.start(this.source);
O=t.render(this.template,P);
this.stop(this.source);
return O;
}});
var e=m.extend({init:function(P,O,Q){this.element=P;
this.bindings=O;
this.options=Q;
},bind:function(P,O){var Q=this;
P=O?P[O]:P;
P.bind(k,function(R){Q.refresh(O||R);
});
Q.refresh(O);
},destroy:function(){}});
var F=e.extend({dataType:function(){var O=this.element.getAttribute("data-type")||this.element.type||"text";
return O.toLowerCase();
},parsedValue:function(){return this._parseValue(this.element.value,this.dataType());
},_parseValue:function(P,O){if(O=="date"){P=t.parseDate(P,"yyyy-MM-dd");
}else{if(O=="datetime-local"){P=t.parseDate(P,["yyyy-MM-ddTHH:mm:ss","yyyy-MM-ddTHH:mm"]);
}else{if(O=="number"){P=t.parseFloat(P);
}else{if(O=="boolean"){P=P.toLowerCase();
if(t.parseFloat(P)!==null){P=Boolean(t.parseFloat(P));
}else{P=(P.toLowerCase()==="true");
}}}}}return P;
}});
f.attr=e.extend({refresh:function(O){this.element.setAttribute(O,this.bindings.attr[O].get());
}});
f.style=e.extend({refresh:function(O){this.element.style[O]=this.bindings.style[O].get()||"";
}});
f.enabled=e.extend({refresh:function(){if(this.bindings.enabled.get()){this.element.removeAttribute("disabled");
}else{this.element.setAttribute("disabled","disabled");
}}});
f.readonly=e.extend({refresh:function(){if(this.bindings.readonly.get()){this.element.setAttribute("readonly","readonly");
}else{this.element.removeAttribute("readonly");
}}});
f.disabled=e.extend({refresh:function(){if(this.bindings.disabled.get()){this.element.setAttribute("disabled","disabled");
}else{this.element.removeAttribute("disabled");
}}});
f.events=e.extend({init:function(P,O,Q){e.fn.init.call(this,P,O,Q);
this.handlers={};
},refresh:function(R){var P=a(this.element),O=this.bindings.events[R],Q=this.handlers[R];
if(Q){P.off(R,Q);
}Q=this.handlers[R]=O.get();
P.on(R,O.source,Q);
},destroy:function(){var O=a(this.element),P;
for(P in this.handlers){O.off(P,this.handlers[P]);
}}});
f.text=e.extend({refresh:function(){var O=this.bindings.text.get();
if(O==null){O="";
}this.element[s]=O;
}});
f.visible=e.extend({refresh:function(){if(this.bindings.visible.get()){this.element.style.display="";
}else{this.element.style.display="none";
}}});
f.invisible=e.extend({refresh:function(){if(!this.bindings.invisible.get()){this.element.style.display="";
}else{this.element.style.display="none";
}}});
f.html=e.extend({refresh:function(){this.element.innerHTML=this.bindings.html.get();
}});
f.value=F.extend({init:function(P,O,Q){F.fn.init.call(this,P,O,Q);
this._change=A(this.change,this);
this.eventName=Q.valueUpdate||k;
a(this.element).on(this.eventName,this._change);
this._initChange=false;
},change:function(){this._initChange=this.eventName!=k;
this.bindings[L].set(this.parsedValue());
this._initChange=false;
},refresh:function(){if(!this._initChange){var P=this.bindings[L].get();
if(P==null){P="";
}var O=this.dataType();
if(O=="date"){P=t.toString(P,"yyyy-MM-dd");
}else{if(O=="datetime-local"){P=t.toString(P,"yyyy-MM-ddTHH:mm:ss");
}}this.element.value=P;
}this._initChange=false;
},destroy:function(){a(this.element).off(this.eventName,this._change);
}});
f.source=e.extend({init:function(P,O,Q){e.fn.init.call(this,P,O,Q);
var R=this.bindings.source.get();
if(R instanceof t.data.DataSource&&Q.autoBind!==false){R.fetch();
}},refresh:function(O){var Q=this,P=Q.bindings.source.get();
if(P instanceof x||P instanceof t.data.DataSource){O=O||{};
if(O.action=="add"){Q.add(O.index,O.items);
}else{if(O.action=="remove"){Q.remove(O.index,O.items);
}else{if(O.action!="itemchange"){Q.render();
}}}}else{Q.render();
}},container:function(){var O=this.element;
if(O.nodeName.toLowerCase()=="table"){if(!O.tBodies[0]){O.appendChild(document.createElement("tbody"));
}O=O.tBodies[0];
}return O;
},template:function(){var P=this.options,Q=P.template,O=this.container().nodeName.toLowerCase();
if(!Q){if(O=="select"){if(P.valueField||P.textField){Q=t.format('<option value="#:{0}#">#:{1}#</option>',P.valueField||P.textField,P.textField||P.valueField);
}else{Q="<option>#:data#</option>";
}}else{if(O=="tbody"){Q="<tr><td>#:data#</td></tr>";
}else{if(O=="ul"||O=="ol"){Q="<li>#:data#</li>";
}else{Q="#:data#";
}}}Q=t.template(Q);
}return Q;
},add:function(S,T){var Q=this.container(),V,R,U,O,P=Q.cloneNode(false),W=Q.children[S];
a(P).html(t.render(this.template(),T));
if(P.children.length){V=this.bindings.source._parents();
for(R=0,U=T.length;
R<U;
R++){O=P.children[0];
Q.insertBefore(O,W||null);
d(O,T[R],this.options.roles,[T[R]].concat(V));
}}},remove:function(R,S){var Q,P=this.container();
for(Q=0;
Q<S.length;
Q++){var O=P.children[R];
J(O);
P.removeChild(O);
}},render:function(){var S=this.bindings.source.get(),R,P,Q,O=this.container(),T=this.template();
if(S instanceof t.data.DataSource){S=S.view();
}if(!(S instanceof x)&&E.call(S)!=="[object Array]"){S=[S];
}if(this.bindings.template){I(O);
a(O).html(this.bindings.template.render(S));
if(O.children.length){R=this.bindings.source._parents();
for(P=0,Q=S.length;
P<Q;
P++){d(O.children[P],S[P],this.options.roles,[S[P]].concat(R));
}}}else{a(O).html(t.render(T,S));
}}});
f.input={checked:F.extend({init:function(P,O,Q){F.fn.init.call(this,P,O,Q);
this._change=A(this.change,this);
a(this.element).change(this._change);
},change:function(){var O=this.element;
var S=this.value();
if(O.type=="radio"){S=this.parsedValue();
this.bindings[l].set(S);
}else{if(O.type=="checkbox"){var R=this.bindings[l].get();
var Q;
if(R instanceof x){S=this.parsedValue();
if(S instanceof Date){for(var P=0;
P<R.length;
P++){if(R[P] instanceof Date&&+R[P]===+S){Q=P;
break;
}}}else{Q=R.indexOf(S);
}if(Q>-1){R.splice(Q,1);
}else{R.push(S);
}}else{this.bindings[l].set(S);
}}}},refresh:function(){var T=this.bindings[l].get(),R=T,S=this.dataType(),O=this.element;
if(O.type=="checkbox"){if(R instanceof x){var Q=-1;
T=this.parsedValue();
if(T instanceof Date){for(var P=0;
P<R.length;
P++){if(R[P] instanceof Date&&+R[P]===+T){Q=P;
break;
}}}else{Q=R.indexOf(T);
}O.checked=(Q>=0);
}else{O.checked=R;
}}else{if(O.type=="radio"&&T!=null){if(S=="date"){T=t.toString(T,"yyyy-MM-dd");
}else{if(S=="datetime-local"){T=t.toString(T,"yyyy-MM-ddTHH:mm:ss");
}}if(O.value===T.toString()){O.checked=true;
}}}},value:function(){var O=this.element,P=O.value;
if(O.type=="checkbox"){P=O.checked;
}return P;
},destroy:function(){a(this.element).off(k,this._change);
}})};
f.select={value:F.extend({init:function(Q,O,P){F.fn.init.call(this,Q,O,P);
this._change=A(this.change,this);
a(this.element).change(this._change);
},parsedValue:function(){var O=this.dataType();
var T=[];
var S,R,P,Q;
for(P=0,Q=this.element.options.length;
P<Q;
P++){R=this.element.options[P];
if(R.selected){S=R.attributes.value;
if(S&&S.specified){S=R.value;
}else{S=R.text;
}T.push(this._parseValue(S,O));
}}return T;
},change:function(){var Y=[],O=this.element,U,P=this.options.valueField||this.options.textField,X=this.options.valuePrimitive,T,W,V,Q,R;
Y=this.parsedValue();
if(P){U=this.bindings.source.get();
if(U instanceof t.data.DataSource){U=U.view();
}for(W=0;
W<Y.length;
W++){for(Q=0,R=U.length;
Q<R;
Q++){var S=X?(this._parseValue(Y[W],this.dataType())===U[Q].get(P)):(this._parseValue(U[Q].get(P),this.dataType()).toString()===Y[W]);
if(S){Y[W]=U[Q];
break;
}}}}V=this.bindings[L].get();
if(V instanceof x){V.splice.apply(V,[0,V.length].concat(Y));
}else{if(!X&&(V instanceof y||V===null||V===K||!P)){this.bindings[L].set(Y[0]);
}else{this.bindings[L].set(Y[0].get(P));
}}},refresh:function(){var R,O=this.element,S=O.options,X=this.options.valuePrimitive,V=this.bindings[L].get(),Y=V,P=this.options.valueField||this.options.textField,Q=false,U=this.dataType(),T;
if(!(Y instanceof x)){Y=new x([V]);
}O.selectedIndex=-1;
for(var W=0;
W<Y.length;
W++){V=Y[W];
if(P&&V instanceof y){V=V.get(P);
}if(U=="date"){V=t.toString(Y[W],"yyyy-MM-dd");
}else{if(U=="datetime-local"){V=t.toString(Y[W],"yyyy-MM-ddTHH:mm:ss");
}}for(R=0;
R<S.length;
R++){T=S[R].value;
if(T===""&&V!==""){T=S[R].text;
}if(V!=null&&T==V.toString()){S[R].selected=true;
Q=true;
}}}},destroy:function(){a(this.element).off(k,this._change);
}})};
function o(O,P,Q){return e.extend({init:function(U,R,S){var T=this;
e.fn.init.call(T,U.element[0],R,S);
T.widget=U;
T._dataBinding=A(T.dataBinding,T);
T._dataBound=A(T.dataBound,T);
T._itemChange=A(T.itemChange,T);
},itemChange:function(R){d(R.item[0],R.data,this._ns(R.ns),[R.data].concat(this.bindings[O]._parents()));
},dataBinding:function(R){var S,U,V=this.widget,T=R.removedItems||V.items();
for(S=0,U=T.length;
S<U;
S++){J(T[S]);
}},_ns:function(S){S=S||t.ui;
var R=[t.ui,t.dataviz.ui,t.mobile.ui];
R.splice(a.inArray(S,R),1);
R.unshift(S);
return t.rolesFromNamespaces(R);
},dataBound:function(S){var U,W,Z=this.widget,V=S.addedItems||Z.items(),R=Z[P],Y,X,T=R.group()||[];
if(V.length){Y=S.addedDataItems||R.flatView();
X=this.bindings[O]._parents();
for(U=0,W=Y.length;
U<W;
U++){d(V[U],Y[U],this._ns(S.ns),[Y[U]].concat(X));
}}},refresh:function(R){var T=this,S,U=T.widget;
R=R||{};
if(!R.action){T.destroy();
U.bind("dataBinding",T._dataBinding);
U.bind("dataBound",T._dataBound);
U.bind("itemChange",T._itemChange);
S=T.bindings[O].get();
if(U[P] instanceof t.data.DataSource&&U[P]!=S){if(S instanceof t.data.DataSource){U[Q](S);
}else{if(S&&S._dataSource){U[Q](S._dataSource);
}else{U[P].data(S);
}}}}},destroy:function(){var R=this.widget;
R.unbind("dataBinding",this._dataBinding);
R.unbind("dataBound",this._dataBound);
R.unbind("itemChange",this._itemChange);
}});
}f.widget={events:e.extend({init:function(Q,O,P){e.fn.init.call(this,Q.element[0],O,P);
this.widget=Q;
this.handlers={};
},refresh:function(Q){var O=this.bindings.events[Q],P=this.handlers[Q];
if(P){this.widget.unbind(Q,P);
}P=O.get();
this.handlers[Q]=function(R){R.data=O.source;
P(R);
if(R.data===O.source){delete R.data;
}};
this.widget.bind(Q,this.handlers[Q]);
},destroy:function(){var O;
for(O in this.handlers){this.widget.unbind(O,this.handlers[O]);
}}}),checked:e.extend({init:function(Q,O,P){e.fn.init.call(this,Q.element[0],O,P);
this.widget=Q;
this._change=A(this.change,this);
this.widget.bind(k,this._change);
},change:function(){this.bindings[l].set(this.value());
},refresh:function(){this.widget.check(this.bindings[l].get()===true);
},value:function(){var O=this.element,P=O.value;
if(P=="on"||P=="off"){P=O.checked;
}return P;
},destroy:function(){this.widget.unbind(k,this._change);
}}),visible:e.extend({init:function(Q,O,P){e.fn.init.call(this,Q.element[0],O,P);
this.widget=Q;
},refresh:function(){var O=this.bindings.visible.get();
this.widget.wrapper[0].style.display=O?"":"none";
}}),invisible:e.extend({init:function(Q,O,P){e.fn.init.call(this,Q.element[0],O,P);
this.widget=Q;
},refresh:function(){var O=this.bindings.invisible.get();
this.widget.wrapper[0].style.display=O?"none":"";
}}),enabled:e.extend({init:function(Q,O,P){e.fn.init.call(this,Q.element[0],O,P);
this.widget=Q;
},refresh:function(){if(this.widget.enable){this.widget.enable(this.bindings.enabled.get());
}}}),disabled:e.extend({init:function(Q,O,P){e.fn.init.call(this,Q.element[0],O,P);
this.widget=Q;
},refresh:function(){if(this.widget.enable){this.widget.enable(!this.bindings.disabled.get());
}}}),source:o("source","dataSource","setDataSource"),value:e.extend({init:function(R,O,P){e.fn.init.call(this,R.element[0],O,P);
this.widget=R;
this._change=a.proxy(this.change,this);
this.widget.first(k,this._change);
var Q=this.bindings.value.get();
this._valueIsObservableObject=!P.valuePrimitive&&(Q==null||Q instanceof y);
this._valueIsObservableArray=Q instanceof x;
this._initChange=false;
},change:function(){var W=this.widget.value(),O=this.options.dataValueField||this.options.dataTextField,Q=E.call(W)==="[object Array]",R=this._valueIsObservableObject,X,Y,Z=[],U,V,P,S,T;
this._initChange=true;
if(O){if(this.bindings.source){T=this.bindings.source.get();
}if(W===""&&(R||this.options.valuePrimitive)){W=null;
}else{if(!T||T instanceof t.data.DataSource){T=this.widget.dataSource.view();
}if(Q){Y=W.length;
Z=W.slice(0);
}for(P=0,S=T.length;
P<S;
P++){U=T[P];
V=U.get(O);
if(Q){for(X=0;
X<Y;
X++){if(V==Z[X]){Z[X]=U;
break;
}}}else{if(V==W){W=R?U:V;
break;
}}}if(Z[0]){if(this._valueIsObservableArray){W=Z;
}else{if(R||!O){W=Z[0];
}else{W=Z[0].get(O);
}}}}}this.bindings.value.set(W);
this._initChange=false;
},refresh:function(){if(!this._initChange){var O=this.options.dataValueField||this.options.dataTextField,R=this.bindings.value.get(),P=0,Q,S=[];
if(R===K){R=null;
}if(O){if(R instanceof x){for(Q=R.length;
P<Q;
P++){S[P]=R[P].get(O);
}R=S;
}else{if(R instanceof y){R=R.get(O);
}}}this.widget.value(R);
}this._initChange=false;
},destroy:function(){this.widget.unbind(k,this._change);
}}),gantt:{dependencies:o("dependencies","dependencies","setDependenciesDataSource")},multiselect:{value:e.extend({init:function(Q,O,P){e.fn.init.call(this,Q.element[0],O,P);
this.widget=Q;
this._change=a.proxy(this.change,this);
this.widget.first(k,this._change);
this._initChange=false;
},change:function(){var aa=this,W=aa.bindings[L].get(),ab=aa.options.valuePrimitive,U=ab?aa.widget.value():aa.widget.dataItems();
var O=this.options.dataValueField||this.options.dataTextField;
U=U.slice(0);
aa._initChange=true;
if(W instanceof x){var X=[];
var S=U.length;
var Q=0,R=0;
var V=W[Q];
var Z=false;
var Y;
var T;
var P;
while(V!==K){P=false;
for(R=0;
R<S;
R++){if(ab){Z=U[R]==V;
}else{T=U[R];
T=T.get?T.get(O):T;
Z=T==(V.get?V.get(O):V);
}if(Z){U.splice(R,1);
S-=1;
P=true;
break;
}}if(!P){X.push(V);
b(W,Q,1);
Y=Q;
}else{Q+=1;
}V=W[Q];
}b(W,W.length,0,U);
if(X.length){W.trigger("change",{action:"remove",items:X,index:Y});
}if(U.length){W.trigger("change",{action:"add",items:U,index:W.length-1});
}}else{aa.bindings[L].set(U);
}aa._initChange=false;
},refresh:function(){if(!this._initChange){var O=this.options.dataValueField||this.options.dataTextField,S=this.bindings.value.get(),P=0,Q,T=[],R;
if(S===K){S=null;
}if(O){if(S instanceof x){for(Q=S.length;
P<Q;
P++){R=S[P];
T[P]=R.get?R.get(O):R;
}S=T;
}else{if(S instanceof y){S=S.get(O);
}}}this.widget.value(S);
}},destroy:function(){this.widget.unbind(k,this._change);
}})},scheduler:{source:o("source","dataSource","setDataSource").extend({dataBound:function(P){var R;
var S;
var U=this.widget;
var Q=P.addedItems||U.items();
var O,T;
if(Q.length){O=P.addedDataItems||U.dataItems();
T=this.bindings.source._parents();
for(R=0,S=O.length;
R<S;
R++){d(Q[R],O[R],this._ns(P.ns),[O[R]].concat(T));
}}}})}};
var b=function(Q,R,U,O){O=O||[];
U=U||0;
var P=O.length;
var T=Q.length;
var V=[].slice.call(Q,R+U);
var W=V.length;
var S;
if(P){P=R+P;
S=0;
for(;
R<P;
R++){Q[R]=O[S];
S++;
}Q.length=P;
}else{if(U){Q.length=R;
U+=R;
while(R<U){delete Q[--U];
}}}if(W){W=R+W;
S=0;
for(;
R<W;
R++){Q[R]=V[S];
S++;
}Q.length=W;
}R=Q.length;
while(R<T){delete Q[R];
R++;
}};
var h=m.extend({init:function(P,O){this.target=P;
this.options=O;
this.toDestroy=[];
},bind:function(O){var T,S,R,Q,P,V=this instanceof N,U=this.binders();
for(T in O){if(T==L){S=true;
}else{if(T==C){R=true;
}else{if(T==r&&!V){Q=true;
}else{if(T==l){P=true;
}else{this.applyBinding(T,O,U);
}}}}}if(R){this.applyBinding(C,O,U);
}if(S){this.applyBinding(L,O,U);
}if(P){this.applyBinding(l,O,U);
}if(Q&&!V){this.applyBinding(r,O,U);
}},binders:function(){return f[this.target.nodeName.toLowerCase()]||{};
},applyBinding:function(S,R,T){var P=T[S]||f[S],U=this.toDestroy,O,Q=R[S];
if(P){P=new P(this.target,R,this.options);
U.push(P);
if(Q instanceof g){P.bind(Q);
U.push(Q);
}else{for(O in Q){P.bind(Q,O);
U.push(Q[O]);
}}}else{if(S!=="template"){throw new Error("The "+S+" binding is not supported by the "+this.target.nodeName.toLowerCase()+" element");
}}},destroy:function(){var O,P,Q=this.toDestroy;
for(O=0,P=Q.length;
O<P;
O++){Q[O].destroy();
}}});
var N=h.extend({binders:function(){return f.widget[this.target.options.name.toLowerCase()]||{};
},applyBinding:function(S,R,T){var P=T[S]||f.widget[S],U=this.toDestroy,O,Q=R[S];
if(P){P=new P(this.target,R,this.target.options);
U.push(P);
if(Q instanceof g){P.bind(Q);
U.push(Q);
}else{for(O in Q){P.bind(Q,O);
U.push(Q[O]);
}}}else{throw new Error("The "+S+" binding is not supported by the "+this.target.options.name+" widget");
}}});
function i(O,P){var Q=t.initWidget(O,{},P);
if(Q){return new N(Q);
}}var u=/[A-Za-z0-9_\-]+:(\{([^}]*)\}|[^,}]+)/g,M=/\s/g;
function z(O){var T={},Q,S,U,P,R,W,V;
V=O.match(u);
for(Q=0,S=V.length;
Q<S;
Q++){U=V[Q];
P=U.indexOf(":");
R=U.substring(0,P);
W=U.substring(P+1);
if(W.charAt(0)=="{"){W=z(W);
}T[R]=W;
}return T;
}function n(P,R,S){var O,Q={};
for(O in P){Q[O]=new S(R,P[O]);
}return Q;
}function d(T,Z,Y,W){var X=T.getAttribute("data-"+t.ns+"role"),U,O=T.getAttribute("data-"+t.ns+"bind"),Q=T.children,R=[],S=true,P,V={},aa;
W=W||[Z];
if(X||O){H(T);
}if(X){aa=i(T,Y);
}if(O){O=z(O.replace(M,""));
if(!aa){V=t.parseOptions(T,{textField:"",valueField:"",template:"",valueUpdate:k,valuePrimitive:false,autoBind:true});
V.roles=Y;
aa=new h(T,V);
}aa.source=Z;
P=n(O,W,g);
if(V.template){P.template=new D(W,"",V.template);
}if(P.click){O.events=O.events||{};
O.events.click=O.click;
P.click.destroy();
delete P.click;
}if(P.source){S=false;
}if(O.attr){P.attr=n(O.attr,W,g);
}if(O.style){P.style=n(O.style,W,g);
}if(O.events){P.events=n(O.events,W,q);
}aa.bind(P);
}if(aa){T.kendoBindingTarget=aa;
}if(S&&Q){for(U=0;
U<Q.length;
U++){R[U]=Q[U];
}for(U=0;
U<R.length;
U++){d(R[U],Z,Y,W);
}}}function c(O,S){var P,Q,R,T=t.rolesFromNamespaces([].slice.call(arguments,2));
S=t.observable(S);
O=a(O);
for(P=0,Q=O.length;
P<Q;
P++){R=O[P];
if(R.nodeType===1){d(R,S,T);
}}}function H(P){var O=P.kendoBindingTarget;
if(O){O.destroy();
if(p){delete P.kendoBindingTarget;
}else{if(P.removeAttribute){P.removeAttribute("kendoBindingTarget");
}else{P.kendoBindingTarget=null;
}}}}function J(O){H(O);
I(O);
}function I(P){var O=P.children;
if(O){for(var Q=0,R=O.length;
Q<R;
Q++){J(O[Q]);
}}}function G(O){var P,Q;
O=a(O);
for(P=0,Q=O.length;
P<Q;
P++){J(O[P]);
}}function v(R,Q){var P=R.element,O=P[0].kendoBindingTarget;
if(O){c(P,O.source,Q);
}}t.unbind=G;
t.bind=c;
t.data.binders=f;
t.data.Binder=e;
t.notify=v;
t.observable=function(O){if(!(O instanceof y)){O=new y(O);
}return O;
};
t.observableHierarchy=function(O){var P=t.data.HierarchicalDataSource.create(O);
function Q(S){var T,R;
for(T=0;
T<S.length;
T++){S[T]._initChildren();
R=S[T].children;
R.fetch();
S[T].items=R.data();
Q(S[T].items);
}}P.fetch();
Q(P.data());
P._data._dataSource=P;
return P._data;
};
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
