(function(b,a){a([],b);
})(function(){(function(a,aM,aI){var V=aM.kendo=aM.kendo||{cultures:{}},C=a.extend,t=a.each,P=a.isArray,ar=a.proxy,ad=a.noop,Z=Math,aC,S=aM.JSON||{},aB={},ao=/%/,E=/\{(\d+)(:[^\}]+)?\}/g,i=/(\d+(?:\.?)\d*)px\s*(\d+(?:\.?)\d*)px\s*(\d+(?:\.?)\d*)px\s*(\d+)?/i,ag=/^(\+|-?)\d+(\.?)\d*$/,F="function",aA="string",af="number",ah="object",ae="null",h="boolean",aJ="undefined",L={},aw={},az=[].slice,M=aM.Globalize;
V.version="2015.1.318";
function j(){}j.extend=function(aT){var aQ=function(){},aS,aV=this,aU=aT&&aT.init?aT.init:function(){aV.apply(this,arguments);
},aR;
aQ.prototype=aV.prototype;
aR=aU.fn=aU.prototype=new aQ();
for(aS in aT){if(aT[aS]!=null&&aT[aS].constructor===Object){aR[aS]=C(true,{},aQ.prototype[aS],aT[aS]);
}else{aR[aS]=aT[aS];
}}aR.constructor=aU;
aU.extend=aV.extend;
return aU;
};
j.prototype._initOptions=function(aQ){this.options=q({},this.options,aQ);
};
var R=V.isFunction=function(aQ){return typeof aQ==="function";
};
var aq=function(){this._defaultPrevented=true;
};
var Q=function(){return this._defaultPrevented===true;
};
var ai=j.extend({init:function(){this._events={};
},bind:function(aQ,aU,aY){var a0=this,aW,aR=typeof aQ===aA?[aQ]:aQ,aX,aZ,aT,aV=typeof aU===F,aS;
if(aU===aI){for(aW in aQ){a0.bind(aW,aQ[aW]);
}return a0;
}for(aW=0,aX=aR.length;
aW<aX;
aW++){aQ=aR[aW];
aT=aV?aU:aU[aQ];
if(aT){if(aY){aZ=aT;
aT=function(){a0.unbind(aQ,aT);
aZ.apply(a0,arguments);
};
aT.original=aZ;
}aS=a0._events[aQ]=a0._events[aQ]||[];
aS.push(aT);
}}return a0;
},one:function(aQ,aR){return this.bind(aQ,aR,true);
},first:function(aQ,aU){var aY=this,aW,aR=typeof aQ===aA?[aQ]:aQ,aX,aT,aV=typeof aU===F,aS;
for(aW=0,aX=aR.length;
aW<aX;
aW++){aQ=aR[aW];
aT=aV?aU:aU[aQ];
if(aT){aS=aY._events[aQ]=aY._events[aQ]||[];
aS.unshift(aT);
}}return aY;
},trigger:function(aR,aQ){var aV=this,aS=aV._events[aR],aT,aU;
if(aS){aQ=aQ||{};
aQ.sender=aV;
aQ._defaultPrevented=false;
aQ.preventDefault=aq;
aQ.isDefaultPrevented=Q;
aS=aS.slice();
for(aT=0,aU=aS.length;
aT<aU;
aT++){aS[aT].call(aV,aQ);
}return aQ._defaultPrevented===true;
}return false;
},unbind:function(aQ,aS){var aU=this,aR=aU._events[aQ],aT;
if(aQ===aI){aU._events={};
}else{if(aR){if(aS){for(aT=aR.length-1;
aT>=0;
aT--){if(aR[aT]===aS||aR[aT].original===aS){aR.splice(aT,1);
}}}else{aU._events[aQ]=[];
}}}return aU;
}});
function k(aR,aT){if(aT){return"'"+aR.split("'").join("\\'").split('\\"').join('\\\\\\"').replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\t/g,"\\t")+"'";
}else{var aQ=aR.charAt(0),aS=aR.substring(1);
if(aQ==="="){return"+("+aS+")+";
}else{if(aQ===":"){return"+$kendoHtmlEncode("+aS+")+";
}else{return";"+aR+";$kendoOutput+=";
}}}}var g=/^\w+/,v=/\$\{([^}]*)\}/g,w=/\\\}/g,n=/__CURLY__/g,x=/\\#/g,ax=/__SHARP__/g,aP=["","0","00","000","0000"];
aC={paramName:"data",useWithBlock:true,render:function(aU,aQ){var aS,aT,aR="";
for(aS=0,aT=aQ.length;
aS<aT;
aS++){aR+=aU(aQ[aS]);
}return aR;
},compile:function(aZ,aV){var aY=C({},this,aV),aW=aY.paramName,aQ=aW.match(g)[0],a0=aY.useWithBlock,aT="var $kendoOutput, $kendoHtmlEncode = kendo.htmlEncode;",aS,aX,aU;
if(R(aZ)){return aZ;
}aT+=a0?"with("+aW+"){":"";
aT+="$kendoOutput=";
aX=aZ.replace(w,"__CURLY__").replace(v,"#=$kendoHtmlEncode($1)#").replace(n,"}").replace(x,"__SHARP__").split("#");
for(aU=0;
aU<aX.length;
aU++){aT+=k(aX[aU],aU%2===0);
}aT+=a0?";}":";";
aT+="return $kendoOutput;";
aT=aT.replace(ax,"#");
try{aS=new Function(aQ,aT);
aS._slotCount=Math.floor(aX.length/2);
return aS;
}catch(aR){throw new Error(V.format("Invalid template:'{0}' Generated code:'{1}'",aZ,aT));
}}};
function ak(aS,aQ,aR){aS=aS+"";
aQ=aQ||2;
aR=aQ-aS.length;
if(aR){return aP[aQ].substring(0,aR)+aS;
}return aS;
}(function(){var aQ=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,aR,aS,aT={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},aV,aX={}.toString;
if(typeof Date.prototype.toJSON!==F){Date.prototype.toJSON=function(){var aY=this;
return isFinite(aY.valueOf())?ak(aY.getUTCFullYear(),4)+"-"+ak(aY.getUTCMonth()+1)+"-"+ak(aY.getUTCDate())+"T"+ak(aY.getUTCHours())+":"+ak(aY.getUTCMinutes())+":"+ak(aY.getUTCSeconds())+"Z":null;
};
String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf();
};
}function aU(aY){aQ.lastIndex=0;
return aQ.test(aY)?'"'+aY.replace(aQ,function(aZ){var a0=aT[aZ];
return typeof a0===aA?a0:"\\u"+("0000"+aZ.charCodeAt(0).toString(16)).slice(-4);
})+'"':'"'+aY+'"';
}function aW(a1,aY){var aZ,a0,a6,a2,a3=aR,a4,a7=aY[a1],a5;
if(a7&&typeof a7===ah&&typeof a7.toJSON===F){a7=a7.toJSON(a1);
}if(typeof aV===F){a7=aV.call(aY,a1,a7);
}a5=typeof a7;
if(a5===aA){return aU(a7);
}else{if(a5===af){return isFinite(a7)?String(a7):ae;
}else{if(a5===h||a5===ae){return String(a7);
}else{if(a5===ah){if(!a7){return ae;
}aR+=aS;
a4=[];
if(aX.apply(a7)==="[object Array]"){a2=a7.length;
for(aZ=0;
aZ<a2;
aZ++){a4[aZ]=aW(aZ,a7)||ae;
}a6=a4.length===0?"[]":aR?"[\n"+aR+a4.join(",\n"+aR)+"\n"+a3+"]":"["+a4.join(",")+"]";
aR=a3;
return a6;
}if(aV&&typeof aV===ah){a2=aV.length;
for(aZ=0;
aZ<a2;
aZ++){if(typeof aV[aZ]===aA){a0=aV[aZ];
a6=aW(a0,a7);
if(a6){a4.push(aU(a0)+(aR?": ":":")+a6);
}}}}else{for(a0 in a7){if(Object.hasOwnProperty.call(a7,a0)){a6=aW(a0,a7);
if(a6){a4.push(aU(a0)+(aR?": ":":")+a6);
}}}}a6=a4.length===0?"{}":aR?"{\n"+aR+a4.join(",\n"+aR)+"\n"+a3+"}":"{"+a4.join(",")+"}";
aR=a3;
return a6;
}}}}}if(typeof S.stringify!==F){S.stringify=function(a1,aZ,a0){var aY;
aR="";
aS="";
if(typeof a0===af){for(aY=0;
aY<a0;
aY+=1){aS+=" ";
}}else{if(typeof a0===aA){aS=a0;
}}aV=aZ;
if(aZ&&typeof aZ!==F&&(typeof aZ!==ah||typeof aZ.length!==af)){throw new Error("JSON.stringify");
}return aW("",{"":a1});
};
}})();
(function(){var aS=/dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|HH|H|hh|h|mm|m|fff|ff|f|tt|ss|s|zzz|zz|z|"[^"]*"|'[^']*'/g,a6=/^(n|c|p|e)(\d*)$/i,a0=/(\\.)|(['][^']*[']?)|(["][^"]*["]?)/g,aR=/\,/g,aT="",a3=".",aQ=",",a5="#",a8="0",a2="??",aU="en-US",a1={}.toString;
V.cultures["en-US"]={name:aU,numberFormat:{pattern:["-n"],decimals:2,",":",",".":".",groupSize:[3],percent:{pattern:["-n %","n %"],decimals:2,",":",",".":".",groupSize:[3],symbol:"%"},currency:{pattern:["($n)","$n"],decimals:2,",":",",".":".",groupSize:[3],symbol:"$"}},calendars:{standard:{days:{names:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],namesAbbr:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],namesShort:["Su","Mo","Tu","We","Th","Fr","Sa"]},months:{names:["January","February","March","April","May","June","July","August","September","October","November","December"],namesAbbr:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},AM:["AM","am","AM"],PM:["PM","pm","PM"],patterns:{d:"M/d/yyyy",D:"dddd, MMMM dd, yyyy",F:"dddd, MMMM dd, yyyy h:mm:ss tt",g:"M/d/yyyy h:mm tt",G:"M/d/yyyy h:mm:ss tt",m:"MMMM dd",M:"MMMM dd",s:"yyyy'-'MM'-'ddTHH':'mm':'ss",t:"h:mm tt",T:"h:mm:ss tt",u:"yyyy'-'MM'-'dd HH':'mm':'ss'Z'",y:"MMMM, yyyy",Y:"MMMM, yyyy"},"/":"/",":":":",firstDay:0,twoDigitYearMax:2029}}};
function aW(a9){if(a9){if(a9.numberFormat){return a9;
}if(typeof a9===aA){var ba=V.cultures;
return ba[a9]||ba[a9.split("-")[0]]||null;
}return null;
}return null;
}function aZ(a9){if(a9){a9=aW(a9);
}return a9||V.cultures.current;
}function aV(a9){a9.groupSizes=a9.groupSize;
a9.percent.groupSizes=a9.percent.groupSize;
a9.currency.groupSizes=a9.currency.groupSize;
}V.culture=function(ba){var bb=V.cultures,a9;
if(ba!==aI){a9=aW(ba)||bb[aU];
a9.calendar=a9.calendars.standard;
bb.current=a9;
if(M&&!M.load){aV(a9.numberFormat);
}}else{return bb.current;
}};
V.findCulture=aW;
V.getCulture=aZ;
V.culture(aU);
function aX(bb,bd,ba){ba=aZ(ba);
var a9=ba.calendars.standard,bc=a9.days,be=a9.months;
bd=a9.patterns[bd]||bd;
return bd.replace(aS,function(bf){var bg;
var bh;
var bi;
if(bf==="d"){bh=bb.getDate();
}else{if(bf==="dd"){bh=ak(bb.getDate());
}else{if(bf==="ddd"){bh=bc.namesAbbr[bb.getDay()];
}else{if(bf==="dddd"){bh=bc.names[bb.getDay()];
}else{if(bf==="M"){bh=bb.getMonth()+1;
}else{if(bf==="MM"){bh=ak(bb.getMonth()+1);
}else{if(bf==="MMM"){bh=be.namesAbbr[bb.getMonth()];
}else{if(bf==="MMMM"){bh=be.names[bb.getMonth()];
}else{if(bf==="yy"){bh=ak(bb.getFullYear()%100);
}else{if(bf==="yyyy"){bh=ak(bb.getFullYear(),4);
}else{if(bf==="h"){bh=bb.getHours()%12||12;
}else{if(bf==="hh"){bh=ak(bb.getHours()%12||12);
}else{if(bf==="H"){bh=bb.getHours();
}else{if(bf==="HH"){bh=ak(bb.getHours());
}else{if(bf==="m"){bh=bb.getMinutes();
}else{if(bf==="mm"){bh=ak(bb.getMinutes());
}else{if(bf==="s"){bh=bb.getSeconds();
}else{if(bf==="ss"){bh=ak(bb.getSeconds());
}else{if(bf==="f"){bh=Z.floor(bb.getMilliseconds()/100);
}else{if(bf==="ff"){bh=bb.getMilliseconds();
if(bh>99){bh=Z.floor(bh/10);
}bh=ak(bh);
}else{if(bf==="fff"){bh=ak(bb.getMilliseconds(),3);
}else{if(bf==="tt"){bh=bb.getHours()<12?a9.AM[0]:a9.PM[0];
}else{if(bf==="zzz"){bg=bb.getTimezoneOffset();
bi=bg<0;
bh=Z.abs(bg/60).toString().split(".")[0];
bg=Z.abs(bg)-(bh*60);
bh=(bi?"+":"-")+ak(bh);
bh+=":"+ak(bg);
}else{if(bf==="zz"||bf==="z"){bh=bb.getTimezoneOffset()/60;
bi=bh<0;
bh=Z.abs(bh).toString().split(".")[0];
bh=(bi?"+":"-")+(bf==="zz"?ak(bh):bh);
}}}}}}}}}}}}}}}}}}}}}}}}return bh!==aI?bh:bf.slice(1,bf.length-1);
});
}function aY(by,bg,ba){ba=aZ(ba);
var bz=ba.numberFormat,bl=bz.groupSize[0],bk=bz[aQ],bd=bz[a3],bC=bz.decimals,bA=bz.pattern[0],bw=[],bH,bt,bu,bc,bh,bx=by<0,br,bi,bs,bj,bD=aT,bI=aT,bq,bv,a9,bm,bn,be,bE,bJ,bp,bo,bB,bb,bG,bF=-1,bf;
if(by===aI){return aT;
}if(!isFinite(by)){return by;
}if(!bg){return ba.name.length?by.toLocaleString():by.toString();
}bh=a6.exec(bg);
if(bh){bg=bh[1].toLowerCase();
bt=bg==="c";
bu=bg==="p";
if(bt||bu){bz=bt?bz.currency:bz.percent;
bl=bz.groupSize[0];
bk=bz[aQ];
bd=bz[a3];
bC=bz.decimals;
bH=bz.symbol;
bA=bz.pattern[bx?0:1];
}bc=bh[2];
if(bc){bC=+bc;
}if(bg==="e"){return bc?by.toExponential(bC):by.toExponential();
}if(bu){by*=100;
}by=a4(by,bC);
bx=by<0;
by=by.split(a3);
br=by[0];
bi=by[1];
if(bx){br=br.substring(1);
}bI=br;
bs=br.length;
if(bs>=bl){bI=aT;
for(bq=0;
bq<bs;
bq++){if(bq>0&&(bs-bq)%bl===0){bI+=bk;
}bI+=br.charAt(bq);
}}if(bi){bI+=bd+bi;
}if(bg==="n"&&!bx){return bI;
}by=aT;
for(bq=0,bv=bA.length;
bq<bv;
bq++){a9=bA.charAt(bq);
if(a9==="n"){by+=bI;
}else{if(a9==="$"||a9==="%"){by+=bH;
}else{by+=a9;
}}}return by;
}if(bx){by=-by;
}if(bg.indexOf("'")>-1||bg.indexOf('"')>-1||bg.indexOf("\\")>-1){bg=bg.replace(a0,function(bL){var bM=bL.charAt(0).replace("\\",""),bK=bL.slice(1).replace(bM,"");
bw.push(bK);
return a2;
});
}bg=bg.split(";");
if(bx&&bg[1]){bg=bg[1];
bn=true;
}else{if(by===0){bg=bg[2]||bg[0];
if(bg.indexOf(a5)==-1&&bg.indexOf(a8)==-1){return bg;
}}else{bg=bg[0];
}}bB=bg.indexOf("%");
bb=bg.indexOf("$");
bu=bB!=-1;
bt=bb!=-1;
if(bu){by*=100;
}if(bt&&bg[bb-1]==="\\"){bg=bg.split("\\").join("");
bt=false;
}if(bt||bu){bz=bt?bz.currency:bz.percent;
bl=bz.groupSize[0];
bk=bz[aQ];
bd=bz[a3];
bC=bz.decimals;
bH=bz.symbol;
}bm=bg.indexOf(aQ)>-1;
if(bm){bg=bg.replace(aR,aT);
}be=bg.indexOf(a3);
bv=bg.length;
if(be!=-1){bi=by.toString().split("e");
if(bi[1]){bi=a4(by,Math.abs(bi[1]));
}else{bi=bi[0];
}bi=bi.split(a3)[1]||aT;
bJ=bg.lastIndexOf(a8)-be;
bE=bg.lastIndexOf(a5)-be;
bp=bJ>-1;
bo=bE>-1;
bq=bi.length;
if(!bp&&!bo){bg=bg.substring(0,be)+bg.substring(be+1);
bv=bg.length;
be=-1;
bq=0;
}if(bp&&bJ>bE){bq=bJ;
}else{if(bE>bJ){if(bo&&bq>bE){bq=bE;
}else{if(bp&&bq<bJ){bq=bJ;
}}}}if(bq>-1){by=a4(by,bq);
}}else{by=a4(by);
}bE=bg.indexOf(a5);
bG=bJ=bg.indexOf(a8);
if(bE==-1&&bJ!=-1){bF=bJ;
}else{if(bE!=-1&&bJ==-1){bF=bE;
}else{bF=bE>bJ?bJ:bE;
}}bE=bg.lastIndexOf(a5);
bJ=bg.lastIndexOf(a8);
if(bE==-1&&bJ!=-1){bf=bJ;
}else{if(bE!=-1&&bJ==-1){bf=bE;
}else{bf=bE>bJ?bE:bJ;
}}if(bF==bv){bf=bF;
}if(bF!=-1){bI=by.toString().split(a3);
br=bI[0];
bi=bI[1]||aT;
bs=br.length;
bj=bi.length;
if(bx&&(by*-1)>=0){bx=false;
}if(bm){if(bs===bl&&bs<be-bG){br=bk+br;
}else{if(bs>bl){bI=aT;
for(bq=0;
bq<bs;
bq++){if(bq>0&&(bs-bq)%bl===0){bI+=bk;
}bI+=br.charAt(bq);
}br=bI;
}}}by=bg.substring(0,bF);
if(bx&&!bn){by+="-";
}for(bq=bF;
bq<bv;
bq++){a9=bg.charAt(bq);
if(be==-1){if(bf-bq<bs){by+=br;
break;
}}else{if(bJ!=-1&&bJ<bq){bD=aT;
}if((be-bq)<=bs&&be-bq>-1){by+=br;
bq=be;
}if(be===bq){by+=(bi?bd:aT)+bi;
bq+=bf-be+1;
continue;
}}if(a9===a8){by+=a9;
bD=a9;
}else{if(a9===a5){by+=bD;
}}}if(bf>=bF){by+=bg.substring(bf+1);
}if(bt||bu){bI=aT;
for(bq=0,bv=by.length;
bq<bv;
bq++){a9=by.charAt(bq);
bI+=(a9==="$"||a9==="%")?bH:a9;
}by=bI;
}bv=bw.length;
if(bv){for(bq=0;
bq<bv;
bq++){by=by.replace(a2,bw[bq]);
}}}return by;
}var a4=function(ba,a9){a9=a9||0;
ba=ba.toString().split("e");
ba=Math.round(+(ba[0]+"e"+(ba[1]?(+ba[1]+a9):a9)));
ba=ba.toString().split("e");
ba=+(ba[0]+"e"+(ba[1]?(+ba[1]-a9):-a9));
return ba.toFixed(a9);
};
var a7=function(bb,ba,a9){if(ba){if(a1.call(bb)==="[object Date]"){return aX(bb,ba,a9);
}else{if(typeof bb===af){return aY(bb,ba,a9);
}}}return bb!==aI?bb:"";
};
if(M&&!M.load){a7=function(bb,ba,a9){if(a.isPlainObject(a9)){a9=a9.name;
}return M.format(bb,ba,a9);
};
}V.format=function(a9){var ba=arguments;
return a9.replace(E,function(bc,bb,bd){var be=ba[parseInt(bb,10)+1];
return a7(be,bd?bd.substring(1):"");
});
};
V._extractFormat=function(a9){if(a9.slice(0,3)==="{0:"){a9=a9.slice(3,a9.length-1);
}return a9;
};
V._activeElement=function(){try{return document.activeElement;
}catch(a9){return document.documentElement.activeElement;
}};
V._round=a4;
V.toString=a7;
})();
(function(){var aZ=/\u00A0/g,aT=/[eE][\-+]?[0-9]+/,a6=/[+|\-]\d{1,2}/,aV=/[+|\-]\d{1,2}:?\d{2}/,aR=/^\/Date\((.*?)\)\/$/,a2=/[+-]\d*/,aU=["G","g","d","F","D","y","m","T","t"],a0={2:/^\d{1,2}/,3:/^\d{1,3}/,4:/^\d{4}/},a1={}.toString;
function a3(a9,a8,a7){return !(a9>=a8&&a9<=a7);
}function aS(a7){return a7.charAt(0);
}function aY(a7){return a.map(a7,aS);
}function aQ(a7,a8){if(!a8&&a7.getHours()===23){a7.setHours(a7.getHours()+2);
}}function aW(a8){var a9=0,ba=a8.length,a7=[];
for(;
a9<ba;
a9++){a7[a9]=(a8[a9]+"").toLowerCase();
}return a7;
}function aX(a7){var a8={},a9;
for(a9 in a7){a8[a9]=aW(a7[a9]);
}return a8;
}function a4(bC,bg,bc){if(!bC){return null;
}var bp=function(bG){var bF=0;
while(bg[bm]===bG){bF++;
bm++;
}if(bF>0){bm-=1;
}return bF;
},bi=function(bH){var bG=a0[bH]||new RegExp("^\\d{1,"+bH+"}"),bF=bC.substr(bD,bH).match(bG);
if(bF){bF=bF[0];
bD+=bF.length;
return parseInt(bF,10);
}return null;
},bh=function(bK,bH){var bF=0,bG=bK.length,bI,bJ,bL;
for(;
bF<bG;
bF++){bI=bK[bF];
bJ=bI.length;
bL=bC.substr(bD,bJ);
if(bH){bL=bL.toLowerCase();
}if(bL==bI){bD+=bJ;
return bF+1;
}}return null;
},ba=function(){var bF=false;
if(bC.charAt(bD)===bg[bm]){bD++;
bF=true;
}return bF;
},a8=bc.calendars.standard,bE=null,bv=null,be=null,bk=null,bt=null,bz=null,bs=null,bm=0,bD=0,bo=false,bd=new Date(),bA=a8.twoDigitYearMax||2029,bf=bd.getFullYear(),a9,bb,bn,bw,by,bB,br,a7,bx,bl,bu,bj,bq;
if(!bg){bg="d";
}bw=a8.patterns[bg];
if(bw){bg=bw;
}bg=bg.split("");
bn=bg.length;
for(;
bm<bn;
bm++){a9=bg[bm];
if(bo){if(a9==="'"){bo=false;
}else{ba();
}}else{if(a9==="d"){bb=bp("d");
if(!a8._lowerDays){a8._lowerDays=aX(a8.days);
}be=bb<3?bi(2):bh(a8._lowerDays[bb==3?"namesAbbr":"names"],true);
if(be===null||a3(be,1,31)){return null;
}}else{if(a9==="M"){bb=bp("M");
if(!a8._lowerMonths){a8._lowerMonths=aX(a8.months);
}bv=bb<3?bi(2):bh(a8._lowerMonths[bb==3?"namesAbbr":"names"],true);
if(bv===null||a3(bv,1,12)){return null;
}bv-=1;
}else{if(a9==="y"){bb=bp("y");
bE=bi(bb);
if(bE===null){return null;
}if(bb==2){if(typeof bA==="string"){bA=bf+parseInt(bA,10);
}bE=(bf-bf%100)+bE;
if(bE>bA){bE-=100;
}}}else{if(a9==="h"){bp("h");
bk=bi(2);
if(bk==12){bk=0;
}if(bk===null||a3(bk,0,11)){return null;
}}else{if(a9==="H"){bp("H");
bk=bi(2);
if(bk===null||a3(bk,0,23)){return null;
}}else{if(a9==="m"){bp("m");
bt=bi(2);
if(bt===null||a3(bt,0,59)){return null;
}}else{if(a9==="s"){bp("s");
bz=bi(2);
if(bz===null||a3(bz,0,59)){return null;
}}else{if(a9==="f"){bb=bp("f");
bq=bC.substr(bD,bb).match(a0[3]);
bs=bi(bb);
if(bs!==null){bq=bq[0].length;
if(bq<3){bs*=Math.pow(10,(3-bq));
}if(bb>3){bs=parseInt(bs.toString().substring(0,3),10);
}}if(bs===null||a3(bs,0,999)){return null;
}}else{if(a9==="t"){bb=bp("t");
a7=a8.AM;
bx=a8.PM;
if(bb===1){a7=aY(a7);
bx=aY(bx);
}by=bh(bx);
if(!by&&!bh(a7)){return null;
}}else{if(a9==="z"){bB=true;
bb=bp("z");
if(bC.substr(bD,1)==="Z"){ba();
continue;
}br=bC.substr(bD,6).match(bb>2?aV:a6);
if(!br){return null;
}br=br[0].split(":");
bl=br[0];
bu=br[1];
if(!bu&&bl.length>3){bD=bl.length-2;
bu=bl.substring(bD);
bl=bl.substring(0,bD);
}bl=parseInt(bl,10);
if(a3(bl,-12,13)){return null;
}if(bb>2){bu=parseInt(bu,10);
if(isNaN(bu)||a3(bu,0,59)){return null;
}}}else{if(a9==="'"){bo=true;
ba();
}else{if(!ba()){return null;
}}}}}}}}}}}}}}bj=bk!==null||bt!==null||bz||null;
if(bE===null&&bv===null&&be===null&&bj){bE=bf;
bv=bd.getMonth();
be=bd.getDate();
}else{if(bE===null){bE=bf;
}if(be===null){be=1;
}}if(by&&bk<12){bk+=12;
}if(bB){if(bl){bk+=-bl;
}if(bu){bt+=-bu;
}bC=new Date(Date.UTC(bE,bv,be,bk,bt,bz,bs));
}else{bC=new Date(bE,bv,be,bk,bt,bz,bs);
aQ(bC,bk);
}if(bE<100){bC.setFullYear(bE);
}if(bC.getDate()!==be&&bB===aI){return null;
}return bC;
}function a5(a7){var a8=a7.substr(0,1)==="-"?-1:1;
a7=a7.substring(1);
a7=(parseInt(a7.substr(0,2),10)*60)+parseInt(a7.substring(2),10);
return a8*a7;
}V.parseDate=function(bf,a9,a7){if(a1.call(bf)==="[object Date]"){return bf;
}var ba=0;
var a8=null;
var bb,bc;
var be;
var bd;
if(bf&&bf.indexOf("/D")===0){a8=aR.exec(bf);
if(a8){a8=a8[1];
be=a2.exec(a8.substring(1));
a8=new Date(parseInt(a8,10));
if(be){be=a5(be[0]);
a8=V.timezone.apply(a8,0);
a8=V.timezone.convert(a8,0,-1*be);
}return a8;
}}a7=V.getCulture(a7);
if(!a9){a9=[];
bc=a7.calendar.patterns;
bb=aU.length;
for(;
ba<bb;
ba++){a9[ba]=bc[aU[ba]];
}ba=0;
a9=["yyyy/MM/dd HH:mm:ss","yyyy/MM/dd HH:mm","yyyy/MM/dd","ddd MMM dd yyyy HH:mm:ss","yyyy-MM-ddTHH:mm:ss.fffffffzzz","yyyy-MM-ddTHH:mm:ss.fffzzz","yyyy-MM-ddTHH:mm:sszzz","yyyy-MM-ddTHH:mm:ss.fffffff","yyyy-MM-ddTHH:mm:ss.fff","yyyy-MM-ddTHH:mmzzz","yyyy-MM-ddTHH:mmzz","yyyy-MM-ddTHH:mm:ss","yyyy-MM-ddTHH:mm","yyyy-MM-dd HH:mm:ss","yyyy-MM-dd HH:mm","yyyy-MM-dd","HH:mm:ss","HH:mm"].concat(a9);
}a9=P(a9)?a9:[a9];
bb=a9.length;
for(;
ba<bb;
ba++){a8=a4(bf,a9[ba],a7);
if(a8){return a8;
}}return a8;
};
V.parseInt=function(a9,a7){var a8=V.parseFloat(a9,a7);
if(a8){a8=a8|0;
}return a8;
};
V.parseFloat=function(bh,a7,a9){if(!bh&&bh!==0){return null;
}if(typeof bh===af){return bh;
}bh=bh.toString();
a7=V.getCulture(a7);
var bc=a7.numberFormat,be=bc.percent,a8=bc.currency,bg=a8.symbol,bf=be.symbol,bb=bh.indexOf("-"),bd,ba;
if(aT.test(bh)){bh=parseFloat(bh.replace(bc["."],"."));
if(isNaN(bh)){bh=null;
}return bh;
}if(bb>0){return null;
}else{bb=bb>-1;
}if(bh.indexOf(bg)>-1||(a9&&a9.toLowerCase().indexOf("c")>-1)){bc=a8;
bd=bc.pattern[0].replace("$",bg).split("n");
if(bh.indexOf(bd[0])>-1&&bh.indexOf(bd[1])>-1){bh=bh.replace(bd[0],"").replace(bd[1],"");
bb=true;
}}else{if(bh.indexOf(bf)>-1){ba=true;
bc=be;
bg=bf;
}}bh=bh.replace("-","").replace(bg,"").replace(aZ," ").split(bc[","].replace(aZ," ")).join("").replace(bc["."],".");
bh=parseFloat(bh);
if(isNaN(bh)){bh=null;
}else{if(bb){bh*=-1;
}}if(bh&&ba){bh/=100;
}return bh;
};
if(M&&!M.load){V.parseDate=function(a9,a8,a7){if(a1.call(a9)==="[object Date]"){return a9;
}return M.parseDate(a9,a8,a7);
};
V.parseFloat=function(a8,a7){if(typeof a8===af){return a8;
}if(a8===aI||a8===null){return null;
}if(a.isPlainObject(a7)){a7=a7.name;
}a8=M.parseFloat(a8,a7);
return isNaN(a8)?null:a8;
};
}})();
function K(aR){var aT=aR.css(V.support.transitions.css+"box-shadow")||aR.css("box-shadow"),aS=aT?aT.match(i)||[0,0,0,0,0]:[0,0,0,0,0],aQ=Z.max((+aS[3]),+(aS[4]||0));
return{left:(-aS[1])+aQ,right:(+aS[1])+aQ,bottom:(+aS[2])+aQ};
}function aN(aS,aQ){var aR=aB.browser,aV,aU=aS.css("direction")=="rtl";
if(!aS.parent().hasClass("k-animation-container")){var aY=K(aS),aZ=aS[0].style.width,aT=aS[0].style.height,aX=ao.test(aZ),aW=ao.test(aT);
if(aR.opera){aY.left=aY.right=aY.bottom=5;
}aV=aX||aW;
if(!aX&&(!aQ||(aQ&&aZ))){aZ=aS.outerWidth();
}if(!aW&&(!aQ||(aQ&&aT))){aT=aS.outerHeight();
}aS.wrap(a("<div/>").addClass("k-animation-container").css({width:aZ,height:aT,marginLeft:aY.left*(aU?1:-1),paddingLeft:aY.left,paddingRight:aY.right,paddingBottom:aY.bottom}));
if(aV){aS.css({width:"100%",height:"100%",boxSizing:"border-box",mozBoxSizing:"border-box",webkitBoxSizing:"border-box"});
}}else{var a0=aS.parent(".k-animation-container"),a1=a0[0].style;
if(a0.is(":hidden")){a0.show();
}aV=ao.test(a1.width)||ao.test(a1.height);
if(!aV){a0.css({width:aS.outerWidth(),height:aS.outerHeight(),boxSizing:"content-box",mozBoxSizing:"content-box",webkitBoxSizing:"content-box"});
}}if(aR.msie&&Z.floor(aR.version)<=7){aS.css({zoom:1});
aS.children(".k-menu").width(aS.width());
}return aS.parent();
}function q(aQ){var aR=1,aS=arguments.length;
for(aR=1;
aR<aS;
aR++){r(aQ,arguments[aR]);
}return aQ;
}function r(aR,a0){var aV=V.data.ObservableArray,aU=V.data.LazyObservableArray,aQ=V.data.DataSource,aT=V.data.HierarchicalDataSource,aW,aZ,aY,aX,aS;
for(aW in a0){aZ=a0[aW];
aY=typeof aZ;
if(aY===ah&&aZ!==null){aX=aZ.constructor;
}else{aX=null;
}if(aX&&aX!==Array&&aX!==aV&&aX!==aU&&aX!==aQ&&aX!==aT){if(aZ instanceof Date){aR[aW]=new Date(aZ.getTime());
}else{if(R(aZ.clone)){aR[aW]=aZ.clone();
}else{aS=aR[aW];
if(typeof(aS)===ah){aR[aW]=aS||{};
}else{aR[aW]={};
}r(aR[aW],aZ);
}}}else{if(aY!==aJ){aR[aW]=aZ;
}}}return aR;
}function aE(aQ,aT,aR){for(var aS in aT){if(aT.hasOwnProperty(aS)&&aT[aS].test(aQ)){return aS;
}}return aR!==aI?aR:aQ;
}function aH(aQ){return aQ.replace(/([a-z][A-Z])/g,function(aR){return aR.charAt(0)+"-"+aR.charAt(1).toLowerCase();
});
}function aF(aQ){return aQ.replace(/\-(\w)/g,function(aS,aR){return aR.toUpperCase();
});
}function H(aR,aS){var aT={},aQ;
if(document.defaultView&&document.defaultView.getComputedStyle){aQ=document.defaultView.getComputedStyle(aR,"");
if(aS){a.each(aS,function(aU,aV){aT[aV]=aQ.getPropertyValue(aV);
});
}}else{aQ=aR.currentStyle;
if(aS){a.each(aS,function(aU,aV){aT[aV]=aQ[aF(aV)];
});
}}if(!V.size(aT)){aT=aQ;
}return aT;
}(function(){aB._scrollbar=aI;
aB.scrollbar=function(aZ){if(!isNaN(aB._scrollbar)&&!aZ){return aB._scrollbar;
}else{var aY=document.createElement("div"),a0;
aY.style.cssText="overflow:scroll;overflow-x:hidden;zoom:1;clear:both;display:block";
aY.innerHTML="&nbsp;";
document.body.appendChild(aY);
aB._scrollbar=a0=aY.offsetWidth-aY.scrollWidth;
document.body.removeChild(aY);
return a0;
}};
aB.isRtl=function(aY){return a(aY).closest(".k-rtl").length>0;
};
var aV=document.createElement("table");
try{aV.innerHTML="<tr><td></td></tr>";
aB.tbodyInnerHtml=true;
}catch(aR){aB.tbodyInnerHtml=false;
}aB.touch="ontouchstart" in aM;
aB.msPointers=aM.MSPointerEvent;
aB.pointers=aM.PointerEvent;
var aX=aB.transitions=false,aW=aB.transforms=false,aS="HTMLElement" in aM?HTMLElement.prototype:[];
aB.hasHW3D=("WebKitCSSMatrix" in aM&&"m11" in new aM.WebKitCSSMatrix())||"MozPerspective" in document.documentElement.style||"msPerspective" in document.documentElement.style;
t(["Moz","webkit","O","ms"],function(){var a0=this.toString(),aY=typeof aV.style[a0+"Transition"]===aA;
if(aY||typeof aV.style[a0+"Transform"]===aA){var aZ=a0.toLowerCase();
aW={css:(aZ!="ms")?"-"+aZ+"-":"",prefix:a0,event:(aZ==="o"||aZ==="webkit")?aZ:""};
if(aY){aX=aW;
aX.event=aX.event?aX.event+"TransitionEnd":"transitionend";
}return false;
}});
aV=null;
aB.transforms=aW;
aB.transitions=aX;
aB.devicePixelRatio=aM.devicePixelRatio===aI?1:aM.devicePixelRatio;
try{aB.screenWidth=aM.outerWidth||aM.screen?aM.screen.availWidth:aM.innerWidth;
aB.screenHeight=aM.outerHeight||aM.screen?aM.screen.availHeight:aM.innerHeight;
}catch(aR){aB.screenWidth=aM.screen.availWidth;
aB.screenHeight=aM.screen.availHeight;
}aB.detectOS=function(a7){var a5=false,a3,a2=[],a4=!/mobile safari/i.test(a7),aZ={wp:/(Windows Phone(?: OS)?)\s(\d+)\.(\d+(\.\d+)?)/,fire:/(Silk)\/(\d+)\.(\d+(\.\d+)?)/,android:/(Android|Android.*(?:Opera|Firefox).*?\/)\s*(\d+)\.(\d+(\.\d+)?)/,iphone:/(iPhone|iPod).*OS\s+(\d+)[\._]([\d\._]+)/,ipad:/(iPad).*OS\s+(\d+)[\._]([\d_]+)/,meego:/(MeeGo).+NokiaBrowser\/(\d+)\.([\d\._]+)/,webos:/(webOS)\/(\d+)\.(\d+(\.\d+)?)/,blackberry:/(BlackBerry|BB10).*?Version\/(\d+)\.(\d+(\.\d+)?)/,playbook:/(PlayBook).*?Tablet\s*OS\s*(\d+)\.(\d+(\.\d+)?)/,windows:/(MSIE)\s+(\d+)\.(\d+(\.\d+)?)/,tizen:/(tizen).*?Version\/(\d+)\.(\d+(\.\d+)?)/i,sailfish:/(sailfish).*rv:(\d+)\.(\d+(\.\d+)?).*firefox/i,ffos:/(Mobile).*rv:(\d+)\.(\d+(\.\d+)?).*Firefox/},a6={ios:/^i(phone|pad|pod)$/i,android:/^android|fire$/i,blackberry:/^blackberry|playbook/i,windows:/windows/,wp:/wp/,flat:/sailfish|ffos|tizen/i,meego:/meego/},a1={tablet:/playbook|ipad|fire/i},a0={omini:/Opera\sMini/i,omobile:/Opera\sMobi/i,firefox:/Firefox|Fennec/i,mobilesafari:/version\/.*safari/i,ie:/MSIE|Windows\sPhone/i,chrome:/chrome|crios/i,webkit:/webkit/i};
for(var aY in aZ){if(aZ.hasOwnProperty(aY)){a2=a7.match(aZ[aY]);
if(a2){if(aY=="windows"&&"plugins" in navigator){return false;
}a5={};
a5.device=aY;
a5.tablet=aE(aY,a1,false);
a5.browser=aE(a7,a0,"default");
a5.name=aE(aY,a6);
a5[a5.name]=true;
a5.majorVersion=a2[2];
a5.minorVersion=a2[3].replace("_",".");
a3=a5.minorVersion.replace(".","").substr(0,2);
a5.flatVersion=a5.majorVersion+a3+(new Array(3-(a3.length<3?a3.length:2)).join("0"));
a5.cordova=typeof aM.PhoneGap!==aJ||typeof aM.cordova!==aJ;
a5.appMode=aM.navigator.standalone||(/file|local|wmapp/).test(aM.location.protocol)||a5.cordova;
if(a5.android&&(aB.devicePixelRatio<1.5&&a5.flatVersion<400||a4)&&(aB.screenWidth>800||aB.screenHeight>800)){a5.tablet=aY;
}break;
}}}return a5;
};
var aU=aB.mobileOS=aB.detectOS(navigator.userAgent);
aB.wpDevicePixelRatio=aU.wp?screen.width/320:0;
aB.kineticScrollNeeded=aU&&(aB.touch||aB.msPointers||aB.pointers);
aB.hasNativeScrolling=false;
if(aU.ios||(aU.android&&aU.majorVersion>2)||aU.wp){aB.hasNativeScrolling=aU;
}aB.mouseAndTouchPresent=aB.touch&&!(aB.mobileOS.ios||aB.mobileOS.android);
aB.detectBrowser=function(a2){var aZ=false,a1=[],a0={webkit:/(chrome)[ \/]([\w.]+)/i,safari:/(webkit)[ \/]([\w.]+)/i,opera:/(opera)(?:.*version|)[ \/]([\w.]+)/i,msie:/(msie\s|trident.*? rv:)([\w.]+)/i,mozilla:/(mozilla)(?:.*? rv:([\w.]+)|)/i};
for(var aY in a0){if(a0.hasOwnProperty(aY)){a1=a2.match(a0[aY]);
if(a1){aZ={};
aZ[aY]=true;
aZ[a1[1].toLowerCase().split(" ")[0].split("/")[0]]=true;
aZ.version=parseInt(document.documentMode||a1[2],10);
break;
}}}return aZ;
};
aB.browser=aB.detectBrowser(navigator.userAgent);
aB.zoomLevel=function(){try{return aB.touch?(document.documentElement.clientWidth/aM.innerWidth):aB.browser.msie&&aB.browser.version>=10?((top||aM).document.documentElement.offsetWidth/(top||aM).innerWidth):1;
}catch(aY){return 1;
}};
aB.cssBorderSpacing=typeof document.documentElement.style.borderSpacing!="undefined"&&!(aB.browser.msie&&aB.browser.version<8);
(function(aY){var aZ="",a0=a(document.documentElement),a1=parseInt(aY.version,10);
if(aY.msie){aZ="ie";
}else{if(aY.mozilla){aZ="ff";
}else{if(aY.safari){aZ="safari";
}else{if(aY.webkit){aZ="webkit";
}else{if(aY.opera){aZ="opera";
}}}}}if(aZ){aZ="k-"+aZ+" k-"+aZ+a1;
}if(aB.mobileOS){aZ+=" k-mobile";
}a0.addClass(aZ);
})(aB.browser);
aB.eventCapture=document.documentElement.addEventListener;
var aT=document.createElement("input");
aB.placeholder="placeholder" in aT;
aB.propertyChangeEvent="onpropertychange" in aT;
aB.input=(function(){var a2=["number","date","time","month","week","datetime","datetime-local"];
var aZ=a2.length;
var a3="test";
var a0={};
var aY=0;
var a1;
for(;
aY<aZ;
aY++){a1=a2[aY];
aT.setAttribute("type",a1);
aT.value=a3;
a0[a1.replace("-","")]=aT.type!=="text"&&aT.value!==a3;
}return a0;
})();
aT.style.cssText="float:left;";
aB.cssFloat=!!aT.style.cssFloat;
aT=null;
aB.stableSort=(function(){var a0=513;
var aZ=[{index:0,field:"b"}];
for(var aY=1;
aY<a0;
aY++){aZ.push({index:aY,field:"a"});
}aZ.sort(function(a1,a2){return a1.field>a2.field?1:(a1.field<a2.field?-1:0);
});
return aZ[0].index===1;
})();
aB.matchesSelector=aS.webkitMatchesSelector||aS.mozMatchesSelector||aS.msMatchesSelector||aS.oMatchesSelector||aS.matchesSelector||aS.matches||function(a0){var aZ=document.querySelectorAll?(this.parentNode||document).querySelectorAll(a0)||[]:a(a0),aY=aZ.length;
while(aY--){if(aZ[aY]==this){return true;
}}return false;
};
aB.pushState=aM.history&&aM.history.pushState;
var aQ=document.documentMode;
aB.hashChange=("onhashchange" in aM)&&!(aB.browser.msie&&(!aQ||aQ<=8));
})();
function ay(aR){var aS=0,aQ;
for(aQ in aR){if(aR.hasOwnProperty(aQ)&&aQ!="toJSON"){aS++;
}}return aS;
}function J(aQ,aU,aS){if(!aU){aU="offset";
}var aT=aQ[aU](),aR=aB.mobileOS;
if(aB.browser.msie&&(aB.pointers||aB.msPointers)&&!aS){aT.top-=(aM.pageYOffset-document.documentElement.scrollTop);
aT.left-=(aM.pageXOffset-document.documentElement.scrollLeft);
}return aT;
}var s={left:{reverse:"right"},right:{reverse:"left"},down:{reverse:"up"},up:{reverse:"down"},top:{reverse:"bottom"},bottom:{reverse:"top"},"in":{reverse:"out"},out:{reverse:"in"}};
function al(aR){var aQ={};
t((typeof aR==="string"?aR.split(" "):aR),function(aS){aQ[aS]=this;
});
return aQ;
}function G(aQ){return new V.effects.Element(aQ);
}var u={};
a.extend(u,{enabled:true,Element:function(aQ){this.element=a(aQ);
},promise:function(aQ,aR){if(!aQ.is(":visible")){aQ.css({display:aQ.data("olddisplay")||"block"}).css("display");
}if(aR.hide){aQ.data("olddisplay",aQ.css("display")).hide();
}if(aR.init){aR.init();
}if(aR.completeCallback){aR.completeCallback(aQ);
}aQ.dequeue();
},disable:function(){this.enabled=false;
this.promise=this.promiseShim;
},enable:function(){this.enabled=true;
this.promise=this.animatedPromise;
}});
u.promiseShim=u.promise;
function ap(aS,aR,aT,aQ){if(typeof aS===aA){if(R(aR)){aQ=aR;
aR=400;
aT=false;
}if(R(aT)){aQ=aT;
aT=false;
}if(typeof aR===h){aT=aR;
aR=400;
}aS={effects:aS,duration:aR,reverse:aT,complete:aQ};
}return C({effects:{},duration:400,reverse:false,init:ad,teardown:ad,hide:false},aS,{completeCallback:aS.complete,complete:ad});
}function c(aS,aW,aR,aX,aQ){var aT=0,aV=aS.length,aU;
for(;
aT<aV;
aT++){aU=a(aS[aT]);
aU.queue(function(){u.promise(aU,ap(aW,aR,aX,aQ));
});
}return aS;
}function aG(aS,aR,aT,aQ){if(aR){aR=aR.split(" ");
t(aR,function(aU,aV){aS.toggleClass(aV,aQ);
});
}return aS;
}if(!("kendoAnimate" in a.fn)){C(a.fn,{kendoStop:function(aQ,aR){return this.stop(aQ,aR);
},kendoAnimate:function(aS,aR,aT,aQ){return c(this,aS,aR,aT,aQ);
},kendoAddClass:function(aQ,aR){return V.toggleClass(this,aQ,aR,true);
},kendoRemoveClass:function(aQ,aR){return V.toggleClass(this,aQ,aR,false);
},kendoToggleClass:function(aQ,aR,aS){return V.toggleClass(this,aQ,aR,aS);
}});
}var b=/&/g,Y=/</g,at=/"/g,f=/'/g,N=/>/g;
function O(aQ){return(""+aQ).replace(b,"&amp;").replace(Y,"&lt;").replace(N,"&gt;").replace(at,"&quot;").replace(f,"&#39;");
}var A=function(aQ){return aQ.target;
};
if(aB.touch){A=function(aQ){var aR="originalEvent" in aQ?aQ.originalEvent.changedTouches:"changedTouches" in aQ?aQ.changedTouches:null;
return aR?document.elementFromPoint(aR[0].clientX,aR[0].clientY):aQ.target;
};
t(["swipe","swipeLeft","swipeRight","swipeUp","swipeDown","doubleTap","tap"],function(aQ,aR){a.fn[aR]=function(aS){return this.bind(aR,aS);
};
});
}if(aB.touch){if(!aB.mobileOS){aB.mousedown="mousedown touchstart";
aB.mouseup="mouseup touchend";
aB.mousemove="mousemove touchmove";
aB.mousecancel="mouseleave touchcancel";
aB.click="click";
aB.resize="resize";
}else{aB.mousedown="touchstart";
aB.mouseup="touchend";
aB.mousemove="touchmove";
aB.mousecancel="touchcancel";
aB.click="touchend";
aB.resize="orientationchange";
}}else{if(aB.pointers){aB.mousemove="pointermove";
aB.mousedown="pointerdown";
aB.mouseup="pointerup";
aB.mousecancel="pointercancel";
aB.click="pointerup";
aB.resize="orientationchange resize";
}else{if(aB.msPointers){aB.mousemove="MSPointerMove";
aB.mousedown="MSPointerDown";
aB.mouseup="MSPointerUp";
aB.mousecancel="MSPointerCancel";
aB.click="MSPointerUp";
aB.resize="orientationchange resize";
}else{aB.mousemove="mousemove";
aB.mousedown="mousedown";
aB.mouseup="mouseup";
aB.mousecancel="mouseleave";
aB.click="click";
aB.resize="resize";
}}}var aO=function(aV,aW){var aX=aW||"d",aS,aR,aT,aU,aQ=1;
for(aR=0,aT=aV.length;
aR<aT;
aR++){aU=aV[aR];
if(aU!==""){aS=aU.indexOf("[");
if(aS!==0){if(aS==-1){aU="."+aU;
}else{aQ++;
aU="."+aU.substring(0,aS)+" || {})"+aU.substring(aS);
}}aQ++;
aX+=aU+((aR<aT-1)?" || {})":")");
}}return new Array(aQ).join("(")+aX;
},X=/^([a-z]+:)?\/\//i;
C(V,{ui:V.ui||{},fx:V.fx||G,effects:V.effects||u,mobile:V.mobile||{},data:V.data||{},dataviz:V.dataviz||{},keys:{INSERT:45,DELETE:46,BACKSPACE:8,TAB:9,ENTER:13,ESC:27,LEFT:37,UP:38,RIGHT:39,DOWN:40,END:35,HOME:36,SPACEBAR:32,PAGEUP:33,PAGEDOWN:34,F2:113,F10:121,F12:123,NUMPAD_PLUS:107,NUMPAD_MINUS:109,NUMPAD_DOT:110},support:V.support||aB,animate:V.animate||c,ns:"",attr:function(aQ){return"data-"+V.ns+aQ;
},getShadows:K,wrap:aN,deepExtend:q,getComputedStyles:H,size:ay,toCamelCase:aF,toHyphens:aH,getOffset:V.getOffset||J,parseEffects:V.parseEffects||al,toggleClass:V.toggleClass||aG,directions:V.directions||s,Observable:ai,Class:j,Template:aC,template:ar(aC.compile,aC),render:ar(aC.render,aC),stringify:ar(S.stringify,S),eventTarget:A,htmlEncode:O,isLocalUrl:function(aQ){return aQ&&!X.test(aQ);
},expr:function(aQ,aS,aR){aQ=aQ||"";
if(typeof aS==aA){aR=aS;
aS=false;
}aR=aR||"d";
if(aQ&&aQ.charAt(0)!=="["){aQ="."+aQ;
}if(aS){aQ=aO(aQ.split("."),aR);
}else{aQ=aR+aQ;
}return aQ;
},getter:function(aQ,aS){var aR=aQ+aS;
return L[aR]=L[aR]||new Function("d","return "+V.expr(aQ,aS));
},setter:function(aQ){return aw[aQ]=aw[aQ]||new Function("d,value",V.expr(aQ)+"=value");
},accessor:function(aQ){return{get:V.getter(aQ),set:V.setter(aQ)};
},guid:function(){var aR="",aQ,aS;
for(aQ=0;
aQ<32;
aQ++){aS=Z.random()*16|0;
if(aQ==8||aQ==12||aQ==16||aQ==20){aR+="-";
}aR+=(aQ==12?4:(aQ==16?(aS&3|8):aS)).toString(16);
}return aR;
},roleSelector:function(aQ){return aQ.replace(/(\S+)/g,"["+V.attr("role")+"=$1],").slice(0,-1);
},directiveSelector:function(aQ){var aS=aQ.split(" ");
if(aS){for(var aR=0;
aR<aS.length;
aR++){if(aS[aR]!="view"){aS[aR]=aS[aR].replace(/(\w*)(view|bar|strip|over)$/,"$1-$2");
}}}return aS.join(" ").replace(/(\S+)/g,"kendo-mobile-$1,").slice(0,-1);
},triggeredByInput:function(aQ){return(/^(label|input|textarea|select)$/i).test(aQ.target.tagName);
},logToConsole:function(aR){var aQ=aM.console;
if(!V.suppressLog&&typeof(aQ)!="undefined"&&aQ.log){aQ.log(aR);
}}});
var aL=ai.extend({init:function(aR,aS){var aT=this;
aT.element=V.jQuery(aR).handler(aT);
aT.angular("init",aS);
ai.fn.init.call(aT);
var aQ=aS?aS.dataSource:null;
if(aQ){aS=C({},aS,{dataSource:{}});
}aS=aT.options=C(true,{},aT.options,aS);
if(aQ){aS.dataSource=aQ;
}if(!aT.element.attr(V.attr("role"))){aT.element.attr(V.attr("role"),(aS.name||"").toLowerCase());
}aT.element.data("kendo"+aS.prefix+aS.name,aT);
aT.bind(aT.events,aS);
},events:[],options:{prefix:""},_hasBindingTarget:function(){return !!this.element[0].kendoBindingTarget;
},_tabindex:function(aT){aT=aT||this.wrapper;
var aQ=this.element,aS="tabindex",aR=aT.attr(aS)||aQ.attr(aS);
aQ.removeAttr(aS);
aT.attr(aS,!isNaN(aR)?aR:0);
},setOptions:function(aQ){this._setEvents(aQ);
a.extend(this.options,aQ);
},_setEvents:function(aT){var aU=this,aR=0,aS=aU.events.length,aQ;
for(;
aR<aS;
aR++){aQ=aU.events[aR];
if(aU.options[aQ]&&aT[aQ]){aU.unbind(aQ,aU.options[aQ]);
}}aU.bind(aU.events,aT);
},resize:function(aR){var aS=this.getSize(),aQ=this._size;
if(aR||!aQ||aS.width!==aQ.width||aS.height!==aQ.height){this._size=aS;
this._resize(aS);
this.trigger("resize",aS);
}},getSize:function(){return V.dimensions(this.element);
},size:function(aQ){if(!aQ){return this.getSize();
}else{this.setSize(aQ);
}},setSize:a.noop,_resize:a.noop,destroy:function(){var aQ=this;
aQ.element.removeData("kendo"+aQ.options.prefix+aQ.options.name);
aQ.element.removeData("handler");
aQ.unbind();
},angular:function(){}});
var p=aL.extend({dataItems:function(){return this.dataSource.flatView();
},_angularItems:function(aQ){var aR=this;
aR.angular(aQ,function(){return{elements:aR.items(),data:a.map(aR.dataItems(),function(aS){return{dataItem:aS};
})};
});
}});
V.dimensions=function(aS,aQ){var aR=aS[0];
if(aQ){aS.css(aQ);
}return{width:aR.offsetWidth,height:aR.offsetHeight};
};
V.notify=ad;
var aD=/template$/i,U=/^\s*(?:\{(?:.|\r\n|\n)*\}|\[(?:.|\r\n|\n)*\])\s*$/,T=/^\{(\d+)(:[^\}]+)?\}|^\[[A-Za-z_]*\]$/,o=/([A-Z])/g;
function am(aQ,aR){var aS;
if(aR.indexOf("data")===0){aR=aR.substring(4);
aR=aR.charAt(0).toLowerCase()+aR.substring(1);
}aR=aR.replace(o,"-$1");
aS=aQ.getAttribute("data-"+V.ns+aR);
if(aS===null){aS=aI;
}else{if(aS==="null"){aS=null;
}else{if(aS==="true"){aS=true;
}else{if(aS==="false"){aS=false;
}else{if(ag.test(aS)){aS=parseFloat(aS);
}else{if(U.test(aS)&&!T.test(aS)){aS=new Function("return ("+aS+")")();
}}}}}}return aS;
}function an(aQ,aS){var aT={},aR,aU;
for(aR in aS){aU=am(aQ,aR);
if(aU!==aI){if(aD.test(aR)){aU=V.template(a("#"+aU).html());
}aT[aR]=aU;
}}return aT;
}V.initWidget=function(aS,aY,a1){var aZ,aX,a3,aU,aW,a0,a2,aR,aT,a5;
if(!a1){a1=V.ui.roles;
}else{if(a1.roles){a1=a1.roles;
}}aS=aS.nodeType?aS:aS[0];
a0=aS.getAttribute("data-"+V.ns+"role");
if(!a0){return;
}aT=a0.indexOf(".")===-1;
if(aT){a3=a1[a0];
}else{a3=V.getter(a0)(aM);
}var aQ=a(aS).data(),a4=a3?"kendo"+a3.fn.options.prefix+a3.fn.options.name:"";
if(aT){a5=new RegExp("^kendo.*"+a0+"$","i");
}else{a5=new RegExp("^"+a4+"$","i");
}for(var aV in aQ){if(aV.match(a5)){if(aV===a4){aZ=aQ[aV];
}else{return aQ[aV];
}}}if(!a3){return;
}aR=am(aS,"dataSource");
aY=a.extend({},an(aS,a3.fn.options),aY);
if(aR){if(typeof aR===aA){aY.dataSource=V.getter(aR)(aM);
}else{aY.dataSource=aR;
}}for(aU=0,aW=a3.fn.events.length;
aU<aW;
aU++){aX=a3.fn.events[aU];
a2=am(aS,aX);
if(a2!==aI){aY[aX]=V.getter(a2)(aM);
}}if(!aZ){aZ=new a3(aS,aY);
}else{if(!a.isEmptyObject(aY)){aZ.setOptions(aY);
}}return aZ;
};
V.rolesFromNamespaces=function(aS){var aT=[],aQ,aR;
if(!aS[0]){aS=[V.ui,V.dataviz.ui];
}for(aQ=0,aR=aS.length;
aQ<aR;
aQ++){aT[aQ]=aS[aQ].roles;
}return C.apply(null,[{}].concat(aT.reverse()));
};
V.init=function(aQ){var aR=V.rolesFromNamespaces(az.call(arguments,1));
a(aQ).find("[data-"+V.ns+"role]").addBack().each(function(){V.initWidget(this,{},aR);
});
};
V.destroy=function(aQ){a(aQ).find("[data-"+V.ns+"role]").addBack().each(function(){var aR=a(this).data();
for(var aS in aR){if(aS.indexOf("kendo")===0&&typeof aR[aS].destroy===F){aR[aS].destroy();
}}});
};
function m(aQ,aR){return a.contains(aQ,aR)?-1:1;
}function au(){var aQ=a(this);
return(a.inArray(aQ.attr("data-"+V.ns+"role"),["slider","rangeslider"])>-1)||aQ.is(":visible");
}V.resize=function(aQ,aR){var aS=a(aQ).find("[data-"+V.ns+"role]").addBack().filter(au);
if(!aS.length){return;
}var aT=a.makeArray(aS);
aT.sort(m);
a.each(aT,function(){var aU=V.widgetInstance(a(this));
if(aU){aU.resize(aR);
}});
};
V.parseOptions=an;
C(V.ui,{Widget:aL,DataBoundWidget:p,roles:{},progress:function(aR,aX){var aV=aR.find(".k-loading-mask"),aW=V.support,aQ=aW.browser,aT,aU,aY,aS;
if(aX){if(!aV.length){aT=aW.isRtl(aR);
aU=aT?"right":"left";
aS=aR.scrollLeft();
aY=aQ.webkit?(!aT?0:aR[0].scrollWidth-aR.width()-2*aS):0;
aV=a("<div class='k-loading-mask'><span class='k-loading-text'>Loading...</span><div class='k-loading-image'/><div class='k-loading-color'/></div>").width("100%").height("100%").css("top",aR.scrollTop()).css(aU,Math.abs(aS)+aY).prependTo(aR);
}}else{if(aV){aV.remove();
}}},plugin:function(aU,aT,aS){var aR=aU.fn.options.name,aQ;
aT=aT||V.ui;
aS=aS||"";
aT[aR]=aU;
aT.roles[aR.toLowerCase()]=aU;
aQ="getKendo"+aS+aR;
aR="kendo"+aS+aR;
a.fn[aR]=function(aW){var aX=this,aV;
if(typeof aW===aA){aV=az.call(arguments,1);
this.each(function(){var a0=a.data(this,aR),aY,aZ;
if(!a0){throw new Error(V.format("Cannot call method '{0}' of {1} before it is initialized",aW,aR));
}aY=a0[aW];
if(typeof aY!==F){throw new Error(V.format("Cannot find method '{0}' of {1}",aW,aR));
}aZ=aY.apply(a0,aV);
if(aZ!==aI){aX=aZ;
return false;
}});
}else{this.each(function(){new aU(this,aW);
});
}return aX;
};
a.fn[aR].widget=aU;
a.fn[aQ]=function(){return this.data(aR);
};
}});
var l={bind:function(){return this;
},nullObject:true,options:{}};
var aa=aL.extend({init:function(aQ,aR){aL.fn.init.call(this,aQ,aR);
this.element.autoApplyNS();
this.wrapper=this.element;
this.element.addClass("km-widget");
},destroy:function(){aL.fn.destroy.call(this);
this.element.kendoDestroy();
},options:{prefix:"Mobile"},events:[],view:function(){var aQ=this.element.closest(V.roleSelector("view splitview modalview drawer"));
return V.widgetInstance(aQ,V.mobile.ui)||l;
},viewHasNativeScrolling:function(){var aQ=this.view();
return aQ&&aQ.options.useNativeScrolling;
},container:function(){var aQ=this.element.closest(V.roleSelector("view layout modalview drawer splitview"));
return V.widgetInstance(aQ.eq(0),V.mobile.ui)||l;
}});
C(V.mobile,{init:function(aQ){V.init(aQ,V.mobile.ui,V.ui,V.dataviz.ui);
},appLevelNativeScrolling:function(){return V.mobile.application&&V.mobile.application.options&&V.mobile.application.options.useNativeScrolling;
},roles:{},ui:{Widget:aa,DataBoundWidget:p.extend(aa.prototype),roles:{},plugin:function(aQ){V.ui.plugin(aQ,V.mobile.ui,"Mobile");
}}});
q(V.dataviz,{init:function(aQ){V.init(aQ,V.dataviz.ui);
},ui:{roles:{},themes:{},views:[],plugin:function(aQ){V.ui.plugin(aQ,V.dataviz.ui);
}},roles:{}});
V.touchScroller=function(aQ,aR){return a(aQ).map(function(aT,aS){aS=a(aS);
if(aB.kineticScrollNeeded&&V.mobile.ui.Scroller&&!aS.data("kendoMobileScroller")){aS.kendoMobileScroller(aR);
return aS.data("kendoMobileScroller");
}else{return false;
}})[0];
};
V.preventDefault=function(aQ){aQ.preventDefault();
};
V.widgetInstance=function(aQ,aV){var aU=aQ.data(V.ns+"role"),aX=[],aR,aT;
if(aU){if(aU==="content"){aU="scroller";
}if(aV){if(aV[0]){for(aR=0,aT=aV.length;
aR<aT;
aR++){aX.push(aV[aR].roles[aU]);
}}else{aX.push(aV.roles[aU]);
}}else{aX=[V.ui.roles[aU],V.dataviz.ui.roles[aU],V.mobile.ui.roles[aU]];
}if(aU.indexOf(".")>=0){aX=[V.getter(aU)(aM)];
}for(aR=0,aT=aX.length;
aR<aT;
aR++){var aW=aX[aR];
if(aW){var aS=aQ.data("kendo"+aW.fn.options.prefix+aW.fn.options.name);
if(aS){return aS;
}}}}};
V.onResize=function(aQ){var aR=aQ;
if(aB.mobileOS.android){aR=function(){setTimeout(aQ,600);
};
}a(aM).on(aB.resize,aR);
return aR;
};
V.unbindResize=function(aQ){a(aM).off(aB.resize,aQ);
};
V.attrValue=function(aQ,aR){return aQ.data(V.ns+aR);
};
V.days={Sunday:0,Monday:1,Tuesday:2,Wednesday:3,Thursday:4,Friday:5,Saturday:6};
function D(aQ,aR){var aS=aQ.nodeName.toLowerCase();
return(/input|select|textarea|button|object/.test(aS)?!aQ.disabled:"a"===aS?aQ.href||aR:aR)&&aK(aQ);
}function aK(aQ){return !a(aQ).parents().addBack().filter(function(){return a.css(this,"visibility")==="hidden"||a.expr.filters.hidden(this);
}).length;
}a.extend(a.expr[":"],{kendoFocusable:function(aQ){var aR=a.attr(aQ,"tabindex");
return D(aQ,!isNaN(aR)&&aR>-1);
}});
var ab=["mousedown","mousemove","mouseenter","mouseleave","mouseover","mouseout","mouseup","click"];
var B="label, input, [data-rel=external]";
var ac={setupMouseMute:function(){var aS=0,aT=ab.length,aQ=document.documentElement;
if(ac.mouseTrap||!aB.eventCapture){return;
}ac.mouseTrap=true;
ac.bustClick=false;
ac.captureMouse=false;
var aR=function(aU){if(ac.captureMouse){if(aU.type==="click"){if(ac.bustClick&&!a(aU.target).is(B)){aU.preventDefault();
aU.stopPropagation();
}}else{aU.stopPropagation();
}}};
for(;
aS<aT;
aS++){aQ.addEventListener(ab[aS],aR,true);
}},muteMouse:function(aQ){ac.captureMouse=true;
if(aQ.data.bustClick){ac.bustClick=true;
}clearTimeout(ac.mouseTrapTimeoutID);
},unMuteMouse:function(){clearTimeout(ac.mouseTrapTimeoutID);
ac.mouseTrapTimeoutID=setTimeout(function(){ac.captureMouse=false;
ac.bustClick=false;
},400);
}};
var y={down:"touchstart mousedown",move:"mousemove touchmove",up:"mouseup touchend touchcancel",cancel:"mouseleave touchcancel"};
if(aB.touch&&(aB.mobileOS.ios||aB.mobileOS.android)){y={down:"touchstart",move:"touchmove",up:"touchend touchcancel",cancel:"touchcancel"};
}else{if(aB.pointers){y={down:"pointerdown",move:"pointermove",up:"pointerup",cancel:"pointercancel pointerleave"};
}else{if(aB.msPointers){y={down:"MSPointerDown",move:"MSPointerMove",up:"MSPointerUp",cancel:"MSPointerCancel MSPointerLeave"};
}}}if(aB.msPointers&&!("onmspointerenter" in aM)){a.each({MSPointerEnter:"MSPointerOver",MSPointerLeave:"MSPointerOut"},function(aR,aQ){a.event.special[aR]={delegateType:aQ,bindType:aQ,handle:function(aS){var aV,aW=this,aU=aS.relatedTarget,aT=aS.handleObj;
if(!aU||(aU!==aW&&!a.contains(aW,aU))){aS.type=aT.origType;
aV=aT.handler.apply(this,arguments);
aS.type=aQ;
}return aV;
}};
});
}var I=function(aQ){return(y[aQ]||aQ);
},z=/([^ ]+)/g;
V.applyEventMap=function(aQ,aR){aQ=aQ.replace(z,I);
if(aR){aQ=aQ.replace(z,"$1."+aR);
}return aQ;
};
var aj=a.fn.on;
function W(aR,aQ){return new W.fn.init(aR,aQ);
}C(true,W,a);
W.fn=W.prototype=new a();
W.fn.constructor=W;
W.fn.init=function(aR,aQ){if(aQ&&aQ instanceof a&&!(aQ instanceof W)){aQ=W(aQ);
}return a.fn.init.call(this,aR,aQ,av);
};
W.fn.init.prototype=W.fn;
var av=W(document);
C(W.fn,{handler:function(aQ){this.data("handler",aQ);
return this;
},autoApplyNS:function(aQ){this.data("kendoNS",aQ||V.guid());
return this;
},on:function(){var aX=this,aV=aX.data("kendoNS");
if(arguments.length===1){return aj.call(aX,arguments[0]);
}var aT=aX,aQ=az.call(arguments);
if(typeof aQ[aQ.length-1]===aJ){aQ.pop();
}var aS=aQ[aQ.length-1],aU=V.applyEventMap(aQ[0],aV);
if(aB.mouseAndTouchPresent&&aU.search(/mouse|click/)>-1&&this[0]!==document.documentElement){ac.setupMouseMute();
var aW=aQ.length===2?null:aQ[1],aR=aU.indexOf("click")>-1&&aU.indexOf("touchend")>-1;
aj.call(this,{touchstart:ac.muteMouse,touchend:ac.unMuteMouse},aW,{bustClick:aR});
}if(typeof aS===aA){aT=aX.data("handler");
aS=aT[aS];
aQ[aQ.length-1]=function(aY){aS.call(aT,aY);
};
}aQ[0]=aU;
aj.apply(aX,aQ);
return aX;
},kendoDestroy:function(aQ){aQ=aQ||this.data("kendoNS");
if(aQ){this.off("."+aQ);
}return this;
}});
V.jQuery=W;
V.eventMap=y;
V.timezone=(function(){var aW={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11};
var aT={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};
function aZ(ba,a7){var a3;
var a8;
var a6;
var a4=a7[3];
var a5=a7[4];
var a9=a7[5];
var a2=a7[8];
if(!a2){a7[8]=a2={};
}if(a2[ba]){return a2[ba];
}if(!isNaN(a5)){a3=new Date(Date.UTC(ba,aW[a4],a5,a9[0],a9[1],a9[2],0));
}else{if(a5.indexOf("last")===0){a3=new Date(Date.UTC(ba,aW[a4]+1,1,a9[0]-24,a9[1],a9[2],0));
a8=aT[a5.substr(4,3)];
a6=a3.getUTCDay();
a3.setUTCDate(a3.getUTCDate()+a8-a6-(a8>a6?7:0));
}else{if(a5.indexOf(">=")>=0){a3=new Date(Date.UTC(ba,aW[a4],a5.substr(5),a9[0],a9[1],a9[2],0));
a8=aT[a5.substr(0,3)];
a6=a3.getUTCDay();
a3.setUTCDate(a3.getUTCDate()+a8-a6+(a8<a6?7:0));
}}}return a2[ba]=a3;
}function aU(a6,a4,a8){a4=a4[a8];
if(!a4){var a5=a8.split(":");
var a2=0;
if(a5.length>1){a2=a5[0]*60+Number(a5[1]);
}return[-1000000,"max","-","Jan",1,[0,0,0],a2,"-"];
}var a7=new Date(a6).getUTCFullYear();
a4=jQuery.grep(a4,function(ba){var a9=ba[0];
var bb=ba[1];
return a9<=a7&&(bb>=a7||(a9==a7&&bb=="only")||bb=="max");
});
a4.push(a6);
a4.sort(function(a9,ba){if(typeof a9!="number"){a9=Number(aZ(a7,a9));
}if(typeof ba!="number"){ba=Number(aZ(a7,ba));
}return a9-ba;
});
var a3=a4[jQuery.inArray(a6,a4)-1]||a4[a4.length-1];
return isNaN(a3)?a3:null;
}function aV(a5,a8,a3){var a7=a8[a3];
if(typeof a7==="string"){a7=a8[a7];
}if(!a7){throw new Error('Timezone "'+a3+'" is either incorrect, or kendo.timezones.min.js is not included.');
}for(var a2=a7.length-1;
a2>=0;
a2--){var a4=a7[a2][3];
if(a4&&a5>a4){break;
}}var a6=a7[a2+1];
if(!a6){throw new Error('Timezone "'+a3+'" not found on '+a5+".");
}return a6;
}function a1(a4,a6,a2,a3){if(typeof a4!=af){a4=Date.UTC(a4.getFullYear(),a4.getMonth(),a4.getDate(),a4.getHours(),a4.getMinutes(),a4.getSeconds(),a4.getMilliseconds());
}var a5=aV(a4,a6,a3);
return{zone:a5,rule:aU(a4,a2,a5[1])};
}function aX(a5,a4){if(a4=="Etc/UTC"||a4=="Etc/GMT"){return 0;
}var a2=a1(a5,this.zones,this.rules,a4);
var a6=a2.zone;
var a3=a2.rule;
return V.parseFloat(a3?a6[0]-a3[6]:a6[0]);
}function aQ(a6,a5){var a3=a1(a6,this.zones,this.rules,a5);
var a7=a3.zone;
var a4=a3.rule;
var a2=a7[2];
if(a2.indexOf("/")>=0){return a2.split("/")[a4&&+a4[6]?1:0];
}else{if(a2.indexOf("%s")>=0){return a2.replace("%s",(!a4||a4[7]=="-")?"":a4[7]);
}}return a2;
}function aS(a2,a4,a6){if(typeof a4==aA){a4=this.offset(a2,a4);
}if(typeof a6==aA){a6=this.offset(a2,a6);
}var a3=a2.getTimezoneOffset();
a2=new Date(a2.getTime()+(a4-a6)*60000);
var a5=a2.getTimezoneOffset();
return new Date(a2.getTime()+(a5-a3)*60000);
}function aR(a2,a3){return this.convert(a2,a2.getTimezoneOffset(),a3);
}function aY(a2,a3){return this.convert(a2,a3,a2.getTimezoneOffset());
}function a0(a2){return this.apply(new Date(a2),"Etc/UTC");
}return{zones:{},rules:{},offset:aX,convert:aS,apply:aR,remove:aY,abbr:aQ,toLocalDate:a0};
})();
V.date=(function(){var a1=60000,a0=86400000;
function aR(a7,a8){if(a8===0&&a7.getHours()===23){a7.setHours(a7.getHours()+2);
return true;
}return false;
}function a2(a7,a8,a9){var ba=a7.getHours();
a9=a9||1;
a8=((a8-a7.getDay())+(7*a9))%7;
a7.setDate(a7.getDate()+a8);
aR(a7,ba);
}function aS(a7,a8,a9){a7=new Date(a7);
a2(a7,a8,a9);
return a7;
}function aT(a7){return new Date(a7.getFullYear(),a7.getMonth(),1);
}function aZ(a7){var a9=new Date(a7.getFullYear(),a7.getMonth()+1,0),a8=aT(a7),ba=Math.abs(a9.getTimezoneOffset()-a8.getTimezoneOffset());
if(ba){a9.setHours(a8.getHours()+(ba/60));
}return a9;
}function aU(a7){a7=new Date(a7.getFullYear(),a7.getMonth(),a7.getDate(),0,0,0);
aR(a7,0);
return a7;
}function a6(a7){return Date.UTC(a7.getFullYear(),a7.getMonth(),a7.getDate(),a7.getHours(),a7.getMinutes(),a7.getSeconds(),a7.getMilliseconds());
}function aV(a7){return a7.getTime()-aU(a7);
}function aX(bc,a8,a7){var ba=aV(a8),a9=aV(a7),bb;
if(!bc||ba==a9){return true;
}if(a8>=a7){a7+=a0;
}bb=aV(bc);
if(ba>bb){bb+=a0;
}if(a9<ba){a9+=a0;
}return bb>=ba&&bb<=a9;
}function aW(bc,a8,a7){var ba=a8.getTime(),a9=a7.getTime(),bb;
if(ba>=a9){a9+=a0;
}bb=bc.getTime();
return bb>=ba&&bb<=a9;
}function aQ(a7,a9){var a8=a7.getHours();
a7=new Date(a7);
a3(a7,a9*a0);
aR(a7,a8);
return a7;
}function a3(a7,ba,a9){var bb=a7.getTimezoneOffset();
var a8;
a7.setTime(a7.getTime()+ba);
if(!a9){a8=a7.getTimezoneOffset()-bb;
a7.setTime(a7.getTime()+a8*a1);
}}function a4(){return aU(new Date());
}function aY(a7){return aU(a7).getTime()==a4().getTime();
}function a5(a7){var a8=new Date(1980,1,1,0,0,0);
if(a7){a8.setHours(a7.getHours(),a7.getMinutes(),a7.getSeconds(),a7.getMilliseconds());
}return a8;
}return{adjustDST:aR,dayOfWeek:aS,setDayOfWeek:a2,getDate:aU,isInDateRange:aW,isInTimeRange:aX,isToday:aY,nextDay:function(a7){return aQ(a7,1);
},previousDay:function(a7){return aQ(a7,-1);
},toUtcTime:a6,MS_PER_DAY:a0,MS_PER_HOUR:60*a1,MS_PER_MINUTE:a1,setTime:a3,addDays:aQ,today:a4,toInvariantTime:a5,firstDayOfMonth:aT,lastDayOfMonth:aZ,getMilliseconds:aV};
})();
V.stripWhitespace=function(aR){if(document.createNodeIterator){var aT=document.createNodeIterator(aR,NodeFilter.SHOW_TEXT,function(aU){return aU.parentNode==aR?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;
},false);
while(aT.nextNode()){if(aT.referenceNode&&!aT.referenceNode.textContent.trim()){aT.referenceNode.parentNode.removeChild(aT.referenceNode);
}}}else{for(var aS=0;
aS<aR.childNodes.length;
aS++){var aQ=aR.childNodes[aS];
if(aQ.nodeType==3&&!/\S/.test(aQ.nodeValue)){aR.removeChild(aQ);
aS--;
}if(aQ.nodeType==1){V.stripWhitespace(aQ);
}}}};
var d=aM.requestAnimationFrame||aM.webkitRequestAnimationFrame||aM.mozRequestAnimationFrame||aM.oRequestAnimationFrame||aM.msRequestAnimationFrame||function(aQ){setTimeout(aQ,1000/60);
};
V.animationFrame=function(aQ){d.call(aM,aQ);
};
var e=[];
V.queueAnimation=function(aQ){e[e.length]=aQ;
if(e.length===1){V.runNextAnimation();
}};
V.runNextAnimation=function(){V.animationFrame(function(){if(e[0]){e.shift()();
if(e[0]){V.runNextAnimation();
}}});
};
V.parseQueryStringParams=function(aV){var aU=aV.split("?")[1]||"",aT={},aS=aU.split(/&|=/),aR=aS.length,aQ=0;
for(;
aQ<aR;
aQ+=2){if(aS[aQ]!==""){aT[decodeURIComponent(aS[aQ])]=decodeURIComponent(aS[aQ+1]);
}}return aT;
};
V.elementUnderCursor=function(aQ){return document.elementFromPoint(aQ.x.client,aQ.y.client);
};
V.wheelDeltaY=function(aT){var aS=aT.originalEvent,aR=aS.wheelDeltaY,aQ;
if(aS.wheelDelta){if(aR===aI||aR){aQ=aS.wheelDelta;
}}else{if(aS.detail&&aS.axis===aS.VERTICAL_AXIS){aQ=(-aS.detail)*10;
}}return aQ;
};
V.throttle=function(aR,aQ){var aU;
var aS=0;
if(!aQ||aQ<=0){return aR;
}var aT=function(){var aY=this;
var aW=+new Date()-aS;
var aV=arguments;
function aX(){aR.apply(aY,aV);
aS=+new Date();
}if(!aS){return aX();
}if(aU){clearTimeout(aU);
}if(aW>aQ){aX();
}else{aU=setTimeout(aX,aQ-aW);
}};
aT.cancel=function(){clearTimeout(aU);
};
return aT;
};
V.caret=function(aR,aY,aS){var aV;
var aT=aY!==aI;
if(aS===aI){aS=aY;
}if(aR[0]){aR=aR[0];
}if(aT&&aR.disabled){return;
}try{if(aR.selectionStart!==aI){if(aT){aR.focus();
aR.setSelectionRange(aY,aS);
}else{aY=[aR.selectionStart,aR.selectionEnd];
}}else{if(document.selection){if(a(aR).is(":visible")){aR.focus();
}aV=aR.createTextRange();
if(aT){aV.collapse(true);
aV.moveStart("character",aY);
aV.moveEnd("character",aS-aY);
aV.select();
}else{var aU=aV.duplicate(),aX,aW;
aV.moveToBookmark(document.selection.createRange().getBookmark());
aU.setEndPoint("EndToStart",aV);
aX=aU.text.length;
aW=aX+aV.text.length;
aY=[aX,aW];
}}}}catch(aQ){aY=[];
}return aY;
};
V.compileMobileDirective=function(aR,aS){var aQ=aM.angular;
aR.attr("data-"+V.ns+"role",aR[0].tagName.toLowerCase().replace("kendo-mobile-","").replace("-",""));
aQ.element(aR).injector().invoke(["$compile",function(aT){var aU=aQ.element(aR).scope();
if(aS){aS(aU);
}aT(aR)(aU);
if(!/^\$(digest|apply)$/.test(aU.$$phase)){aU.$digest();
}}]);
return V.widgetInstance(aR,V.mobile.ui);
};
V.antiForgeryTokens=function(){var aS={},aR=a("meta[name=csrf-token],meta[name=_csrf]").attr("content"),aQ=a("meta[name=csrf-param],meta[name=_csrf_header]").attr("content");
a("input[name^='__RequestVerificationToken']").each(function(){aS[this.name]=this.value;
});
if(aQ!==aI&&aR!==aI){aS[aQ]=aR;
}return aS;
};
(function(){function aS(aW,aX,a2,a1){var aY=a("<form>").attr({action:a2,method:"POST",target:a1});
var aV=V.antiForgeryTokens();
aV.fileName=aX;
var a0=aW.split(";base64,");
aV.contentType=a0[0].replace("data:","");
aV.base64=a0[1];
for(var aZ in aV){if(aV.hasOwnProperty(aZ)){a("<input>").attr({value:aV[aZ],name:aZ,type:"hidden"}).appendTo(aY);
}}aY.appendTo("body").submit().remove();
}var aR=document.createElement("a");
var aQ="download" in aR;
function aT(aZ,a0){var aX=aZ;
if(typeof aZ=="string"){var a2=aZ.split(";base64,");
var aY=a2[0];
var aW=atob(a2[1]);
var aV=new Uint8Array(aW.length);
for(var a1=0;
a1<aW.length;
a1++){aV[a1]=aW.charCodeAt(a1);
}aX=new Blob([aV.buffer],{type:aY});
}navigator.msSaveBlob(aX,a0);
}function aU(aV,aX){if(aM.Blob&&aV instanceof Blob){aV=URL.createObjectURL(aV);
}aR.download=aX;
aR.href=aV;
var aW=document.createEvent("MouseEvents");
aW.initMouseEvent("click",true,false,aM,0,0,0,0,0,false,false,false,false,0,null);
aR.dispatchEvent(aW);
}V.saveAs=function(aV){var aW=aS;
if(!aV.forceProxy){if(aQ){aW=aU;
}else{if(navigator.msSaveBlob){aW=aT;
}}}aW(aV.dataURI,aV.fileName,aV.proxyURL,aV.proxyTarget);
};
})();
})($telerik.$,window);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
