(function(b,a){a(["./kendo.calendar","./kendo.popup"],b);
})(function(){(function(a,S){var y=window.kendo,R=y.ui,T=R.Widget,I=y.parseDate,A=y.keys,Q=y.template,b=y._activeElement,q="<div />",O="<span />",G=".kendoDatePicker",i="click"+G,H="open",j="close",h="change",n="dateView",p="disabled",L="readonly",o="k-state-default",s="k-state-focused",N="k-state-selected",P="k-state-disabled",t="k-state-hover",z="keydown"+G,u="mouseenter"+G+" mouseleave"+G,E="mousedown"+G,v="id",C="min",B="max",D="month",c="aria-disabled",d="aria-expanded",e="aria-hidden",f="aria-readonly",g=y.calendar,x=g.isInRange,M=g.restrictValue,w=g.isEqualDatePart,r=a.extend,K=a.proxy,k=Date;
function F(V){var W=V.parseFormats,U=V.format;
g.normalize(V);
W=a.isArray(W)?W:[W];
if(a.inArray(U,W)===-1){W.splice(0,0,V.format);
}V.parseFormats=W;
}function J(U){U.preventDefault();
}var m=function(X){var Y=this,W,U=document.body,V=a(q).attr(e,"true").addClass("k-calendar-container").appendTo(U);
Y.options=X=X||{};
W=X.id;
if(W){W+="_dateview";
V.attr(v,W);
Y._dateViewID=W;
}Y.popup=new R.Popup(V,r(X.popup,X,{name:"Popup",isRtl:y.support.isRtl(X.anchor)}));
Y.div=V;
Y.value(X.value);
};
m.prototype={_calendar:function(){var X=this;
var U=X.calendar;
var W=X.options;
var V;
if(!U){V=a(q).attr(v,y.guid()).appendTo(X.popup.element).on(E,J).on(i,"td:has(.k-link)",K(X._click,X));
X.calendar=U=new R.Calendar(V);
X._setOptions(W);
y.calendar.makeUnselectable(U.element);
U.navigate(X._value||X._current,W.start);
X.value(X._value);
}},_setOptions:function(U){this.calendar.setOptions({focusOnNav:false,change:U.change,culture:U.culture,dates:U.dates,depth:U.depth,footer:U.footer,format:U.format,max:U.max,min:U.min,month:U.month,start:U.start});
},setOptions:function(V){var U=this.options;
this.options=r(U,V,{change:U.change,close:U.close,open:U.open});
if(this.calendar){this._setOptions(this.options);
}},destroy:function(){this.popup.destroy();
},open:function(){var U=this;
U._calendar();
U.popup.open();
},close:function(){this.popup.close();
},min:function(U){this._option(C,U);
},max:function(U){this._option(B,U);
},toggle:function(){var U=this;
U[U.popup.visible()?j:H]();
},move:function(V){var Y=this,W=V.keyCode,U=Y.calendar,X=V.ctrlKey&&W==A.DOWN||W==A.ENTER;
if(W==A.ESC){Y.close();
return;
}if(V.altKey){if(W==A.DOWN){Y.open();
V.preventDefault();
}else{if(W==A.UP){Y.close();
V.preventDefault();
}}return;
}if(!Y.popup.visible()){return;
}if(X&&U._cell.hasClass(N)){Y.close();
V.preventDefault();
return;
}Y._current=U._move(V);
},current:function(U){this._current=U;
this.calendar._focus(U);
},value:function(X){var W=this,U=W.calendar,V=W.options;
W._value=X;
W._current=new k(+M(X,V.min,V.max));
if(U){U.value(X);
}},_click:function(U){if(U.currentTarget.className.indexOf(N)!==-1){this.close();
}},_option:function(V,X){var W=this;
var U=W.calendar;
W.options[V]=X;
if(U){U[V](X);
}}};
m.normalize=F;
y.DateView=m;
var l=T.extend({init:function(X,Y){var Z=this,U,V;
T.fn.init.call(Z,X,Y);
X=Z.element;
Y=Z.options;
Y.min=I(X.attr("min"))||I(Y.min);
Y.max=I(X.attr("max"))||I(Y.max);
F(Y);
Z._wrapper();
Z.dateView=new m(r({},Y,{id:X.attr(v),anchor:Z.wrapper,change:function(){Z._change(this.value());
Z.close();
},close:function(aa){if(Z.trigger(j)){aa.preventDefault();
}else{X.attr(d,false);
V.attr(e,true);
}},open:function(ab){var ac=Z.options,aa;
if(Z.trigger(H)){ab.preventDefault();
}else{if(Z.element.val()!==Z._oldText){aa=I(X.val(),ac.parseFormats,ac.culture);
Z.dateView[aa?"current":"value"](aa);
}X.attr(d,true);
V.attr(e,false);
Z._updateARIA(aa);
}}}));
V=Z.dateView.div;
Z._icon();
try{X[0].setAttribute("type","text");
}catch(W){X[0].type="text";
}X.addClass("k-input").attr({role:"combobox","aria-expanded":false,"aria-owns":Z.dateView._dateViewID});
Z._reset();
Z._template();
U=X.is("[disabled]");
if(U){Z.enable(false);
}else{Z.readonly(X.is("[readonly]"));
}Z._old=Z._update(Y.value||Z.element.val());
Z._oldText=X.val();
y.notify(Z);
},events:[H,j,h],options:{name:"DatePicker",value:null,footer:"",format:"",culture:"",parseFormats:[],min:new Date(1900,0,1),max:new Date(2099,11,31),start:D,depth:D,animation:{},month:{},dates:[],ARIATemplate:'Current focused date is #=kendo.toString(data.current, "D")#'},setOptions:function(U){var V=this;
var W=V._value;
T.fn.setOptions.call(V,U);
U=V.options;
U.min=I(U.min);
U.max=I(U.max);
F(U);
V.dateView.setOptions(U);
if(W){V.element.val(y.toString(W,U.format,U.culture));
V._updateARIA(W);
}},_editable:function(X){var Z=this,W=Z._dateIcon.off(G),V=Z.element.off(G),aa=Z._inputWrapper.off(G),Y=X.readonly,U=X.disable;
if(!Y&&!U){aa.addClass(o).removeClass(P).on(u,Z._toggleHover);
V.removeAttr(p).removeAttr(L).attr(c,false).attr(f,false).on("keydown"+G,K(Z._keydown,Z)).on("focusout"+G,K(Z._blur,Z)).on("focus"+G,function(){Z._inputWrapper.addClass(s);
});
W.on(i,K(Z._click,Z)).on(E,J);
}else{aa.addClass(U?P:o).removeClass(U?o:P);
V.attr(p,U).attr(L,Y).attr(c,U).attr(f,Y);
}},readonly:function(U){this._editable({readonly:U===S?true:U,disable:false});
},enable:function(U){this._editable({readonly:false,disable:!(U=U===S?true:U)});
},destroy:function(){var U=this;
T.fn.destroy.call(U);
U.dateView.destroy();
U.element.off(G);
U._dateIcon.off(G);
U._inputWrapper.off(G);
if(U._form){U._form.off("reset",U._resetHandler);
}},open:function(){this.dateView.open();
},close:function(){this.dateView.close();
},min:function(U){return this._option(C,U);
},max:function(U){return this._option(B,U);
},value:function(V){var U=this;
if(V===S){return U._value;
}U._old=U._update(V);
if(U._old===null){U.element.val("");
}U._oldText=U.element.val();
},_toggleHover:function(U){a(U.currentTarget).toggleClass(t,U.type==="mouseenter");
},_blur:function(){var U=this,V=U.element.val();
U.close();
if(V!==U._oldText){U._change(V);
}U._inputWrapper.removeClass(s);
},_click:function(){var V=this,U=V.element;
V.dateView.toggle();
if(!y.support.touch&&U[0]!==b()){U.focus();
}},_change:function(V){var U=this;
V=U._update(V);
if(+U._old!=+V){U._old=V;
U._oldText=U.element.val();
U.element.trigger(h);
U.trigger(h);
}},_keydown:function(V){var W=this,U=W.dateView,X=W.element.val();
if(!U.popup.visible()&&V.keyCode==A.ENTER&&X!==W._oldText){W._change(X);
}else{U.move(V);
W._updateARIA(U._current);
}},_icon:function(){var W=this,U=W.element,V;
V=U.next("span.k-select");
if(!V[0]){V=a('<span unselectable="on" class="k-select"><span unselectable="on" class="k-icon k-i-calendar">select</span></span>').insertAfter(U);
}W._dateIcon=V.attr({role:"button","aria-controls":W.dateView._dateViewID});
},_option:function(U,X){var W=this,V=W.options;
if(X===S){return V[U];
}X=I(X,V.parseFormats,V.culture);
if(!X){return;
}V[U]=new k(+X);
W.dateView[U](X);
},_update:function(ac){var ab=this,aa=ab.options,Z=aa.min,Y=aa.max,U=ab._value,V=I(ac,aa.parseFormats,aa.culture),X=(V===null&&U===null)||(V instanceof Date&&U instanceof Date),W;
if(+V===+U&&X){W=y.toString(V,aa.format,aa.culture);
if(W!==ac){ab.element.val(V===null?ac:W);
}return V;
}if(V!==null&&w(V,Z)){V=M(V,Z,Y);
}else{if(!x(V,Z,Y)){V=null;
}}ab._value=V;
ab.dateView.value(V);
ab.element.val(V?y.toString(V,aa.format,aa.culture):ac);
ab._updateARIA(V);
return V;
},_wrapper:function(){var V=this,U=V.element,W;
W=U.parents(".k-datepicker");
if(!W[0]){W=U.wrap(O).parent().addClass("k-picker-wrap k-state-default");
W=W.wrap(O).parent();
}W[0].style.cssText=U[0].style.cssText;
U.css({width:"100%",height:U[0].style.height});
V.wrapper=W.addClass("k-widget k-datepicker k-header").addClass(U[0].className);
V._inputWrapper=a(W[0].firstChild);
},_reset:function(){var X=this,U=X.element,W=U.attr("form"),V=W?a("#"+W):U.closest("form");
if(V[0]){X._resetHandler=function(){X.value(U[0].defaultValue);
};
X._form=V.on("reset",X._resetHandler);
}},_template:function(){this._ariaTemplate=Q(this.options.ARIATemplate);
},_updateARIA:function(W){var V;
var X=this;
var U=X.dateView.calendar;
X.element.removeAttr("aria-activedescendant");
if(U){V=U._cell;
V.attr("aria-label",X._ariaTemplate({current:W||U.current()}));
X.element.attr("aria-activedescendant",V.attr("id"));
}}});
R.plugin(l);
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
