(function(b,a){a(["./kendo.core"],b);
})(function(){(function(a,an){var F=window.kendo,y=F.effects,t=a.each,w=a.extend,R=a.proxy,Z=F.support,h=Z.browser,ag=Z.transforms,aj=Z.transitions,W={scale:0,scalex:0,scaley:0,scale3d:0},al={translate:0,translatex:0,translatey:0,translate3d:0},z=(typeof document.documentElement.style.zoom!=="undefined")&&!ag,H=/matrix3?d?\s*\(.*,\s*([\d\.\-]+)\w*?,\s*([\d\.\-]+)\w*?,\s*([\d\.\-]+)\w*?,\s*([\d\.\-]+)\w*?/i,o=/^(-?[\d\.\-]+)?[\w\s]*,?\s*(-?[\d\.\-]+)?[\w\s]*/i,am=/translatex?$/i,K=/(zoom|fade|expand)(\w+)/,X=/(zoom|fade|expand)/,ao=/[xy]$/i,af=["perspective","rotate","rotatex","rotatey","rotatez","rotate3d","scale","scalex","scaley","scalez","scale3d","skew","skewx","skewy","translate","translatex","translatey","translatez","translate3d","matrix","matrix3d"],ad=["rotate","scale","scalex","scaley","skew","skewx","skewy","translate","translatex","translatey","matrix"],ae={rotate:"deg",scale:"",skew:"px",translate:"px"},p=ag.css,V=Math.round,g="",S="px",I="none",e="auto",ap="width",A="height",B="hidden",L="origin",b="abortId",M="overflow",ak="translate",Q="position",l="completeCallback",ai=p+"transition",ab=p+"transform",f=p+"backface-visibility",P=p+"perspective",r="1500px",ac="perspective("+r+")",E=Z.mobileOS&&Z.mobileOS.majorVersion==7,s={left:{reverse:"right",property:"left",transition:"translatex",vertical:false,modifier:-1},right:{reverse:"left",property:"left",transition:"translatex",vertical:false,modifier:1},down:{reverse:"up",property:"top",transition:"translatey",vertical:true,modifier:1},up:{reverse:"down",property:"top",transition:"translatey",vertical:true,modifier:-1},top:{reverse:"bottom"},bottom:{reverse:"top"},"in":{reverse:"out",modifier:-1},out:{reverse:"in",modifier:1},vertical:{reverse:"vertical"},horizontal:{reverse:"horizontal"}};
F.directions=s;
w(a.fn,{kendoStop:function(aq,ar){if(aj){return y.stopQueue(this,aq||false,ar||false);
}else{return this.stop(aq,ar);
}}});
if(ag&&!aj){t(ad,function(aq,ar){a.fn[ar]=function(av){if(typeof av=="undefined"){return d(this,ar);
}else{var at=a(this)[0],au=ar+"("+av+ae[ar.replace(ao,"")]+")";
if(at.style.cssText.indexOf(ab)==-1){a(this).css(ab,au);
}else{at.style.cssText=at.style.cssText.replace(new RegExp(ar+"\\(.*?\\)","i"),au);
}}return this;
};
a.fx.step[ar]=function(at){a(at.elem)[ar](at.now);
};
});
var q=a.fx.prototype.cur;
a.fx.prototype.cur=function(){if(ad.indexOf(this.prop)!=-1){return parseFloat(a(this.elem)[this.prop]());
}return q.apply(this,arguments);
};
}F.toggleClass=function(at,ar,au,aq){if(ar){ar=ar.split(" ");
if(aj){au=w({exclusive:"all",duration:400,ease:"ease-out"},au);
at.css(ai,au.exclusive+" "+au.duration+"ms "+au.ease);
setTimeout(function(){at.css(ai,"").css(A);
},au.duration);
}t(ar,function(av,aw){at.toggleClass(aw,aq);
});
}return at;
};
F.parseEffects=function(ar,at){var aq={};
if(typeof ar==="string"){t(ar.split(" "),function(ax,aA){var ay=!X.test(aA),az=aA.replace(K,function(aD,aB,aC){return aB+":"+aC.toLowerCase();
}),av=az.split(":"),au=av[1],aw={};
if(av.length>1){aw.direction=(at&&ay?s[au].reverse:au);
}aq[av[0]]=aw;
});
}else{t(ar,function(av){var au=this.direction;
if(au&&at&&!X.test(av)){this.direction=s[au].reverse;
}aq[av]=this;
});
}return aq;
};
function O(aq){return parseInt(aq,10);
}function N(aq,ar){return O(aq.css(ar));
}function G(ar){var aq=[];
for(var at in ar){aq.push(at);
}return aq;
}function Y(ar){for(var aq in ar){if(af.indexOf(aq)!=-1&&ad.indexOf(aq)==-1){delete ar[aq];
}}return ar;
}function J(ar,aw){var ax=[],aq={},av,au,ay,at;
for(au in aw){av=au.toLowerCase();
at=ag&&af.indexOf(av)!=-1;
if(!Z.hasHW3D&&at&&ad.indexOf(av)==-1){delete aw[au];
}else{ay=aw[au];
if(at){ax.push(au+"("+ay+")");
}else{aq[au]=ay;
}}}if(ax.length){aq[ab]=ax.join(" ");
}return aq;
}if(aj){w(y,{transition:function(at,aw,av){var aq,ar=0,au=at.data("keys")||[],az;
av=w({duration:200,ease:"ease-out",complete:null,exclusive:"all"},av);
var ay=false;
var ax=function(){if(!ay){ay=true;
if(az){clearTimeout(az);
az=null;
}at.removeData(b).dequeue().css(ai,"").css(ai);
av.complete.call(at);
}};
av.duration=a.fx?a.fx.speeds[av.duration]||av.duration:av.duration;
aq=J(at,aw);
a.merge(au,G(aq));
at.data("keys",a.unique(au)).height();
at.css(ai,av.exclusive+" "+av.duration+"ms "+av.ease).css(ai);
at.css(aq).css(ab);
if(aj.event){at.one(aj.event,ax);
if(av.duration!==0){ar=500;
}}az=setTimeout(ax,av.duration+ar);
at.data(b,az);
at.data(l,ax);
},stopQueue:function(au,aq,av){var at,ax=au.data("keys"),aw=(!av&&ax),ar=au.data(l);
if(aw){at=F.getComputedStyles(au[0],ax);
}if(ar){ar();
}if(aw){au.css(at);
}return au.removeData("keys").stop(aq);
}});
}function d(ar,au){if(ag){var av=ar.css(ab);
if(av==I){return au=="scale"?1:0;
}var at=av.match(new RegExp(au+"\\s*\\(([\\d\\w\\.]+)")),aq=0;
if(at){aq=O(at[1]);
}else{at=av.match(H)||[0,0,0,0,0];
au=au.toLowerCase();
if(am.test(au)){aq=parseFloat(at[3]/at[2]);
}else{if(au=="translatey"){aq=parseFloat(at[4]/at[2]);
}else{if(au=="scale"){aq=parseFloat(at[2]);
}else{if(au=="rotate"){aq=parseFloat(Math.atan2(at[2],at[1]));
}}}}}return aq;
}else{return parseFloat(ar.css(au));
}}var v=F.Class.extend({init:function(aq,ar){var at=this;
at.element=aq;
at.effects=[];
at.options=ar;
at.restore=[];
},run:function(aw){var aF=this,au,az,aA,aB=aw.length,ax=aF.element,aC=aF.options,at=a.Deferred(),aD={},ay={},aE,aq,ar;
aF.effects=aw;
at.then(a.proxy(aF,"complete"));
ax.data("animating",true);
for(az=0;
az<aB;
az++){au=aw[az];
au.setReverse(aC.reverse);
au.setOptions(aC);
aF.addRestoreProperties(au.restore);
au.prepare(aD,ay);
aq=au.children();
for(aA=0,ar=aq.length;
aA<ar;
aA++){aq[aA].duration(aC.duration).run();
}}for(var av in aC.effects){w(ay,aC.effects[av].properties);
}if(!ax.is(":visible")){w(aD,{display:ax.data("olddisplay")||"block"});
}if(ag&&!aC.reset){aE=ax.data("targetTransform");
if(aE){aD=w(aE,aD);
}}aD=J(ax,aD);
if(ag&&!aj){aD=Y(aD);
}ax.css(aD).css(ab);
for(az=0;
az<aB;
az++){aw[az].setup();
}if(aC.init){aC.init();
}ax.data("targetTransform",ay);
y.animate(ax,ay,w({},aC,{complete:at.resolve}));
return at.promise();
},stop:function(){a(this.element).kendoStop(true,true);
},addRestoreProperties:function(au){var aq=this.element,av,ar=0,at=au.length;
for(;
ar<at;
ar++){av=au[ar];
this.restore.push(av);
if(!aq.data(av)){aq.data(av,aq.css(av));
}}},restoreCallback:function(){var aq=this.element;
for(var ar=0,at=this.restore.length;
ar<at;
ar++){var au=this.restore[ar];
aq.css(au,aq.data(au));
}},complete:function(){var aw=this,at=0,ar=aw.element,av=aw.options,aq=aw.effects,au=aq.length;
ar.removeData("animating").dequeue();
if(av.hide){ar.data("olddisplay",ar.css("display")).hide();
}this.restoreCallback();
if(z&&!ag){setTimeout(a.proxy(this,"restoreCallback"),0);
}for(;
at<au;
at++){aq[at].teardown();
}if(av.completeCallback){av.completeCallback(ar);
}}});
y.promise=function(aw,ax){var au=[],ar,av=new v(aw,ax),ay=F.parseEffects(ax.effects),aq;
ax.effects=ay;
for(var at in ay){ar=y[i(at)];
if(ar){aq=new ar(aw,ay[at].direction);
au.push(aq);
}}if(au[0]){av.run(au);
}else{if(!aw.is(":visible")){aw.css({display:aw.data("olddisplay")||"block"}).css("display");
}if(ax.init){ax.init();
}aw.dequeue();
av.complete();
}};
w(y,{animate:function(aq,at,ar){var au=ar.transition!==false;
delete ar.transition;
if(aj&&"transition" in y&&au){y.transition(aq,at,ar);
}else{if(ag){aq.animate(Y(at),{queue:false,show:false,hide:false,duration:ar.duration,complete:ar.complete});
}else{aq.each(function(){var av=a(this),aw={};
t(af,function(aA,aG){var aD,ax=at?at[aG]+" ":null;
if(ax){var aF=at;
if(aG in W&&at[aG]!==an){aD=ax.match(o);
if(ag){w(aF,{scale:+aD[0]});
}}else{if(aG in al&&at[aG]!==an){var aE=av.css(Q),aB=(aE=="absolute"||aE=="fixed");
if(!av.data(ak)){if(aB){av.data(ak,{top:N(av,"top")||0,left:N(av,"left")||0,bottom:N(av,"bottom"),right:N(av,"right")});
}else{av.data(ak,{top:N(av,"marginTop")||0,left:N(av,"marginLeft")||0});
}}var aC=av.data(ak);
aD=ax.match(o);
if(aD){var ay=aG==ak+"y"?+null:+aD[1],az=aG==ak+"y"?+aD[1]:+aD[2];
if(aB){if(!isNaN(aC.right)){if(!isNaN(ay)){w(aF,{right:aC.right-ay});
}}else{if(!isNaN(ay)){w(aF,{left:aC.left+ay});
}}if(!isNaN(aC.bottom)){if(!isNaN(az)){w(aF,{bottom:aC.bottom-az});
}}else{if(!isNaN(az)){w(aF,{top:aC.top+az});
}}}else{if(!isNaN(ay)){w(aF,{marginLeft:aC.left+ay});
}if(!isNaN(az)){w(aF,{marginTop:aC.top+az});
}}}}}if(!ag&&aG!="scale"&&aG in aF){delete aF[aG];
}if(aF){w(aw,aF);
}}});
if(h.msie){delete aw.scale;
}av.animate(aw,{queue:false,show:false,hide:false,duration:ar.duration,complete:ar.complete});
});
}}}});
y.animatedPromise=y.promise;
var u=F.Class.extend({init:function(ar,aq){var at=this;
at.element=ar;
at._direction=aq;
at.options={};
at._additionalEffects=[];
if(!at.restore){at.restore=[];
}},reverse:function(){this._reverse=true;
return this.run();
},play:function(){this._reverse=false;
return this.run();
},add:function(aq){this._additionalEffects.push(aq);
return this;
},direction:function(aq){this._direction=aq;
return this;
},duration:function(aq){this._duration=aq;
return this;
},compositeRun:function(){var at=this,ar=new v(at.element,{reverse:at._reverse,duration:at._duration}),aq=at._additionalEffects.concat([at]);
return ar.run(aq);
},run:function(){if(this._additionalEffects&&this._additionalEffects[0]){return this.compositeRun();
}var aB=this,au=aB.element,aw=0,ay=aB.restore,ax=ay.length,aC,at=a.Deferred(),az={},av={},aA,aq=aB.children(),ar=aq.length;
at.then(a.proxy(aB,"_complete"));
au.data("animating",true);
for(aw=0;
aw<ax;
aw++){aC=ay[aw];
if(!au.data(aC)){au.data(aC,au.css(aC));
}}for(aw=0;
aw<ar;
aw++){aq[aw].duration(aB._duration).run();
}aB.prepare(az,av);
if(!au.is(":visible")){w(az,{display:au.data("olddisplay")||"block"});
}if(ag){aA=au.data("targetTransform");
if(aA){az=w(aA,az);
}}az=J(au,az);
if(ag&&!aj){az=Y(az);
}au.css(az).css(ab);
aB.setup();
au.data("targetTransform",av);
y.animate(au,av,{duration:aB._duration,complete:at.resolve});
return at.promise();
},stop:function(){var at=0,aq=this.children(),ar=aq.length;
for(at=0;
at<ar;
at++){aq[at].stop();
}a(this.element).kendoStop(true,true);
return this;
},restoreCallback:function(){var aq=this.element;
for(var ar=0,at=this.restore.length;
ar<at;
ar++){var au=this.restore[ar];
aq.css(au,aq.data(au));
}},_complete:function(){var ar=this,aq=ar.element;
aq.removeData("animating").dequeue();
ar.restoreCallback();
if(ar.shouldHide()){aq.data("olddisplay",aq.css("display")).hide();
}if(z&&!ag){setTimeout(a.proxy(ar,"restoreCallback"),0);
}ar.teardown();
},setOptions:function(aq){w(true,this.options,aq);
},children:function(){return[];
},shouldHide:a.noop,setup:a.noop,prepare:a.noop,teardown:a.noop,directions:[],setReverse:function(aq){this._reverse=aq;
return this;
}});
function i(aq){return aq.charAt(0).toUpperCase()+aq.substring(1);
}function m(au,aq){var at=u.extend(aq),ar=at.prototype.directions;
y[i(au)]=at;
y.Element.prototype[au]=function(av,aw,ax,ay){return new at(this.element,av,aw,ax,ay);
};
t(ar,function(av,aw){y.Element.prototype[au+i(aw)]=function(ax,ay,az){return new at(this.element,aw,ax,ay,az);
};
});
}var x=["left","right","up","down"],D=["in","out"];
m("slideIn",{directions:x,divisor:function(aq){this.options.divisor=aq;
return this;
},prepare:function(aw,at){var ay=this,az,ar=ay.element,aq=s[ay._direction],av=-aq.modifier*(aq.vertical?ar.outerHeight():ar.outerWidth()),ax=av/(ay.options&&ay.options.divisor||1)+S,au="0px";
if(ay._reverse){az=aw;
aw=at;
at=az;
}if(ag){aw[aq.transition]=ax;
at[aq.transition]=au;
}else{aw[aq.property]=ax;
at[aq.property]=au;
}}});
m("tile",{directions:x,init:function(ar,aq,at){u.prototype.init.call(this,ar,aq);
this.options={previous:at};
},previousDivisor:function(aq){this.options.previousDivisor=aq;
return this;
},children:function(){var aw=this,av=aw._reverse,au=aw.options.previous,at=aw.options.previousDivisor||1,ar=aw._direction;
var aq=[F.fx(aw.element).slideIn(ar).setReverse(av)];
if(au){aq.push(F.fx(au).slideIn(s[ar].reverse).divisor(at).setReverse(!av));
}return aq;
}});
function n(at,au,ar,aq){m(at,{directions:D,startValue:function(av){this._startValue=av;
return this;
},endValue:function(av){this._endValue=av;
return this;
},shouldHide:function(){return this._shouldHide;
},prepare:function(ay,av){var aC=this,aB,aw,ax=this._direction==="out",az=aC.element.data(au),aA=!(isNaN(az)||az==ar);
if(aA){aB=az;
}else{if(typeof this._startValue!=="undefined"){aB=this._startValue;
}else{aB=ax?ar:aq;
}}if(typeof this._endValue!=="undefined"){aw=this._endValue;
}else{aw=ax?aq:ar;
}if(this._reverse){ay[au]=aw;
av[au]=aB;
}else{ay[au]=aB;
av[au]=aw;
}aC._shouldHide=av[au]===aq;
}});
}n("fade","opacity",1,0);
n("zoom","scale",1,0.01);
m("slideMargin",{prepare:function(ay,ar){var az=this,aq=az.element,av=az.options,aw=aq.data(L),au=av.offset,at,ax=az._reverse;
if(!ax&&aw===null){aq.data(L,parseFloat(aq.css("margin-"+av.axis)));
}at=(aq.data(L)||0);
ar["margin-"+av.axis]=!ax?at+au:at;
}});
m("slideTo",{prepare:function(aw,ar){var ax=this,aq=ax.element,au=ax.options,at=au.offset.split(","),av=ax._reverse;
if(ag){ar.translatex=!av?at[0]:0;
ar.translatey=!av?at[1]:0;
}else{ar.left=!av?at[0]:0;
ar.top=!av?at[1]:0;
}aq.css("left");
}});
m("expand",{directions:["horizontal","vertical"],restore:[M],prepare:function(aA,ar){var aB=this,aq=aB.element,av=aB.options,ay=aB._reverse,aw=aB._direction==="vertical"?A:ap,az=aq[0].style[aw],au=aq.data(aw),at=parseFloat(au||az),ax=V(aq.css(aw,e)[aw]());
aA.overflow=B;
at=(av&&av.reset)?ax||at:at||ax;
ar[aw]=(ay?0:at)+S;
aA[aw]=(ay?at:0)+S;
if(au===an){aq.data(aw,az);
}},shouldHide:function(){return this._reverse;
},teardown:function(){var au=this,aq=au.element,at=au._direction==="vertical"?A:ap,ar=aq.data(at);
if(ar==e||ar===g){setTimeout(function(){aq.css(at,e).css(at);
},0);
}}});
var aa={position:"absolute",marginLeft:0,marginTop:0,scale:1};
m("transfer",{init:function(aq,ar){this.element=aq;
this.options={target:ar};
this.restore=[];
},setup:function(){this.element.appendTo(document.body);
},prepare:function(ax,at){var ay=this,ar=ay.element,av=y.box(ar),au=y.box(ay.options.target),aq=d(ar,"scale"),aw=y.fillScale(au,av),az=y.transformOrigin(au,av);
w(ax,aa);
at.scale=1;
ar.css(ab,"scale(1)").css(ab);
ar.css(ab,"scale("+aq+")");
ax.top=av.top;
ax.left=av.left;
ax.transformOrigin=az.x+S+" "+az.y+S;
if(ay._reverse){ax.scale=aw;
}else{at.scale=aw;
}}});
var k={top:"rect(auto auto $size auto)",bottom:"rect($size auto auto auto)",left:"rect(auto $size auto auto)",right:"rect(auto auto auto $size)"};
var U={top:{start:"rotatex(0deg)",end:"rotatex(180deg)"},bottom:{start:"rotatex(-180deg)",end:"rotatex(0deg)"},left:{start:"rotatey(0deg)",end:"rotatey(-180deg)"},right:{start:"rotatey(180deg)",end:"rotatey(0deg)"}};
function j(aq,ar){var au=F.directions[ar].vertical,at=(aq[au?A:ap]()/2)+"px";
return k[ar].replace("$size",at);
}m("turningPage",{directions:x,init:function(at,ar,aq){u.prototype.init.call(this,at,ar);
this._container=aq;
},prepare:function(av,ar){var aw=this,at=aw._reverse,aq=at?s[aw._direction].reverse:aw._direction,au=U[aq];
av.zIndex=1;
if(aw._clipInHalf){av.clip=j(aw._container,F.directions[aq].reverse);
}av[f]=B;
ar[ab]=ac+(at?au.start:au.end);
av[ab]=ac+(at?au.end:au.start);
},setup:function(){this._container.append(this.element);
},face:function(aq){this._face=aq;
return this;
},shouldHide:function(){var at=this,ar=at._reverse,aq=at._face;
return(ar&&!aq)||(!ar&&aq);
},clipInHalf:function(aq){this._clipInHalf=aq;
return this;
},temporary:function(){this.element.addClass("temp-page");
return this;
}});
m("staticPage",{directions:x,init:function(at,ar,aq){u.prototype.init.call(this,at,ar);
this._container=aq;
},restore:["clip"],prepare:function(at,ar){var au=this,aq=au._reverse?s[au._direction].reverse:au._direction;
at.clip=j(au._container,aq);
at.opacity=0.999;
ar.opacity=1;
},shouldHide:function(){var at=this,ar=at._reverse,aq=at._face;
return(ar&&!aq)||(!ar&&aq);
},face:function(aq){this._face=aq;
return this;
}});
m("pageturn",{directions:["horizontal","vertical"],init:function(at,ar,au,aq){u.prototype.init.call(this,at,ar);
this.options={};
this.options.face=au;
this.options.back=aq;
},children:function(){var az=this,av=az.options,ar=az._direction==="horizontal"?"left":"top",ax=F.directions[ar].reverse,aw=az._reverse,ay,au=av.face.clone(true).removeAttr("id"),aq=av.back.clone(true).removeAttr("id"),at=az.element;
if(aw){ay=ar;
ar=ax;
ax=ay;
}return[F.fx(av.face).staticPage(ar,at).face(true).setReverse(aw),F.fx(av.back).staticPage(ax,at).setReverse(aw),F.fx(au).turningPage(ar,at).face(true).clipInHalf(true).temporary().setReverse(aw),F.fx(aq).turningPage(ax,at).clipInHalf(true).temporary().setReverse(aw)];
},prepare:function(ar,aq){ar[P]=r;
ar.transformStyle="preserve-3d";
ar.opacity=0.999;
aq.opacity=1;
},teardown:function(){this.element.find(".temp-page").remove();
}});
m("flip",{directions:["horizontal","vertical"],init:function(at,ar,au,aq){u.prototype.init.call(this,at,ar);
this.options={};
this.options.face=au;
this.options.back=aq;
},children:function(){var ax=this,at=ax.options,aq=ax._direction==="horizontal"?"left":"top",av=F.directions[aq].reverse,au=ax._reverse,aw,ar=ax.element;
if(au){aw=aq;
aq=av;
av=aw;
}return[F.fx(at.face).turningPage(aq,ar).face(true).setReverse(au),F.fx(at.back).turningPage(av,ar).setReverse(au)];
},prepare:function(aq){aq[P]=r;
aq.transformStyle="preserve-3d";
}});
var T=!Z.mobileOS.android;
var C=".km-touch-scrollbar, .km-actionsheet-wrapper";
m("replace",{_before:a.noop,_after:a.noop,init:function(aq,ar,at){u.prototype.init.call(this,aq);
this._previous=a(ar);
this._transitionClass=at;
},duration:function(){throw new Error("The replace effect does not support duration setting; the effect duration may be customized through the transition class rule");
},beforeTransition:function(aq){this._before=aq;
return this;
},afterTransition:function(aq){this._after=aq;
return this;
},_both:function(){return a().add(this._element).add(this._previous);
},_containerClass:function(){var ar=this._direction,aq="k-fx k-fx-start k-fx-"+this._transitionClass;
if(ar){aq+=" k-fx-"+ar;
}if(this._reverse){aq+=" k-fx-reverse";
}return aq;
},complete:function(ar){if(!this.deferred||(ar&&a(ar.target).is(C))){return;
}var aq=this.container;
aq.removeClass("k-fx-end").removeClass(this._containerClass()).off(aj.event,this.completeProxy);
this._previous.hide().removeClass("k-fx-current");
this.element.removeClass("k-fx-next");
if(T){aq.css(M,"");
}if(!this.isAbsolute){this._both().css(Q,"");
}this.deferred.resolve();
delete this.deferred;
},run:function(){if(this._additionalEffects&&this._additionalEffects[0]){return this.compositeRun();
}var ay=this,au=ay.element,ax=ay._previous,ar=au.parents().filter(ax.parents()).first(),aq=ay._both(),at=a.Deferred(),aw=au.css(Q),av;
if(!ar.length){ar=au.parent();
}this.container=ar;
this.deferred=at;
this.isAbsolute=aw=="absolute";
if(!this.isAbsolute){aq.css(Q,"absolute");
}if(T){av=ar.css(M);
ar.css(M,"hidden");
}if(!aj){this.complete();
}else{au.addClass("k-fx-hidden");
ar.addClass(this._containerClass());
this.completeProxy=a.proxy(this,"complete");
ar.on(aj.event,this.completeProxy);
F.animationFrame(function(){au.removeClass("k-fx-hidden").addClass("k-fx-next");
ax.css("display","").addClass("k-fx-current");
ay._before(ax,au);
F.animationFrame(function(){ar.removeClass("k-fx-start").addClass("k-fx-end");
ay._after(ax,au);
});
});
}return at.promise();
},stop:function(){this.complete();
}});
var c=F.Class.extend({init:function(){var aq=this;
aq._tickProxy=R(aq._tick,aq);
aq._started=false;
},tick:a.noop,done:a.noop,onEnd:a.noop,onCancel:a.noop,start:function(){if(!this.enabled()){return;
}if(!this.done()){this._started=true;
F.animationFrame(this._tickProxy);
}else{this.onEnd();
}},enabled:function(){return true;
},cancel:function(){this._started=false;
this.onCancel();
},_tick:function(){var aq=this;
if(!aq._started){return;
}aq.tick();
if(!aq.done()){F.animationFrame(aq._tickProxy);
}else{aq._started=false;
aq.onEnd();
}}});
var ah=c.extend({init:function(aq){var ar=this;
w(ar,aq);
c.fn.init.call(ar);
},done:function(){return this.timePassed()>=this.duration;
},timePassed:function(){return Math.min(this.duration,(new Date())-this.startDate);
},moveTo:function(ar){var at=this,aq=at.movable;
at.initial=aq[at.axis];
at.delta=ar.location-at.initial;
at.duration=typeof ar.duration=="number"?ar.duration:300;
at.tick=at._easeProxy(ar.ease);
at.startDate=new Date();
at.start();
},_easeProxy:function(aq){var ar=this;
return function(){ar.movable.moveAxis(ar.axis,aq(ar.timePassed(),ar.initial,ar.delta,ar.duration));
};
}});
w(ah,{easeOutExpo:function(au,aq,ar,at){return(au==at)?aq+ar:ar*(-Math.pow(2,-10*au/at)+1)+aq;
},easeOutBack:function(av,aq,ar,at,au){au=1.70158;
return ar*((av=av/at-1)*av*((au+1)*av+au)+1)+aq;
}});
y.Animation=c;
y.Transition=ah;
y.createEffect=m;
y.box=function(aq){aq=a(aq);
var ar=aq.offset();
ar.width=aq.outerWidth();
ar.height=aq.outerHeight();
return ar;
};
y.transformOrigin=function(aq,ar){var at=(aq.left-ar.left)*ar.width/(ar.width-aq.width),au=(aq.top-ar.top)*ar.height/(ar.height-aq.height);
return{x:isNaN(at)?0:at,y:isNaN(au)?0:au};
};
y.fillScale=function(aq,ar){return Math.min(aq.width/ar.width,aq.height/ar.height);
};
y.fitScale=function(aq,ar){return Math.max(aq.width/ar.width,aq.height/ar.height);
};
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
