(function(b,a){a(["./kendo.data","./kendo.popup","./kendo.window","./kendo.resizable","./kendo.gantt.list","./kendo.gantt.timeline","./kendo.grid","./kendo.pdf"],b);
})(function(){(function(a,Z){var E=window.kendo;
var e=E.support.browser;
var I=E.Observable;
var aa=E.ui.Widget;
var j=E.data.DataSource;
var K=E.data.ObservableObject;
var J=E.data.ObservableArray;
var O=E.data.Query;
var B=a.isArray;
var A=a.inArray;
var C=E.isFunction;
var N=a.proxy;
var r=a.extend;
var D=a.isPlainObject;
var G=a.map;
var F=E.keys;
var H=".kendoGantt";
var L="p0";
var U="tabIndex";
var g="click";
var ab="width";
var T="string";
var n={down:{origin:"bottom center",position:"top center"},up:{origin:"top center",position:"bottom center"}};
var d="aria-activedescendant";
var b="gantt_active_cell";
var c="action-option-focused";
var o=".";
var V="Are you sure you want to delete this task?";
var m="Are you sure you want to delete this dependency?";
var f='<button class="#=styles.button# #=className#" #if (action) {#data-action="#=action#"#}#><span class="#=iconClass#"></span>#=text#</button>';
var h='<a class="#=className#" #=attr# href="\\#">#=text#</a>';
var z=E.template('<ul class="#=styles.viewsWrapper#">#for(var view in views){#<li class="#=styles.viewButtonDefault# #=styles.viewButton#-#= view.toLowerCase() #" data-#=ns#name="#=view#"><a href="\\#" class="#=styles.link#">#=views[view].title#</a></li>#}#</ul>');
var W=E.template('<div class="#=styles.popupWrapper#"><ul class="#=styles.popupList#" role="listbox">#for(var i = 0, l = actions.length; i < l; i++){#<li class="#=styles.item#" data-action="#=actions[i].data#" role="option">#=actions[i].text#</span>#}#</ul></div>');
var l=function(ad,ae){var ac={name:ae.field};
var af=ae.model.fields[ae.field].validation;
if(af&&D(af)&&af.message){ac[E.attr("dateCompare-msg")]=af.message;
}a('<input type="text" required '+E.attr("type")+'="date" '+E.attr("role")+'="datetimepicker" '+E.attr("bind")+'="value:'+ae.field+'" '+E.attr("validate")+"='true' />").attr(ac).appendTo(ad);
a("<span "+E.attr("for")+'="'+ae.field+'" class="k-invalid-msg"/>').hide().appendTo(ad);
};
var Q=function(ac,ad){a('<a href="#" class="'+ad.styles.button+'">'+ad.messages.assingButton+"</a>").click(ad.click).appendTo(ac);
};
var x={wrapper:"k-widget k-gantt",listWrapper:"k-gantt-layout k-gantt-treelist",list:"k-gantt-treelist",timelineWrapper:"k-gantt-layout k-gantt-timeline",timeline:"k-gantt-timeline",splitBarWrapper:"k-splitbar k-state-default k-splitbar-horizontal k-splitbar-draggable-horizontal k-gantt-layout",splitBar:"k-splitbar",splitBarHover:"k-splitbar-horizontal-hover",popupWrapper:"k-list-container",popupList:"k-list k-reset",resizeHandle:"k-resize-handle",icon:"k-icon",item:"k-item",line:"k-line",buttonDelete:"k-gantt-delete",buttonCancel:"k-gantt-cancel",buttonSave:"k-gantt-update",primary:"k-primary",hovered:"k-state-hover",selected:"k-state-selected",focused:"k-state-focused",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",popup:{form:"k-popup-edit-form",editForm:"k-gantt-edit-form",formContainer:"k-edit-form-container",resourcesFormContainer:"k-resources-form-container",message:"k-popup-message",buttonsContainer:"k-edit-buttons k-state-default",button:"k-button",editField:"k-edit-field",editLabel:"k-edit-label",resourcesField:"k-gantt-resources"},toolbar:{headerWrapper:"k-floatwrap k-header k-gantt-toolbar",footerWrapper:"k-floatwrap k-header k-gantt-toolbar",toolbar:"k-gantt-toolbar",views:"k-gantt-views",viewsWrapper:"k-reset k-header k-gantt-views",actions:"k-gantt-actions",button:"k-button k-button-icontext",iconPlus:"k-icon k-i-plus",iconPdf:"k-icon k-i-pdf",viewButtonDefault:"k-state-default",viewButton:"k-view",link:"k-link",pdfButton:"k-gantt-pdf",appendButton:"k-gantt-create"}};
function S(ac){return"["+E.attr("uid")+(ac?"='"+ac+"']":"]");
}function Y(ac){delete ac.name;
delete ac.prefix;
delete ac.remove;
delete ac.edit;
delete ac.add;
delete ac.navigate;
return ac;
}function k(ag){if(ag.filter("[name=end], [name=start]").length){var af=ag.attr("name");
var ai=E.widgetInstance(ag,E.ui);
var ad={};
var ac=ag;
var ae;
var ah;
while(ac!==window&&!ae){ac=ac.parent();
ae=ac.data("kendoEditable");
}ah=ae?ae.options.model:null;
if(!ah){return true;
}ad.start=ah.start;
ad.end=ah.end;
ad[af]=ai?ai.value():E.parseDate(ag.value());
return ad.start<=ad.end;
}return true;
}function s(ag,ac){var ah=ag.parents("["+E.attr("role")+'="gantt"]');
var af=[];
var ae=R(ah);
ag.attr(U,0);
if(ac){ae.each(function(ai,aj){af[ai]=a(aj).scrollTop();
});
}try{ag[0].setActive();
}catch(ad){ag[0].focus();
}if(ac){ae.each(function(ai,aj){a(aj).scrollTop(af[ai]);
});
}}function R(ac){return a(ac).parentsUntil("body").filter(function(af,ae){var ad=E.getComputedStyles(ae,["overflow"]);
return ad.overflow!="visible";
}).add(window);
}var X=I.extend({init:function(ac,ad){I.fn.init.call(this);
this.element=ac;
this.options=r(true,{},this.options,ad);
this._popup();
},options:{direction:"down",navigatable:false},_current:function(ae){var ad=t.styles;
var ac=this.list.find(o+ad.focused);
var af=ac[ae]();
if(af.length){ac.removeClass(ad.focused).removeAttr("id");
af.addClass(ad.focused).attr("id",c);
this.list.find("ul").removeAttr(d).attr(d,c);
}},_popup:function(){var ag=this;
var ad=t.styles;
var ae="li"+o+ad.item;
var ac=this.options.messages.actions;
var af=this.options.navigatable;
this.list=a(W({styles:ad,actions:[{data:"add",text:ac.addChild},{data:"insert-before",text:ac.insertBefore},{data:"insert-after",text:ac.insertAfter}]}));
this.element.append(this.list);
this.popup=new E.ui.Popup(this.list,r({anchor:this.element,open:function(ah){ag._adjustListWidth();
},animation:this.options.animation},n[this.options.direction]));
this.element.on(g+H,o+ad.toolbar.appendButton,function(ai){var aj=a(this);
var ah=aj.attr(E.attr("action"));
ai.preventDefault();
if(ah){ag.trigger("command",{type:ah});
}else{ag.popup.open();
if(af){ag.list.find("li:first").addClass(ad.focused).attr("id",c).end().find("ul").attr({TABINDEX:0,"aria-activedescendant":c}).focus();
}}});
this.list.find(ae).hover(function(){a(this).addClass(ad.hovered);
},function(){a(this).removeClass(ad.hovered);
}).end().on(g+H,ae,function(ah){ag.trigger("command",{type:a(this).attr(E.attr("action"))});
ag.popup.close();
});
if(af){this.popup.bind("close",function(){ag.list.find(ae).removeClass(ad.focused).end().find("ul").attr(U,0);
ag.element.parents("["+E.attr("role")+'="gantt"]').find(o+ad.gridContent+" > table:first").focus();
});
this.list.find("ul").on("keydown"+H,function(ah){var ai=ah.keyCode;
switch(ai){case F.UP:ah.preventDefault();
ag._current("prev");
break;
case F.DOWN:ah.preventDefault();
ag._current("next");
break;
case F.ENTER:ag.list.find(o+ad.focused).click();
break;
case F.ESC:ah.preventDefault();
ag.popup.close();
break;
}});
}},_adjustListWidth:function(){var ae=this.list;
var af=ae[0].style.width;
var ag=this.element;
var ac;
var ad;
if(!ae.data(ab)&&af){return;
}ac=window.getComputedStyle?window.getComputedStyle(ag[0],null):0;
ad=ac?parseFloat(ac.width):ag.outerWidth();
if(ac&&(e.mozilla||e.msie)){ad+=parseFloat(ac.paddingLeft)+parseFloat(ac.paddingRight)+parseFloat(ac.borderLeftWidth)+parseFloat(ac.borderRightWidth);
}if(ae.css("box-sizing")!=="border-box"){af=ad-(ae.outerWidth()-ae.width());
}else{af=ad;
}ae.css({fontFamily:ag.css("font-family"),width:af}).data(ab,af);
},destroy:function(){this.popup.destroy();
this.element.off(H);
this.list.off(H);
this.unbind();
}});
var i=function(ad,ac){return function(ag){ag=B(af)?{data:ag}:ag;
var af=ag||{};
var ae=af.data;
af.data=ae;
if(!(af instanceof ad)&&af instanceof j){throw new Error("Incorrect DataSource type. Only "+ac+" instances are supported");
}return af instanceof ad?af:new ad(af);
};
};
var v=E.data.Model.define({id:"id",fields:{id:{type:"number"},predecessorId:{type:"number"},successorId:{type:"number"},type:{type:"number"}}});
var w=j.extend({init:function(ac){j.fn.init.call(this,r(true,{},{schema:{modelBase:v,model:v}},ac));
},successors:function(ac){return this._dependencies("predecessorId",ac);
},predecessors:function(ac){return this._dependencies("successorId",ac);
},dependencies:function(ac){var ad=this.predecessors(ac);
var ae=this.successors(ac);
ad.push.apply(ad,ae);
return ad;
},_dependencies:function(ad,af){var ac=this.view();
var ae={field:ad,operator:"eq",value:af};
ac=new O(ac).filter(ae).toArray();
return ac;
}});
w.create=i(w,"GanttDependencyDataSource");
var y=E.data.Model.define({duration:function(){var ac=this.end;
var ad=this.start;
return ac-ad;
},isMilestone:function(){return this.duration()===0;
},_offset:function(af){var ac=["start","end"];
var ae;
for(var ad=0;
ad<ac.length;
ad++){ae=new Date(this.get(ac[ad]).getTime()+af);
this.set(ac[ad],ae);
}},id:"id",fields:{id:{type:"number"},parentId:{type:"number",defaultValue:null,validation:{required:true}},orderId:{type:"number",validation:{required:true}},title:{type:"string",defaultValue:""},start:{type:"date",validation:{required:true,dateCompare:k,message:"Start date should be before or equal to the end date"}},end:{type:"date",validation:{required:true,dateCompare:k,message:"End date should be after or equal to the start date"}},percentComplete:{type:"number",validation:{required:true,min:0,max:1,step:0.01}},summary:{type:"boolean"},expanded:{type:"boolean",defaultValue:true}}});
var u=j.extend({init:function(ac){j.fn.init.call(this,r(true,{},{schema:{modelBase:y,model:y}},ac));
},remove:function(ae){var ad=ae.get("parentId");
var ac=this.taskAllChildren(ae);
this._removeItems(ac);
ae=j.fn.remove.call(this,ae);
this._childRemoved(ad,ae.get("orderId"));
return ae;
},add:function(ac){if(!ac){return;
}ac=this._toGanttTask(ac);
return this.insert(this.taskSiblings(ac).length,ac);
},insert:function(ac,ad){if(!ad){return;
}ad=this._toGanttTask(ad);
ad.set("orderId",ac);
ad=j.fn.insert.call(this,ac,ad);
this._reorderSiblings(ad,this.taskSiblings(ad).length-1);
this._resolveSummaryFields(this.taskParent(ad));
return ad;
},taskChildren:function(af){var ac=this.view();
var ad={field:"parentId",operator:"eq",value:null};
var ae=this._sort||{field:"orderId",dir:"asc"};
var ag;
if(!!af){ag=af.get("id");
if(ag===Z||ag===null||ag===""){return[];
}ad.value=ag;
}ac=new O(ac).filter(ad).sort(ae).toArray();
return ac;
},taskAllChildren:function(ae){var ad=[];
var af=this;
var ac=function(ag){var ah=af.taskChildren(ag);
ad.push.apply(ad,ah);
G(ah,ac);
};
if(!!ae){ac(ae);
}else{ad=this.view();
}return ad;
},taskSiblings:function(ad){if(!ad){return null;
}var ac=this.taskParent(ad);
return this.taskChildren(ac);
},taskParent:function(ac){if(!ac||ac.get("parentId")===null){return null;
}return this.get(ac.parentId);
},taskLevel:function(ae){var ac=0;
var ad=this.taskParent(ae);
while(ad!==null){ac+=1;
ad=this.taskParent(ad);
}return ac;
},taskTree:function(ah){var ae=[];
var ad;
var ai=this.taskChildren(ah);
for(var af=0,ag=ai.length;
af<ag;
af++){ad=ai[af];
ae.push(ad);
if(ad.get("expanded")){var ac=this.taskTree(ad);
ae.push.apply(ae,ac);
}}return ae;
},update:function(ag,ah){var ai=this;
var af;
var ae=function(an,am){var aj=ai.taskAllChildren(an);
for(var ak=0,al=aj.length;
ak<al;
ak++){aj[ak]._offset(am);
}};
var ad=function(aj){var ak=aj.field;
var al=aj.sender;
switch(ak){case"start":ai._resolveSummaryStart(ai.taskParent(al));
ae(al,al.get(ak).getTime()-af.getTime());
break;
case"end":ai._resolveSummaryEnd(ai.taskParent(al));
break;
case"percentComplete":ai._resolveSummaryPercentComplete(ai.taskParent(al));
break;
case"orderId":ai._reorderSiblings(al,af);
break;
}};
if(ah.parentId!==Z){af=ag.get("parentId");
if(af!==ah.parentId){ag.set("parentId",ah.parentId);
ai._childRemoved(af,ag.get("orderId"));
ag.set("orderId",ai.taskSiblings(ag).length-1);
ai._resolveSummaryFields(ai.taskParent(ag));
}delete ah.parentId;
}ag.bind("change",ad);
for(var ac in ah){af=ag.get(ac);
ag.set(ac,ah[ac]);
}ag.unbind("change",ad);
},_resolveSummaryFields:function(ac){if(!ac){return;
}this._updateSummary(ac);
if(!this.taskChildren(ac).length){return;
}this._resolveSummaryStart(ac);
this._resolveSummaryEnd(ac);
this._resolveSummaryPercentComplete(ac);
},_resolveSummaryStart:function(ad){var ae=this;
var ac=function(ak){var af=ae.taskChildren(ak);
var aj=af[0].start.getTime();
var ag;
for(var ah=1,ai=af.length;
ah<ai;
ah++){ag=af[ah].start.getTime();
if(ag<aj){aj=ag;
}}return new Date(aj);
};
this._updateSummaryRecursive(ad,"start",ac);
},_resolveSummaryEnd:function(ad){var ae=this;
var ac=function(ak){var af=ae.taskChildren(ak);
var aj=af[0].end.getTime();
var ag;
for(var ah=1,ai=af.length;
ah<ai;
ah++){ag=af[ah].end.getTime();
if(ag>aj){aj=ag;
}}return new Date(aj);
};
this._updateSummaryRecursive(ad,"end",ac);
},_resolveSummaryPercentComplete:function(ad){var ae=this;
var ac=function(ag){var af=ae.taskChildren(ag);
var ah=new O(af).aggregate([{field:"percentComplete",aggregate:"average"}]);
return ah.percentComplete.average;
};
this._updateSummaryRecursive(ad,"percentComplete",ac);
},_updateSummaryRecursive:function(af,ad,ac){if(!af){return;
}var ag=ac(af);
af.set(ad,ag);
var ae=this.taskParent(af);
if(ae){this._updateSummaryRecursive(ae,ad,ac);
}},_childRemoved:function(ah,ae){var ag=ah===null?null:this.get(ah);
var ac=this.taskChildren(ag);
for(var ad=ae,af=ac.length;
ad<af;
ad++){ac[ad].set("orderId",ad);
}this._resolveSummaryFields(ag);
},_reorderSiblings:function(ak,ag){var ah=ak.get("orderId");
var ac=ah>ag;
var aj=ac?ag:ah;
var ad=ac?ah:ag;
var af=ac?aj:aj+1;
var ai=this.taskSiblings(ak);
ad=Math.min(ad,ai.length-1);
for(var ae=aj;
ae<=ad;
ae++){if(ai[ae]===ak){continue;
}ai[ae].set("orderId",af);
af+=1;
}},_updateSummary:function(ad){if(ad!==null){var ac=this.taskChildren(ad).length;
ad.set("summary",ac>0);
}},_toGanttTask:function(ac){if(!(ac instanceof y)){var ad=ac;
ac=this._createNewModel();
ac.accept(ad);
}return ac;
}});
u.create=i(u,"GanttDataSource");
r(true,E.data,{GanttDataSource:u,GanttTask:y,GanttDependencyDataSource:w,GanttDependency:v});
var q={desktop:{dateRange:l,resources:Q}};
var p=E.Observable.extend({init:function(ac,ad){E.Observable.fn.init.call(this);
this.element=ac;
this.options=r(true,{},this.options,ad);
this.createButton=this.options.createButton;
},fields:function(ad,ag){var aj=this;
var ah=this.options;
var af=ah.messages.editor;
var ai=ah.resources;
var ae;
var ac=function(ak){ak.preventDefault();
ai.editor(aj.container.find(o+t.styles.popup.resourcesField),ag);
};
if(ah.editable.template){ae=a.map(ag.fields,function(al,ak){return{field:ak};
});
}else{ae=[{field:"title",title:af.title},{field:"start",title:af.start,editor:ad.dateRange},{field:"end",title:af.end,editor:ad.dateRange},{field:"percentComplete",title:af.percentComplete,format:L}];
if(ag.get(ai.field)){ae.push({field:ai.field,title:af.resources,messages:af,editor:ad.resources,click:ac,styles:t.styles.popup});
}}return ae;
},_buildEditTemplate:function(ai,ae,ac){var al=this.options.resources;
var an=this.options.editable.template;
var am=r({},E.Template,this.options.templateSettings);
var aj=am.paramName;
var ak=t.styles.popup;
var af="";
if(an){if(typeof an===T){an=window.unescape(an);
}af+=(E.template(an,am))(ai);
}else{for(var ag=0,ah=ae.length;
ag<ah;
ag++){var ad=ae[ag];
af+='<div class="'+ak.editLabel+'"><label for="'+ad.field+'">'+(ad.title||ad.field||"")+"</label></div>";
if(ad.field===al.field){af+='<div class="'+ak.resourcesField+'" style="display:none"></div>';
}if((!ai.editable||ai.editable(ad.field))){ac.push(ad);
af+="<div "+E.attr("container-for")+'="'+ad.field+'" class="'+ak.editField+'"></div>';
}else{var ao="#:";
if(ad.field){ad=E.expr(ad.field,aj);
ao+=ad+"==null?'':"+ad;
}else{ao+="''";
}ao+="#";
ao=E.template(ao,am);
af+='<div class="'+ak.editField+'">'+ao(ai)+"</div>";
}}}return af;
}});
var M=p.extend({destroy:function(){this.close();
this.unbind();
},editTask:function(ac){this.editable=this._createPopupEditor(ac);
},close:function(){var ad=this;
var ac=function(){if(ad.editable){ad.editable.destroy();
ad.editable=null;
ad.container=null;
}if(ad.popup){ad.popup.destroy();
ad.popup=null;
}};
if(this.editable&&this.container.is(":visible")){this.container.data("kendoWindow").bind("deactivate",ac).close();
}else{ac();
}},showDialog:function(ag){var ac=ag.buttons;
var ai=t.styles.popup;
var ad=E.format('<div class="{0}"><div class="{1}"><p class="{2}">{3}</p><div class="{4}">',ai.form,ai.formContainer,ai.message,ag.text,ai.buttonsContainer);
for(var ae=0,af=ac.length;
ae<af;
ae++){ad+=this.createButton(ac[ae]);
}ad+="</div></div></div>";
var aj=this.element;
if(this.popup){this.popup.destroy();
}var ah=this.popup=a(ad).appendTo(aj).eq(0).on("click",o+ai.button,function(al){al.preventDefault();
ah.close();
var ak=a(al.currentTarget).index();
ac[ak].click();
}).kendoWindow({modal:true,resizable:false,draggable:false,title:ag.title,visible:false,close:function(){this.destroy();
aj.focus();
}}).getKendoWindow();
ah.center().open();
},_createPopupEditor:function(al){var am=this;
var aj={};
var ai=this.options.messages;
var ag=t.styles;
var ak=ag.popup;
var ah=E.format('<div {0}="{1}" class="{2} {3}"><div class="{4}">',E.attr("uid"),al.uid,ak.form,ak.editForm,ak.formContainer);
var af=this.fields(q.desktop,al);
var ad=[];
ah+=this._buildEditTemplate(al,af,ad);
ah+='<div class="'+ak.buttonsContainer+'">';
ah+=this.createButton({name:"update",text:ai.save,className:t.styles.primary});
ah+=this.createButton({name:"cancel",text:ai.cancel});
ah+=this.createButton({name:"delete",text:ai.destroy});
ah+="</div></div></div>";
var ac=this.container=a(ah).appendTo(this.element).eq(0).kendoWindow(r({modal:true,resizable:false,draggable:true,title:ai.editor.editorTitle,visible:false,close:function(an){if(an.userTriggered){if(am.trigger("cancel",{container:ac,model:al})){an.preventDefault();
}}}},aj));
var ae=ac.kendoEditable({fields:ad,model:al,clearContainer:false,validateOnBlur:true,target:am.options.target}).data("kendoEditable");
if(!this.trigger("edit",{container:ac,model:al})){ac.data("kendoWindow").center().open();
ac.on(g+H,o+ag.buttonCancel,function(an){an.preventDefault();
an.stopPropagation();
am.trigger("cancel",{container:ac,model:al});
});
ac.on(g+H,o+ag.buttonSave,function(an){an.preventDefault();
an.stopPropagation();
var ap=am.fields(q.desktop,al);
var at={};
var ao;
for(var aq=0,ar=ap.length;
aq<ar;
aq++){ao=ap[aq].field;
at[ao]=al.get(ao);
}am.trigger("save",{container:ac,model:al,updateInfo:at});
});
ac.on(g+H,o+ag.buttonDelete,function(an){an.preventDefault();
an.stopPropagation();
am.trigger("remove",{container:ac,model:al});
});
}else{am.trigger("cancel",{container:ac,model:al});
}return ae;
}});
var P=aa.extend({init:function(ac,ad){aa.fn.init.call(this,ac,ad);
this.wrapper=this.element;
this.model=this.options.model;
this.resourcesField=this.options.resourcesField;
this.createButton=this.options.createButton;
this._initContainer();
this._attachHandlers();
},events:["save"],open:function(){this.window.center().open();
this.grid.resize(true);
},close:function(){this.window.bind("deactivate",N(this.destroy,this)).close();
},destroy:function(){this._dettachHandlers();
this.grid.destroy();
this.grid=null;
this.window.destroy();
this.window=null;
aa.fn.destroy.call(this);
E.destroy(this.wrapper);
this.element=this.wrapper=null;
},_attachHandlers:function(){var ad=t.styles;
var ae=this.grid;
var ac=this._cancelProxy=N(this._cancel,this);
this.container.on(g+H,o+ad.buttonCancel,this._cancelProxy);
this._saveProxy=N(this._save,this);
this.container.on(g+H,o+ad.buttonSave,this._saveProxy);
this.window.bind("close",function(af){if(af.userTriggered){ac(af);
}});
ae.wrapper.on(g+H,"input[type='checkbox']",function(af){var ag=a(this);
var ai=a(ag).closest("tr");
var ah=ae.dataSource.getByUid(ai.attr(E.attr("uid")));
var aj=a(ag).is(":checked")?1:"";
ah.set("value",aj);
});
},_dettachHandlers:function(){this._cancelProxy=null;
this._saveProxy=null;
this.container.off(H);
this.grid.wrapper.off();
},_cancel:function(ac){ac.preventDefault();
this.close();
},_save:function(ac){ac.preventDefault();
this._updateModel();
if(!this.wrapper.is(o+t.styles.popup.resourcesField)){this.trigger("save",{container:this.wrapper,model:this.model});
}this.close();
},_initContainer:function(){var ad=t.styles.popup;
var ac=E.format('<div class="{0} {1}"><div class="{2} {3}"/></div>"',ad.form,ad.editForm,ad.formContainer,ad.resourcesFormContainer);
ac=a(ac);
this.container=ac.find(o+ad.resourcesFormContainer);
this.window=ac.kendoWindow({modal:true,resizable:false,draggable:true,visible:false,title:this.options.messages.resourcesEditorTitle}).data("kendoWindow");
this._resourceGrid();
this._createButtons();
},_resourceGrid:function(){var ae=this;
var ad=this.options.messages;
var ac=a('<div id="resources-grid"/>').appendTo(this.container);
this.grid=new E.ui.Grid(ac,{columns:[{field:"name",title:ad.resourcesHeader,template:"<label><input type='checkbox' value='#=name#'# if (value > 0 && value !== null) {#checked='checked'# } #/>#=name#</labe>"},{field:"value",title:ad.unitsHeader,template:function(af){var ah=af.format;
var ag=af.value!==null?af.value:"";
return ah?E.toString(ag,ah):ag;
}}],height:280,sortable:true,editable:true,filterable:true,dataSource:{data:ae.options.data,schema:{model:{id:"id",fields:{id:{from:"id"},name:{from:"name",type:"string",editable:false},value:{from:"value",type:"number",defaultValue:""},format:{from:"format",type:"string"}}}}},save:function(af){var ag=!!af.values.value;
af.container.parent().find("input[type='checkbox']").prop("checked",ag);
}});
},_createButtons:function(){var ac=this.options.buttons;
var ad='<div class="'+t.styles.popup.buttonsContainer+'">';
for(var ae=0,af=ac.length;
ae<af;
ae++){ad+=this.createButton(ac[ae]);
}ad+="</div>";
this.container.append(ad);
},_updateModel:function(){var af=[];
var ag;
var ac=this.grid.dataSource.data();
for(var ad=0,ae=ac.length;
ad<ae;
ad++){ag=ac[ad].get("value");
if(ag!==null&&ag>0){af.push(ac[ad]);
}}this.model[this.resourcesField]=af;
}});
var t=aa.extend({init:function(ac,ad){if(B(ad)){ad={dataSource:ad};
}aa.fn.init.call(this,ac,ad);
this._wrapper();
this._resources();
this._timeline();
this._toolbar();
this._footer();
this._adjustDimensions();
this._preventRefresh=true;
this.view(this.timeline._selectedViewName);
this._preventRefresh=false;
this._dataSource();
this._assignments();
this._dropDowns();
this._list();
this._dependencies();
this._resizable();
this._scrollable();
this._dataBind();
this._attachEvents();
this._createEditor();
E.notify(this);
},events:["dataBinding","dataBound","add","edit","remove","cancel","save","change","navigate","moveStart","move","moveEnd","resizeStart","resize","resizeEnd"],options:{name:"Gantt",autoBind:true,navigatable:false,selectable:true,editable:true,columns:[],views:[],dataSource:{},dependencies:{},resources:{},assignments:{},messages:{save:"Save",cancel:"Cancel",destroy:"Delete",deleteTaskConfirmation:V,deleteDependencyConfirmation:m,deleteTaskWindowTitle:"Delete task",deleteDependencyWindowTitle:"Delete dependency",views:{day:"Day",week:"Week",month:"Month",year:"Year",start:"Start",end:"End"},actions:{append:"Add Task",addChild:"Add Child",insertBefore:"Add Above",insertAfter:"Add Below",pdf:"Export to PDF"},editor:{editorTitle:"Task",resourcesEditorTitle:"Resources",title:"Title",start:"Start",end:"End",percentComplete:"Complete",resources:"Resources",assingButton:"Assign",resourcesHeader:"Resources",unitsHeader:"Units"}},showWorkHours:true,showWorkDays:true,toolbar:null,workDayStart:new Date(1980,1,1,8,0,0),workDayEnd:new Date(1980,1,1,17,0,0),workWeekStart:1,workWeekEnd:5,hourSpan:1,snap:true,height:600,listWidth:"30%"},select:function(ad){var ac=this.list;
if(!ad){return ac.select();
}ac.select(ad);
return;
},clearSelection:function(){this.list.clearSelection();
},destroy:function(){aa.fn.destroy.call(this);
if(this.dataSource){this.dataSource.unbind("change",this._refreshHandler);
this.dataSource.unbind("progress",this._progressHandler);
this.dataSource.unbind("error",this._errorHandler);
}if(this.dependencies){this.dependencies.unbind("change",this._dependencyRefreshHandler);
this.dependencies.unbind("error",this._dependencyErrorHandler);
}if(this.timeline){this.timeline.unbind();
this.timeline.destroy();
}if(this.list){this.list.unbind();
this.list.destroy();
}if(this.footerDropDown){this.footerDropDown.destroy();
}if(this.headerDropDown){this.headerDropDown.destroy();
}if(this._editor){this._editor.destroy();
}if(this._resizeDraggable){this._resizeDraggable.destroy();
}this.toolbar.off(H);
a(window).off("resize"+H,this._resizeHandler);
a(this.wrapper).off(H);
this.toolbar=null;
this.footer=null;
},_attachEvents:function(){this._resizeHandler=N(this.resize,this);
a(window).on("resize"+H,this._resizeHandler);
},_wrapper:function(){var ac=t.styles;
var af=[ac.icon,ac.resizeHandle].join(" ");
var ae=this.options;
var ad=ae.height;
var ag=ae.width;
this.wrapper=this.element.addClass(ac.wrapper).append("<div class='"+ac.listWrapper+"'><div></div></div>").append("<div class='"+ac.splitBarWrapper+"'><div class='"+af+"'></div></div>").append("<div class='"+ac.timelineWrapper+"'><div></div></div>");
this.wrapper.find(o+ac.list).width(ae.listWidth);
if(ad){this.wrapper.height(ad);
}if(ag){this.wrapper.width(ag);
}},_toolbar:function(){var ah=this;
var ae=t.styles;
var ak=o+ae.toolbar.views+" > li";
var ag=o+ae.toolbar.pdfButton;
var af=ae.hovered;
var ac=this.options.toolbar;
var ad=a("<div class='"+ae.toolbar.actions+"'>");
var ai;
var aj;
if(!C(ac)){ac=(typeof ac===T?ac:this._actions(ac));
ac=N(E.template(ac),this);
}aj=a(z({ns:E.ns,views:this.timeline.views,styles:ae.toolbar}));
ad.append(ac({}));
ai=a("<div class='"+ae.toolbar.headerWrapper+"'>").append(ad).append(aj);
this.wrapper.prepend(ai);
this.toolbar=ai;
ai.on(g+H,ak,function(al){al.preventDefault();
var am=a(this).attr(E.attr("name"));
if(!ah.trigger("navigate",{view:am})){ah.view(am);
}}).on(g+H,ag,function(al){al.preventDefault();
ah.saveAsPDF();
});
this.wrapper.find(o+ae.toolbar.toolbar+" li").hover(function(){a(this).addClass(af);
},function(){a(this).removeClass(af);
});
},_actions:function(){var ag=this.options;
var ac=ag.toolbar;
var ad="";
if(!B(ac)){if(ag.editable){ac=["append"];
}else{return ad;
}}for(var ae=0,af=ac.length;
ae<af;
ae++){ad+=this._createButton(ac[ae]);
}return ad;
},_footer:function(){if(!this.options.editable){return;
}var af=t.styles.toolbar;
var ag=this.options.messages.actions;
var ad=a(E.template(f)(r(true,{styles:af},{text:ag.append,action:"add",className:af.appendButton,iconClass:af.iconPlus})));
var ac=a("<div class='"+af.actions+"'>").append(ad);
var ae=a("<div class='"+af.footerWrapper+"'>").append(ac);
this.wrapper.append(ae);
this.footer=ae;
},_createButton:function(ad){var ag=t.styles.toolbar;
var af={append:{text:"Add Task",action:"add",className:ag.appendButton,iconClass:ag.iconPlus},pdf:{text:"Export to PDF",className:ag.pdfButton,iconClass:ag.iconPdf}};
var aj=ad.template||f;
var ah=this.options.messages.actions;
var ae=typeof ad===T?ad:ad.name||ad.text;
var ac=af[ae]?af[ae].className:"k-gantt-"+(ae||"").replace(/\s/g,"");
var ai={iconClass:"",action:"",text:ae,className:ac,styles:t.styles.toolbar};
if(!ae&&!(D(ad)&&ad.template)){throw new Error("Custom commands should have name specified");
}ai=r(true,ai,af[ae],{text:ah[ae]});
if(D(ad)){if(ad.className&&A(ai.className,ad.className.split(" "))<0){ad.className+=" "+ai.className;
}ai=r(true,ai,ad);
}return E.template(aj)(ai);
},_adjustDimensions:function(){var ac=this.element;
var ae=t.styles;
var af=o+ae.list;
var ai=o+ae.timeline;
var ag=o+ae.splitBar;
var aj=this.toolbar.outerHeight();
var ad=this.footer?this.footer.outerHeight():0;
var ak=ac.height();
var al=ac.width();
var ah=ac.find(ag).outerWidth();
var am=ac.find(af).outerWidth();
ac.children([af,ai,ag].join(",")).height(ak-(aj+ad)).end().children(ai).width(al-(ah+am));
},_scrollTo:function(af){var ag=this.timeline.view();
var ac=E.attr("uid");
var ad=typeof af==="string"?af:af.closest("tr"+S()).attr(ac);
var ae=ag.content.find(S(ad));
if(ae.length!==0){ag._scrollTo(ae);
}},_dropDowns:function(){var ag=this;
var ad=o+t.styles.toolbar.actions;
var ac=this.options.messages.actions;
var ae=this.dataSource;
var ah=this.timeline;
var af=function(ai){var ap=ai.type;
var ak;
var ao=ae._createNewModel();
var am=ag.dataItem(ag.select());
var al=ae.taskParent(am);
var aj=ah.view()._timeSlots()[0];
var an=ap==="add"?am:al;
ao.set("title","New task");
if(an){ao.set("parentId",an.get("id"));
ao.set("start",an.get("start"));
ao.set("end",an.get("end"));
}else{ao.set("start",aj.start);
ao.set("end",aj.end);
}if(ap!=="add"){ak=am.get("orderId");
ak=ap==="insert-before"?ak:ak+1;
}ag._createTask(ao,ak);
};
if(!this.options.editable){return;
}this.footerDropDown=new X(this.footer.children(ad).eq(0),{messages:{actions:ac},direction:"up",animation:{open:{effects:"slideIn:up"}},navigatable:ag.options.navigatable});
this.headerDropDown=new X(this.toolbar.children(ad).eq(0),{messages:{actions:ac},navigatable:ag.options.navigatable});
this.footerDropDown.bind("command",af);
this.headerDropDown.bind("command",af);
},_list:function(){var al=this;
var ai=al.options.navigatable;
var af=t.styles;
var ah=this.wrapper.find(o+af.list);
var ae=ah.find("> div");
var am=this.wrapper.find(o+af.toolbar.actions+" > button");
var aj={columns:this.options.columns||[],dataSource:this.dataSource,selectable:this.options.selectable,editable:this.options.editable,listWidth:ah.outerWidth(),resourcesField:this.resources.field};
var ad=aj.columns;
var ac;
var ak=function(){if(ai){al._current(al._cachedCurrent);
s(al.list.content.find("table"),true);
}delete al._cachedCurrent;
};
for(var ag=0;
ag<ad.length;
ag++){ac=ad[ag];
if(ac.field===this.resources.field&&typeof ac.editor!=="function"){ac.editor=N(this._createResourceEditor,this);
}}this.list=new E.ui.GanttList(ae,aj);
this.list.bind("render",function(){al._navigatable();
},true).bind("edit",function(an){al._cachedCurrent=an.cell;
if(al.trigger("edit",{task:an.model,container:an.cell})){an.preventDefault();
}}).bind("cancel",function(an){if(al.trigger("cancel",{task:an.model,container:an.cell})){an.preventDefault();
}ak();
}).bind("update",function(an){al._updateTask(an.task,an.updateInfo);
ak();
}).bind("change",function(){al.trigger("change");
var an=al.list.select();
if(an.length){am.removeAttr("data-action","add");
al.timeline.select("[data-uid='"+an.attr("data-uid")+"']");
}else{am.attr("data-action","add");
al.timeline.clearSelection();
}});
},_timeline:function(){var af=this;
var ad=t.styles;
var ae=Y(r(true,{resourcesField:this.resources.field},this.options));
var ac=this.wrapper.find(o+ad.timeline+" > div");
this.timeline=new E.ui.GanttTimeline(ac,ae);
this.timeline.bind("navigate",function(ag){af.toolbar.find(o+ad.toolbar.views+" > li").removeClass(ad.selected).end().find(o+ad.toolbar.viewButton+"-"+ag.view.replace(/\./g,"\\.").toLowerCase()).addClass(ad.selected);
af.refresh();
}).bind("moveStart",function(ag){if(af.trigger("moveStart",{task:ag.task})){ag.preventDefault();
}}).bind("move",function(ag){var aj=ag.task;
var ai=ag.start;
var ah=new Date(ai.getTime()+aj.duration());
if(af.trigger("move",{task:aj,start:ai,end:ah})){ag.preventDefault();
}}).bind("moveEnd",function(ag){var aj=ag.task;
var ai=ag.start;
var ah=new Date(ai.getTime()+aj.duration());
if(!af.trigger("moveEnd",{task:aj,start:ai,end:ah})){af._updateTask(af.dataSource.getByUid(aj.uid),{start:ai,end:ah});
}}).bind("resizeStart",function(ag){if(af.trigger("resizeStart",{task:ag.task})){ag.preventDefault();
}}).bind("resize",function(ag){if(af.trigger("resize",{task:ag.task,start:ag.start,end:ag.end})){ag.preventDefault();
}}).bind("resizeEnd",function(ag){var ah=ag.task;
var ai={};
if(ag.resizeStart){ai.start=ag.start;
}else{ai.end=ag.end;
}if(!af.trigger("resizeEnd",{task:ah,start:ag.start,end:ag.end})){af._updateTask(af.dataSource.getByUid(ah.uid),ai);
}}).bind("percentResizeEnd",function(ag){af._updateTask(af.dataSource.getByUid(ag.task.uid),{percentComplete:ag.percentComplete});
}).bind("dependencyDragEnd",function(ah){var ag=af.dependencies._createNewModel({type:ah.type,predecessorId:ah.predecessor.id,successorId:ah.successor.id});
af._createDependency(ag);
}).bind("select",function(ag){af.select("[data-uid='"+ag.uid+"']");
}).bind("editTask",function(ag){af.editTask(ag.uid);
}).bind("clear",function(ag){af.clearSelection();
}).bind("removeTask",function(ag){af.removeTask(af.dataSource.getByUid(ag.uid));
}).bind("removeDependency",function(ag){af.removeDependency(af.dependencies.getByUid(ag.uid));
});
},_dataSource:function(){var ad=this.options;
var ac=ad.dataSource;
ac=B(ac)?{data:ac}:ac;
if(this.dataSource&&this._refreshHandler){this.dataSource.unbind("change",this._refreshHandler).unbind("progress",this._progressHandler).unbind("error",this._errorHandler);
}else{this._refreshHandler=N(this.refresh,this);
this._progressHandler=N(this._requestStart,this);
this._errorHandler=N(this._error,this);
}this.dataSource=E.data.GanttDataSource.create(ac).bind("change",this._refreshHandler).bind("progress",this._progressHandler).bind("error",this._errorHandler);
},_dependencies:function(){var ad=this.options.dependencies||{};
var ac=B(ad)?{data:ad}:ad;
if(this.dependencies&&this._dependencyRefreshHandler){this.dependencies.unbind("change",this._dependencyRefreshHandler).unbind("error",this._dependencyErrorHandler);
}else{this._dependencyRefreshHandler=N(this.refreshDependencies,this);
this._dependencyErrorHandler=N(this._error,this);
}this.dependencies=E.data.GanttDependencyDataSource.create(ac).bind("change",this._dependencyRefreshHandler).bind("error",this._dependencyErrorHandler);
},_resources:function(){var ad=this.options.resources;
var ac=ad.dataSource||{};
this.resources={field:"resources",dataTextField:"name",dataColorField:"color",dataFormatField:"format"};
r(this.resources,ad);
this.resources.dataSource=E.data.DataSource.create(ac);
},_assignments:function(){var ac=this.options.assignments;
var ad=ac.dataSource||{};
if(this.assignments){this.assignments.dataSource.unbind("change",this._assignmentsRefreshHandler);
}else{this._assignmentsRefreshHandler=N(this.refresh,this);
}this.assignments={dataTaskIdField:"taskId",dataResourceIdField:"resourceId",dataValueField:"value"};
r(this.assignments,ac);
this.assignments.dataSource=E.data.DataSource.create(ad);
this.assignments.dataSource.bind("change",this._assignmentsRefreshHandler);
},_createEditor:function(ac){var ae=this;
var ad=this._editor=new M(this.wrapper,r({},this.options,{target:this,resources:{field:this.resources.field,editor:N(this._createResourceEditor,this)},createButton:N(this._createPopupButton,this)}));
ad.bind("cancel",function(af){var ag=ae.dataSource.getByUid(af.model.uid);
if(ae.trigger("cancel",{container:af.container,task:ag})){af.preventDefault();
return;
}ae.cancelTask();
}).bind("edit",function(af){var ag=ae.dataSource.getByUid(af.model.uid);
if(ae.trigger("edit",{container:af.container,task:ag})){af.preventDefault();
}}).bind("save",function(af){var ag=ae.dataSource.getByUid(af.model.uid);
ae.saveTask(ag,af.updateInfo);
}).bind("remove",function(af){ae.removeTask(af.model.uid);
});
},_createResourceEditor:function(ac,ah){var aj=this;
var ag=ah instanceof K?ah:ah.model;
var ae=ag.get("id");
var af=this.options.messages;
var ai=aj.resources.field;
var ad=this._resourceEditor=new P(ac,{resourcesField:ai,data:this._wrapResourceData(ae),model:ag,messages:r({},af.editor),buttons:[{name:"update",text:af.save,className:t.styles.primary},{name:"cancel",text:af.cancel}],createButton:N(this._createPopupButton,this),save:function(ak){aj._updateAssignments(ak.model.get("id"),ak.model.get(ai));
}});
ad.open();
},_createPopupButton:function(ac){var ad=ac.name||ac.text;
var ae={className:t.styles.popup.button+" k-gantt-"+(ad||"").replace(/\s/g,""),text:ad,attr:""};
if(!ad&&!(D(ac)&&ac.template)){throw new Error("Custom commands should have name specified");
}if(D(ac)){if(ac.className){ac.className+=" "+ae.className;
}ae=r(true,ae,ac);
}return E.template(h)(ae);
},view:function(ac){return this.timeline.view(ac);
},dataItem:function(ae){if(!ae){return null;
}var ad=this.list;
var ac=ad.content.find(ae);
return ad._modelFromElement(ac);
},setDataSource:function(ac){this.options.dataSource=ac;
this._dataSource();
this.list._setDataSource(this.dataSource);
if(this.options.autoBind){ac.fetch();
}},setDependenciesDataSource:function(ac){this.options.dependencies=ac;
this._dependencies();
if(this.options.autoBind){ac.fetch();
}},items:function(){return this.wrapper.children(".k-task");
},_updateAssignments:function(ah,an){var ae=this.assignments.dataSource;
var ao=this.assignments.dataTaskIdField;
var am=this.assignments.dataResourceIdField;
var af=false;
var ad=new O(ae.view()).filter({field:ao,operator:"eq",value:ah}).toArray();
var ac;
var al;
var ap;
while(ad.length){ac=ad[0];
for(var ag=0,aj=an.length;
ag<aj;
ag++){al=an[ag];
if(ac.get(am)===al.get("id")){ap=an[ag].get("value");
this._updateAssignment(ac,ap);
an.splice(ag,1);
af=true;
break;
}}if(!af){this._removeAssignment(ac);
}af=false;
ad.shift();
}for(var ai=0,ak=an.length;
ai<ak;
ai++){al=an[ai];
this._createAssignment(al,ah);
}ae.sync();
},cancelTask:function(){var ad=this._editor;
var ac=ad.container;
if(ac){ad.close();
}},editTask:function(ae){var ac=typeof ae==="string"?this.dataSource.getByUid(ae):ae;
if(!ac){return;
}var ad=this.dataSource._createNewModel(ac.toJSON());
ad.uid=ac.uid;
this.cancelTask();
this._editTask(ad);
},_editTask:function(ac){this._editor.editTask(ac);
},saveTask:function(af,ag){var ae=this._editor;
var ac=ae.container;
var ad=ae.editable;
if(ac&&ad&&ad.end()){this._updateTask(af,ag);
}},_updateTask:function(ad,ae){var ac=this.resources.field;
if(!this.trigger("save",{task:ad,values:ae})){this._preventRefresh=true;
this.dataSource.update(ad,ae);
if(ae[ac]){this._updateAssignments(ad.get("id"),ae[ac]);
}this._syncDataSource();
}},_updateAssignment:function(ac,ae){var ad=this.assignments.dataValueField;
ac.set(ad,ae);
},removeTask:function(ae){var ad=this;
var ac=typeof ae==="string"?this.dataSource.getByUid(ae):ae;
if(!ac){return;
}this._taskConfirm(function(af){if(!af){ad._removeTask(ac);
}},ac);
},_createTask:function(ae,ad){if(!this.trigger("add",{task:ae,dependency:null})){var ac=this.dataSource;
this._preventRefresh=true;
if(ad===Z){ac.add(ae);
}else{ac.insert(ad,ae);
}this._scrollToUid=ae.uid;
this._syncDataSource();
}},_createDependency:function(ac){if(!this.trigger("add",{task:null,dependency:ac})){this._preventDependencyRefresh=true;
this.dependencies.add(ac);
this._preventDependencyRefresh=false;
this.dependencies.sync();
}},_createAssignment:function(ag,af){var ad=this.assignments;
var ae=ad.dataSource;
var aj=ad.dataTaskIdField;
var ah=ad.dataResourceIdField;
var ai=ad.dataValueField;
var ac=ae._createNewModel();
ac[aj]=af;
ac[ah]=ag.get("id");
ac[ai]=ag.get("value");
ae.add(ac);
},removeDependency:function(ae){var ad=this;
var ac=typeof ae==="string"?this.dependencies.getByUid(ae):ae;
if(!ac){return;
}this._dependencyConfirm(function(af){if(!af){ad._removeDependency(ac);
}},ac);
},_removeTaskDependencies:function(af,ac){this._preventDependencyRefresh=true;
for(var ad=0,ae=ac.length;
ad<ae;
ad++){this.dependencies.remove(ac[ad]);
}this._preventDependencyRefresh=false;
this.dependencies.sync();
},_removeTaskAssignments:function(ah){var ad=this.assignments.dataSource;
var ac=ad.view();
var ae={field:this.assignments.dataTaskIdField,operator:"eq",value:ah.get("id")};
ac=new O(ac).filter(ae).toArray();
this._preventRefresh=true;
for(var af=0,ag=ac.length;
af<ag;
af++){ad.remove(ac[af]);
}this._preventRefresh=false;
ad.sync();
},_removeTask:function(ad){var ac=this.dependencies.dependencies(ad.id);
if(!this.trigger("remove",{task:ad,dependencies:ac})){this._removeTaskDependencies(ad,ac);
this._removeTaskAssignments(ad);
this._preventRefresh=true;
if(this.dataSource.remove(ad)){this._syncDataSource();
}this._preventRefresh=false;
}},_removeDependency:function(ac){if(!this.trigger("remove",{task:null,dependencies:[ac]})){if(this.dependencies.remove(ac)){this.dependencies.sync();
}}},_removeAssignment:function(ac){this.assignments.dataSource.remove(ac);
},_taskConfirm:function(ac,ae){var ad=this.options.messages;
this._confirm(ac,{model:ae,text:ad.deleteTaskConfirmation,title:ad.deleteTaskWindowTitle});
},_dependencyConfirm:function(ac,ad){var ae=this.options.messages;
this._confirm(ac,{model:ad,text:ae.deleteDependencyConfirmation,title:ae.deleteDependencyWindowTitle});
},_confirm:function(ad,ag){var ae=this.options.editable;
var af;
var ac;
if(ae===true||ae.confirmation!==false){af=this.options.messages;
ac=[{name:"delete",text:af.destroy,className:t.styles.primary,click:function(){ad();
}},{name:"cancel",text:af.cancel,click:function(){ad(true);
}}];
this.showDialog(r(true,{},ag,{buttons:ac}));
}else{ad();
}},showDialog:function(ac){this._editor.showDialog(ac);
},refresh:function(ag){if(this._preventRefresh||this.list.editable){return;
}this._progress(false);
var af=this.dataSource;
var ai=af.taskTree();
var ah=this._scrollToUid;
var ae;
var ad;
var ac=-1;
if(this.current){ad=this.current.closest("tr").attr(E.attr("uid"));
ac=this.current.index();
}if(this.trigger("dataBinding")){return;
}if(this.resources.dataSource.data().length!==0){this._assignResources(ai);
}if(this._editor){this._editor.close();
}this.clearSelection();
this.list._render(ai);
this.timeline._render(ai);
this.timeline._renderDependencies(this.dependencies.view());
if(ah){this._scrollTo(ah);
this.select(S(ah));
}if((ah||ad)&&ac>=0){ae=this.list.content.find("tr"+S((ah||ad))+" > td:eq("+ac+")");
this._current(ae);
}this._scrollToUid=null;
this.trigger("dataBound");
},refreshDependencies:function(ac){if(this._preventDependencyRefresh){return;
}if(this.trigger("dataBinding")){return;
}this.timeline._renderDependencies(this.dependencies.view());
this.trigger("dataBound");
},_assignResources:function(aj){var ak=this;
var ai=this.resources;
var ae=this.assignments;
var af=function(){var am=ae.dataSource.view();
var an={field:ae.dataTaskIdField};
am=new O(am).group(an).toArray();
return am;
};
var ad=af();
var ac=function(ap,am){var aq=ap.get("id");
E.setter(ai.field)(ap,new J([]));
for(var an=0,ao=ad.length;
an<ao;
an++){if(ad[an].value===aq){am(ap,ad[an].items);
}}};
var al=function(av,ao){for(var ap=0,aq=ao.length;
ap<aq;
ap++){var an=ao[ap];
var ar=ai.dataSource.get(an.get(ae.dataResourceIdField));
var au=an.get(ae.dataValueField);
var at=an.get(ae.dataResourceIdField);
var aw=ar.get(ai.dataFormatField)||L;
var am=E.toString(au,aw);
av[ai.field].push(new K({id:at,name:ar.get(ai.dataTextField),color:ar.get(ai.dataColorField),value:au,formatedValue:am}));
}};
for(var ag=0,ah=aj.length;
ag<ah;
ag++){ac(aj[ag],al);
}},_wrapResourceData:function(ae){var ak=this;
var ai=[];
var ag;
var ah=this.resources.dataSource.view();
var ac=this.assignments.dataSource.view();
var aj=new O(ac).filter({field:ak.assignments.dataTaskIdField,operator:"eq",value:ae}).toArray();
var al=function(am){var an=null;
new O(aj).filter({field:ak.assignments.dataResourceIdField,operator:"eq",value:am}).select(function(ao){an+=ao.get(ak.assignments.dataValueField);
});
return an;
};
for(var ad=0,af=ah.length;
ad<af;
ad++){ag=ah[ad];
ai.push({id:ag.get("id"),name:ag.get(ak.resources.dataTextField),format:ag.get(ak.resources.dataFormatField)||L,value:al(ag.id)});
}return ai;
},_syncDataSource:function(){this._preventRefresh=false;
this._requestStart();
this.dataSource.sync();
},_requestStart:function(){this._progress(true);
},_error:function(){this._progress(false);
},_progress:function(ac){E.ui.progress(this.element,ac);
},_resizable:function(){var ae=this;
var ak=this.wrapper;
var ad=t.styles;
var ac=o+ad.gridContent;
var aj=ak.find(o+ad.list);
var ah=ak.find(o+ad.timeline);
var ai;
var ag;
var af;
this._resizeDraggable=ak.find(o+ad.splitBar).height(aj.height()).hover(function(al){a(this).addClass(ad.splitBarHover);
},function(al){a(this).removeClass(ad.splitBarHover);
}).end().kendoResizable({orientation:"horizontal",handle:o+ad.splitBar,start:function(al){ai=aj.width();
ag=ah.width();
af=ah.find(ac).scrollLeft();
},resize:function(am){var al=am.x.initialDelta;
if(E.support.isRtl(ak)){al*=-1;
}if(ai+al<0||ag-al<0){return;
}aj.width(ai+al);
ah.width(ag-al);
ah.find(ac).scrollLeft(af+al);
ae.timeline.view()._renderCurrentTime();
}}).data("kendoResizable");
},_scrollable:function(){var ad=t.styles;
var ac=o+ad.gridContent;
var ae=o+ad.gridHeaderWrap;
var af=this.timeline.element;
var ag=this.list.element;
af.find(ac).on("scroll",function(ah){af.find(ae).scrollLeft(this.scrollLeft);
ag.find(ac).scrollTop(this.scrollTop);
});
ag.find(ac).on("scroll",function(ah){ag.find(ae).scrollLeft(this.scrollLeft);
}).on("DOMMouseScroll"+H+" mousewheel"+H,function(aj){var ah=af.find(ac);
var ak=ah.scrollTop();
var ai=E.wheelDeltaY(aj);
if(ai){aj.preventDefault();
a(aj.currentTarget).one("wheel"+H,false);
ah.scrollTop(ak+(-ai));
}});
},_navigatable:function(){var aq=this;
var an=this.options.navigatable;
var ag=this.options.editable;
var aj=this.list.header.find("table");
var ae=this.list.content.find("table");
var ai=t.styles;
var ak=E.support.isRtl(this.wrapper);
var ar=this.timeline.element.find(o+ai.gridContent);
var ap=aj.add(ae);
var ac=S();
var ad;
var ah={collapse:false,expand:true};
var ao=function(au){var av=aq.timeline.view()._timeSlots()[0].offsetWidth;
ar.scrollLeft(ar.scrollLeft()+(au?-av:av));
};
var am=function(av){var aw=aq.current.parent("tr"+S());
var au=aq.current.index();
var ax=aw[av]();
if(aq.select().length!==0){aq.clearSelection();
}if(ax.length!==0){aq._current(ax.children("td:eq("+au+")"));
aq._scrollTo(aq.current);
}else{if(aq.current.is("td")&&av=="prev"){s(aj);
}else{if(aq.current.is("th")&&av=="next"){s(ae);
}}}};
var al=function(au){var av=aq.current[au]();
if(av.length!==0){aq._current(av);
ad=aq.current.index();
}};
var at=function(av){var au=aq.dataItem(aq.current);
if(au.summary&&au.expanded!==av){au.set("expanded",av);
}};
var af=function(){if(!aq.options.editable||aq.list.editable){return;
}var au=aq.select();
var av=E.attr("uid");
if(au.length){aq.removeTask(au.attr(av));
}};
a(this.wrapper).on("mousedown"+H,"tr"+ac+", div"+ac+":not("+o+ai.line+")",function(aw){var av=a(aw.currentTarget);
var ax=a(aw.target).is(":button,a,:input,a>.k-icon,textarea,span.k-icon,span.k-link,.k-input,.k-multiselect-wrap");
var au;
if(aw.ctrlKey){return;
}if(an){if(av.is("tr")){au=a(aw.target).closest("td");
}else{au=aq.list.content.find("tr"+S(av.attr(E.attr("uid")))+" > td:first");
}aq._current(au);
}if((an||ag)&&!ax){setTimeout(function(){s(aq.list.content.find("table"),true);
},2);
}});
if(an!==true){ae.on("keydown"+H,function(au){if(au.keyCode==F.DELETE){af();
}});
return;
}ap.on("focus"+H,function(av){var ax=this===ae.get(0)?"td":"th";
var ay=a(this);
var aw=aq.select();
var au=aq.current||a((aw.length?aw:this)).find(ax+":eq("+(ad||0)+")");
aq._current(au);
}).on("blur"+H,function(){aq._current();
if(this==aj){a(this).attr(U,-1);
}}).on("keydown"+H,function(au){var aw=au.keyCode;
var av;
if(!aq.current){return;
}av=aq.current.is("td");
switch(aw){case F.RIGHT:au.preventDefault();
if(au.altKey){ao();
}else{if(au.ctrlKey){at(ak?ah.collapse:ah.expand);
}else{al(ak?"prev":"next");
}}break;
case F.LEFT:au.preventDefault();
if(au.altKey){ao(true);
}else{if(au.ctrlKey){at(ak?ah.expand:ah.collapse);
}else{al(ak?"next":"prev");
}}break;
case F.UP:au.preventDefault();
am("prev");
break;
case F.DOWN:au.preventDefault();
am("next");
break;
case F.SPACEBAR:au.preventDefault();
if(av){aq.select(aq.current.closest("tr"));
}break;
case F.ENTER:au.preventDefault();
if(av){if(aq.options.editable){aq._cachedCurrent=aq.current;
aq.list._startEditHandler(aq.current);
au.stopPropagation();
}}else{aq.current.children("a.k-link").click();
}break;
case F.ESC:au.stopPropagation();
break;
case F.DELETE:if(av){af();
}break;
default:if(aw>=49&&aw<=57){aq.view(aq.timeline._viewByIndex(aw-49));
}break;
}});
},_current:function(ad){var ae=t.styles;
var ac;
if(this.current&&this.current.length){this.current.removeClass(ae.focused).removeAttr("id");
}if(ad&&ad.length){this.current=ad.addClass(ae.focused).attr("id",b);
ac=a(E._activeElement());
if(ac.is("table")&&this.wrapper.find(ac).length>0){ac.removeAttr(d).attr(d,b);
}}else{this.current=null;
}},_dataBind:function(){var ad=this;
if(ad.options.autoBind){this._preventRefresh=true;
this._preventDependencyRefresh=true;
var ac=a.map([this.dataSource,this.dependencies,this.resources.dataSource,this.assignments.dataSource],function(ae){return ae.fetch();
});
a.when.apply(null,ac).done(function(){ad._preventRefresh=false;
ad._preventDependencyRefresh=false;
ad.refresh();
});
}},_resize:function(){this._adjustDimensions();
this.timeline.view()._adjustHeight();
this.timeline.view()._renderCurrentTime();
this.list._adjustHeight();
}});
if(E.PDFMixin){E.PDFMixin.extend(t.fn);
t.fn._drawPDF=function(){var ad="."+x.list;
var ae=this.wrapper.find(ad).width();
var ac=this.wrapper.clone();
ac.find(ad).css("width",ae);
return this._drawPDFShadow(ac);
};
}E.ui.plugin(t);
r(true,t,{styles:x});
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
