(function(b,a){a(["./kendo.core","./kendo.userevents"],b);
})(function(){(function(a,I){var r=window.kendo,f=r.caret,s=r.keys,H=r.ui,J=H.Widget,b=r._activeElement,j=r._extractFormat,x=r.parseFloat,y=r.support.placeholder,m=r.getCulture,C=r._round,g="change",i="disabled",B="readonly",p="k-input",E="spin",u=".kendoNumericTextBox",G="touchend",t="mouseleave"+u,o="mouseenter"+u+" "+t,h="k-state-default",l="k-state-focused",n="k-state-hover",k="focus",z=".",D="k-state-selected",F="k-state-disabled",c="aria-disabled",d="aria-readonly",q=/^(-)?(\d*)$/,v=null,A=a.proxy;
var w=J.extend({init:function(L,P){var R=this,M=P&&P.step!==I,O,N,Q,S,K;
J.fn.init.call(R,L,P);
P=R.options;
L=R.element.on("focusout"+u,A(R._focusout,R)).attr("role","spinbutton");
P.placeholder=P.placeholder||L.attr("placeholder");
R._reset();
R._wrapper();
R._arrows();
R._input();
if(!r.support.mobileOS){R._text.on(k+u,A(R._click,R));
}else{R._text.on(G+u+" "+k+u,function(T){R._toggleText(false);
L.focus();
});
}O=R.min(L.attr("min"));
N=R.max(L.attr("max"));
Q=R._parse(L.attr("step"));
if(P.min===v&&O!==v){P.min=O;
}if(P.max===v&&N!==v){P.max=N;
}if(!M&&Q!==v){P.step=Q;
}L.attr("aria-valuemin",P.min).attr("aria-valuemax",P.max);
P.format=j(P.format);
S=P.value;
R.value(S!==v?S:L.val());
K=L.is("[disabled]");
if(K){R.enable(false);
}else{R.readonly(L.is("[readonly]"));
}r.notify(R);
},options:{name:"NumericTextBox",decimals:v,min:v,max:v,value:v,step:1,culture:"",format:"n",spinners:true,placeholder:"",upArrowText:"Increase value",downArrowText:"Decrease value"},events:[g,E],_editable:function(M){var P=this,L=P.element,K=M.disable,N=M.readonly,O=P._text.add(L),Q=P._inputWrapper.off(o);
P._toggleText(true);
P._upArrowEventHandler.unbind("press");
P._downArrowEventHandler.unbind("press");
L.off("keydown"+u).off("keypress"+u).off("paste"+u);
if(!N&&!K){Q.addClass(h).removeClass(F).on(o,P._toggleHover);
O.removeAttr(i).removeAttr(B).attr(c,false).attr(d,false);
P._upArrowEventHandler.bind("press",function(R){R.preventDefault();
P._spin(1);
P._upArrow.addClass(D);
});
P._downArrowEventHandler.bind("press",function(R){R.preventDefault();
P._spin(-1);
P._downArrow.addClass(D);
});
P.element.on("keydown"+u,A(P._keydown,P)).on("keypress"+u,A(P._keypress,P)).on("paste"+u,A(P._paste,P));
}else{Q.addClass(K?F:h).removeClass(K?h:F);
O.attr(i,K).attr(B,N).attr(c,K).attr(d,N);
}},readonly:function(K){this._editable({readonly:K===I?true:K,disable:false});
},enable:function(K){this._editable({readonly:false,disable:!(K=K===I?true:K)});
},destroy:function(){var K=this;
K.element.add(K._text).add(K._upArrow).add(K._downArrow).add(K._inputWrapper).off(u);
K._upArrowEventHandler.destroy();
K._downArrowEventHandler.destroy();
if(K._form){K._form.off("reset",K._resetHandler);
}J.fn.destroy.call(K);
},min:function(K){return this._option("min",K);
},max:function(K){return this._option("max",K);
},step:function(K){return this._option("step",K);
},value:function(M){var L=this,K;
if(M===I){return L._value;
}M=L._parse(M);
K=L._adjust(M);
if(M!==K){return;
}L._update(M);
L._old=L._value;
},focus:function(){this._focusin();
},_adjust:function(O){var N=this,M=N.options,L=M.min,K=M.max;
if(O===v){return O;
}if(L!==v&&O<L){O=L;
}else{if(K!==v&&O>K){O=K;
}}return O;
},_arrows:function(){var P=this,L,K=function(){clearTimeout(P._spinning);
L.removeClass(D);
},N=P.options,O=N.spinners,M=P.element;
L=M.siblings(".k-icon");
if(!L[0]){L=a(e("n",N.upArrowText)+e("s",N.downArrowText)).insertAfter(M);
L.wrapAll('<span class="k-select"/>');
}if(!O){L.parent().toggle(O);
P._inputWrapper.addClass("k-expand-padding");
}P._upArrow=L.eq(0);
P._upArrowEventHandler=new r.UserEvents(P._upArrow,{release:K});
P._downArrow=L.eq(1);
P._downArrowEventHandler=new r.UserEvents(P._downArrow,{release:K});
},_blur:function(){var K=this;
K._toggleText(true);
K._change(K.element.val());
},_click:function(K){var L=this;
clearTimeout(L._focusing);
L._focusing=setTimeout(function(){var S=K.target,R=f(S)[0],U=S.value.substring(0,R),O=L._format(L.options.format),P=O[","],T,Q,N,M=0;
if(P){Q=new RegExp("\\"+P,"g");
N=new RegExp("([\\d\\"+P+"]+)(\\"+O[z]+")?(\\d+)?");
}if(N){T=N.exec(U);
}if(T){M=T[0].replace(Q,"").length;
if(U.indexOf("(")!=-1&&L._value<0){M++;
}}L._focusin();
f(L.element[0],M);
});
},_change:function(L){var K=this;
K._update(L);
L=K._value;
if(K._old!=L){K._old=L;
K.element.trigger(g);
K.trigger(g);
}},_culture:function(K){return K||m(this.options.culture);
},_focusin:function(){var K=this;
K._inputWrapper.addClass(l);
K._toggleText(false);
K.element[0].focus();
},_focusout:function(){var K=this;
clearTimeout(K._focusing);
K._inputWrapper.removeClass(l).removeClass(n);
K._blur();
},_format:function(L,K){var M=this._culture(K).numberFormat;
L=L.toLowerCase();
if(L.indexOf("c")>-1){M=M.currency;
}else{if(L.indexOf("p")>-1){M=M.percent;
}}return M;
},_input:function(){var P=this,L="k-formatted-value",N=P.element.addClass(p).show()[0],K=N.accessKey,Q=P.wrapper,O;
O=Q.find(z+L);
if(!O[0]){O=a('<input type="text"/>').insertBefore(N).addClass(L);
}try{N.setAttribute("type","text");
}catch(M){N.type="text";
}O[0].tabIndex=N.tabIndex;
O[0].style.cssText=N.style.cssText;
O.prop("placeholder",P.options.placeholder);
if(K){O.attr("accesskey",K);
N.accessKey="";
}P._text=O.addClass(N.className);
},_keydown:function(K){var M=this,L=K.keyCode;
M._key=L;
if(L==s.DOWN){M._step(-1);
}else{if(L==s.UP){M._step(1);
}else{if(L==s.ENTER){M._change(M.element.val());
}}}},_keypress:function(L){if(L.which===0||L.metaKey||L.ctrlKey||L.keyCode===s.BACKSPACE||L.keyCode===s.ENTER){return;
}var U=this;
var P=U.options.min;
var M=U.element;
var R=f(M);
var T=R[0];
var S=R[1];
var K=String.fromCharCode(L.which);
var Q=U._format(U.options.format);
var N=U._key===s.NUMPAD_DOT;
var V=M.val();
var O;
if(N){K=Q[z];
}V=V.substring(0,T)+K+V.substring(S);
O=U._numericRegex(Q).test(V);
if(O&&N){M.val(V);
f(M,T+K.length);
L.preventDefault();
}else{if((P!==null&&P>=0&&V.charAt(0)==="-")||!O){L.preventDefault();
}}U._key=0;
},_numericRegex:function(K){var N=this;
var M=K[z];
var L=N.options.decimals;
if(M===z){M="\\"+M;
}if(L===v){L=K.decimals;
}if(L===0){return q;
}if(N._separator!==M){N._separator=M;
N._floatRegExp=new RegExp("^(-)?(((\\d+("+M+"\\d*)?)|("+M+"\\d*)))?$");
}return N._floatRegExp;
},_paste:function(K){var M=this,L=K.target,N=L.value;
setTimeout(function(){if(M._parse(L.value)===v){M._update(N);
}});
},_option:function(K,N){var M=this,L=M.options;
if(N===I){return L[K];
}N=M._parse(N);
if(!N&&K==="step"){return;
}L[K]=N;
M.element.attr("aria-value"+K,N).attr(K,N);
},_spin:function(K,M){var L=this;
M=M||500;
clearTimeout(L._spinning);
L._spinning=setTimeout(function(){L._spin(K,50);
},M);
L._step(K);
},_step:function(L){var M=this,K=M.element,N=M._parse(K.val())||0;
if(b()!=K[0]){M._focusin();
}N+=M.options.step*L;
M._update(M._adjust(N));
M.trigger(E);
},_toggleHover:function(K){a(K.currentTarget).toggleClass(n,K.type==="mouseenter");
},_toggleText:function(L){var K=this;
K._text.toggle(L);
K.element.toggle(!L);
},_parse:function(L,K){return x(L,this._culture(K),this.options.format);
},_update:function(R){var Q=this,P=Q.options,M=P.format,L=P.decimals,K=Q._culture(),O=Q._format(M,K),N;
if(L===v){L=O.decimals;
}R=Q._parse(R,K);
N=R!==v;
if(N){R=parseFloat(C(R,L));
}Q._value=R=Q._adjust(R);
Q._placeholder(r.toString(R,M,K));
if(N){R=R.toString();
if(R.indexOf("e")!==-1){R=C(+R,L);
}R=R.replace(z,O[z]);
}else{R="";
}Q.element.val(R).attr("aria-valuenow",R);
},_placeholder:function(K){this._text.val(K);
if(!y&&!K){this._text.val(this.options.placeholder);
}},_wrapper:function(){var M=this,L=M.element,K=L[0],N;
N=L.parents(".k-numerictextbox");
if(!N.is("span.k-numerictextbox")){N=L.hide().wrap('<span class="k-numeric-wrap k-state-default" />').parent();
N=N.wrap("<span/>").parent();
}N[0].style.cssText=K.style.cssText;
K.style.width="";
M.wrapper=N.addClass("k-widget k-numerictextbox").addClass(K.className).css("display","");
M._inputWrapper=a(N[0].firstChild);
},_reset:function(){var N=this,K=N.element,M=K.attr("form"),L=M?a("#"+M):K.closest("form");
if(L[0]){N._resetHandler=function(){setTimeout(function(){N.value(K[0].value);
});
};
N._form=L.on("reset",N._resetHandler);
}}});
function e(K,L){return'<span unselectable="on" class="k-link"><span unselectable="on" class="k-icon k-i-arrow-'+K+'" title="'+L+'">'+L+"</span></span>";
}H.plugin(w);
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
