(function(b,a){a(["./kendo.core","./kendo.color","./kendo.drawing"],b);
})(function(){(function(q,N,aj){var y=q.kendo;
var r=!!q.Uint8Array;
var K="\n";
var ai=0;
var b=(function(){var ao="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
return{decode:function(aB){var ay=aB.replace(/[^A-Za-z0-9\+\/\=]/g,""),ax=0,az=ay.length,aA=[];
while(ax<az){var at=ao.indexOf(ay.charAt(ax++));
var au=ao.indexOf(ay.charAt(ax++));
var av=ao.indexOf(ay.charAt(ax++));
var aw=ao.indexOf(ay.charAt(ax++));
var ap=(at<<2)|(au>>>4);
var aq=((au&15)<<4)|(av>>>2);
var ar=((av&3)<<6)|aw;
aA.push(ap);
if(av!=64){aA.push(aq);
}if(aw!=64){aA.push(ar);
}}return aA;
},encode:function(ap){var ay=0,az=ap.length;
var aA="";
while(ay<az){var aq=ap[ay++];
var ar=ap[ay++];
var at=ap[ay++];
var au=aq>>>2;
var av=((aq&3)<<4)|(ar>>>4);
var aw=((ar&15)<<2)|(at>>>6);
var ax=at&63;
if(ay-az==2){aw=ax=64;
}else{if(ay-az==1){ax=64;
}}aA+=ao.charAt(au)+ao.charAt(av)+ao.charAt(aw)+ao.charAt(ax);
}return aA;
}};
}());
var M={a0:[2383.94,3370.39],a1:[1683.78,2383.94],a2:[1190.55,1683.78],a3:[841.89,1190.55],a4:[595.28,841.89],a5:[419.53,595.28],a6:[297.64,419.53],a7:[209.76,297.64],a8:[147.4,209.76],a9:[104.88,147.4],a10:[73.7,104.88],b0:[2834.65,4008.19],b1:[2004.09,2834.65],b2:[1417.32,2004.09],b3:[1000.63,1417.32],b4:[708.66,1000.63],b5:[498.9,708.66],b6:[354.33,498.9],b7:[249.45,354.33],b8:[175.75,249.45],b9:[124.72,175.75],b10:[87.87000000000001,124.72],c0:[2599.37,3676.54],c1:[1836.85,2599.37],c2:[1298.27,1836.85],c3:[918.43,1298.27],c4:[649.13,918.43],c5:[459.21,649.13],c6:[323.15,459.21],c7:[229.61,323.15],c8:[161.57,229.61],c9:[113.39,161.57],c10:[79.37000000000001,113.39],executive:[521.86,756],folio:[612,936],legal:[612,1008],letter:[612,792],tabloid:[792,1224]};
function G(){var ao=0,aq=c();
function ap(){for(var ar=0;
ar<arguments.length;
++ar){var au=arguments[ar];
if(au===aj){throw new Error("Cannot output undefined to PDF");
}else{if(au instanceof af){au.beforeRender(ap);
au.render(ap);
}else{if(v(au)){ag(au,ap);
}else{if(w(au)){ah(au,ap);
}else{if(typeof au=="number"){if(isNaN(au)){throw new Error("Cannot output NaN to PDF");
}var at=au.toFixed(7);
if(at.indexOf(".")>=0){at=at.replace(/\.?0+$/,"");
}if(at=="-0"){at="0";
}aq.writeString(at);
}else{if(/string|boolean/.test(typeof au)){aq.writeString(au+"");
}else{if(typeof au.get=="function"){aq.write(au.get());
}else{if(typeof au=="object"){if(!au){aq.writeString("null");
}else{ap(new Q(au));
}}}}}}}}}}}ap.writeData=function(ar){aq.write(ar);
};
ap.withIndent=function(ar){++ao;
ar(ap);
--ao;
};
ap.indent=function(){ap(K,L("",ao*2,"  "));
ap.apply(null,arguments);
};
ap.offset=function(){return aq.offset();
};
ap.toString=function(){throw new Error("FIX CALLER");
};
ap.get=function(){return aq.get();
};
ap.stream=function(){return aq;
};
return ap;
}function am(ar,ap){var ao=ar.beforeRender;
var aq=ar.render;
ar.beforeRender=function(){};
ar.render=function(at){at(ap," 0 R");
};
ar.renderFull=function(at){ar._offset=at.offset();
at(ap," 0 obj ");
ao.call(ar,at);
aq.call(ar,at);
at(" endobj");
};
}function p(ao){var aq=ao("paperSize",M.a4);
if(!aq){return{};
}if(typeof aq=="string"){aq=M[aq.toLowerCase()];
if(aq==null){throw new Error("Unknown paper size");
}}aq[0]=ak(aq[0]);
aq[1]=ak(aq[1]);
if(ao("landscape",false)){aq=[Math.max(aq[0],aq[1]),Math.min(aq[0],aq[1])];
}var ap=ao("margin");
if(ap){if(typeof ap=="string"||typeof ap=="number"){ap=ak(ap,0);
ap={left:ap,top:ap,right:ap,bottom:ap};
}else{ap={left:ak(ap.left,0),top:ak(ap.top,0),right:ak(ap.right,0),bottom:ak(ap.bottom,0)};
}if(ao("addMargin")){aq[0]+=ap.left+ap.right;
aq[1]+=ap.top+ap.bottom;
}}return{paperSize:aq,margin:ap};
}function R(at){var aw=this;
var au=G();
var aq=0;
var ar=[];
function ap(ay,ax){return(at&&at[ay]!=null)?at[ay]:ax;
}aw.getOption=ap;
aw.attach=function(ax){if(ar.indexOf(ax)<0){am(ax,++aq);
ar.push(ax);
}return ax;
};
aw.pages=[];
aw.FONTS={};
aw.IMAGES={};
aw.GRAD_COL_FUNCTIONS={};
aw.GRAD_OPC_FUNCTIONS={};
aw.GRAD_COL={};
aw.GRAD_OPC={};
var ao=aw.attach(new P());
var av=aw.attach(new Y());
ao.setPages(av);
aw.addPage=function(aB){var aD=p(function(aH,aG){return(aB&&aB[aH]!=null)?aB[aH]:aG;
});
var aE=aD.paperSize;
var aA=aD.margin;
var az=aE[0];
var ay=aE[1];
if(aA){az-=aA.left+aA.right;
ay-=aA.top+aA.bottom;
}var ax=new ab(G(),null,true);
var aF={Contents:aw.attach(ax),Parent:av,MediaBox:[0,0,aE[0],aE[1]]};
var aC=new X(aw,aF);
aC._content=ax;
av.addPage(aw.attach(aC));
aC.transform(1,0,0,-1,0,aE[1]);
if(aA){aC.translate(aA.left,aA.top);
aC.rect(0,0,az,ay);
aC.clip();
}aw.pages.push(aC);
return aC;
};
aw.render=function(){var ax;
au("%PDF-1.4",K,"%\xc2\xc1\xda\xcf\xce",K,K);
for(ax=0;
ax<ar.length;
++ax){ar[ax].renderFull(au);
au(K,K);
}var ay=au.offset();
au("xref",K,0," ",ar.length+1,K);
au("0000000000 65535 f ",K);
for(ax=0;
ax<ar.length;
++ax){au(an(ar[ax]._offset,10)," 00000 n ",K);
}au(K);
au("trailer",K);
au(new Q({Size:ar.length+1,Root:ao,Info:new Q({Producer:new ac(ap("producer","Kendo UI PDF Generator")),Title:new ac(ap("title","")),Author:new ac(ap("author","")),Subject:new ac(ap("subject","")),Keywords:new ac(ap("keywords","")),Creator:new ac(ap("creator","Kendo UI PDF Generator")),CreationDate:ap("date",new Date())})}),K,K);
au("startxref",K,ay,K);
au("%%EOF",K);
return au.stream().offset(0);
};
}var l={"Times-Roman":true,"Times-Bold":true,"Times-Italic":true,"Times-BoldItalic":true,Helvetica:true,"Helvetica-Bold":true,"Helvetica-Oblique":true,"Helvetica-BoldOblique":true,Courier:true,"Courier-Bold":true,"Courier-Oblique":true,"Courier-BoldOblique":true,Symbol:true,ZapfDingbats:true};
function z(ar,ao){function ap(){if(q.console){if(q.console.error){q.console.error("Cannot load URL: %s",ar);
}else{q.console.log("Cannot load URL: %s",ar);
}}ao(null);
}var aq=new XMLHttpRequest();
aq.open("GET",ar,true);
if(r){aq.responseType="arraybuffer";
}aq.onload=function(){if(aq.status==200||aq.status==304){if(r){ao(new Uint8Array(aq.response));
}else{ao(new VBArray(aq.responseBody).toArray());
}}else{ap();
}};
aq.onerror=ap;
aq.send(null);
}function A(aq,ao){var ap=l[aq];
if(ap){ao(ap);
}else{z(aq,function(ar){if(ar==null){throw new Error("Cannot load font from "+aq);
}else{var at=new y.pdf.TTFFont(ar);
l[aq]=at;
ao(at);
}});
}}var t={};
function C(ar,ao){var ap=t[ar];
if(ap){ao(ap);
}else{ap=new Image();
if(!(/^data:/i.test(ar))){ap.crossOrigin="Anonymous";
}ap.src=ar;
var aq=function(){var av=document.createElement("canvas");
av.width=ap.width;
av.height=ap.height;
var aw=av.getContext("2d");
aw.drawImage(ap,0,0);
var aB;
try{aB=aw.getImageData(0,0,ap.width,ap.height);
}catch(ay){return ao(t[ar]="TAINTED");
}var az=false,aD=c(),au=c();
var aC=aB.data;
var aA=0;
while(aA<aC.length){aD.writeByte(aC[aA++]);
aD.writeByte(aC[aA++]);
aD.writeByte(aC[aA++]);
var at=aC[aA++];
if(at<255){az=true;
}au.writeByte(at);
}if(az){ap=new Z(ap.width,ap.height,aD,au);
}else{var ax=av.toDataURL("image/jpeg");
ax=ax.substr(ax.indexOf(";base64,")+8);
var aE=c();
aE.writeBase64(ax);
aE.offset(0);
ap=new U(ap.width,ap.height,aE);
}ao(t[ar]=ap);
};
if(ap.complete){aq();
}else{ap.onload=aq;
ap.onerror=function(at){ao(t[ar]="TAINTED");
};
}}}function H(ao){return function(at,ap){var ar=at.length,aq=ar;
if(ar===0){return ap();
}while(aq-->0){ao(at[aq],function(){if(--ar===0){ap();
}});
}};
}var B=H(A);
var D=H(C);
R.prototype={loadFonts:B,loadImages:D,getFont:function(ap){var ao=this.FONTS[ap];
if(!ao){ao=l[ap];
if(!ao){throw new Error("Font "+ap+" has not been loaded");
}if(ao===true){ao=this.attach(new aa(ap));
}else{ao=this.attach(new S(this,ao));
}this.FONTS[ap]=ao;
}return ao;
},getImage:function(ap){var ao=this.IMAGES[ap];
if(!ao){ao=t[ap];
if(!ao){throw new Error("Image "+ap+" has not been loaded");
}if(ao==="TAINTED"){return null;
}ao=this.IMAGES[ap]=this.attach(ao.asStream(this));
}return ao;
},getOpacityGS:function(at,ap){var ar=N(at).toFixed(3);
at=N(ar);
ar+=ap?"S":"F";
var ao=this._opacityGSCache||(this._opacityGSCache={});
var aq=ao[ar];
if(!aq){var au={Type:a("ExtGState")};
if(ap){au.CA=at;
}else{au.ca=at;
}aq=this.attach(new Q(au));
aq._resourceName=a("GS"+(++ai));
ao[ar]=aq;
}return aq;
},dict:function(ao){return new Q(ao);
},name:function(ao){return a(ao);
},stream:function(ap,ao){return new ab(ao,ap);
}};
function L(aq,ap,ao){while(aq.length<ap){aq=ao+aq;
}return aq;
}function an(ap,ao){return L(ap+"",ao,"0");
}function s(ap,ao){return Object.prototype.hasOwnProperty.call(ap,ao);
}var v=Array.isArray||function(ao){return ao instanceof Array;
};
function w(ao){return ao instanceof Date;
}function ag(ao,ap){ap("[");
if(ao.length>0){ap.withIndent(function(){for(var aq=0;
aq<ao.length;
++aq){if(aq>0&&aq%8===0){ap.indent(ao[aq]);
}else{ap(" ",ao[aq]);
}}});
}ap(" ]");
}function ah(ao,ap){ap("(D:",an(ao.getUTCFullYear(),4),an(ao.getUTCMonth()+1,2),an(ao.getUTCDate(),2),an(ao.getUTCHours(),2),an(ao.getUTCMinutes(),2),an(ao.getUTCSeconds(),2),"Z)");
}function I(ao){return ao*(72/25.4);
}function i(ao){return I(ao*10);
}function u(ao){return ao*72;
}function ak(ar,ao){if(typeof ar=="number"){return ar;
}if(typeof ar=="string"){var ap;
ap=/^\s*([0-9.]+)\s*(mm|cm|in|pt)\s*$/.exec(ar);
if(ap){var aq=N(ap[1]);
if(!isNaN(aq)){if(ap[2]=="pt"){return aq;
}return{mm:I,cm:i,"in":u}[ap[2]](aq);
}}}if(ao!=null){return ao;
}throw new Error("Can't parse unit: "+ar);
}function af(){}af.prototype.beforeRender=function(){};
function j(ap,ar,ao){if(!ao){ao=af;
}ap.prototype=new ao();
for(var aq in ar){if(s(ar,aq)){ap.prototype[aq]=ar[aq];
}}return ap;
}var ac=j(function ac(ao){this.value=ao;
},{render:function(aq){var ar="",ao=this.escape();
for(var ap=0;
ap<ao.length;
++ap){ar+=String.fromCharCode(ao.charCodeAt(ap)&255);
}aq("(",ar,")");
},escape:function(){return this.value.replace(/([\(\)\\])/g,"\\$1");
},toString:function(){return this.value;
}});
var T=j(function T(ao){this.value=ao;
},{render:function(ap){ap("<");
for(var ao=0;
ao<this.value.length;
++ao){ap(an(this.value.charCodeAt(ao).toString(16),4));
}ap(">");
}},ac);
var V=j(function V(ao){this.name=ao;
},{render:function(ao){ao("/"+this.escape());
},escape:function(){return this.name.replace(/[^\x21-\x7E]/g,function(ao){return"#"+an(ao.charCodeAt(0).toString(16),2);
});
},toString:function(){return this.name;
}});
var W={};
V.get=a;
function a(ao){if(s(W,ao)){return W[ao];
}return(W[ao]=new V(ao));
}var Q=j(function Q(ao){this.props=ao;
},{render:function(ap){var aq=this.props,ao=true;
ap("<<");
ap.withIndent(function(){for(var ar in aq){if(s(aq,ar)&&!/^_/.test(ar)){ao=false;
ap.indent(a(ar)," ",aq[ar]);
}}});
if(!ao){ap.indent();
}ap(">>");
}});
var ab=j(function ab(ap,aq,ao){if(typeof ap=="string"){var ar=c();
ar.write(ap);
ap=ar;
}this.data=ap;
this.props=aq||{};
this.compress=ao;
},{render:function(ap){var ao=this.data.get(),aq=this.props;
if(this.compress&&q.pako&&typeof q.pako.deflate=="function"){if(!aq.Filter){aq.Filter=[];
}else{if(!(aq.Filter instanceof Array)){aq.Filter=[aq.Filter];
}}aq.Filter.unshift(a("FlateDecode"));
ao=q.pako.deflate(ao);
}aq.Length=ao.length;
ap(new Q(aq)," stream",K);
ap.writeData(ao);
ap(K,"endstream");
}});
var P=j(function P(ao){ao=this.props=ao||{};
ao.Type=a("Catalog");
},{setPages:function(ao){this.props.Pages=ao;
}},Q);
var Y=j(function Y(){this.props={Type:a("Pages"),Kids:[],Count:0};
},{addPage:function(ao){this.props.Kids.push(ao);
this.props.Count++;
}},Q);
function U(aq,ap,ao){this.asStream=function(){var ar=new ab(ao,{Type:a("XObject"),Subtype:a("Image"),Width:aq,Height:ap,BitsPerComponent:8,ColorSpace:a("DeviceRGB"),Filter:a("DCTDecode")});
ar._resourceName=a("I"+(++ai));
return ar;
};
}function Z(ar,ap,aq,ao){this.asStream=function(au){var at=new ab(ao,{Type:a("XObject"),Subtype:a("Image"),Width:ar,Height:ap,BitsPerComponent:8,ColorSpace:a("DeviceGray")},true);
var av=new ab(aq,{Type:a("XObject"),Subtype:a("Image"),Width:ar,Height:ap,BitsPerComponent:8,ColorSpace:a("DeviceRGB"),SMask:au.attach(at)},true);
av._resourceName=a("I"+(++ai));
return av;
};
}var aa=j(function aa(ao){this.props={Type:a("Font"),Subtype:a("Type1"),BaseFont:a(ao)};
this._resourceName=a("F"+(++ai));
},{encodeText:function(ao){return new ac(ao+"");
}},Q);
var S=j(function S(aq,ao,ar){ar=this.props=ar||{};
ar.Type=a("Font");
ar.Subtype=a("Type0");
ar.Encoding=a("Identity-H");
this._pdf=aq;
this._font=ao;
this._sub=ao.makeSubset();
this._resourceName=a("F"+(++ai));
var ap=ao.head;
this.name=ao.psName;
var at=this.scale=ao.scale;
this.bbox=[ap.xMin*at,ap.yMin*at,ap.xMax*at,ap.yMax*at];
this.italicAngle=ao.post.italicAngle;
this.ascent=ao.ascent*at;
this.descent=ao.descent*at;
this.lineGap=ao.lineGap*at;
this.capHeight=ao.os2.capHeight||this.ascent;
this.xHeight=ao.os2.xHeight||0;
this.stemV=0;
this.familyClass=(ao.os2.familyClass||0)>>8;
this.isSerif=this.familyClass>=1&&this.familyClass<=7;
this.isScript=this.familyClass==10;
this.flags=((ao.post.isFixedPitch?1:0)|(this.isSerif?1<<1:0)|(this.isScript?1<<3:0)|(this.italicAngle!==0?1<<6:0)|(1<<5));
},{encodeText:function(ao){return new T(this._sub.encodeText(ao+""));
},getTextWidth:function(ap,at){var au=0,ao=this._font.cmap.getUnicodeEntry().codeMap;
for(var ar=0;
ar<at.length;
++ar){var aq=ao[at.charCodeAt(ar)];
au+=this._font.widthOfGlyph(aq||0);
}return au*ap/1000;
},beforeRender:function(){var aA=this;
var aw=aA._font;
var aB=aA._sub;
var aq=aB.render();
var ax=new ab(c(aq),{Length1:aq.length},true);
var at=aA._pdf.attach(new Q({Type:a("FontDescriptor"),FontName:a(aA._sub.psName),FontBBox:aA.bbox,Flags:aA.flags,StemV:aA.stemV,ItalicAngle:aA.italicAngle,Ascent:aA.ascent,Descent:aA.descent,CapHeight:aA.capHeight,XHeight:aA.xHeight,FontFile2:aA._pdf.attach(ax)}));
var ap=aB.ncid2ogid;
var av=aB.firstChar;
var ay=aB.lastChar;
var ao=[];
(function az(aG,aE){if(aG<=ay){var aF=ap[aG];
if(aF==null){az(aG+1);
}else{if(!aE){ao.push(aG,aE=[]);
}aE.push(aA._font.widthOfGlyph(aF));
az(aG+1,aE);
}}})(av);
var ar=new Q({Type:a("Font"),Subtype:a("CIDFontType2"),BaseFont:a(aA._sub.psName),CIDSystemInfo:new Q({Registry:new ac("Adobe"),Ordering:new ac("Identity"),Supplement:0}),FontDescriptor:at,FirstChar:av,LastChar:ay,DW:Math.round(aA._font.widthOfGlyph(0)),W:ao,CIDToGIDMap:aA._pdf.attach(aA._makeCidToGidMap())});
var au=aA.props;
au.BaseFont=a(aA._sub.psName);
au.DescendantFonts=[aA._pdf.attach(ar)];
var aC=new ad(av,ay,aB.subset);
var aD=new ab(G(),null,true);
aD.data(aC);
au.ToUnicode=aA._pdf.attach(aD);
},_makeCidToGidMap:function(){return new ab(c(this._sub.cidToGidMap()),null,true);
}},Q);
var ad=j(function ae(ao,ap,aq){this.firstChar=ao;
this.lastChar=ap;
this.map=aq;
},{render:function(ao){ao.indent("/CIDInit /ProcSet findresource begin");
ao.indent("12 dict begin");
ao.indent("begincmap");
ao.indent("/CIDSystemInfo <<");
ao.indent("  /Registry (Adobe)");
ao.indent("  /Ordering (UCS)");
ao.indent("  /Supplement 0");
ao.indent(">> def");
ao.indent("/CMapName /Adobe-Identity-UCS def");
ao.indent("/CMapType 2 def");
ao.indent("1 begincodespacerange");
ao.indent("  <0000><ffff>");
ao.indent("endcodespacerange");
var ap=this;
ao.indent(ap.lastChar-ap.firstChar+1," beginbfchar");
ao.withIndent(function(){for(var aq=ap.firstChar;
aq<=ap.lastChar;
++aq){var ar=ap.map[aq];
ao.indent("<",an(aq.toString(16),4),">","<",an(ar.toString(16),4),">");
}});
ao.indent("endbfchar");
ao.indent("endcmap");
ao.indent("CMapName currentdict /CMap defineresource pop");
ao.indent("end");
ao.indent("end");
}});
function F(ao){return ao.map(function(ap){return v(ap)?F(ap):typeof ap=="number"?(Math.round(ap*1000)/1000).toFixed(3):ap;
}).join(" ");
}function e(av,aw,ar,ao,ax,at,ap){var au=F([aw,ar,ao,ax,at,ap]);
var aq=av.GRAD_COL_FUNCTIONS[au];
if(!aq){aq=av.GRAD_COL_FUNCTIONS[au]=av.attach(new Q({FunctionType:2,Domain:[0,1],Range:[0,1,0,1,0,1],N:1,C0:[aw,ar,ao],C1:[ax,at,ap]}));
}return aq;
}function h(at,ao,ap){var ar=F([ao,ap]);
var aq=at.GRAD_OPC_FUNCTIONS[ar];
if(!aq){aq=at.GRAD_OPC_FUNCTIONS[ar]=at.attach(new Q({FunctionType:2,Domain:[0,1],Range:[0,1],N:1,C0:[ao],C1:[ap]}));
}return aq;
}function E(ay,aB){var au=false;
var ax=[];
var ap=[];
var aw=[];
var at=[];
var av,az,aq,aA,ar;
for(av=1;
av<aB.length;
++av){az=aB[av-1];
aq=aB[av];
aA=az.color;
ar=aq.color;
ap.push(e(ay,aA.r,aA.g,aA.b,ar.r,ar.g,ar.b));
if(aA.a<1||ar.a<1){au=true;
}aw.push(aq.offset);
at.push(0,1);
}if(au){for(av=1;
av<aB.length;
++av){az=aB[av-1];
aq=aB[av];
aA=az.color;
ar=aq.color;
ax.push(h(ay,aA.a,ar.a));
}}aw.pop();
return{hasAlpha:au,colors:ao(ap),opacities:au?ao(ax):null};
function ao(aC){if(aC.length==1){return aC[0];
}return{FunctionType:3,Functions:aC,Domain:[0,1],Bounds:aw,Encode:at};
}}function d(av,au,ax,aq,ar,ap){var aw,at;
if(!ap){var ao=[au].concat(aq);
ax.forEach(function(ay){ao.push(ay.offset,ay.color.r,ay.color.g,ay.color.b);
});
at=F(ao);
aw=av.GRAD_COL[at];
}if(!aw){aw=new Q({Type:a("Shading"),ShadingType:au?3:2,ColorSpace:a("DeviceRGB"),Coords:aq,Domain:[0,1],Function:ar,Extend:[true,true]});
av.attach(aw);
aw._resourceName="S"+(++ai);
if(at){av.GRAD_COL[at]=aw;
}}return aw;
}function g(aw,au,ax,aq,ar,ap){var av,at;
if(!ap){var ao=[au].concat(aq);
ax.forEach(function(ay){ao.push(ay.offset,ay.color.a);
});
at=F(ao);
av=aw.GRAD_OPC[at];
}if(!av){av=new Q({Type:a("ExtGState"),AIS:false,CA:1,ca:1,SMask:{Type:a("Mask"),S:a("Luminosity"),G:aw.attach(new ab("/a0 gs /s0 sh",{Type:a("XObject"),Subtype:a("Form"),FormType:1,BBox:(ap?[ap.left,ap.top+ap.height,ap.left+ap.width,ap.top]:[0,1,1,0]),Group:{Type:a("Group"),S:a("Transparency"),CS:a("DeviceGray"),I:true},Resources:{ExtGState:{a0:{CA:1,ca:1}},Shading:{s0:{ColorSpace:a("DeviceGray"),Coords:aq,Domain:[0,1],ShadingType:au?3:2,Function:ar,Extend:[true,true]}}}}))}});
aw.attach(av);
av._resourceName="O"+(++ai);
if(at){aw.GRAD_OPC[at]=av;
}}return av;
}function f(av,ar,ao){var at=ar.type=="radial";
var aq=E(av,ar.stops);
var ap=at?[ar.start.x,ar.start.y,ar.start.r,ar.end.x,ar.end.y,ar.end.r]:[ar.start.x,ar.start.y,ar.end.x,ar.end.y];
var aw=d(av,at,ar.stops,ap,aq.colors,ar.userSpace&&ao);
var au=aq.hasAlpha?g(av,at,ar.stops,ap,aq.opacities,ar.userSpace&&ao):null;
return{hasAlpha:aq.hasAlpha,shading:aw,opacity:au};
}var X=j(function X(ao,ap){this._pdf=ao;
this._rcount=0;
this._textMode=false;
this._fontResources={};
this._gsResources={};
this._xResources={};
this._patResources={};
this._shResources={};
this._opacity=1;
this._matrix=[1,0,0,1,0,0];
this._annotations=[];
this._font=null;
this._fontSize=null;
this._contextStack=[];
ap=this.props=ap||{};
ap.Type=a("Page");
ap.ProcSet=[a("PDF"),a("Text"),a("ImageB"),a("ImageC"),a("ImageI")];
ap.Resources=new Q({Font:new Q(this._fontResources),ExtGState:new Q(this._gsResources),XObject:new Q(this._xResources),Pattern:new Q(this._patResources),Shading:new Q(this._shResources)});
ap.Annots=this._annotations;
},{_out:function(){this._content.data.apply(null,arguments);
},transform:function(ao,ap,aq,ar,at,au){if(!x(arguments)){this._matrix=J(arguments,this._matrix);
this._out(ao," ",ap," ",aq," ",ar," ",at," ",au," cm");
this._out(K);
}},translate:function(ao,ap){this.transform(1,0,0,1,ao,ap);
},scale:function(ao,ap){this.transform(ao,0,0,ap,0,0);
},rotate:function(ao){var ap=Math.cos(ao),aq=Math.sin(ao);
this.transform(ap,aq,-aq,ap,0,0);
},beginText:function(){this._textMode=true;
this._out("BT",K);
},endText:function(){this._textMode=false;
this._out("ET",K);
},_requireTextMode:function(){if(!this._textMode){throw new Error("Text mode required; call page.beginText() first");
}},_requireFont:function(){if(!this._font){throw new Error("No font selected; call page.setFont() first");
}},setFont:function(ao,ap){this._requireTextMode();
if(ao==null){ao=this._font;
}else{if(!(ao instanceof S)){ao=this._pdf.getFont(ao);
}}if(ap==null){ap=this._fontSize;
}this._fontResources[ao._resourceName]=ao;
this._font=ao;
this._fontSize=ap;
this._out(ao._resourceName," ",ap," Tf",K);
},setTextLeading:function(ao){this._requireTextMode();
this._out(ao," TL",K);
},setTextRenderingMode:function(ao){this._requireTextMode();
this._out(ao," Tr",K);
},showText:function(ar,ap){this._requireFont();
if(ar.length>1&&ap&&this._font instanceof S){var ao=this._font.getTextWidth(this._fontSize,ar);
var aq=ap/ao*100;
this._out(aq," Tz ");
}this._out(this._font.encodeText(ar)," Tj",K);
},showTextNL:function(ao){this._requireFont();
this._out(this._font.encodeText(ao)," '",K);
},addLink:function(ar,ao){var ap=this._toPage({x:ao.left,y:ao.bottom});
var aq=this._toPage({x:ao.right,y:ao.top});
this._annotations.push(new Q({Type:a("Annot"),Subtype:a("Link"),Rect:[ap.x,ap.y,aq.x,aq.y],Border:[0,0,0],A:new Q({Type:a("Action"),S:a("URI"),URI:new ac(ar)})}));
},setStrokeColor:function(aq,ap,ao){this._out(aq," ",ap," ",ao," RG",K);
},setOpacity:function(ao){this.setFillOpacity(ao);
this.setStrokeOpacity(ao);
this._opacity*=ao;
},setStrokeOpacity:function(ap){if(ap<1){var ao=this._pdf.getOpacityGS(this._opacity*ap,true);
this._gsResources[ao._resourceName]=ao;
this._out(ao._resourceName," gs",K);
}},setFillColor:function(aq,ap,ao){this._out(aq," ",ap," ",ao," rg",K);
},setFillOpacity:function(ap){if(ap<1){var ao=this._pdf.getOpacityGS(this._opacity*ap,false);
this._gsResources[ao._resourceName]=ao;
this._out(ao._resourceName," gs",K);
}},gradient:function(aq,ao){this.save();
this.rect(ao.left,ao.top,ao.width,ao.height);
this.clip();
if(!aq.userSpace){this.transform(ao.width,0,0,ao.height,ao.left,ao.top);
}var ap=f(this._pdf,aq,ao);
var at=ap.shading._resourceName,ar;
this._shResources[at]=ap.shading;
if(ap.hasAlpha){ar=ap.opacity._resourceName;
this._gsResources[ar]=ap.opacity;
this._out("/"+ar+" gs ");
}this._out("/"+at+" sh",K);
this.restore();
},setDashPattern:function(ao,ap){this._out(ao," ",ap," d",K);
},setLineWidth:function(ao){this._out(ao," w",K);
},setLineCap:function(ao){this._out(ao," J",K);
},setLineJoin:function(ao){this._out(ao," j",K);
},setMitterLimit:function(ao){this._out(ao," M",K);
},save:function(){this._contextStack.push(this._context());
this._out("q",K);
},restore:function(){this._out("Q",K);
this._context(this._contextStack.pop());
},moveTo:function(ao,ap){this._out(ao," ",ap," m",K);
},lineTo:function(ao,ap){this._out(ao," ",ap," l",K);
},bezier:function(ao,ar,ap,at,aq,au){this._out(ao," ",ar," ",ap," ",at," ",aq," ",au," c",K);
},bezier1:function(ao,aq,ap,ar){this._out(ao," ",aq," ",ap," ",ar," y",K);
},bezier2:function(ao,aq,ap,ar){this._out(ao," ",aq," ",ap," ",ar," v",K);
},close:function(){this._out("h",K);
},rect:function(aq,ar,ap,ao){this._out(aq," ",ar," ",ap," ",ao," re",K);
},ellipse:function(au,av,ar,at){function ao(aw){return au+aw;
}function ap(aw){return av+aw;
}var aq=0.5522847498307936;
this.moveTo(ao(0),ap(at));
this.bezier(ao(ar*aq),ap(at),ao(ar),ap(at*aq),ao(ar),ap(0));
this.bezier(ao(ar),ap(-at*aq),ao(ar*aq),ap(-at),ao(0),ap(-at));
this.bezier(ao(-ar*aq),ap(-at),ao(-ar),ap(-at*aq),ao(-ar),ap(0));
this.bezier(ao(-ar),ap(at*aq),ao(-ar*aq),ap(at),ao(0),ap(at));
},circle:function(ap,aq,ao){this.ellipse(ap,aq,ao,ao);
},stroke:function(){this._out("S",K);
},nop:function(){this._out("n",K);
},clip:function(){this._out("W n",K);
},clipStroke:function(){this._out("W S",K);
},closeStroke:function(){this._out("s",K);
},fill:function(){this._out("f",K);
},fillStroke:function(){this._out("B",K);
},drawImage:function(ap){var ao=this._pdf.getImage(ap);
if(ao){this._xResources[ao._resourceName]=ao;
this._out(ao._resourceName," Do",K);
}},comment:function(ap){var ao=this;
ap.split(/\r?\n/g).forEach(function(aq){ao._out("% ",aq,K);
});
},_context:function(ao){if(ao!=null){this._opacity=ao.opacity;
this._matrix=ao.matrix;
}else{return{opacity:this._opacity,matrix:this._matrix};
}},_toPage:function(aw){var av=this._matrix;
var ao=av[0],ap=av[1],aq=av[2],ar=av[3],at=av[4],au=av[5];
return{x:ao*aw.x+aq*aw.y+at,y:ap*aw.x+ar*aw.y+au};
}},Q);
function c(ao){var au=0,at=0;
if(ao==null){ao=r?new Uint8Array(256):[];
}else{at=ao.length;
}var ap=r?function(aQ){if(aQ>=ao.length){var aR=new Uint8Array(Math.max(aQ+256,ao.length*2));
aR.set(ao,0);
ao=aR;
}}:function(){};
var ar=r?function(){return new Uint8Array(ao.buffer,0,at);
}:function(){return ao;
};
var aH=r?function(aQ){if(typeof aQ=="string"){return aP(aQ);
}var aR=aQ.length;
ap(au+aR);
ao.set(aQ,au);
au+=aR;
if(au>at){at=au;
}}:function(aQ){if(typeof aQ=="string"){return aP(aQ);
}for(var aR=0;
aR<aQ.length;
++aR){aI(aQ[aR]);
}};
var aE=r?function(aR,aQ){if(ao.buffer.slice){return new Uint8Array(ao.buffer.slice(aR,aR+aQ));
}else{var aS=new Uint8Array(aQ);
aS.set(new Uint8Array(ao.buffer,aR,aQ));
return aS;
}}:function(aR,aQ){return ao.slice(aR,aR+aQ);
};
function aq(){return au>=at;
}function aw(){return au<at?ao[au++]:0;
}function aI(aQ){ap(au);
ao[au++]=aQ&255;
if(au>at){at=au;
}}function aB(){return(aw()<<8)|aw();
}function aN(aQ){aI(aQ>>8);
aI(aQ);
}function aC(){var aQ=aB();
return aQ>=32768?aQ-65536:aQ;
}function aO(aQ){aN(aQ<0?aQ+65536:aQ);
}function az(){return(aB()*65536)+aB();
}function aL(aQ){aN((aQ>>>16)&65535);
aN(aQ&65535);
}function aA(){var aQ=az();
return aQ>=2147483648?aQ-4294967296:aQ;
}function aM(aQ){aL(aQ<0?aQ+4294967296:aQ);
}function ax(){return az()/65536;
}function aJ(aQ){aL(Math.round(aQ*65536));
}function ay(){return aA()/65536;
}function aK(aQ){aM(Math.round(aQ*65536));
}function av(aQ){return aG(aQ,aw);
}function aD(aQ){return String.fromCharCode.apply(String,av(aQ));
}function aP(aR){for(var aQ=0;
aQ<aR.length;
++aQ){aI(aR.charCodeAt(aQ));
}}function aG(aR,aS){for(var aT=new Array(aR),aQ=0;
aQ<aR;
++aQ){aT[aQ]=aS();
}return aT;
}var aF={eof:aq,readByte:aw,writeByte:aI,readShort:aB,writeShort:aN,readLong:az,writeLong:aL,readFixed:ax,writeFixed:aJ,readShort_:aC,writeShort_:aO,readLong_:aA,writeLong_:aM,readFixed_:ay,writeFixed_:aK,read:av,write:aH,readString:aD,writeString:aP,times:aG,get:ar,slice:aE,offset:function(aQ){if(aQ!=null){au=aQ;
return aF;
}return au;
},skip:function(aQ){au+=aQ;
},toString:function(){throw new Error("FIX CALLER.  BinaryStream is no longer convertible to string!");
},length:function(){return at;
},saveExcursion:function(aQ){var aR=au;
try{return aQ();
}finally{au=aR;
}},writeBase64:function(aQ){if(window.atob){aP(window.atob(aQ));
}else{aH(b.decode(aQ));
}},base64:function(){return b.encode(ar());
}};
return aF;
}function al(ao){return ao.replace(/^\s*(['"])(.*)\1\s*$/,"$2");
}function O(ao){var ar=/^\s*((normal|italic)\s+)?((normal|small-caps)\s+)?((normal|bold|\d+)\s+)?(([0-9.]+)(px|pt))(\/(([0-9.]+)(px|pt)|normal))?\s+(.*?)\s*$/i;
var aq=ar.exec(ao);
if(!aq){return{fontSize:12,fontFamily:"sans-serif"};
}var ap=aq[8]?parseInt(aq[8],10):12;
return{italic:aq[2]&&aq[2].toLowerCase()=="italic",variant:aq[4],bold:aq[6]&&/bold|700/i.test(aq[6]),fontSize:ap,lineHeight:aq[12]?aq[12]=="normal"?ap:parseInt(aq[12],10):null,fontFamily:aq[14].split(/\s*,\s*/g).map(al)};
}function o(at){function aq(av){if(at.bold){av+="|bold";
}if(at.italic){av+="|italic";
}return av.toLowerCase();
}var ao=at.fontFamily;
var ar,au;
if(ao instanceof Array){for(var ap=0;
ap<ao.length;
++ap){ar=aq(ao[ap]);
au=m[ar];
if(au){break;
}}}else{au=m[ao.toLowerCase()];
}while(typeof au=="function"){au=au();
}if(!au){au="Times-Roman";
}return au;
}var m={serif:"Times-Roman","serif|bold":"Times-Bold","serif|italic":"Times-Italic","serif|bold|italic":"Times-BoldItalic","sans-serif":"Helvetica","sans-serif|bold":"Helvetica-Bold","sans-serif|italic":"Helvetica-Oblique","sans-serif|bold|italic":"Helvetica-BoldOblique",monospace:"Courier","monospace|bold":"Courier-Bold","monospace|italic":"Courier-Oblique","monospace|bold|italic":"Courier-BoldOblique",zapfdingbats:"ZapfDingbats","zapfdingbats|bold":"ZapfDingbats","zapfdingbats|italic":"ZapfDingbats","zapfdingbats|bold|italic":"ZapfDingbats"};
function n(ao,ap){ao=ao.toLowerCase();
m[ao]=function(){return m[ap];
};
m[ao+"|bold"]=function(){return m[ap+"|bold"];
};
m[ao+"|italic"]=function(){return m[ap+"|italic"];
};
m[ao+"|bold|italic"]=function(){return m[ap+"|bold|italic"];
};
}n("Times New Roman","serif");
n("Courier New","monospace");
n("Arial","sans-serif");
n("Helvetica","sans-serif");
n("Verdana","sans-serif");
n("Tahoma","sans-serif");
n("Georgia","sans-serif");
n("Monaco","monospace");
n("Andale Mono","monospace");
function k(ap,aq){if(arguments.length==1){for(var ao in ap){if(s(ap,ao)){k(ao,ap[ao]);
}}}else{ap=ap.toLowerCase();
m[ap]=aq;
switch(ap){case"dejavu sans":m["sans-serif"]=aq;
break;
case"dejavu sans|bold":m["sans-serif|bold"]=aq;
break;
case"dejavu sans|italic":m["sans-serif|italic"]=aq;
break;
case"dejavu sans|bold|italic":m["sans-serif|bold|italic"]=aq;
break;
case"dejavu serif":m.serif=aq;
break;
case"dejavu serif|bold":m["serif|bold"]=aq;
break;
case"dejavu serif|italic":m["serif|italic"]=aq;
break;
case"dejavu serif|bold|italic":m["serif|bold|italic"]=aq;
break;
case"dejavu mono":m.monospace=aq;
break;
case"dejavu mono|bold":m["monospace|bold"]=aq;
break;
case"dejavu mono|italic":m["monospace|italic"]=aq;
break;
case"dejavu mono|bold|italic":m["monospace|bold|italic"]=aq;
break;
}}}y.pdf={Document:R,BinaryStream:c,defineFont:k,parseFontDef:O,getFontURL:o,loadFonts:B,loadImages:D,getPaperOptions:p,TEXT_RENDERING_MODE:{fill:0,stroke:1,fillAndStroke:2,invisible:3,fillAndClip:4,strokeAndClip:5,fillStrokeClip:6,clip:7}};
function J(ao,ar){var ap=ao[0],at=ao[1],av=ao[2],ax=ao[3],az=ao[4],aB=ao[5];
var aq=ar[0],au=ar[1],aw=ar[2],ay=ar[3],aA=ar[4],aC=ar[5];
return[ap*aq+at*aw,ap*au+at*ay,av*aq+ax*aw,av*au+ax*ay,az*aq+aB*aw+aA,az*au+aB*ay+aC];
}function x(ao){return ao[0]===1&&ao[1]===0&&ao[2]===0&&ao[3]===1&&ao[4]===0&&ao[5]===0;
}})(this,parseFloat);
(function(e){function g(w,v){return Object.prototype.hasOwnProperty.call(w,v);
}function r(v){return Object.keys(v).sort(function(w,x){return w-x;
}).map(parseFloat);
}var p=e.kendo.pdf;
var a=p.BinaryStream;
function d(v){this.raw=v;
this.scalerType=v.readLong();
this.tableCount=v.readShort();
this.searchRange=v.readShort();
this.entrySelector=v.readShort();
this.rangeShift=v.readShort();
var y=this.tables={};
for(var x=0;
x<this.tableCount;
++x){var w={tag:v.readString(4),checksum:v.readLong(),offset:v.readLong(),length:v.readLong()};
y[w.tag]=w;
}}d.prototype={readTable:function(x,v){var w=this.tables[x];
if(!w){throw new Error("Table "+x+" not found in directory");
}return(this[x]=w.table=new v(this,w));
},render:function(I){var G=Object.keys(I).length;
var z=Math.pow(2,Math.floor(Math.log(G)/Math.LN2));
var D=z*16;
var x=Math.floor(Math.log(z)/Math.LN2);
var C=G*16-D;
var B=a();
B.writeLong(this.scalerType);
B.writeShort(G);
B.writeShort(D);
B.writeShort(x);
B.writeShort(C);
var w=G*16;
var A=B.offset()+w;
var y=null;
var H=a();
for(var J in I){if(g(I,J)){var F=I[J];
B.writeString(J);
B.writeLong(this.checksum(F));
B.writeLong(A);
B.writeLong(F.length);
H.write(F);
if(J=="head"){y=A;
}A+=F.length;
while(A%4){H.writeByte(0);
A++;
}}}B.write(H.get());
var E=this.checksum(B.get());
var v=2981146554-E;
B.offset(y+8);
B.writeLong(v);
return B.get();
},checksum:function(v){v=a(v);
var w=0;
while(!v.eof()){w+=v.readLong();
}return w&4294967295;
}};
function c(x){function v(z,y){this.definition=y;
this.length=y.length;
this.offset=y.offset;
this.file=z;
this.rawData=z.raw;
this.parse(z.raw);
}v.prototype.raw=function(){return this.rawData.slice(this.offset,this.length);
};
for(var w in x){if(g(x,w)){v[w]=v.prototype[w]=x[w];
}}return v;
}var h=c({parse:function(v){v.offset(this.offset);
this.version=v.readLong();
this.revision=v.readLong();
this.checkSumAdjustment=v.readLong();
this.magicNumber=v.readLong();
this.flags=v.readShort();
this.unitsPerEm=v.readShort();
this.created=v.read(8);
this.modified=v.read(8);
this.xMin=v.readShort_();
this.yMin=v.readShort_();
this.xMax=v.readShort_();
this.yMax=v.readShort_();
this.macStyle=v.readShort();
this.lowestRecPPEM=v.readShort();
this.fontDirectionHint=v.readShort_();
this.indexToLocFormat=v.readShort_();
this.glyphDataFormat=v.readShort_();
},render:function(v){var w=a();
w.writeLong(this.version);
w.writeLong(this.revision);
w.writeLong(0);
w.writeLong(this.magicNumber);
w.writeShort(this.flags);
w.writeShort(this.unitsPerEm);
w.write(this.created);
w.write(this.modified);
w.writeShort_(this.xMin);
w.writeShort_(this.yMin);
w.writeShort_(this.xMax);
w.writeShort_(this.yMax);
w.writeShort(this.macStyle);
w.writeShort(this.lowestRecPPEM);
w.writeShort_(this.fontDirectionHint);
w.writeShort_(v);
w.writeShort_(this.glyphDataFormat);
return w.get();
}});
var k=c({parse:function(v){v.offset(this.offset);
var w=this.file.head.indexToLocFormat;
if(w===0){this.offsets=v.times(this.length/2,function(){return 2*v.readShort();
});
}else{this.offsets=v.times(this.length/4,v.readLong);
}},offsetOf:function(v){return this.offsets[v];
},lengthOf:function(v){return this.offsets[v+1]-this.offsets[v];
},render:function(x){var y=a();
var w=x[x.length-1]>65535;
for(var v=0;
v<x.length;
++v){if(w){y.writeLong(x[v]);
}else{y.writeShort(x[v]/2);
}}return{format:w?1:0,table:y.get()};
}});
var i=c({parse:function(v){v.offset(this.offset);
this.version=v.readLong();
this.ascent=v.readShort_();
this.descent=v.readShort_();
this.lineGap=v.readShort_();
this.advanceWidthMax=v.readShort();
this.minLeftSideBearing=v.readShort_();
this.minRightSideBearing=v.readShort_();
this.xMaxExtent=v.readShort_();
this.caretSlopeRise=v.readShort_();
this.caretSlopeRun=v.readShort_();
this.caretOffset=v.readShort_();
v.skip(4*2);
this.metricDataFormat=v.readShort_();
this.numOfLongHorMetrics=v.readShort();
},render:function(v){var w=a();
w.writeLong(this.version);
w.writeShort_(this.ascent);
w.writeShort_(this.descent);
w.writeShort_(this.lineGap);
w.writeShort(this.advanceWidthMax);
w.writeShort_(this.minLeftSideBearing);
w.writeShort_(this.minRightSideBearing);
w.writeShort_(this.xMaxExtent);
w.writeShort_(this.caretSlopeRise);
w.writeShort_(this.caretSlopeRun);
w.writeShort_(this.caretOffset);
w.write([0,0,0,0,0,0,0,0]);
w.writeShort_(this.metricDataFormat);
w.writeShort(v.length);
return w.get();
}});
var l=c({parse:function(v){v.offset(this.offset);
this.version=v.readLong();
this.numGlyphs=v.readShort();
this.maxPoints=v.readShort();
this.maxContours=v.readShort();
this.maxComponentPoints=v.readShort();
this.maxComponentContours=v.readShort();
this.maxZones=v.readShort();
this.maxTwilightPoints=v.readShort();
this.maxStorage=v.readShort();
this.maxFunctionDefs=v.readShort();
this.maxInstructionDefs=v.readShort();
this.maxStackElements=v.readShort();
this.maxSizeOfInstructions=v.readShort();
this.maxComponentElements=v.readShort();
this.maxComponentDepth=v.readShort();
},render:function(v){var w=a();
w.writeLong(this.version);
w.writeShort(v.length);
w.writeShort(this.maxPoints);
w.writeShort(this.maxContours);
w.writeShort(this.maxComponentPoints);
w.writeShort(this.maxComponentContours);
w.writeShort(this.maxZones);
w.writeShort(this.maxTwilightPoints);
w.writeShort(this.maxStorage);
w.writeShort(this.maxFunctionDefs);
w.writeShort(this.maxInstructionDefs);
w.writeShort(this.maxStackElements);
w.writeShort(this.maxSizeOfInstructions);
w.writeShort(this.maxComponentElements);
w.writeShort(this.maxComponentDepth);
return w.get();
}});
var j=c({parse:function(v){v.offset(this.offset);
var w=this.file,x=w.hhea;
this.metrics=v.times(x.numOfLongHorMetrics,function(){return{advance:v.readShort(),lsb:v.readShort_()};
});
var y=w.maxp.numGlyphs-w.hhea.numOfLongHorMetrics;
this.leftSideBearings=v.times(y,v.readShort_);
},forGlyph:function(v){var w=this.metrics;
var x=w.length;
if(v<x){return w[v];
}return{advance:w[x-1].advance,lsb:this.leftSideBearings[v-x]};
},render:function(v){var y=a();
for(var w=0;
w<v.length;
++w){var x=this.forGlyph(v[w]);
y.writeShort(x.advance);
y.writeShort_(x.lsb);
}return y.get();
}});
var f=(function(){function y(D){this.raw=D;
}y.prototype={compound:false,render:function(){return this.raw.get();
}};
var v=1;
var z=8;
var x=32;
var B=64;
var A=128;
var C=256;
function w(D){this.raw=D;
var F=this.glyphIds=[];
var G=this.idOffsets=[];
while(true){var E=D.readShort();
G.push(D.offset());
F.push(D.readShort());
if(!(E&x)){break;
}D.skip(E&v?4:2);
if(E&A){D.skip(8);
}else{if(E&B){D.skip(4);
}else{if(E&z){D.skip(2);
}}}}}w.prototype={compound:true,render:function(F){var G=a(this.raw.get());
for(var D=0;
D<this.glyphIds.length;
++D){var E=this.glyphIds[D];
G.offset(this.idOffsets[D]);
G.writeShort(F[E]);
}return G.get();
}};
return c({parse:function(D){this.cache={};
},glyphFor:function(G){var D=this.cache;
if(g(D,G)){return D[G];
}var I=this.file.loca;
var H=I.lengthOf(G);
if(H===0){return(D[G]=null);
}var E=this.rawData;
var K=this.offset+I.offsetOf(G);
var L=a(E.slice(K,H));
var J=L.readShort_();
var N=L.readShort_();
var P=L.readShort_();
var M=L.readShort_();
var O=L.readShort_();
var F=D[G]=J==-1?new w(L):new y(L);
F.numberOfContours=J;
F.xMin=N;
F.yMin=P;
F.xMax=M;
F.yMax=O;
return F;
},render:function(E,J,I){var K=a(),H=[];
for(var F=0;
F<J.length;
++F){var G=J[F];
var D=E[G];
H.push(K.offset());
if(D){K.write(D.render(I));
}}H.push(K.offset());
return{table:K.get(),offsets:H};
}});
}());
var m=(function(){function v(x,w){this.text=x;
this.length=x.length;
this.platformID=w.platformID;
this.platformSpecificID=w.platformSpecificID;
this.languageID=w.languageID;
this.nameID=w.nameID;
}return c({parse:function(x){x.offset(this.offset);
var y=x.readShort();
var w=x.readShort();
var C=this.offset+x.readShort();
var A=x.times(w,function(){return{platformID:x.readShort(),platformSpecificID:x.readShort(),languageID:x.readShort(),nameID:x.readShort(),length:x.readShort(),offset:x.readShort()+C};
});
var D=this.strings={};
for(var z=0;
z<A.length;
++z){var B=A[z];
x.offset(B.offset);
var E=x.readString(B.length);
if(!D[B.nameID]){D[B.nameID]=[];
}D[B.nameID].push(new v(E,B));
}this.postscriptEntry=D[6][0];
this.postscriptName=this.postscriptEntry.text.replace(/[^\x20-\x7F]/g,"");
},render:function(A){var D=this.strings;
var C=0;
for(var w in D){if(g(D,w)){C+=D[w].length;
}}var z=a();
var E=a();
z.writeShort(0);
z.writeShort(C);
z.writeShort(6+12*C);
for(w in D){if(g(D,w)){var y=w==6?[new v(A,this.postscriptEntry)]:D[w];
for(var x=0;
x<y.length;
++x){var B=y[x];
z.writeShort(B.platformID);
z.writeShort(B.platformSpecificID);
z.writeShort(B.languageID);
z.writeShort(B.nameID);
z.writeShort(B.length);
z.writeShort(E.offset());
E.writeString(B.text);
}}}z.write(E.get());
return z.get();
}});
})();
var q=(function(){var v=".notdef .null nonmarkingreturn space exclam quotedbl numbersign dollar percent ampersand quotesingle parenleft parenright asterisk plus comma hyphen period slash zero one two three four five six seven eight nine colon semicolon less equal greater question at A B C D E F G H I J K L M N O P Q R S T U V W X Y Z bracketleft backslash bracketright asciicircum underscore grave a b c d e f g h i j k l m n o p q r s t u v w x y z braceleft bar braceright asciitilde Adieresis Aring Ccedilla Eacute Ntilde Odieresis Udieresis aacute agrave acircumflex adieresis atilde aring ccedilla eacute egrave ecircumflex edieresis iacute igrave icircumflex idieresis ntilde oacute ograve ocircumflex odieresis otilde uacute ugrave ucircumflex udieresis dagger degree cent sterling section bullet paragraph germandbls registered copyright trademark acute dieresis notequal AE Oslash infinity plusminus lessequal greaterequal yen mu partialdiff summation product pi integral ordfeminine ordmasculine Omega ae oslash questiondown exclamdown logicalnot radical florin approxequal Delta guillemotleft guillemotright ellipsis nonbreakingspace Agrave Atilde Otilde OE oe endash emdash quotedblleft quotedblright quoteleft quoteright divide lozenge ydieresis Ydieresis fraction currency guilsinglleft guilsinglright fi fl daggerdbl periodcentered quotesinglbase quotedblbase perthousand Acircumflex Ecircumflex Aacute Edieresis Egrave Iacute Icircumflex Idieresis Igrave Oacute Ocircumflex apple Ograve Uacute Ucircumflex Ugrave dotlessi circumflex tilde macron breve dotaccent ring cedilla hungarumlaut ogonek caron Lslash lslash Scaron scaron Zcaron zcaron brokenbar Eth eth Yacute yacute Thorn thorn minus multiply onesuperior twosuperior threesuperior onehalf onequarter threequarters franc Gbreve gbreve Idotaccent Scedilla scedilla Cacute cacute Ccaron ccaron dcroat".split(/\s+/g);
return c({parse:function(w){w.offset(this.offset);
this.format=w.readLong();
this.italicAngle=w.readFixed_();
this.underlinePosition=w.readShort_();
this.underlineThickness=w.readShort_();
this.isFixedPitch=w.readLong();
this.minMemType42=w.readLong();
this.maxMemType42=w.readLong();
this.minMemType1=w.readLong();
this.maxMemType1=w.readLong();
var y;
switch(this.format){case 65536:case 196608:break;
case 131072:y=w.readShort();
this.glyphNameIndex=w.times(y,w.readShort);
this.names=[];
var x=this.offset+this.length;
while(w.offset()<x){this.names.push(w.readString(w.readByte()));
}break;
case 151552:y=w.readShort();
this.offsets=w.read(y);
break;
case 262144:this.map=w.times(this.file.maxp.numGlyphs,w.readShort);
break;
}},glyphFor:function(w){switch(this.format){case 65536:return v[w]||".notdef";
case 131072:var x=this.glyphNameIndex[w];
if(x<v.length){return v[x];
}return this.names[x-v.length]||".notdef";
case 151552:case 196608:return".notdef";
case 262144:return this.map[w]||65535;
}},render:function(A){if(this.format==196608){return this.raw();
}var B=a(this.rawData.slice(this.offset,32));
B.writeLong(131072);
B.offset(32);
var z=[];
var D=[];
for(var w=0;
w<A.length;
++w){var x=A[w];
var C=this.glyphFor(x);
var y=v.indexOf(C);
if(y>=0){z.push(y);
}else{z.push(v.length+D.length);
D.push(C);
}}B.writeShort(A.length);
for(w=0;
w<z.length;
++w){B.writeShort(z[w]);
}for(w=0;
w<D.length;
++w){B.writeByte(D[w].length);
B.writeString(D[w]);
}return B.get();
}});
})();
var b=(function(){function v(x,y){var z=this;
z.platformID=x.readShort();
z.platformSpecificID=x.readShort();
z.offset=y+x.readLong();
x.saveExcursion(function(){x.offset(z.offset);
z.format=x.readShort();
z.length=x.readShort();
z.language=x.readShort();
z.isUnicode=(z.platformID==3&&z.platformSpecificID==1&&z.format==4)||(z.platformID===0&&z.format==4);
z.codeMap={};
switch(z.format){case 0:for(var G=0;
G<256;
++G){z.codeMap[G]=x.readByte();
}break;
case 4:var K=x.readShort()/2;
x.skip(6);
var D=x.times(K,x.readShort);
x.skip(2);
var M=x.times(K,x.readShort);
var H=x.times(K,x.readShort_);
var I=x.times(K,x.readShort);
var B=(z.length+z.offset-x.offset())/2;
var F=x.times(B,x.readShort);
for(G=0;
G<K;
++G){var L=M[G],C=D[G];
for(var A=L;
A<=C;
++A){var E;
if(I[G]===0){E=A+H[G];
}else{var J=I[G]/2-(K-G)+(A-L);
E=F[J]||0;
if(E!==0){E+=H[G];
}}z.codeMap[A]=E&65535;
}}}});
}function w(K,M){var y=r(K);
var U=[];
var D=[];
var J=null;
var B=null;
function L(W){return M[K[W]];
}for(var H=0;
H<y.length;
++H){var x=y[H];
var F=L(x);
var z=F-x;
if(J==null||z!==B){if(J){D.push(J);
}U.push(x);
B=z;
}J=x;
}if(J){D.push(J);
}D.push(65535);
U.push(65535);
var R=U.length;
var S=R*2;
var Q=2*Math.pow(2,Math.floor(Math.log(R)/Math.LN2));
var E=Math.log(Q/2)/Math.LN2;
var P=S-Q;
var A=[];
var O=[];
var G=[];
for(H=0;
H<R;
++H){var T=U[H];
var C=D[H];
if(T==65535){A.push(0);
O.push(0);
break;
}var V=L(T);
if(T-V>=32768){A.push(0);
O.push(2*(G.length+R-H));
for(var I=T;
I<=C;
++I){G.push(L(I));
}}else{A.push(V-T);
O.push(0);
}}var N=a();
N.writeShort(3);
N.writeShort(1);
N.writeLong(12);
N.writeShort(4);
N.writeShort(16+R*8+G.length*2);
N.writeShort(0);
N.writeShort(S);
N.writeShort(Q);
N.writeShort(E);
N.writeShort(P);
D.forEach(N.writeShort);
N.writeShort(0);
U.forEach(N.writeShort);
A.forEach(N.writeShort_);
O.forEach(N.writeShort);
G.forEach(N.writeShort);
return N.get();
}return c({parse:function(x){var z=this;
var y=z.offset;
x.offset(y);
z.version=x.readShort();
var A=x.readShort();
z.unicodeEntry=null;
z.tables=x.times(A,function(){var B=new v(x,y);
if(B.isUnicode){z.unicodeEntry=B;
}return B;
});
},render:function(x,y){var z=a();
z.writeShort(0);
z.writeShort(1);
z.write(w(x,y));
return z.get();
},getUnicodeEntry:function(){if(!this.unicodeEntry){throw new Error("Font doesn't have an Unicode encoding");
}return this.unicodeEntry;
}});
})();
var o=c({parse:function(v){v.offset(this.offset);
this.version=v.readShort();
this.averageCharWidth=v.readShort_();
this.weightClass=v.readShort();
this.widthClass=v.readShort();
this.type=v.readShort();
this.ySubscriptXSize=v.readShort_();
this.ySubscriptYSize=v.readShort_();
this.ySubscriptXOffset=v.readShort_();
this.ySubscriptYOffset=v.readShort_();
this.ySuperscriptXSize=v.readShort_();
this.ySuperscriptYSize=v.readShort_();
this.ySuperscriptXOffset=v.readShort_();
this.ySuperscriptYOffset=v.readShort_();
this.yStrikeoutSize=v.readShort_();
this.yStrikeoutPosition=v.readShort_();
this.familyClass=v.readShort_();
this.panose=v.times(10,v.readByte);
this.charRange=v.times(4,v.readLong);
this.vendorID=v.readString(4);
this.selection=v.readShort();
this.firstCharIndex=v.readShort();
this.lastCharIndex=v.readShort();
if(this.version>0){this.ascent=v.readShort_();
this.descent=v.readShort_();
this.lineGap=v.readShort_();
this.winAscent=v.readShort();
this.winDescent=v.readShort();
this.codePageRange=v.times(2,v.readLong);
if(this.version>1){this.xHeight=v.readShort();
this.capHeight=v.readShort();
this.defaultChar=v.readShort();
this.breakChar=v.readShort();
this.maxContext=v.readShort();
}}},render:function(){return this.raw();
}});
var t=100000;
function n(){var x="",w=t+"";
for(var v=0;
v<w.length;
++v){x+=String.fromCharCode(w.charCodeAt(v)-48+65);
}++t;
return x;
}function s(v){this.font=v;
this.subset={};
this.unicodes={};
this.ogid2ngid={0:0};
this.ngid2ogid={0:0};
this.ncid2ogid={};
this.next=this.firstChar=1;
this.nextGid=1;
this.psName=n()+"+"+this.font.psName;
}s.prototype={use:function(v){var w;
if(typeof v=="string"){var A="";
for(var x=0;
x<v.length;
++x){w=this.use(v.charCodeAt(x));
A+=String.fromCharCode(w);
}return A;
}w=this.unicodes[v];
if(!w){w=this.next++;
this.subset[w]=v;
this.unicodes[v]=w;
var z=this.font.cmap.getUnicodeEntry().codeMap[v];
if(z){this.ncid2ogid[w]=z;
if(this.ogid2ngid[z]==null){var y=this.nextGid++;
this.ogid2ngid[z]=y;
this.ngid2ogid[y]=z;
}}}return w;
},encodeText:function(v){return this.use(v);
},glyphIds:function(){return r(this.ogid2ngid);
},glyphsFor:function(w,z){if(!z){z={};
}for(var x=0;
x<w.length;
++x){var y=w[x];
if(!z[y]){var v=z[y]=this.font.glyf.glyphFor(y);
if(v&&v.compound){this.glyphsFor(v.glyphIds,z);
}}}return z;
},render:function(){var x=this.glyphsFor(this.glyphIds());
for(var B in x){if(g(x,B)){B=parseInt(B,10);
if(this.ogid2ngid[B]==null){var z=this.nextGid++;
this.ogid2ngid[B]=z;
this.ngid2ogid[z]=B;
}}}var A=r(this.ngid2ogid);
var C=A.map(function(E){return this.ngid2ogid[E];
},this);
var v=this.font;
var w=v.glyf.render(x,C,this.ogid2ngid);
var y=v.loca.render(w.offsets);
this.lastChar=this.next-1;
var D={cmap:b.render(this.ncid2ogid,this.ogid2ngid),glyf:w.table,loca:y.table,hmtx:v.hmtx.render(C),hhea:v.hhea.render(C),maxp:v.maxp.render(C),post:v.post.render(C),name:v.name.render(this.psName),head:v.head.render(y.format),"OS/2":v.os2.render()};
return this.font.directory.render(D);
},cidToGidMap:function(){var z=a(),w=0;
for(var v=this.firstChar;
v<this.next;
++v){while(w<v){z.writeShort(0);
w++;
}var y=this.ncid2ogid[v];
if(y){var x=this.ogid2ngid[y];
z.writeShort(x);
}else{z.writeShort(0);
}w++;
}return z.get();
}};
function u(A,x){var B=this;
var v=B.contents=a(A);
if(v.readString(4)=="ttcf"){if(!x){throw new Error("Must specify a name for TTC files");
}var C=v.readLong();
var y=v.readLong();
for(var w=0;
w<y;
++w){var z=v.readLong();
v.saveExcursion(function(){v.offset(z);
B.parse();
});
if(B.psName==x){return;
}}throw new Error("Font "+x+" not found in collection");
}else{v.offset(0);
B.parse();
}}u.prototype={parse:function(){var v=this.directory=new d(this.contents);
this.head=v.readTable("head",h);
this.loca=v.readTable("loca",k);
this.hhea=v.readTable("hhea",i);
this.maxp=v.readTable("maxp",l);
this.hmtx=v.readTable("hmtx",j);
this.glyf=v.readTable("glyf",f);
this.name=v.readTable("name",m);
this.post=v.readTable("post",q);
this.cmap=v.readTable("cmap",b);
this.os2=v.readTable("OS/2",o);
this.psName=this.name.postscriptName;
this.ascent=this.os2.ascent||this.hhea.ascent;
this.descent=this.os2.descent||this.hhea.descent;
this.lineGap=this.os2.lineGap||this.hhea.lineGap;
this.scale=1000/this.head.unitsPerEm;
},widthOfGlyph:function(v){return this.hmtx.forGlyph(v).advance*this.scale;
},makeSubset:function(){return new s(this);
}};
p.TTFFont=u;
})(this);
(function(q,a){var k=q.drawing;
var p=q.geometry;
var c=k.Color;
var E=q.pdf.TEXT_RENDERING_MODE;
var d={dash:[4],dashDot:[4,2,1,2],dot:[1,2],longDash:[8,2],longDashDot:[8,2,1,2],longDashDotDot:[8,2,1,2,1,2],solid:[]};
var r={butt:0,round:1,square:2};
var s={miter:0,round:1,bevel:2};
function y(M,H){var K=[],N=[],P=M.options;
function L(S,Q,R){if(!R){R=P;
}if(R.pdf&&R.pdf[S]!=null){return R.pdf[S];
}return Q;
}var O=L("multiPage");
M.traverse(function(Q){e({Image:function(R){if(N.indexOf(R.src())<0){N.push(R.src());
}},Text:function(R){var S=q.pdf.parseFontDef(R.options.font);
var T=q.pdf.getFontURL(S);
if(K.indexOf(T)<0){K.push(T);
}}},Q);
});
function J(){if(--I>0){return;
}var R=new (q.pdf.Document)({producer:L("producer"),title:L("title"),author:L("author"),subject:L("subject"),keywords:L("keywords"),creator:L("creator"),date:L("date")});
function Q(U){var V=U.options;
var aa=w(U);
var T=aa.bbox;
U=aa.root;
var Y=L("paperSize",L("paperSize","auto"),V),S=false;
if(Y=="auto"){if(T){var Z=T.getSize();
Y=[Z.width,Z.height];
S=true;
var W=T.getOrigin();
aa=new k.Group();
aa.transform(new p.Matrix(1,0,0,1,-W.x,-W.y));
aa.append(U);
U=aa;
}else{Y="A4";
}}var X;
X=R.addPage({paperSize:Y,margin:L("margin",L("margin"),V),addMargin:S,landscape:L("landscape",L("landscape",false),V)});
h(U,X,R);
}if(O){M.children.forEach(Q);
}else{Q(M);
}H(R.render(),R);
}var I=2;
q.pdf.loadFonts(K,J);
q.pdf.loadImages(N,J);
}function G(I,H){y(I,function(J){H("data:application/pdf;base64,"+J.base64());
});
}function F(I,H){y(I,function(J){H(new Blob([J.get()],{type:"application/pdf"}));
});
}function z(J,I,K,H){if(window.Blob&&!q.support.browser.safari){F(J,function(L){q.saveAs({dataURI:L,fileName:I});
if(H){H(L);
}});
}else{G(J,function(L){q.saveAs({dataURI:L,fileName:I,proxyURL:K});
if(H){H(L);
}});
}}function e(J,H){var I=J[H.nodeType];
if(I){return I.call.apply(I,arguments);
}return H;
}function h(H,K,L){if(H.DEBUG){K.comment(H.DEBUG);
}var M=H.transform();
var J=H.opacity();
K.save();
if(J!=null&&J<1){K.setOpacity(J);
}C(H,K,L);
B(H,K,L);
A(H,K,L);
if(M){var I=M.matrix();
K.transform(I.a,I.b,I.c,I.d,I.e,I.f);
}e({Path:m,MultiPath:l,Circle:g,Arc:f,Text:n,Image:j,Group:i},H,K,L);
K.restore();
}function C(J,N,O){var P=J.stroke&&J.stroke();
if(!P){return;
}var H=P.color;
if(H){H=x(H);
if(H==null){return;
}N.setStrokeColor(H.r,H.g,H.b);
if(H.a!=1){N.setStrokeOpacity(H.a);
}}var Q=P.width;
if(Q!=null){if(Q===0){return;
}N.setLineWidth(Q);
}var I=P.dashType;
if(I){N.setDashPattern(d[I],0);
}var K=P.lineCap;
if(K){N.setLineCap(r[K]);
}var L=P.lineJoin;
if(L){N.setLineJoin(s[L]);
}var M=P.opacity;
if(M!=null){N.setStrokeOpacity(M);
}}function B(I,L,M){var J=I.fill&&I.fill();
if(!J){return;
}if(J instanceof k.Gradient){return;
}var H=J.color;
if(H){H=x(H);
if(H==null){return;
}L.setFillColor(H.r,H.g,H.b);
if(H.a!=1){L.setFillOpacity(H.a);
}}var K=J.opacity;
if(K!=null){L.setFillOpacity(K);
}}function A(I,J,K){var H=I.clip();
if(H){b(H,J,K);
J.clip();
}}function D(H){return(H&&(H instanceof k.Gradient||(H.color&&!/^(none|transparent)$/i.test(H.color)&&(H.width==null||H.width>0)&&(H.opacity==null||H.opacity>0))));
}function v(I,N,O,R){var K=I.fill();
if(K instanceof k.Gradient){if(R){N.clipStroke();
}else{N.clip();
}var M=K instanceof k.RadialGradient;
var Q,J;
if(M){Q={x:K.center().x,y:K.center().y,r:0};
J={x:K.center().x,y:K.center().y,r:K.radius()};
}else{Q={x:K.start().x,y:K.start().y};
J={x:K.end().x,y:K.end().y};
}var L={type:M?"radial":"linear",start:Q,end:J,userSpace:K.userSpace(),stops:K.stops.elements().map(function(V){var U=V.offset();
if(/%$/.test(U)){U=parseFloat(U)/100;
}else{U=parseFloat(U);
}var T=x(V.color());
T.a*=V.opacity();
return{offset:U,color:T};
})};
var H=I.rawBBox();
var S=H.topLeft(),P=H.getSize();
H={left:S.x,top:S.y,width:P.width,height:P.height};
N.gradient(L,H);
return true;
}}function u(H,I,J){if(D(H.fill())&&D(H.stroke())){if(!v(H,I,J,true)){I.fillStroke();
}}else{if(D(H.fill())){if(!v(H,I,J,false)){I.fill();
}}else{if(D(H.stroke())){I.stroke();
}else{I.nop();
}}}}function t(L,K,M){var N=L.segments;
if(N.length==4&&L.options.closed){var H=[];
for(var I=0;
I<N.length;
++I){if(N[I].controlIn()){return false;
}H[I]=N[I].anchor();
}var J=(H[0].y==H[1].y&&H[1].x==H[2].x&&H[2].y==H[3].y&&H[3].x==H[0].x)||(H[0].x==H[1].x&&H[1].y==H[2].y&&H[2].x==H[3].x&&H[3].y==H[0].y);
if(J){K.rect(H[0].x,H[0].y,H[2].x-H[0].x,H[2].y-H[0].y);
return true;
}}}function b(J,L,M){var Q=J.segments;
if(Q.length===0){return;
}if(!t(J,L,M)){for(var N,K=0;
K<Q.length;
++K){var P=Q[K];
var H=P.anchor();
if(!N){L.moveTo(H.x,H.y);
}else{var O=N.controlOut();
var I=P.controlIn();
if(O&&I){L.bezier(O.x,O.y,I.x,I.y,H.x,H.y);
}else{L.lineTo(H.x,H.y);
}}N=P;
}if(J.options.closed){L.close();
}}}function m(H,I,J){b(H,I,J);
u(H,I,J);
}function l(H,J,L){var K=H.paths;
for(var I=0;
I<K.length;
++I){b(K[I],J,L);
}u(H,J,L);
}function g(H,J,K){var I=H.geometry();
J.circle(I.center.x,I.center.y,I.radius);
u(H,J,K);
}function f(H,J,K){var L=H.geometry().curvePoints();
J.moveTo(L[0].x,L[0].y);
for(var I=1;
I<L.length;
){J.bezier(L[I].x,L[I++].y,L[I].x,L[I++].y,L[I].x,L[I++].y);
}u(H,J,K);
}function n(H,J,K){var M=q.pdf.parseFontDef(H.options.font);
var L=H._position;
var I;
if(H.fill()&&H.stroke()){I=E.fillAndStroke;
}else{if(H.fill()){I=E.fill;
}else{if(H.stroke()){I=E.stroke;
}}}J.transform(1,0,0,-1,L.x,L.y+M.fontSize);
J.beginText();
J.setFont(q.pdf.getFontURL(M),M.fontSize);
J.setTextRenderingMode(I);
J.showText(H.content(),H._pdfRect?H._pdfRect.width():null);
J.endText();
}function i(I,K,L){if(I._pdfLink){K.addLink(I._pdfLink.url,I._pdfLink);
}var H=I.children;
for(var J=0;
J<H.length;
++J){h(H[J],K,L);
}}function j(H,I,J){var N=H.src();
var K=H.rect();
var M=K.getOrigin();
var L=K.getSize();
I.transform(L.width,0,0,-L.height,M.x,M.y+L.height);
I.drawImage(N);
}function o(I,K){var H=a.Deferred();
for(var J in K){I.options.set("pdf."+J,K[J]);
}k.pdf.toDataURL(I,H.resolve);
return H.promise();
}function x(I){var H=q.parseColor(I,true);
return H?H.toRGB():null;
}function w(P){var J=false;
var M=p.Matrix.unit();
var K=null;
var I;
do{I=false;
P=N(P);
}while(P&&I);
return{root:P,bbox:K};
function H(S){I=true;
return S;
}function Q(S){return(S.visible()&&S.opacity()>0&&(D(S.fill())||D(S.stroke())));
}function O(S){var T=[];
for(var V=0;
V<S.length;
++V){var U=N(S[V]);
if(U!=null){T.push(U);
}}return T;
}function R(W,T){var U=J;
var V=M;
if(W.transform()){M=M.multiplyCopy(W.transform().matrix());
}var S=W.clip();
if(S){S=S.bbox();
if(S){S=S.bbox(M);
J=J?p.Rect.intersect(J,S):S;
}}try{return T();
}finally{J=U;
M=V;
}}function L(T){if(J==null){return false;
}var S=T.rawBBox().bbox(M);
if(J&&S){S=p.Rect.intersect(S,J);
}return S;
}function N(S){return R(S,function(){if(!(S instanceof k.Group||S instanceof k.MultiPath)){var T=L(S);
if(!T){return H(null);
}K=K?p.Rect.union(K,T):T;
}return e({Path:function(U){if(U.segments.length===0||!Q(U)){return H(null);
}return U;
},MultiPath:function(V){if(!Q(V)){return H(null);
}var U=new k.MultiPath(V.options);
U.paths=O(V.paths);
if(U.paths.length===0){return H(null);
}return U;
},Circle:function(U){if(!Q(U)){return H(null);
}return U;
},Arc:function(U){if(!Q(U)){return H(null);
}return U;
},Text:function(U){if(!/\S/.test(U.content())||!Q(U)){return H(null);
}return U;
},Image:function(U){if(!(U.visible()&&U.opacity()>0)){return H(null);
}return U;
},Group:function(V){var U=new k.Group(V.options);
U.children=O(V.children);
U._pdfLink=V._pdfLink;
if(V!==P&&U.children.length===0&&!V._pdfLink){return H(null);
}return U;
}},S);
});
}}q.deepExtend(k,{exportPDF:o,pdf:{toDataURL:G,toBlob:F,saveAs:z,toStream:y}});
})(window.kendo,window.kendo.jQuery);
(function(b,a){b.PDFMixin={extend:function(c){c.events.push("pdfExport");
c.options.pdf=this.options;
c.saveAsPDF=this.saveAsPDF;
c._drawPDF=this._drawPDF;
c._drawPDFShadow=this._drawPDFShadow;
},options:{fileName:"Export.pdf",proxyURL:"",paperSize:"auto",allPages:false,landscape:false,margin:null,title:null,author:null,subject:null,keywords:null,creator:"Kendo UI PDF Generator",date:null},saveAsPDF:function(){var e=new a.Deferred();
var f=e.promise();
var c={promise:f};
if(this.trigger("pdfExport",c)){return;
}var d=this.options.pdf;
d.multiPage=d.allPages;
this._drawPDF(e).then(function(g){return b.drawing.exportPDF(g,d);
}).done(function(g){b.saveAs({dataURI:g,fileName:d.fileName,proxyURL:d.proxyURL,forceProxy:d.forceProxy});
e.resolve();
}).fail(function(g){e.reject(g);
});
return f;
},_drawPDF:function(){return b.drawing.drawDOM(this.wrapper);
},_drawPDFShadow:function(c){var f=this.wrapper;
var e=a("<div class='k-pdf-export-shadow'>").css("width",f.width());
f.before(e);
e.append(c||f.clone());
var d=b.drawing.drawDOM(e);
d.done(function(){e.remove();
});
return d;
}};
})(kendo,window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
