(function(b,a){a(["./kendo.core"],b);
})(function(){(function(a,K){var u=window.kendo,J=u.ui,M=J.Widget,G=u.support,s=u.getOffset,h=u._activeElement,z="open",l="close",o="deactivate",c="activate",k="center",v="left",D="right",H="top",j="bottom",b="absolute",t="hidden",i="body",w="location",B="position",L="visible",q="effects",d="k-state-active",e="k-state-border",f=/k-state-border-(\w+)/,g=".k-picker-wrap, .k-dropdown-wrap, .k-link",x="down",p=a(document.documentElement),N=a(window),E="scroll",C="resize scroll",n=G.transitions.css,I=n+"transform",r=a.extend,y=".kendoPopup",F=["font-size","font-family","font-stretch","font-style","font-weight","line-height"];
function m(O,P){return O===P||a.contains(O,P);
}var A=M.extend({init:function(O,P){var R=this,Q;
P=P||{};
if(P.isRtl){P.origin=P.origin||j+" "+D;
P.position=P.position||H+" "+D;
}M.fn.init.call(R,O,P);
O=R.element;
P=R.options;
R.collisions=P.collision?P.collision.split(" "):[];
R.downEvent=u.applyEventMap(x,u.guid());
if(R.collisions.length===1){R.collisions.push(R.collisions[0]);
}Q=a(R.options.anchor).closest(".k-popup,.k-group").filter(":not([class^=km-])");
P.appendTo=a(a(P.appendTo)[0]||Q[0]||i);
R.element.hide().addClass("k-popup k-group k-reset").toggleClass("k-rtl",!!P.isRtl).css({position:b}).appendTo(P.appendTo).on("mouseenter"+y,function(){R._hovered=true;
}).on("mouseleave"+y,function(){R._hovered=false;
});
R.wrapper=a();
if(P.animation===false){P.animation={open:{effects:{}},close:{hide:true,effects:{}}};
}r(P.animation.open,{complete:function(){R.wrapper.css({overflow:L});
R._activated=true;
R._trigger(c);
}});
r(P.animation.close,{complete:function(){R._animationClose();
}});
R._mousedownProxy=function(S){R._mousedown(S);
};
R._resizeProxy=function(S){R._resize(S);
};
if(P.toggleTarget){a(P.toggleTarget).on(P.toggleEvent+y,a.proxy(R.toggle,R));
}},events:[z,c,l,o],options:{name:"Popup",toggleEvent:"click",origin:j+" "+v,position:H+" "+v,anchor:i,appendTo:null,collision:"flip fit",viewport:window,copyAnchorStyles:true,autosize:false,modal:false,adjustSize:{width:0,height:0},animation:{open:{effects:"slideIn:down",transition:true,duration:200},close:{duration:100,hide:true}}},_animationClose:function(){var T=this,S=T.options;
T.wrapper.hide();
var R=T.wrapper.data(w),O=a(S.anchor),Q,P;
if(R){T.wrapper.css(R);
}if(S.anchor!=i){Q=((O.attr("class")||"").match(f)||["","down"])[1];
P=e+"-"+Q;
O.removeClass(P).children(g).removeClass(d).removeClass(P);
T.element.removeClass(e+"-"+u.directions[Q].reverse);
}T._closing=false;
T._trigger(o);
},destroy:function(){var R=this,P=R.options,O=R.element.off(y),Q;
M.fn.destroy.call(R);
if(P.toggleTarget){a(P.toggleTarget).off(y);
}if(!P.modal){p.unbind(R.downEvent,R._mousedownProxy);
R._scrollableParents().unbind(E,R._resizeProxy);
N.unbind(C,R._resizeProxy);
}u.destroy(R.element.children());
O.removeData();
if(P.appendTo[0]===document.body){Q=O.parent(".k-animation-container");
if(Q[0]){Q.remove();
}else{O.remove();
}}},open:function(Y,Z){var W=this,T={isFixed:!isNaN(parseInt(Z,10)),x:Y,y:Z},S=W.element,V=W.options,R="down",P,X,O=a(V.anchor),U=S[0]&&S.hasClass("km-widget");
if(!W.visible()){if(V.copyAnchorStyles){if(U&&F[0]=="font-size"){F.shift();
}S.css(u.getComputedStyles(O[0],F));
}if(S.data("animating")||W._trigger(z)){return;
}W._activated=false;
if(!V.modal){p.unbind(W.downEvent,W._mousedownProxy).bind(W.downEvent,W._mousedownProxy);
if(!(G.mobileOS.ios||G.mobileOS.android)){W._scrollableParents().unbind(E,W._resizeProxy).bind(E,W._resizeProxy);
N.unbind(C,W._resizeProxy).bind(C,W._resizeProxy);
}}W.wrapper=X=u.wrap(S,V.autosize).css({overflow:t,display:"block",position:b});
if(G.mobileOS.android){X.css(I,"translatez(0)");
}X.css(B);
if(a(V.appendTo)[0]==document.body){X.css(H,"-10000px");
}P=r(true,{},V.animation.open);
W.flipped=W._position(T);
P.effects=u.parseEffects(P.effects,W.flipped);
R=P.effects.slideIn?P.effects.slideIn.direction:R;
if(V.anchor!=i){var Q=e+"-"+R;
S.addClass(e+"-"+u.directions[R].reverse);
O.addClass(Q).children(g).addClass(d).addClass(Q);
}S.data(q,P.effects).kendoStop(true).kendoAnimate(P);
}},toggle:function(){var O=this;
O[O.visible()?l:z]();
},visible:function(){return this.element.is(":"+L);
},close:function(S){var T=this,R=T.options,U,O,Q,P;
if(T.visible()){U=(T.wrapper[0]?T.wrapper:u.wrap(T.element).hide());
if(T._closing||T._trigger(l)){return;
}T.element.find(".k-popup").each(function(){var W=a(this),V=W.data("kendoPopup");
if(V){V.close(S);
}});
p.unbind(T.downEvent,T._mousedownProxy);
T._scrollableParents().unbind(E,T._resizeProxy);
N.unbind(C,T._resizeProxy);
if(S){O={hide:true,effects:{}};
}else{O=r(true,{},R.animation.close);
Q=T.element.data(q);
P=O.effects;
if(!P&&!u.size(P)&&Q&&u.size(Q)){O.effects=Q;
O.reverse=true;
}T._closing=true;
}T.element.kendoStop(true);
U.css({overflow:t});
T.element.kendoAnimate(O);
}},_trigger:function(O){return this.trigger(O,{type:O});
},_resize:function(O){var P=this;
if(O.type==="resize"){clearTimeout(P._resizeTimeout);
P._resizeTimeout=setTimeout(function(){P._position();
P._resizeTimeout=null;
},50);
}else{if(!P._hovered||(P._activated&&P.element.hasClass("k-list-container"))){P.close();
}}},_mousedown:function(Q){var V=this,P=V.element[0],S=V.options,O=a(S.anchor)[0],W=S.toggleTarget,U=u.eventTarget(Q),T=a(U).closest(".k-popup"),R=T.parent().parent(".km-shim").length;
T=T[0];
if(!R&&T&&T!==V.element[0]){return;
}if(a(Q.target).closest("a").data("rel")==="popover"){return;
}if(!m(P,U)&&!m(O,U)&&!(W&&m(a(W)[0],U))){V.close();
}},_fit:function(P,Q,R){var O=0;
if(P+Q>R){O=R-(P+Q);
}if(P<0){O=-P;
}return O;
},_flip:function(Q,U,O,V,R,T,P){var S=0;
P=P||U;
if(T!==R&&T!==k&&R!==k){if(Q+P>V){S+=-(O+U);
}if(Q+S<0){S+=O+U;
}}return S;
},_scrollableParents:function(){return a(this.options.anchor).parentsUntil("body").filter(function(Q,P){var O=u.getComputedStyles(P,["overflow"]);
return O.overflow!="visible";
});
},_position:function(T){var ai=this,S=ai.element.css(B,""),an=ai.wrapper,ab=ai.options,aj=a(ab.viewport),al=aj.offset(),P=a(ab.anchor),ac=ab.origin.toLowerCase().split(" "),ag=ab.position.toLowerCase().split(" "),R=ai.collisions,ap=G.zoomLevel(),ah,ad,ae,ao=10002,W=!!((aj[0]==window)&&window.innerWidth&&(ap<=1.02)),V=0,X,am,ak;
am=W?window.innerWidth:aj.width();
ak=W?window.innerHeight:aj.height();
ah=P.parents().filter(an.siblings());
if(ah[0]){ae=Math.max(Number(ah.css("zIndex")),0);
if(ae){ao=ae+10;
}else{ad=P.parentsUntil(ah);
for(X=ad.length;
V<X;
V++){ae=Number(a(ad[V]).css("zIndex"));
if(ae&&ao<ae){ao=ae+10;
}}}}an.css("zIndex",ao);
if(T&&T.isFixed){an.css({left:T.x,top:T.y});
}else{an.css(ai._align(ac,ag));
}var af=s(an,B,P[0]===an.offsetParent()[0]),Z=s(an),Q=P.offsetParent().parent(".k-animation-container,.k-popup,.k-group");
if(Q.length){af=s(an,B,true);
Z=s(an);
}if(aj[0]===window){Z.top-=(window.pageYOffset||document.documentElement.scrollTop||0);
Z.left-=(window.pageXOffset||document.documentElement.scrollLeft||0);
}else{Z.top-=al.top;
Z.left-=al.left;
}if(!ai.wrapper.data(w)){an.data(w,r({},af));
}var aa=r({},Z),Y=r({},af),O=ab.adjustSize;
if(R[0]==="fit"){Y.top+=ai._fit(aa.top,an.outerHeight()+O.height,ak/ap);
}if(R[1]==="fit"){Y.left+=ai._fit(aa.left,an.outerWidth()+O.width,am/ap);
}var U=r({},Y);
if(R[0]==="flip"){Y.top+=ai._flip(aa.top,S.outerHeight(),P.outerHeight(),ak/ap,ac[0],ag[0],an.outerHeight());
}if(R[1]==="flip"){Y.left+=ai._flip(aa.left,S.outerWidth(),P.outerWidth(),am/ap,ac[1],ag[1],an.outerWidth());
}S.css(B,b);
an.css(Y);
return(Y.left!=U.left||Y.top!=U.top);
},_align:function(Z,aa){var ac=this,U=ac.wrapper,O=a(ac.options.anchor),ae=Z[0],W=Z[1],af=aa[0],X=aa[1],Q=s(O),S=a(ac.options.appendTo),T,ag=U.outerWidth(),V=U.outerHeight(),R=O.outerWidth(),P=O.outerHeight(),ad=Q.top,Y=Q.left,ab=Math.round;
if(S[0]!=document.body){T=s(S);
ad-=T.top;
Y-=T.left;
}if(ae===j){ad+=P;
}if(ae===k){ad+=ab(P/2);
}if(af===j){ad-=V;
}if(af===k){ad-=ab(V/2);
}if(W===D){Y+=R;
}if(W===k){Y+=ab(R/2);
}if(X===D){Y-=ag;
}if(X===k){Y-=ab(ag/2);
}return{top:ad,left:Y};
}});
J.plugin(A);
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
