(function(b,a){a(["./kendo.core"],b);
})(function(){(function(a,Z){var v=window.kendo,i=v.Class,aa=v.ui.Widget,M=a.proxy,u=v.isFunction,Y="k-toolbar",e="k-button",D="k-overflow-button",V="k-toggle-button",f="k-button-group",P="k-split-button",O="k-separator",J="k-popup",N="k-toolbar-resizable",R="k-state-active",S="k-state-disabled",r="k-group-start",q="k-group-end",L="k-primary",s="k-icon",t="k-i-",g="k-button-icon",h="k-button-icontext",y="k-list-container k-split-container",Q="k-split-button-arrow",B="k-overflow-anchor",F="k-overflow-container",p="k-toolbar-first-visible",x="k-toolbar-last-visible",j="click",U="toggle",z="open",k="close",I="overflowOpen",E="overflowClose",H="never",C="auto",A="always",G="k-overflow-hidden",w=v.attr("uid"),T=v.template,l={button:{base:m,toolbar:o,overflow:n},buttonGroup:{base:function(ag,ad,ab){var af=ag.buttons,ae;
if(!af){return;
}if(ag.attributes){ab.attr(ag.attributes);
}ab.data({type:"buttonGroup"});
ab.attr(w,ag.uid);
for(var ac=0;
ac<af.length;
ac++){if(!af[ac].uid){af[ac].uid=v.guid();
}ae=ad(a.extend({mobile:ag.mobile},af[ac]));
ae.appendTo(ab);
}ab.children().first().addClass(r);
ab.children().last().addClass(q);
},toolbar:function(ac){var ab=a("<div></div>");
l.buttonGroup.base(ac,l.button.toolbar,ab);
ab.addClass(f);
if(ac.align){ab.addClass("k-align-"+ac.align);
}if(ac.id){ab.attr("id",ac.id);
}return ab;
},overflow:function(ac){var ab=a("<li></li>");
l.buttonGroup.base(ac,l.button.overflow,ab);
ab.addClass((ac.mobile?"":f)+" k-overflow-group");
if(ac.id){ab.attr("id",ac.id+"_overflow");
}return ab;
}},splitButton:{toolbar:function(ah){var ac=a('<div class="'+P+'"></div>'),ag=l.button.toolbar(ah),ab=a('<a class="'+e+" "+Q+'"><span class="'+(ah.mobile?"km-icon km-arrowdown":"k-icon k-i-arrow-s")+'"></span></a>'),aj=a('<ul class="'+y+'"></ul>'),ai,af=ah.menuButtons,ae;
ag.appendTo(ac);
ab.appendTo(ac);
aj.appendTo(ac);
for(var ad=0;
ad<af.length;
ad++){ae=l.button.toolbar(a.extend({mobile:ah.mobile,click:ah.click},af[ad]));
ae.wrap("<li></li>").parent().appendTo(aj);
}if(ah.align){ac.addClass("k-align-"+ah.align);
}if(!ah.id){ah.id=ah.uid;
}ac.attr("id",ah.id+"_wrapper");
aj.attr("id",ah.id+"_optionlist").attr(w,ah.rootUid);
if(ah.mobile){aj=b(aj);
}ai=aj.kendoPopup({appendTo:ah.mobile?a(ah.mobile).children(".km-pane"):null,anchor:ac,copyAnchorStyles:false,animation:ah.animation,open:d}).data("kendoPopup");
ac.data({type:"splitButton",kendoPopup:ai});
ac.attr(w,ah.uid);
return ac;
},overflow:function(ag){var ab=a('<li class="'+P+'"></li>'),af=l.button.overflow(ag),ae=ag.menuButtons,ad;
af.appendTo(ab);
for(var ac=0;
ac<ae.length;
ac++){ad=l.button.overflow(a.extend({mobile:ag.mobile},ae[ac]));
ad.appendTo(ab);
}ab.data({type:"splitButton"});
ab.attr(w,ag.uid);
return ab;
}},separator:{base:function(ac,ad){var ab=ad?a("<li>&nbsp;</li>"):a("<div>&nbsp;</div>");
ab.data({type:"separator"});
ab.attr(w,ac.uid);
if(ac.attributes){ab.attr(ac.attributes);
}ab.addClass(O);
return ab;
},toolbar:function(ac){var ab=l.separator.base(ac,false);
if(ac.id){ab.attr("id",ac.id);
}return ab;
},overflow:function(ac){var ab=l.separator.base(ac,true);
if(ac.id){ab.attr("id",ac.id+"_overflow");
}return ab;
}},overflowAnchor:'<div class="k-overflow-anchor"></div>',overflowContainer:'<ul class="k-overflow-container k-list-container"></ul>'};
function m(ac){var ab=ac.useButtonTag?a("<button></button>"):a("<a></a>");
ab.data({type:"button"});
ab.attr(w,ac.uid);
if(ac.attributes){ab.attr(ac.attributes);
}if(ac.togglable){ab.addClass(V);
if(ac.selected){ab.addClass(R);
}}if(ac.enable===false){ab.addClass(S);
}if(ac.url!==Z&&!ac.useButtonTag){ab.attr("href",ac.url);
if(ac.mobile){ab.attr(v.attr("role"),"button");
}}if(ac.group){ab.attr(v.attr("group"),ac.group);
}if(!ac.togglable&&ac.click&&u(ac.click)){ab.data("click",ac.click);
}if(ac.togglable&&ac.toggle&&u(ac.toggle)){ab.data("toggle",ac.toggle);
}return ab;
}function o(ad){var ab=l.button.base(ad),ac;
ab.addClass(e);
if(ad.primary){ab.addClass(L);
}if(ad.align){ab.addClass("k-align-"+ad.align);
}if(ad.id){ab.attr("id",ad.id);
}if(ad.showText!="overflow"&&ad.text){if(ad.mobile){ab.html('<span class="km-text">'+ad.text+"</span>");
}else{ab.html(ad.text);
}}ac=(ad.showIcon!="overflow")&&(ad.icon||ad.spriteCssClass||ad.imageUrl);
if(ac){c(ad,ab);
}return ab;
}function n(ad){var ab=l.button.base(ad),ac;
ab.addClass(D+" "+e);
if(ad.primary){ab.addClass(L);
}if(ad.id){ab.attr("id",ad.id+"_overflow");
}if(ad.showText!="toolbar"&&ad.text){if(ad.mobile){ab.html('<span class="km-text">'+ad.text+"</span>");
}else{ab.html(ad.text);
}}ac=(ad.showIcon!="toolbar")&&(ad.icon||ad.spriteCssClass||ad.imageUrl);
if(ac){c(ad,ab);
}return ab;
}function c(ag,ab){var ac=ag.icon,ai=ag.spriteCssClass,ad=ag.imageUrl,af,ah,ae;
if(ai||ad||ac){af=true;
ab.contents().not("span.k-sprite,span."+s+",img.k-image").each(function(ak,aj){if(aj.nodeType==1||aj.nodeType==3&&a.trim(aj.nodeValue).length>0){af=false;
}});
if(af){ab.addClass(g);
}else{ab.addClass(h);
}}if(ac){ah=ab.children("span."+s).first();
if(!ah[0]){ah=a('<span class="'+s+'"></span>').prependTo(ab);
}ah.addClass(t+ac);
}else{if(ai){ah=ab.children("span.k-sprite").first();
if(!ah[0]){ah=a('<span class="k-sprite"></span>').prependTo(ab);
}ah.addClass(ai);
}else{if(ad){ae=ab.children("img.k-image").first();
if(!ae[0]){ae=a('<img alt="icon" class="k-image" />').prependTo(ab);
}ae.attr("src",ad);
}}}}function d(ad){var ab=this.options.anchor,ac=ab.outerWidth(),ae;
v.wrap(this.element).addClass("k-split-wrapper");
if(this.element.css("box-sizing")!=="border-box"){ae=ac-(this.element.outerWidth()-this.element.width());
}else{ae=ac;
}this.element.css({fontFamily:ab.css("font-family"),"min-width":ae});
}function W(ab){if(!ab.target.is(".k-toggle-button")){ab.target.toggleClass(R,ab.type=="press");
}}function b(ab){ab=a(ab);
return ab.hasClass("km-actionsheet")?ab.closest(".km-popup-wrapper"):ab.addClass("km-widget km-actionsheet").wrap('<div class="km-actionsheet-wrapper km-actionsheet-tablet km-widget km-popup"></div>').parent().wrap('<div class="km-popup-wrapper k-popup"></div>').parent();
}function K(ab){ab.preventDefault();
}var X=aa.extend({init:function(ab,ad){var ae=this;
aa.fn.init.call(ae,ab,ad);
ad=ae.options;
ab=ae.wrapper=ae.element;
ab.addClass(Y+" k-widget");
this.uid=v.guid();
ab.attr(w,this.uid);
ae.isMobile=(typeof ad.mobile==="boolean")?ad.mobile:ae.element.closest(".km-root")[0];
ae.animation=ae.isMobile?{open:{effects:"fade"}}:{};
if(ae.isMobile){ab.addClass("km-widget");
s="km-icon";
t="km-";
e="km-button";
f="km-buttongroup km-widget";
R="km-state-active";
S="km-state-disabled";
}if(ad.resizable){ae._renderOverflow();
ab.addClass(N);
ae.overflowUserEvents=new v.UserEvents(ae.element,{threshold:5,allowSelection:true,filter:"."+B,tap:M(ae._toggleOverflow,ae)});
v.onResize(function(){ae.resize();
});
}else{ae.popup={element:a([])};
}if(ad.items&&ad.items.length){for(var ac=0;
ac<ad.items.length;
ac++){ae.add(ad.items[ac]);
}}ae.userEvents=new v.UserEvents(document,{threshold:5,allowSelection:true,filter:"["+w+"="+this.uid+"] ."+e+", ["+w+"="+this.uid+"] ."+D,tap:M(ae._buttonClick,ae),press:W,release:W});
ae.element.on(j,"."+S,K);
if(ad.resizable){ae.popup.element.on(j,+"."+S,K);
}if(ad.resizable){this._toggleOverflowAnchor();
}v.notify(ae);
},events:[j,U,z,k,I,E],options:{name:"ToolBar",items:[],resizable:true,mobile:null},destroy:function(){var ab=this;
ab.element.find("."+P).each(function(ad,ac){a(ac).data("kendoPopup").destroy();
});
ab.userEvents.destroy();
if(ab.options.resizable){ab.overflowUserEvents.destroy();
ab.popup.destroy();
}aa.fn.destroy.call(ab);
},add:function(ae){var ab=l[ae.type],ah=ae.template,ac,ai=this,ad=ai.isMobile?"":"k-item k-state-default",ag=ae.overflowTemplate,af;
a.extend(ae,{uid:v.guid(),animation:ai.animation,mobile:ai.isMobile,rootUid:ai.uid});
if(ah&&!ag){ae.overflow=H;
}if(ae.overflow!==H&&ai.options.resizable){if(ag){af=u(ag)?a(ag(ae)):a(ag);
if(ae.id){af.attr("id",ae.id+"_overflow");
}}else{if(ab){af=(ab.overflow||a.noop)(ae);
}}if(af&&af.length){if(af.prop("tagName")!=="LI"){af.removeAttr(w);
af=af.wrap("<li></li>").parent();
af.attr(w,ae.uid);
}ai._attributes(af,ae);
af.addClass(ad).appendTo(ai.popup.container);
if(af.data("overflow")===C){af.addClass(G);
}ai.angular("compile",function(){return{elements:af.get()};
});
}}if(ae.overflow!==A){if(ah){ac=u(ah)?ah(ae):ah;
if(!(ac instanceof jQuery)){ac=a(ac.replace(/^\s+|\s+$/g,""));
}ac=ac.wrap("<div></div>").parent();
if(ae.id){ac.attr("id",ae.id);
}if(ae.attributes){ac.attr(ae.attributes);
}ac.attr(w,ae.uid);
}else{if(ab){ac=(ab.toolbar||a.noop)(ae);
}}if(ac&&ac.length){ai._attributes(ac,ae);
if(ai.options.resizable){ac.appendTo(ai.element).css("visibility","hidden");
ai._shrink(ai.element.innerWidth());
ac.css("visibility","visible");
}else{ac.appendTo(ai.element);
}ai.angular("compile",function(){return{elements:ac.get()};
});
}}},remove:function(ab){var ae,ad,ac=this.options.resizable,af,ag;
ae=this.element.find(ab);
if(ac){ad=this.popup.element.find(ab);
}if(ae.length){af=ae.data("type");
ag=ae.attr(w);
if(ae.parent("."+P).data("type")==="splitButton"){af="splitButton";
ae=ae.parent();
}ad=ac?this.popup.element.find("li["+w+"='"+ag+"']"):a([]);
}else{if(ad.length){af=ad.data("type");
ad=ad.parent();
if(ad.data("type")==="splitButton"){af="splitButton";
}ag=ad.attr(w);
ae=this.element.find("div."+P+"["+w+"='"+ag+"']");
}}if(af==="splitButton"&&ae.data("kendoPopup")){ae.data("kendoPopup").destroy();
}ae.remove();
ad.remove();
},enable:function(ab,ac){var ad=this.element.find(ab).attr(w);
if(!ad&&this.popup){ad=this.popup.element.find(ab).parent("li").attr(w);
}if(typeof ac=="undefined"){ac=true;
}if(ac){a("["+w+"='"+ad+"']").removeClass(S);
}else{a("["+w+"='"+ad+"']").addClass(S);
}},getSelectedFromGroup:function(ab){return this.element.find("."+V+"[data-group='"+ab+"']").filter("."+R);
},toggle:function(ab,ac){var ad=a(ab),ag=ad.data("uid"),ae=ad.data("group"),af;
if(ad.hasClass(V)){if(ae){this.element.add(this.popup.element).find("."+V+"[data-group='"+ae+"']").filter("."+R).removeClass(R);
}if(a.contains(this.element[0],ad[0])){af=this.popup.element.find("["+w+"='"+ag+"']");
if(af.prop("tagName")==="LI"){af=af.find("."+V+":first");
}}else{ag=ag?ag:ad.parent().data("uid");
af=this.element.find("["+w+"='"+ag+"']");
}ad.add(af).toggleClass(R,ac);
}},_attributes:function(ab,ac){ab.attr(v.attr("overflow"),ac.overflow||C);
},_renderOverflow:function(){var ac=this,ab=l.overflowContainer;
ac.overflowAnchor=a(l.overflowAnchor).addClass(e);
ac.element.append(ac.overflowAnchor);
if(ac.isMobile){ac.overflowAnchor.append('<span class="km-icon km-more"></span>');
ab=b(ab);
}else{ac.overflowAnchor.append('<span class="k-icon k-i-more"></span>');
}ac.popup=new v.ui.Popup(ab,{origin:"bottom right",position:"top right",anchor:ac.overflowAnchor,animation:ac.animation,appendTo:ac.isMobile?a(ac.isMobile).children(".km-pane"):null,copyAnchorStyles:false,open:function(ad){var ae=v.wrap(ac.popup.element).addClass("k-overflow-wrapper");
if(!ac.isMobile){ae.css("margin-left",(ae.outerWidth()-ae.width())/2+1);
}else{ac.popup.container.css("max-height",(parseFloat(a(".km-content:visible").innerHeight())-15)+"px");
}if(ac.trigger(I)){ad.preventDefault();
}},close:function(ad){if(ac.trigger(E)){ad.preventDefault();
}}});
if(ac.isMobile){ac.popup.container=ac.popup.element.find("."+F);
}else{ac.popup.container=ac.popup.element;
}ac.popup.container.attr(w,this.uid);
},_toggleOverflowAnchor:function(){if(this.popup.element.children(":not(."+G+", ."+J+")").length>0){this.overflowAnchor.css({visibility:"visible",width:""});
}else{this.overflowAnchor.css({visibility:"hidden",width:"1px"});
}},_buttonClick:function(ab){var al=this,ai,ak,aj,ah,ag,ad,ae,ac,af;
ab.preventDefault();
ak=a(ab.target).closest("."+e,al.element);
if(ak.hasClass(B)){return;
}if(!ak.length&&al.popup){ak=a(ab.target).closest("."+D,al.popup.container);
}ah=ak.hasClass(D)?ak.parent("li").hasClass(S):ak.hasClass(S);
if(ah){return;
}if(ab.target.closest("."+Q).length){al._toggle(ab);
return;
}af=ak.attr("id")?ak.attr("id").replace(/(_overflow$)/,""):Z;
if(ak.hasClass(V)){ad=ak.data("group");
ae=u(ak.data("toggle"))?ak.data("toggle"):null;
al.toggle(ak);
ag=ak.hasClass(R);
ac={target:ak,group:ad,checked:ag,id:af};
if(ae){ae.call(al,ac);
}al.trigger(U,ac);
}else{ae=u(ak.data("click"))?ak.data("click"):null;
ac={target:ak,id:af};
if(ae){ae.call(al,ac);
}al.trigger(j,ac);
}if(ak.hasClass(D)){al.popup.close();
}aj=ak.closest(".k-split-container");
if(aj[0]){ai=aj.data("kendoPopup");
(ai?ai:aj.parents(".km-popup-wrapper").data("kendoPopup")).close();
}},_toggle:function(ab){var ae=a(ab.target).closest("."+P),ad=ae.data("kendoPopup"),ac;
ab.preventDefault();
if(ae.hasClass(S)){return;
}if(ad.element.is(":visible")){ac=this.trigger(k,{target:ae});
}else{ac=this.trigger(z,{target:ae});
}if(!ac){ad.toggle();
}},_toggleOverflow:function(){this.popup.toggle();
},_resize:function(ac){var ab=ac.width;
if(!this.options.resizable){return;
}this.popup.close();
this._shrink(ab);
this._stretch(ab);
this._markVisibles();
this._toggleOverflowAnchor();
},_childrenWidth:function(){var ab=0;
this.element.children(":visible").each(function(){ab+=a(this).outerWidth(true);
});
return Math.ceil(ab);
},_shrink:function(ac){var ab,ae;
if(ac<this._childrenWidth()){ae=this.element.children(":visible:not([data-overflow='never'], ."+B+")");
for(var ad=ae.length-1;
ad>=0;
ad--){ab=ae.eq(ad);
if(ac>this._childrenWidth()){break;
}else{this._hideItem(ab);
}}}},_stretch:function(ac){var ab,ad;
if(ac>this._childrenWidth()){ad=this.element.children(":hidden");
for(var ae=0;
ae<ad.length;
ae++){ab=ad.eq(ae);
if(ac<this._childrenWidth()||!this._showItem(ab,ac)){break;
}}}},_hideItem:function(ab){ab.hide();
if(this.popup){this.popup.container.find(">li[data-uid='"+ab.data("uid")+"']").removeClass(G);
}},_showItem:function(ac,ab){if(ac.length&&ab>this._childrenWidth()+ac.outerWidth(true)){ac.show();
if(this.popup){this.popup.container.find(">li[data-uid='"+ac.data("uid")+"']").addClass(G);
}return true;
}return false;
},_markVisibles:function(){var ab=this.popup.container.children(),ac=this.element.children(":not(.k-overflow-anchor)"),ad=ab.filter(":not(.k-overflow-hidden)"),ae=ac.filter(":visible");
ab.add(ac).removeClass(p+" "+x);
ad.first().add(ae.first()).addClass(p);
ad.last().add(ae.last()).addClass(x);
}});
v.ui.plugin(X);
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
