(function(b,a){a(["./kendo.dataviz.chart"],b);
})(function(){(function(a,t){var l=window.kendo,f=l.dataviz,d=f.ui.Chart,o=l.data.ObservableArray,q=f.SharedTooltip,i=l.deepExtend,k=a.isArray,j=f.inArray,m=Math;
var e="k-",g=150,h=150,b="bar",c="bullet",p="pie",n=[b,c];
var r=d.extend({init:function(w,z){var v=this,y=v.stage=a("<span />"),x=z||{};
w=a(w).addClass(e+"sparkline").empty().append(y);
v._initialWidth=m.floor(w.width());
x=u(x);
if(k(x)||x instanceof o){x={seriesDefaults:{data:x}};
}if(!x.series){x.series=[{data:u(x.data)}];
}i(x,{seriesDefaults:{type:x.type}});
if(j(x.series[0].type,n)||j(x.seriesDefaults.type,n)){x=i({},{categoryAxis:{crosshair:{visible:false}}},x);
}d.fn.init.call(v,w,x);
},options:{name:"Sparkline",chartArea:{margin:2},axisDefaults:{visible:false,majorGridLines:{visible:false},valueAxis:{narrowRange:true}},seriesDefaults:{type:"line",area:{line:{width:0.5}},bar:{stack:true},padding:2,width:0.5,overlay:{gradient:null},highlight:{visible:false},border:{width:0},markers:{size:2,visible:false}},tooltip:{visible:true,shared:true},categoryAxis:{crosshair:{visible:true,tooltip:{visible:false}}},legend:{visible:false},transitions:false,pointWidth:5,panes:[{clip:false}]},_modelOptions:function(){var v=this,w=v.options,x,A=v._initialWidth,z=v.stage;
v.stage.children().hide();
var y=a("<span>&nbsp;</span>");
v.stage.append(y);
x=i({width:A?A:v._autoWidth(),height:z.height(),transitions:w.transitions},w.chartArea,{inline:true,align:false});
z.css({width:x.width,height:x.height});
y.remove();
v.stage.children().show();
v.surface.resize();
return x;
},_createTooltip:function(){var v=this,x=v.options,w=v.element,y;
if(v._sharedTooltip()){y=new s(w,v._plotArea,x.tooltip);
}else{y=d.fn._createTooltip.call(v);
}return y;
},_surfaceWrap:function(){return this.stage;
},_autoWidth:function(){var v=this,A=v.options,z=f.getSpacing(A.chartArea.margin),B=A.series,x=v.dataSource.total(),C=0,D,y,w;
for(y=0;
y<B.length;
y++){w=B[y];
if(w.type===b){return g;
}if(w.type===c){return h;
}if(w.type===p){return v.stage.height();
}if(w.data){C=m.max(C,w.data.length);
}}D=m.max(x,C)*A.pointWidth;
if(D>0){D+=z.left+z.right;
}return D;
}});
var s=q.extend({options:{animation:{duration:0}},_anchor:function(w,y){var v=q.fn._anchor.call(this,w,y);
var x=this._measure();
v.y=-x.height-this.options.offset;
return v;
},_hideElement:function(){if(this.element){this.element.hide().remove();
}}});
function u(v){return typeof v==="number"?[v]:v;
}f.ui.plugin(r);
i(f,{SparklineSharedTooltip:s});
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
