(function(b,a){a(["./kendo.dataviz.core"],b);
})(function(){(function(r){var a=r,p=document,t=Math,s=window.kendo,f=s.Class,j=s.dataviz,d=j.Box2D,q=j.ExpandAnimation,v=j.Point2D,ac=j.ViewBase,ad=j.ViewElement,k=s.deepExtend,o=j.defined,B=j.round,z=j.renderTemplate,A=j.rotatePoint,ab=j.uniqueId;
var e="butt",g=j.CLIP,h=j.COORD_PRECISION,i=j.DASH_ARRAYS,n=j.DEFAULT_WIDTH,m=j.DEFAULT_HEIGHT,l=j.DEFAULT_FONT,u="none",w="radial",C="solid",D="square",E="http://www.w3.org/2000/svg",Z="transparent",aa="undefined";
var X=ac.extend({init:function(ae){var af=this;
ac.fn.init.call(af,ae);
af.decorators.push(new Q(af),new L(af));
if(j.ui.Chart){af.decorators.push(new j.BarAnimationDecorator(af),new j.PieAnimationDecorator(af),new j.BubbleAnimationDecorator(af));
}af.decorators.push(new G(af),new j.FadeAnimationDecorator(af));
if(j.Gauge){af.decorators.push(new j.RadialPointerAnimationDecorator(af),new j.ArrowPointerAnimationDecorator(af),new j.BarIndicatorAnimationDecorator(af));
}af.defsId=ab();
af.template=X.template;
af.display=af.options.inline?"inline":"block";
if(!af.template){af.template=X.template=z("<?xml version='1.0' ?><svg xmlns='"+E+"' version='1.1' width='#= d.options.width #px' height='#= d.options.height #px' style='position: relative; display: #= d.display #;'>#= d.renderDefinitions() ##= d.renderContent() #</svg>");
}},options:{width:n,height:m,encodeText:false},renderTo:function(ae){var af=this,ag;
af.setupAnimations();
j.renderSVG(ae,af.render());
ag=ae.firstElementChild;
af.alignToScreen(ag);
af.playAnimations();
af._viewElement=ag;
return ag;
},renderDefinitions:function(){var ag=this,ae=ag.defsId,af=ac.fn.renderDefinitions.call(ag);
return"<defs id='"+ae+"'>"+af+"</defs>";
},renderElement:function(ai){var aj=this,ae=p.createElement("div"),af=p.getElementById(aj.defsId),ag,ah;
j.renderSVG(ae,"<?xml version='1.0' ?><svg xmlns='"+E+"' version='1.1'>"+aj.renderDefinitions()+ai.render()+"</svg>");
ag=ae.firstElementChild.firstChild;
ah=ae.firstElementChild.lastChild;
if(af&&af.textContent!==ag.textContent){af.parentNode.replaceChild(ag,af);
}return ah;
},createGroup:function(ae){return this.decorate(new M(ae));
},createClipPath:function(ah,ae){var ai=this,ag=ai.definitions[ah],af=[ai.createRect(ae,{})];
if(!ag){ag=new H({id:ah});
ag.children=af;
ai.definitions[ah]=ag;
}else{ag.children=af;
ag.refresh();
}return ag;
},createText:function(ae,af){return this.decorate(new W(ae,k({encode:this.options.encodeText},af)));
},createRect:function(ae,af){return this.decorate(new N(ae.points(),true,this.setDefaults(af)));
},createCubicCurve:function(ag,af,ae){return this.decorate(new I(ag,af,ae));
},createLine:function(af,ah,ag,ai,ae){return this.decorate(new N([new v(af,ah),new v(ag,ai)],false,this.setDefaults(ae)));
},createMultiLine:function(ae,af){return this.decorate(new P(ae,false,this.setDefaults(af)));
},createPolyline:function(ag,ae,af){return this.decorate(new N(ag,ae,this.setDefaults(af)));
},createCircle:function(ae,ag,af){return this.decorate(new F(ae,ag,af));
},createSector:function(af,ae){return this.decorate(new V(af,ae));
},createRing:function(af,ae){return this.decorate(new U(af,ae));
},createPin:function(af,ae){return this.decorate(new S(af,ae));
},createGradient:function(ae){if(ae.type===w){if(o(ae.ir)){return new J(ae);
}else{return new T(ae);
}}else{return new O(ae);
}},alignToScreen:function(ag){var ae;
try{ae=ag.getScreenCTM?ag.getScreenCTM():null;
}catch(af){}if(ae){var ah=-ae.e%1,aj=-ae.f%1,ai=ag.style;
if(ah!==0||aj!==0){ai.left=ah+"px";
ai.top=aj+"px";
}}}});
var Y=ad.extend({renderClipPath:function(){var af=this,ag=af.options.clipPathId,ae="";
if(ag){ae=af.renderAttr("clip-path","url("+c()+"#"+ag+")");
}return ae;
}});
var W=Y.extend({init:function(ae,af){var ag=this;
Y.fn.init.call(ag,af);
ag.content=ae;
ag.template=W.template;
if(!ag.template){ag.template=W.template=z("<text #= d.renderId() # #= d.renderDataAttributes() # x='#= Math.round(d.options.x) #' y='#= Math.round(d.options.y + d.options.baseline) #' fill-opacity='#= d.options.fillOpacity #' #= d.options.rotation ? d.renderRotation() : '' # style='font: #= d.options.font #; #= d.renderCursor() #' fill='#= d.options.color #'>#= d.renderContent() #</text>");
}},options:{x:0,y:0,baseline:0,font:l,size:{width:0,height:0},fillOpacity:1,cursor:{}},refresh:function(ae){var af=this.options;
a(ae).attr({"fill-opacity":af.fillOpacity});
},clone:function(){var ae=this;
return new W(ae.content,k({},ae.options));
},renderRotation:function(){var am=this,ai=am.options,al=ai.size,ae=B(ai.x+al.normalWidth/2,h),af=B(ai.y+al.normalHeight/2,h),aj=B(ai.x+al.width/2,h),ak=B(ai.y+al.height/2,h),ag=B(aj-ae,h),ah=B(ak-af,h);
return"transform='translate("+ag+","+ah+") rotate("+ai.rotation+","+ae+","+af+")'";
},renderContent:function(){var ae=this.content;
if(this.options.encode){ae=j.decodeEntities(ae);
ae=s.htmlEncode(ae);
}return ae;
}});
var R=Y.extend({init:function(ae){var af=this;
Y.fn.init.call(af,ae);
af.template=R.template;
if(!af.template){af.template=R.template=z("<path #= d.renderId() ##= d.renderClipPath() #style='display: #= d.renderDisplay() #; #= d.renderCursor() #' #= d.renderDataAttributes() # d='#= d.renderPoints() #' #= d.renderAttr(\"stroke\", d.options.stroke) # #= d.renderAttr(\"stroke-width\", d.options.strokeWidth) ##= d.renderDashType() # stroke-linecap='#= d.renderLinecap() #' stroke-linejoin='round' fill-opacity='#= d.options.fillOpacity #' stroke-opacity='#= d.options.strokeOpacity #' fill='#= d.renderFill() #'></path>");
}},options:{fill:"",fillOpacity:1,strokeOpacity:1,rotation:[0,0,0],strokeLineCap:D,visible:true,cursor:{}},refresh:function(ae){var af=this.options;
a(ae).attr({d:this.renderPoints(),"fill-opacity":af.fillOpacity,"stroke-opacity":af.strokeOpacity}).css("display",this.renderDisplay());
},clone:function(){return new R(k({},this.options));
},renderPoints:function(){},renderDashType:function(){var af=this,ae=af.options;
return y(ae.dashType,ae.strokeWidth);
},renderLinecap:function(){var af=this.options,ae=af.dashType,ag=af.strokeLineCap;
return(ae&&ae!=C)?e:ag;
},renderFill:function(){var ae=this.options.fill;
if(ae&&ae!==Z){return ae;
}return u;
},renderDisplay:function(){return this.options.visible?"block":"none";
},destroy:function(){}});
var I=R.extend({init:function(ah,ag,ae){var af=this;
R.fn.init.call(af,ag);
af.areaPoints=ae;
af.points=ah;
},renderPoints:function(){var af=this,ai=af.points,ag=[],ae=af.areaPoints;
for(var ah=0;
ah<ai.length;
ah++){if(ah%3==1){ag.push("C");
}ag.push(B(ai[ah].x,h)+" "+B(ai[ah].y,h));
}if(ae&&ae.length){for(ah=0;
ah<ae.length;
ah++){ag.push("L "+ae[ah].x+" "+ae[ah].y);
}ag.push("z");
}return"M "+ag.join(" ");
}});
var N=R.extend({init:function(ah,ae,ag){var af=this;
R.fn.init.call(af,ag);
af.points=ah;
af.closed=ae;
},renderPoints:function(){var ae=this,af=ae.points;
return ae._renderPoints(af);
},_renderPoints:function(ag){var af=this,ak=af.options.rotation,ai=new v(ak[1],ak[2]),ah=-ak[0],ae,aj=[];
for(ae=0;
ae<ag.length;
ae++){aj.push(af._print(ag[ae].clone().rotate(ai,ah)));
}if(af.closed){aj.push("z");
}return"M"+aj.join(" ");
},clone:function(){var ae=this;
return new N(k([],ae.points),ae.closed,k({},ae.options));
},_print:function(ah){var af=this,ag=af.options,aj=ag.strokeWidth,ai=ag.align!==false&&aj&&aj%2!==0,ae=ai?b:B;
return ae(ah.x,h)+" "+ae(ah.y,h);
}});
var P=N.extend({renderPoints:function(){var ag=this,ae=ag.points,ah=[],af;
for(af=0;
af<ae.length;
af++){ah.push(ag._renderPoints(ae[af]));
}return ah.join(" ");
}});
var U=R.extend({init:function(ae,af){var ag=this;
R.fn.init.call(ag,af);
ag.pathTemplate=U.pathTemplate;
if(!ag.pathTemplate){ag.pathTemplate=U.pathTemplate=z("M #= d.firstOuterPoint.x # #= d.firstOuterPoint.y # A#= d.r # #= d.r # 0 #= d.isReflexAngle ? '1' : '0' #,1 #= d.secondOuterPoint.x # #= d.secondOuterPoint.y # L #= d.secondInnerPoint.x # #= d.secondInnerPoint.y # A#= d.ir # #= d.ir # 0 #= d.isReflexAngle ? '1' : '0' #,0 #= d.firstInnerPoint.x # #= d.firstInnerPoint.y # z");
}ag.config=ae||{};
},renderPoints:function(){var al=this,am=al.config,ap=am.startAngle,af=am.angle+ap,aj=(af-ap)>180,ak=t.max(am.r,0),ai=t.max(am.ir,0),ae=am.c,ah=am.point(ap),ag=am.point(ap,true),ao,an;
if(B(ap)%360===B(af)%360){af-=0.05;
}ao=am.point(af);
an=am.point(af,true);
return al.pathTemplate({firstOuterPoint:ah,secondOuterPoint:ao,isReflexAngle:aj,r:ak,ir:ai,cx:ae.x,cy:ae.y,firstInnerPoint:ag,secondInnerPoint:an});
},clone:function(){var ae=this;
return new U(k({},ae.config),k({},ae.options));
}});
var S=R.extend({init:function(ae,af){var ag=this;
R.fn.init.call(ag,af);
ag.pathTemplate=S.pathTemplate;
if(!ag.pathTemplate){ag.pathTemplate=S.pathTemplate=z("M #= d.origin.x # #= d.origin.y # #= d.as.x # #= d.as.y # A#= d.r # #= d.r # 0 #= d.isReflexAngle ? '1' : '0' #,0 #= d.ae.x # #= d.ae.y # z");
}ag.config=ae||new j.Pin();
},renderPoints:function(){var am=this,ah=am.config,an=ah.radius,ai=t.PI/180,ae=ah.arcAngle,aj=an*t.sin(ae*ai/2),ak=ah.height-an*(1-t.cos(ae*ai/2)),al=ah.origin,ag={x:al.x+aj,y:al.y-ak},af={x:al.x-aj,y:al.y-ak},ao=function(ar,aq){var at=am.options.rotation,ap=ah.rotation;
ar=A(ar.x,ar.y,at[1],at[2],-at[0]);
if(aq){ar=A(ar.x,ar.y,al.x,al.y,ap);
}return ar;
};
al=ao(al);
return am.pathTemplate({origin:al,as:ao(ag,true),ae:ao(af,true),r:an,isReflexAngle:ae>180});
}});
var V=U.extend({init:function(ae,af){var ag=this;
U.fn.init.call(ag,ae,af);
ag.pathTemplate=V.pathTemplate;
if(!ag.pathTemplate){ag.pathTemplate=V.pathTemplate=z("M #= d.firstOuterPoint.x # #= d.firstOuterPoint.y # A#= d.r # #= d.r # 0 #= d.isReflexAngle ? '1' : '0' #,1 #= d.secondOuterPoint.x # #= d.secondOuterPoint.y # L #= d.cx # #= d.cy # z");
}},options:{fill:"",fillOpacity:1,strokeOpacity:1,strokeLineCap:D},clone:function(){var ae=this;
return new V(k({},ae.config),k({},ae.options));
}});
var F=ad.extend({init:function(ae,ah,ag){var af=this;
ad.fn.init.call(af,ag);
af.c=ae;
af.r=ah;
af.template=F.template;
if(!af.template){af.template=F.template=z("<circle #= d.renderId() # #= d.renderDataAttributes() #cx='#= d.c.x #' cy='#= d.c.y #' r='#= d.r #' #= d.renderAttr(\"stroke\", d.options.stroke) # #= d.renderAttr(\"stroke-width\", d.options.strokeWidth) #fill-opacity='#= d.options.fillOpacity #' stroke-opacity='#= d.options.strokeOpacity #'  fill='#= d.options.fill || \"none\" #'></circle>");
}},options:{fill:"",fillOpacity:1,strokeOpacity:1},refresh:function(ae){a(ae).attr({r:t.max(0,this.r),"fill-opacity":this.options.fillOpacity});
},clone:function(){var ae=this;
return new F(k({},ae.c),ae.r,k({},ae.options));
}});
var M=Y.extend({init:function(af){var ae=this;
ad.fn.init.call(ae,af);
ae.template=M.template;
if(!ae.template){ae.template=M.template=z("<g#= d.renderId() ##= d.renderDataAttributes() ##= d.renderClipPath() #>#= d.renderContent() #</g>");
}}});
var H=ad.extend({init:function(af){var ae=this;
ad.fn.init.call(ae,af);
ae.template=H.template;
if(!ae.template){ae.template=H.template=z('<clipPath#= d.renderAttr("id", d.options.id) #>#= d.renderContent() #</clipPath>');
}},refresh:function(){var ae=p.getElementById(this.options.id);
if(ae){a(ae).children().attr("d",this.children[0].renderPoints());
}}});
var K=ad.extend({init:function(af){var ae=this;
ad.fn.init.call(ae,af);
},options:{id:""},renderStops:function(){var af=this,aj=af.options.stops,ak=af.stopTemplate,ag,ah=aj.length,ae,ai="";
for(ag=0;
ag<ah;
ag++){ae=aj[ag];
ai+=ak(ae);
}return ai;
}});
var O=K.extend({init:function(af){var ae=this;
K.fn.init.call(ae,af);
ae.template=O.template;
ae.stopTemplate=O.stopTemplate;
if(!ae.template){ae.template=O.template=z("<linearGradient id='#= d.options.id #' gradientTransform='rotate(#= d.options.rotation #)'> #= d.renderStops() #</linearGradient>");
ae.stopTemplate=O.stopTemplate=z("<stop offset='#= Math.round(d.offset * 100) #%' style='stop-color:#= d.color #;stop-opacity:#= d.opacity #' />");
}},options:{rotation:0}});
var T=K.extend({init:function(af){var ae=this;
K.fn.init.call(ae,af);
ae.template=T.template;
ae.stopTemplate=T.stopTemplate;
if(!ae.template){ae.template=T.template=z("<radialGradient id='#= d.options.id #' cx='#= d.options.cx #' cy='#= d.options.cy #' fx='#= d.options.cx #' fy='#= d.options.cy #' r='#= d.options.r #' gradientUnits='userSpaceOnUse'>#= d.renderStops() #</radialGradient>");
ae.stopTemplate=T.stopTemplate=z("<stop offset='#= Math.round(d.offset * 100) #%' style='stop-color:#= d.color #;stop-opacity:#= d.opacity #' />");
}}});
var J=ad.extend({init:function(af){var ae=this;
ad.fn.init.call(ae,af);
ae.template=J.template;
ae.stopTemplate=J.stopTemplate;
if(!ae.template){ae.template=J.template=z("<radialGradient id='#= d.options.id #' cx='#= d.options.cx #' cy='#= d.options.cy #' fx='#= d.options.cx #' fy='#= d.options.cy #' r='#= d.options.r #' gradientUnits='userSpaceOnUse'>#= d.renderStops() #</radialGradient>");
ae.stopTemplate=J.stopTemplate=z("<stop offset='#= d.offset #%' style='stop-color:#= d.color #;stop-opacity:#= d.opacity #' />");
}},options:{id:""},renderStops:function(){var af=this,ai=af.options,ak=ai.stops,al=af.stopTemplate,am=((ai.ir/ai.r)*100),ag,ah=ak.length,ae,aj="";
ae=k({},ak[0]);
ae.offset=am;
aj+=al(ae);
for(ag=1;
ag<ah;
ag++){ae=k({},ak[ag]);
ae.offset=ae.offset*(100-am)+am;
aj+=al(ae);
}return aj;
}});
function Q(ae){this.view=ae;
}Q.prototype={decorate:function(af){var ae=this,ak=ae.view,ai=af.options,ah=ai.id,ag,aj;
if(ai.overlay){af.options.id=ab();
ag=ak.createGroup();
aj=af.clone();
ag.children.push(af,aj);
aj.options.id=ah;
aj.options.fill=ai.overlay;
return ag;
}else{return af;
}}};
function L(ae){this.view=ae;
}L.prototype={decorate:function(af){var ae=this,ag=af.options;
ag.fill=ae.getPaint(ag.fill);
return af;
},getPaint:function(aj){var ae=this,ak=ae.view,af=ak.definitions,ah,ai,ag;
if(aj&&o(aj.gradient)){ah=ak.buildGradient(aj);
if(ah){ai=ah.id;
ag=af[ai];
if(!ag){ag=ak.createGradient(ah);
af[ai]=ag;
}return"url("+c()+"#"+ag.options.id+")";
}else{return u;
}}else{return aj;
}}};
var G=f.extend({init:function(ae){this.view=ae;
},decorate:function(ak){var ai=this,am=ai.view,af=ai.clipId,al=am.options,ae=ak.options.animation,aj=am.definitions,ag,ah;
if(ae&&ae.type===g&&al.transitions){if(!af){ai.clipId=af=ab();
}ag=aj[af];
if(!ag){ag=new H({id:af});
ah=am.createRect(new d(0,0,al.width,al.height),{id:ab()});
ag.children.push(ah);
aj[af]=ag;
am.animations.push(new q(ah,{size:al.width}));
}ak.options.clipPathId=af;
}return ak;
}});
function b(ae){return t.round(ae)+0.5;
}function y(ae,ai){var ah=[],af,ag;
ae=ae?ae.toLowerCase():null;
if(ae&&ae!=C){af=i[ae];
for(ag=0;
ag<af.length;
ag++){ah.push(af[ag]*(ai||1));
}return"stroke-dasharray='"+ah.join(" ")+"' ";
}return"";
}var x=function(ae,af){ae.innerHTML=af;
};
function c(){var ae=p.getElementsByTagName("base")[0],ah="",ag=p.location.href,af=ag.indexOf("#");
if(ae&&!s.support.browser.msie){if(af!==-1){ag=ag.substring(0,af);
}ah=ag;
}return ah;
}(function(){var ag="<svg xmlns='"+E+"'></svg>",af=p.createElement("div"),ae=typeof DOMParser!=aa;
af.innerHTML=ag;
if(ae&&af.firstChild.namespaceURI!=E){x=function(ai,al){var ak=new DOMParser(),ah=ak.parseFromString(al,"text/xml"),aj=p.adoptNode(ah.documentElement);
ai.innerHTML="";
ai.appendChild(aj);
};
}})();
if(j.supportsSVG()){j.ViewFactory.current.register("svg",X,10);
}k(j,{renderSVG:x,SVGCircle:F,SVGClipAnimationDecorator:G,SVGClipPath:H,SVGGradientDecorator:L,SVGGroup:M,SVGLine:N,SVGMultiLine:P,SVGLinearGradient:O,SVGOverlayDecorator:Q,SVGPath:R,SVGRadialGradient:T,SVGDonutGradient:J,SVGRing:U,SVGSector:V,SVGText:W,SVGView:X});
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
