(function(b,a){a(["./kendo.dataviz.core"],b);
})(function(){(function(t){var a=t,q=document,w=Math,u=window.kendo,g=u.Class,l=u.deepExtend,k=u.dataviz,i=k.Color,f=k.Box2D,y=k.Point2D,r=k.ExpandAnimation,G=k.ViewBase,H=k.ViewElement,p=k.defined,A=k.renderTemplate,F=k.uniqueId,B=k.rotatePoint,C=k.round,D=k.supportsSVG;
var b="#000",h=k.CLIP,j=k.COORD_PRECISION,o=k.DEFAULT_WIDTH,n=k.DEFAULT_HEIGHT,m=k.DEFAULT_FONT,x="object",v="linear",z="radial",E="transparent";
var ac=G.extend({init:function(ad){var ae=this;
G.fn.init.call(ae,ad);
ae.decorators.push(new U(ae),new P(ae),new K(ae));
if(k.ui.Chart){ae.decorators.push(new k.BarAnimationDecorator(ae),new k.PieAnimationDecorator(ae),new k.BubbleAnimationDecorator(ae));
}ae.decorators.push(new J(ae));
if(!s()){ae.decorators.push(new k.FadeAnimationDecorator(ae));
}if(k.Gauge){ae.decorators.push(new k.RadialPointerAnimationDecorator(ae),new k.ArrowPointerAnimationDecorator(ae),new k.BarIndicatorAnimationDecorator(ae));
}ae.template=ac.template;
ae.tagName=ae.options.inline?"span":"div";
if(!ae.template){ae.template=ac.template=A("<#= d.tagName # style='width:#= d.options.width #px; height:#= d.options.height #px; position: relative;'>#= d.renderContent() #</#= d.tagName #>");
}},options:{width:o,height:n},renderTo:function(ad){var ae=this,af;
if(q.namespaces){q.namespaces.add("kvml","urn:schemas-microsoft-com:vml","#default#VML");
}ae.setupAnimations();
ad.innerHTML=ae.render();
ae.playAnimations();
af=ad.firstChild;
ae._viewElement=af;
return af;
},renderElement:function(af){var ad=q.createElement("div"),ae;
ad.style.display="none";
q.body.appendChild(ad);
ad.innerHTML=af.render();
ae=ad.firstChild;
q.body.removeChild(ad);
return ae;
},createText:function(ad,ae){return this.decorate((ae&&ae.rotation)?new Y(ad,ae):new ab(ad,ae));
},createRect:function(ad,ae){return this.decorate(new R(ad.points(),true,this.setDefaults(ae)));
},createCubicCurve:function(af,ae,ad){return new M(af,ae,ad);
},createLine:function(ae,ag,af,ah,ad){return this.decorate(new R([new y(ae,ag),new y(af,ah)],false,this.setDefaults(ad)));
},createMultiLine:function(ad,ae){return this.decorate(new T(ad,false,this.setDefaults(ae)));
},createPolyline:function(af,ad,ae){return this.decorate(new R(af,ad,this.setDefaults(ae)));
},createCircle:function(ad,af,ae){return this.decorate(new I(ad,af,ae));
},createSector:function(ae,ad){return this.decorate(new Z(ae,ad));
},createRing:function(ae,ad){return this.decorate(new X(ae,this.setDefaults(ad)));
},createGroup:function(ad){return this.decorate(new Q(this.setDefaults(ad)));
},createClipPath:function(af,ad){var ag=this,ae;
ae=new L(ad,{id:af});
ag.definitions[af]=ae;
return ae;
},createGradient:function(ad){var ae=p(ad.cx)&&p(ad.cy)&&p(ad.bbox);
if(ad.type===z&&ae){return new W(ad);
}else{if(ad.type===v){return new S(ad);
}else{return b;
}}}});
var ab=H.extend({init:function(ad,ae){var af=this;
H.fn.init.call(af,ae);
af.content=ad;
af.template=ab.template;
if(!af.template){af.template=ab.template=A("<kvml:textbox #= d.renderId() # #= d.renderDataAttributes() #style='position: absolute; left: #= d.options.x #px; top: #= d.options.y #px; font: #= d.options.font #; color: #= d.options.color #; visibility: #= d.renderVisibility() #; white-space: nowrap; #= d.renderCursor() #'>#= d.content #</kvml:textbox>");
}},options:{x:0,y:0,font:m,color:b,fillOpacity:1,cursor:{}},refresh:function(ad){a(ad).css("visibility",this.renderVisibility());
},clone:function(){var ad=this;
return new ab(ad.content,l({},ad.options));
},renderVisibility:function(){return this.options.fillOpacity>0?"visible":"hidden";
},renderCursor:function(){var ad=this.options,ae="";
if(p(ad.cursor.style)){ae+="cursor: "+ad.cursor.style+";";
}return ae;
}});
var Y=H.extend({init:function(ad,ae){var af=this;
H.fn.init.call(af,ae);
af.content=ad;
af.template=Y.template;
if(!af.template){af.template=Y.template=A("<kvml:shape #= d.renderId() # #= d.renderDataAttributes() #style='position: absolute; top: 0px; left: 0px; width: 1px; height: 1px;' stroked='false' coordsize='1,1'>#= d.renderPath() #<kvml:fill color='#= d.options.color #' /><kvml:textpath on='true' style='font: #= d.options.font #;' fitpath='false' string='#= d.content #' /></kvml:shape>");
}},options:{x:0,y:0,font:m,color:b,size:{width:0,height:0}},renderPath:function(){var ak=this,ah=ak.options,al=ah.size.width,ag=ah.size.height,ae=ah.x+al/2,af=ah.y+ag/2,ad=-ah.rotation,ai=B(ah.x,af,ae,af,ad),aj=B(ah.x+al,af,ae,af,ad);
return"<kvml:path textpathok='true' v='m "+C(ai.x)+","+C(ai.y)+" l "+C(aj.x)+","+C(aj.y)+"' />";
}});
var aa=H.extend({init:function(ad){var ae=this;
H.fn.init.call(ae,ad);
ae.template=aa.template;
if(!ae.template){ae.template=aa.template=A('<kvml:stroke on=\'#= !!d.options.stroke && !!d.options.strokeWidth #\' #= d.renderAttr("color", d.options.stroke) #weight=\'#= d.options.strokeWidth || 0 #px\' #= d.renderAttr("dashstyle", d.options.dashType) ##= d.renderAttr("opacity", d.options.strokeOpacity) # />');
}},refresh:function(ad){try{ad.opacity=this.options.strokeOpacity;
}catch(ae){}}});
var N=H.extend({init:function(ad){var ae=this;
H.fn.init.call(ae,ad);
ae.template=N.template;
if(!ae.template){ae.template=N.template=A('<kvml:fill on=\'#= d.isEnabled() #\' #= d.renderAttr("color", d.options.fill) ##= d.renderAttr("weight", d.options.fillWidth) ##= d.renderAttr("opacity", d.options.fillOpacity) # />');
}},isEnabled:function(){var ad=this.options.fill;
return !!ad&&ad.toLowerCase()!==E;
},refresh:function(ad){try{ad.opacity=this.options.fillOpacity;
}catch(ae){}}});
var V=H.extend({init:function(ad){var ae=this;
H.fn.init.call(ae,ad);
ae.template=V.template;
if(!ae.template){ae.template=V.template=A("<kvml:shape #= d.renderId() # #= d.renderDataAttributes() #style='position:absolute; #= d.renderSize() # display:#= d.renderDisplay() #; #= d.renderCursor() #' coordorigin='0 0' #= d.renderCoordsize() #><kvml:path v='#= d.renderPoints() # e' />#= d.fill.render() + d.stroke.render() #</kvml:shape>");
}ae.stroke=new aa(ae.options);
ae.fill=new N(ae.options);
},options:{fill:"",fillOpacity:1,strokeOpacity:1,rotation:[0,0,0],visible:true,cursor:{}},renderCoordsize:function(){var ad=this.options.align===false?10000:1;
return"coordsize='"+ad+" "+ad+"'";
},renderSize:function(){var ad=this.options.align===false?100:1;
return"width:"+ad+"px; height:"+ad+"px;";
},render:function(){var ad=this;
ad.fill.options.fillOpacity=ad.options.fillOpacity;
ad.stroke.options.strokeOpacity=ad.options.strokeOpacity;
return H.fn.render.call(ad);
},renderDisplay:function(){return this.options.visible?"block":"none";
},renderPoints:function(){},refresh:function(ad){if(!ad){return;
}var ah=this,ae=a(ad),ag=ae[0].parentNode,af=ah.fill,ai=ah.stroke;
if(ag){ae.find("path")[0].v=this.renderPoints();
af.options=ai.options=ah.options;
af.refresh(ae.find("fill")[0]);
ai.refresh(ae.find("stroke")[0]);
ae.css("display",ah.renderDisplay());
ag.style.cssText=ag.style.cssText;
}},renderCursor:function(){var ad=this.options,ae="";
if(p(ad.cursor.style)){ae+="cursor: "+ad.cursor.style+";";
}return ae;
}});
var M=V.extend({init:function(ag,af,ad){var ae=this;
V.fn.init.call(ae,af);
ae.points=ag;
ae.areaPoints=ad;
},renderPoints:function(){var af=this,ah,aj,ad=af.areaPoints,ak=af.points,ag=[],ae;
for(ah=1;
ah<ak.length;
ah+=3){ae=[];
for(var ai=0;
ai<3;
ai++){aj=ak[ah+ai];
ae.push(C(aj.x)+","+C(aj.y));
}ag.push("C "+ae.join(" "));
}if(ad&&ad.length){for(ah=0;
ah<ad.length;
ah++){ag.push("L "+C(ad[ah].x)+","+C(ad[ah].y));
}ag.push("X");
}return"M "+w.round(ak[0].x)+","+w.round(ak[0].y)+" "+ag.join(" ")+" E";
}});
var R=V.extend({init:function(ag,ad,af){var ae=this;
V.fn.init.call(ae,af);
ae.points=ag;
ae.closed=ad;
},renderPoints:function(){var ad=this,ae=ad.points;
return ad._renderPoints(ae);
},_renderPoints:function(ag){var af=this,ae,ad=ag.length,ai=function(aj){var ak=af.options.rotation;
return B(aj.x,aj.y,ak[1],ak[2],-ak[0]);
},ah="m "+af._print(ai(ag[0]));
if(ad>1){ah+=" l ";
for(ae=1;
ae<ad;
ae++){ah+=af._print(ai(ag[ae]));
if(ae<ad-1){ah+=", ";
}}}if(af.closed){ah+=" x";
}return ah;
},clone:function(){var ad=this;
return new R(l([],ad.points),ad.closed,l({},ad.options));
},_print:function(ad){var ae=this.options.align===false?100:1;
return w.round(ad.x*ae)+","+w.round(ad.y*ae);
}});
var T=R.extend({renderPoints:function(){var af=this,ad=af.points,ag=[],ae;
for(ae=0;
ae<ad.length;
ae++){ag.push(af._renderPoints(ad[ae]));
}return ag.join(" ");
}});
var X=V.extend({init:function(ad,ae){var af=this;
V.fn.init.call(af,ae);
af.pathTemplate=X.pathTemplate;
if(!af.pathTemplate){af.pathTemplate=X.pathTemplate=A("M #= d.osp.x #,#= d.osp.y # WA #= d.obb.l #,#= d.obb.t # #= d.obb.r #,#= d.obb.b # #= d.osp.x #,#= d.osp.y # #= d.oep.x #,#= d.oep.y # L #= d.iep.x #,#= d.iep.y # AT #= d.ibb.l #,#= d.ibb.t # #= d.ibb.r #,#= d.ibb.b # #= d.iep.x #,#= d.iep.y # #= d.isp.x #,#= d.isp.y # X E");
}af.config=ad;
},renderPoints:function(){var aq=this,ae=aq.config,ap=w.max(C(ae.r),0),al=w.max(C(ae.ir),0),af=C(ae.c.x),ag=C(ae.c.y),at=ae.startAngle,ah=ae.angle+at,ad=ah-at,am={l:af-ap,t:ag-ap,r:af+ap,b:ag+ap},ai={l:af-al,t:ag-al,r:af+al,b:ag+al},ao,ak,aj,an;
function ar(au){return new y(C(au.x),C(au.y));
}if(ad<=1){ah+=1-ad;
}else{if(ad>359){ah-=1-ad;
}}ao=ar(ae.point(at));
ak=ar(ae.point(at,true));
an=ar(ae.point(ah));
aj=ar(ae.point(ah,true));
return aq.pathTemplate({obb:am,ibb:ai,osp:ao,isp:ak,oep:an,iep:aj,cx:af,cy:ag});
},clone:function(){var ad=this;
return new X(l({},ad.config),l({},ad.options));
}});
var Z=X.extend({init:function(ad,ae){var af=this;
X.fn.init.call(af,ad,ae);
af.pathTemplate=Z.pathTemplate;
if(!af.pathTemplate){af.pathTemplate=Z.pathTemplate=A("M #= d.osp.x #,#= d.osp.y # WA #= d.obb.l #,#= d.obb.t # #= d.obb.r #,#= d.obb.b # #= d.osp.x #,#= d.osp.y # #= d.oep.x #,#= d.oep.y # L #= d.cx #,#= d.cy # X E");
}},clone:function(){var ad=this;
return new Z(l({},ad.config),l({},ad.options));
}});
var I=H.extend({init:function(ad,ag,af){var ae=this;
H.fn.init.call(ae,af);
ae.c=ad;
ae.r=ag;
ae.template=I.template;
if(!ae.template){ae.template=I.template=A("<kvml:oval #= d.renderId() # #= d.renderDataAttributes() #style='position:absolute; width:#= d.r * 2 #px; height:#= d.r * 2 #px; top:#= d.c.y - d.r #px; left:#= d.c.x - d.r #px;'>#= d.fill.render() + d.stroke.render() #</kvml:oval>");
}ae.stroke=new aa(ae.options);
ae.fill=new N(ae.options);
},options:{fill:"",fillOpacity:1},refresh:function(af){var ae=this,ad=ae.c,ah=w.max(0,ae.r),ai=ah*2,ag=a(af);
ag.css({width:ai,height:ai,top:ad.y-ah,left:ad.x-ah});
ae.fill.options=ae.options;
ae.fill.refresh(ag.find("fill")[0]);
},clone:function(){var ad=this;
return new I(l({},ad.c),ad.r,l({},ad.options));
}});
var Q=H.extend({init:function(ae){var ad=this;
H.fn.init.call(ad,ae);
ad.tagName=ad.options.inline?"span":"div";
ad.template=Q.template;
if(!ad.template){ad.template=Q.template=A("<#= d.tagName # #= d.renderId() ##= d.renderDataAttributes() #style='position: absolute; white-space: nowrap;'>#= d.renderContent() #</#= d.tagName #>");
}}});
var L=H.extend({init:function(ad,af){var ae=this;
H.fn.init.call(ae,af);
ae.tagName=ae.options.inline?"span":"div";
ae.template=L.template;
ae.clipTemplate=L.clipTemplate;
if(!ae.template){ae.template=L.template=A("<#= d.tagName # #= d.renderId() #style='position:absolute;width:#= d.box.width() #px; height:#= d.box.height() + d.box.y1#px; top:0px; left:0px; clip:#= d._renderClip() #;' >#= d.renderContent() #</#= d.tagName #>");
ae.clipTemplate=L.clipTemplate=A("rect(#= d.points[0].y #px #= d.points[1].x #px #= d.points[2].y #px #= d.points[0].x #px)");
}ae.box=ad;
ae.points=ad.points();
},clone:function(){var ad=this;
return new L(ad.box,l({},ad.options));
},refresh:function(ad){if(ad){ad.style.clip=this._renderClip();
}},_renderClip:function(){return this.clipTemplate(this);
},destroy:function(){a("#"+this.options.id+">*").unwrap();
}});
var O=H.extend({init:function(ae){var ad=this;
H.fn.init.call(ad,ae);
},options:{opacity:1},renderColors:function(){var ae=this,ah=ae.options,ak=ah.stops,ad,af,ag=ak.length,ai=[],aj=w.round;
for(af=0;
af<ag;
af++){ad=ak[af];
ai.push(aj(ad.offset*100)+"% "+ad.color);
}return ai.join(",");
}});
var S=O.extend({init:function(ae){var ad=this;
O.fn.init.call(ad,ae);
ad.template=S.template;
if(!ad.template){ad.template=S.template=A("<kvml:fill type='gradient' angle='#= 270 - d.options.rotation #' colors='#= d.renderColors() #' opacity='#= d.options.opacity #' />");
}},options:{rotation:0}});
var W=O.extend({init:function(ae){var ad=this;
O.fn.init.call(ad,ae);
ad.template=W.template;
if(!ad.template){ad.template=W.template=A("<kvml:fill type='gradienttitle' focus='100%' focusposition='#= d.focusPosition() #'colors='#= d.renderColors() #' color='#= d.firstColor() #' color2='#= d.lastColor() #' opacity='#= d.options.opacity #' />");
}},focusPosition:function(){var ai=this.options,ad=ai.bbox,ae=ai.cx,af=ai.cy,ag=Math.max(0,Math.min(1,(ae-ad.x1)/ad.width())),ah=Math.max(0,Math.min(1,(af-ad.y1)/ad.height()));
return C(ag,j)+" "+C(ah,j);
},firstColor:function(){var ad=this.options.stops;
return ad[0].color;
},lastColor:function(){var ad=this.options.stops;
return ad[ad.length-1].color;
}});
function U(ad){this.view=ad;
}U.prototype={decorate:function(ae){var af=ae.options,ah=this.view,ag,ad;
if(af.overlay){ad=af.overlay.bbox;
ag=ah.buildGradient(l({},af.overlay,{_overlayFill:af.fill,_bboxHash:p(ad)?ad.getHash():""}));
}if(!ag){return ae;
}delete af.overlay;
af.fill=l(e(af.fill,ag),{opacity:af.fillOpacity});
return ae;
}};
function P(ad){this.view=ad;
}P.prototype={decorate:function(ae){var ad=this,ah=ad.view,ag=ae.options,af=ag.fill;
if(af&&af.supportVML!==false){if(af.gradient){af=ah.buildGradient(af);
}if(typeof af===x){ae.fill=ah.createGradient(af);
}}return ae;
}};
function K(ad){this.view=ad;
}K.prototype={decorate:function(af){var ae=this,ag=ae.view,ad=ag.definitions[af.options.clipPathId];
if(ad){ad=ad.clone();
ad.options.id=F();
ad.children.push(af);
return ad;
}return af;
}};
var J=g.extend({init:function(ad){this.view=ad;
},decorate:function(ag){var af=this,ai=af.view,ah=ai.options,ad=ag.options.animation,ae;
if(ad&&ad.type===h&&ah.transitions){ae=new L(new f(0,0,ah.width,ah.height),{id:F(),inline:ah.inline});
ai.animations.push(new r(ae,{size:ah.width}));
ae.children.push(ag);
return ae;
}else{return ag;
}}});
function s(){return u.support.browser.msie&&!D()&&typeof window.performance!=="undefined";
}function d(af,ai,ad){var ag=new i(af),aj=new i(ai),ak=c(ag.r,aj.r,ad),ah=c(ag.g,aj.g,ad),ae=c(ag.b,aj.b,ad);
return new i(ak,ah,ae).toHex();
}function c(ad,af,ae){return w.round(ae*af+(1-ae)*ad);
}function e(ad,ae){var ai=ae.stops,ak=ai.length,ag=l({},ae),af,aj,ah;
ag.stops=[];
for(af=0;
af<ak;
af++){aj=ai[af];
ah=ag.stops[af]=l({},ai[af]);
ah.color=d(ad,aj.color,aj.opacity);
ah.opacity=0;
}return ag;
}if(u.support.browser.msie){k.ViewFactory.current.register("vml",ac,20);
}l(k,{VMLCircle:I,VMLClipAnimationDecorator:J,VMLClipDecorator:K,VMLClipRect:L,VMLFill:N,VMLGroup:Q,VMLLine:R,VMLMultiLine:T,VMLLinearGradient:S,VMLOverlayDecorator:U,VMLPath:V,VMLRadialGradient:W,VMLRing:X,VMLRotatedText:Y,VMLSector:Z,VMLStroke:aa,VMLText:ab,VMLView:ac,blendColors:d,blendGradient:e});
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
