'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_FontSettings

    '''<summary>
    '''DDLfontName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLfontName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLfontSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLfontSize As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CBXbold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBXbold As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CBXitalic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBXitalic As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CBXunderline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBXunderline As Global.System.Web.UI.WebControls.CheckBox
End Class
