'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_ConstraintsDetails

    '''<summary>
    '''LTmessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmessage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''RPTconstraints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTconstraints As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''LTcssClassPassed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassPassed As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassWaiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassWaiting As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassNotPassed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassNotPassed As Global.System.Web.UI.WebControls.Literal
End Class
