'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_EnrollBulkAction

    '''<summary>
    '''LBenrollToCommunitiesBulkTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBenrollToCommunitiesBulkTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BTNenrollToSelectedCommunities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNenrollToSelectedCommunities As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CBXselectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBXselectAll As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LBenrollToSelectOnAllPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBenrollToSelectOnAllPages As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBextraInfoForCommunitiesSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBextraInfoForCommunitiesSelected As Global.System.Web.UI.WebControls.Label
End Class
