'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserSettings

    '''<summary>
    '''LTpageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTpageTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTtitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LKBsaveTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKBsaveTop As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LKBbackTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKBbackTop As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''UCactionMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCactionMessages As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''UCtkSet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCtkSet As Global.Comunita_OnLine.UC_TicketUserSettings

    '''<summary>
    '''LKBsaveBot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKBsaveBot As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LKBbackBot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKBbackBot As Global.System.Web.UI.WebControls.LinkButton
End Class
