'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CommunityRepositoryImport

    '''<summary>
    '''MLVimport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVimport As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWerror As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBerror As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VIWselectFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWselectFolder As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''Div2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HYPbackToFileManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPbackToFileManagement As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''WZRimportCommunityItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WZRimportCommunityItem As Global.System.Web.UI.WebControls.Wizard

    '''<summary>
    '''WSTcommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WSTcommunity As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''LBselectCommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBselectCommunity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLcommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLcommunity As Global.Comunita_OnLine.UC_SearchCommunityByService

    '''<summary>
    '''WSTfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WSTfile As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''LBfileToExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBfileToExport As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLsourceItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLsourceItems As Global.Comunita_OnLine.UC_SelectCommunityFiles

    '''<summary>
    '''WSTfolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WSTfolder As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''LBselectFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBselectFolder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBcommunity_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcommunity_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBcommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcommunity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBpath_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBpath_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UDPdata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UDPdata As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''LBpath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBpath As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BTNeditPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNeditPath As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LBvisibleTo_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBvisibleTo_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RBLvisibleTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBLvisibleTo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''WSTmultipleFileError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WSTmultipleFileError As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''LBmultipleFileError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBmultipleFileError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPTfileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTfileName As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''UDPselectFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UDPselectFolder As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''CTRLCommunityFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLCommunityFolder As Global.Comunita_OnLine.UC_SelectCommunityFolder

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AjaxPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AjaxPortal)
        End Get
    End Property
End Class
