'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_EditField
    
    '''<summary>
    '''MLVfield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVfield As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''VIWunknown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWunknown As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''VIWempty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWempty As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''VIWfield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWfield As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''LBdisclaimer_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdisclaimer_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBfieldDescription_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBfieldDescription_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXBdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBdescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LBfieldtags_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBfieldtags_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXBtags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBtags As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DVhelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVhelp As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LBfieldHelp_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBfieldHelp_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXBhelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBhelp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DVmaxChar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVmaxChar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LBfieldMaxChar_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBfieldMaxChar_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXBmaxChar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBmaxChar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RNVBmaxChar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RNVBmaxChar As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''DVdisclaimerType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdisclaimerType As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LBfieldDisclaimerType_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBfieldDisclaimerType_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RBLdisclaimerType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBLdisclaimerType As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''MLVadvanced control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVadvanced As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''VIWnone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWnone As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''VIWmultipleChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWmultipleChoice As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''FSmultipleChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FSmultipleChoice As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LBmultipleChoice_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBmultipleChoice_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CBXmultipleChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBXmultipleChoice As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''LBminOptions_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBminOptions_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXTminOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTminOptions As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LTminOptionsInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTminOptionsInfo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LBmaxOptions_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBmaxOptions_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXTmaxOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTmaxOptions As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LTmaxOptionsInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmaxOptionsInfo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''RPToptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPToptions As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''VIWdropdownlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWdropdownlist As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''RPTcomboOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTcomboOptions As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''VIWtable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWtable As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''LBtableCols_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtableCols_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXBtableCols control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBtableCols As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LBtableCols_desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtableCols_desc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBtableRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtableRows As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXBmaxRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBmaxRows As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RNVmaxRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RNVmaxRows As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''SPmaxTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPmaxTotal As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LBtableMaxTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtableMaxTotal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXBtableMaxTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBtableMaxTotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''VIWtableSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWtableSummary As Global.System.Web.UI.WebControls.View
End Class
