'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProjectMap

    '''<summary>
    '''CTRLselectUsersHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLselectUsersHeader As Global.Comunita_OnLine.UC_SelectUsersHeader

    '''<summary>
    '''CTRLmodalPlayerHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmodalPlayerHeader As Global.Comunita_OnLine.UC_ModalPlayerHeader

    '''<summary>
    '''MLVprojectMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVprojectMap As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWempty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWempty As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBemptyMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBemptyMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VIWmap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWmap As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''DVresourcesTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVresourcesTop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LNBmanageProjectResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBmanageProjectResources As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBaddUsersFromCommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBaddUsersFromCommunity As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBaddCustomUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBaddCustomUser As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBaddCustomUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBaddCustomUsers As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBaddActivityTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBaddActivityTop As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNsaveProjectMapTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNsaveProjectMapTop As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''HYPgoToProjectEditTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPgoToProjectEditTop As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPbackToResourceDashboardTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPbackToResourceDashboardTop As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPbackToManagerDashboardTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPbackToManagerDashboardTop As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPbackToProjectsTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPbackToProjectsTop As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LTprojectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTprojectName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBattachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBattachments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLmessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmessages As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''CTRLprojectInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLprojectInfo As Global.Comunita_OnLine.UC_ProjectDateInfo

    '''<summary>
    '''LNBshowResourcesColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBshowResourcesColumn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBhideResourcesColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBhideResourcesColumn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBshowDateColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBshowDateColumns As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBhideDateColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBhideDateColumns As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''DVpredecessorsCommand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpredecessorsCommand As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LNBshowPredecessorsColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBshowPredecessorsColumn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBhidePredecessorsColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBhidePredecessorsColumn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HYPprojectMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPprojectMap As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPprojectMapReorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPprojectMapReorder As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPprojectGantt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPprojectGantt As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPprojectMapBulkEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPprojectMapBulkEdit As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LBthDisplayOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBthDisplayOrder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBthName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBthName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBthStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBthStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBthDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBthDuration As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''THpredecessors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents THpredecessors As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''LBthPredecessors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBthPredecessors As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBthPredecessorsLegend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBthPredecessorsLegend As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBthStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBthStartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBthEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBthEndDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBthResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBthResources As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPTactivities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTactivities As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''CTRLinLineAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLinLineAdd As Global.Comunita_OnLine.UC_ActivityInLineAdd

    '''<summary>
    '''TDfooterToolBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TDfooterToolBar As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''DVtableCommands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVtableCommands As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LNBexpandNodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBexpandNodes As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBcompressNodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBcompressNodes As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBwideview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBwideview As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBnarrowview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBnarrowview As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBtoggleresources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBtoggleresources As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBrestoreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBrestoreview As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''CTRLlegend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLlegend As Global.Comunita_OnLine.UC_StatusLegend

    '''<summary>
    '''CTRLpredecessorsHelper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLpredecessorsHelper As Global.Comunita_OnLine.UC_PredecessorsHelper

    '''<summary>
    '''DVcommandsBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVcommandsBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DVresourcesBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVresourcesBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LNBmanageProjectResourcesBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBmanageProjectResourcesBottom As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBaddUsersFromCommunityBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBaddUsersFromCommunityBottom As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBaddCustomUserBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBaddCustomUserBottom As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBaddCustomUsersBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBaddCustomUsersBottom As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBaddActivityBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBaddActivityBottom As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNsaveProjectMapBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNsaveProjectMapBottom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''HYPgoToProjectEditBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPgoToProjectEditBottom As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPbackToResourceDashboardBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPbackToResourceDashboardBottom As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPbackToManagerDashboardBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPbackToManagerDashboardBottom As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPbackToProjectsBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPbackToProjectsBottom As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''DVselectUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVselectUsers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CLTRselectUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLTRselectUsers As Global.Comunita_OnLine.UC_SelectUsers

    '''<summary>
    '''DVaddExternalResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVaddExternalResources As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CTRLaddExternalResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLaddExternalResources As Global.Comunita_OnLine.UC_AddExternalResource

    '''<summary>
    '''DVprojectResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVprojectResources As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MLVmanageResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVmanageResources As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWmanageResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWmanageResources As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''CTRLmanageResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmanageResources As Global.Comunita_OnLine.UC_ManageProjectResources

    '''<summary>
    '''VIWvirtualDeleteResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWvirtualDeleteResource As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''CTRLconfirmRemoveResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLconfirmRemoveResource As Global.Comunita_OnLine.UC_ConfirmResourceToRemove

    '''<summary>
    '''DVactivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVactivity As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CTRLactivityEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLactivityEdit As Global.Comunita_OnLine.UC_ActivityEditor

    '''<summary>
    '''DVselectResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVselectResources As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HDNactivityRowNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDNactivityRowNumber As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''LBactivity_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivity_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBactivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactivity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLselectActivityResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLselectActivityResources As Global.Comunita_OnLine.UC_SelectResources

    '''<summary>
    '''BTNselectActivityResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNselectActivityResources As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LNBcloseSelectActivityResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBcloseSelectActivityResources As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''CTRLattachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLattachment As Global.Comunita_OnLine.UC_DialogProjectAttachments

    '''<summary>
    '''LTstatusContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTstatusContent As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTstatuslight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTstatuslight As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTfullColSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTfullColSpan As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTnocpmColSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTnocpmColSpan As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTdurationEstimatedRegex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTdurationEstimatedRegex As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTdurationRegex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTdurationRegex As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTpredecessorsCssClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTpredecessorsCssClass As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AjaxPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AjaxPortal)
        End Get
    End Property
End Class
