'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ResourceDashboard

    '''<summary>
    '''CTRLadvancedProgressBarHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLadvancedProgressBarHeader As Global.Comunita_OnLine.UC_AdvancedProgressBarHeader

    '''<summary>
    '''CTRLdialogHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLdialogHeader As Global.Comunita_OnLine.UC_TaskInfoHeader

    '''<summary>
    '''MLVprojectList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVprojectList As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWempty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWempty As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBemptyMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBemptyMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VIWcontent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWcontent As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''BTNsaveMyCompletenessTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNsaveMyCompletenessTop As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''HYPprojectListResourceTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPprojectListResourceTop As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPprojectListManagerTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPprojectListManagerTop As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''CTRLmessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmessages As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''CTRLtopControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLtopControls As Global.Comunita_OnLine.UC_DasboardListTopControl

    '''<summary>
    '''CTRLlistPlain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLlistPlain As Global.Comunita_OnLine.UC_TaskListPlain

    '''<summary>
    '''CTRLlistTree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLlistTree As Global.Comunita_OnLine.UC_TaskListTree

    '''<summary>
    '''CTRLlistMultipleTree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLlistMultipleTree As Global.Comunita_OnLine.UC_TaskListMultipleTree

    '''<summary>
    '''DVcommandsBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVcommandsBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BTNsaveMyCompletenessBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNsaveMyCompletenessBottom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''HYPprojectListResourceBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPprojectListResourceBottom As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPprojectListManagerBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPprojectListManagerBottom As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AjaxPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AjaxPortal)
        End Get
    End Property
End Class
