'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_FuzzyInputIntermediateValues

    '''<summary>
    '''DVdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTfuzzyInputDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTfuzzyInputDescription As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBfuzzyInputTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBfuzzyInputTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SLratingValuesFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SLratingValuesFrom As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''LBfuzzyInputTitleBetween control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBfuzzyInputTitleBetween As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SLratingValuesTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SLratingValuesTo As Global.System.Web.UI.HtmlControls.HtmlSelect
End Class
