'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_ConfirmResourceToRemove

    '''<summary>
    '''DVdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBdescriptionAssignedTasks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdescriptionAssignedTasks As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPTactions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTactions As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''DVcommands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVcommands As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BTNapplyRemoveResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNapplyRemoveResource As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNcancelRemoveResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNcancelRemoveResource As Global.System.Web.UI.WebControls.Button
End Class
