'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CommitteeSummary

    '''<summary>
    '''CTRLheader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLheader As Global.Comunita_OnLine.UC_CallHeader

    '''<summary>
    '''DVexport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVexport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LNBexportAllCommitteeSummaryToCsv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBexportAllCommitteeSummaryToCsv As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBexportAllCommitteeSummaryToXLS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBexportAllCommitteeSummaryToXLS As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBexportFilteredCommitteeSummaryToCsv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBexportFilteredCommitteeSummaryToCsv As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBexportFilteredCommitteeSummaryToXLS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBexportFilteredCommitteeSummaryToXLS As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBexportAllEvaluationsSummaryDataToCsv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBexportAllEvaluationsSummaryDataToCsv As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBexportAllEvaluationsSummaryData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBexportAllEvaluationsSummaryData As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBexportFullEvaluationsSummaryDataToCsv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBexportFullEvaluationsSummaryDataToCsv As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBexportFullEvaluationsSummaryDataToXml control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBexportFullEvaluationsSummaryDataToXml As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HYPlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPlist As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPmanage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPmanage As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPbackToSummaryIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPbackToSummaryIndex As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''CTRLdssMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLdssMessage As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''DVfilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVfilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBsearchEvaluationsFor_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsearchEvaluationsFor_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TXBusername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBusername As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNfindEvaluations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNfindEvaluations As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DVsubmitterType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVsubmitterType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBsubmitterType_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsubmitterType_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLsubmitterTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLsubmitterTypes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DVstatusfilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVstatusfilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBevaluationStatusFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBevaluationStatusFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RBLevaluationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBLevaluationStatus As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''MLVstatistics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVstatistics As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWempty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWempty As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBnocalls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBnocalls As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VIWnoItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWnoItems As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBnoEvaluations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBnoEvaluations As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VIWstatistics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWstatistics As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''DVpagerTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpagerTop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTpageTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTpageTop As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''PGgridTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PGgridTop As Global.Comunita_OnLine.UC_PagerControl

    '''<summary>
    '''HYPcloseComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPcloseComments As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LTevaluatorsSliderTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTevaluatorsSliderTop As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TRmultipleCommittees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRmultipleCommittees As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''HYPorderByEvaluationIndexUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByEvaluationIndexUp As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPorderByEvaluationIndexDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByEvaluationIndexDown As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LTsubmitterName_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsubmitterName_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''HYPorderByUserUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByUserUp As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPorderByUserDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByUserDown As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LTsubmitterType_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsubmitterType_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''HYPorderByTypeUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByTypeUp As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPorderByTypeDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByTypeDown As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LTsubmissionPoints_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsubmissionPoints_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''HYPorderByEvaluationPointsUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByEvaluationPointsUp As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPorderByEvaluationPointsDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByEvaluationPointsDown As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''DDLcommittees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLcommittees As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''THsubmitternumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents THsubmitternumber As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''HYPorderByEvaluationIndexUpSingle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByEvaluationIndexUpSingle As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPorderByEvaluationIndexDownSingle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByEvaluationIndexDownSingle As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''THsubmittername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents THsubmittername As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''LTsubmitterNameSingle_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsubmitterNameSingle_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''HYPorderByUserUpSingle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByUserUpSingle As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPorderByUserDownSingle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByUserDownSingle As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''THsubmittertype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents THsubmittertype As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''LTsubmitterTypeSingle_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsubmitterTypeSingle_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''HYPorderByTypeUpSingle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByTypeUpSingle As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPorderByTypeDownSingle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByTypeDownSingle As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''THpoints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents THpoints As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''LTsubmissionPointsSingle_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsubmissionPointsSingle_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''HYPorderByEvaluationPointsUpSingle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByEvaluationPointsUpSingle As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPorderByEvaluationPointsDownSingle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPorderByEvaluationPointsDownSingle As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''RPTevaluators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTevaluators As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''THevaluatorPlaceHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents THevaluatorPlaceHolder As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''RPTevaluations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTevaluations As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''LTevaluatorsSliderBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTevaluatorsSliderBottom As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DVpagerBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpagerBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTpageBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTpageBottom As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''PGgridBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PGgridBottom As Global.Comunita_OnLine.UC_PagerControl

    '''<summary>
    '''HDNdownloadTokenValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDNdownloadTokenValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AjaxPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AjaxPortal)
        End Get
    End Property
End Class
