(function(a,c){Type.registerNamespace("Telerik.Web.UI.Editor");
var b=Telerik.Web.UI.Editor;
b.FindReplaceEventArgs=function(d){this._find=d.find;
this._replace=d.replace;
this._backwards=d.backwards;
};
a.registerControlProperties(b.FindReplaceEventArgs,{find:"",replace:"",backwards:false});
b.FindReplaceEventArgs.registerClass("Telerik.Web.UI.Editor.FindReplaceEventArgs",Sys.EventArgs);
})($telerik.$);
(function(a,e){Type.registerNamespace("Telerik.Web.UI.Editor");
var c=Telerik.Web.UI.Editor;
var b=Function.createDelegate;
c.FindReplaceManager=function(f,h,g){this.editor=f;
this.ui=h;
this.highlighter=new c.HighlightCommand(f);
this.options=a.extend({localization:{}},g||{});
this.engine=$create(c.EditorFindReplaceEngine,{editor:f},null,null,null);
this._selectionChangeDelegate=b(this,this._selectionChangeHandler);
this.attachEventHandlers();
};
c.FindReplaceManager.prototype={toggle:function(){if(this.isVisible()){this.hide();
}else{this.show();
}},show:function(){var g=this.ui.get_element();
var f=this.ui.get_findInput();
var h=this.editor.get_toolAdapter();
if(h.isEditEnabled&&h.isEditEnabled()){h.toggleEdit();
}g.style.display="";
f.focus();
this.editor.add_selectionChange(this._selectionChangeDelegate);
},hide:function(){var g=this.ui.get_element();
var f=this.ui.get_findInput();
f.blur();
g.style.display="none";
this.highlighter.remove();
this.editor.remove_selectionChange(this._selectionChangeDelegate);
},isVisible:function(){var f=this.ui.get_element();
return(f.style.display!="none");
},attachEventHandlers:function(){var f=this.ui;
this._findDelegate=b(this,this._findHandler);
this._replaceDelegate=b(this,this._replaceHandler);
this._replaceAllDelegate=b(this,this._replaceAllHandler);
this._settingsDelegate=b(this,this._settingsHandler);
f.add_find(this._findDelegate);
f.add_replace(this._replaceDelegate);
f.add_all(this._replaceAllDelegate);
f.add_settings(this._settingsDelegate);
},detachEventHandlers:function(){var f=this.ui;
f.remove_find(this._findDelegate);
f.remove_replace(this._replaceDelegate);
f.remove_all(this._replaceAllDelegate);
f.remove_settings(this._settingsDelegate);
this.editor.remove_selectionChange(this._selectionChangeDelegate);
this._findDelegate=e;
this._replaceDelegate=e;
this._replaceAllDelegate=e;
this._settingsDelegate=e;
this._selectionChangeDelegate=e;
},dispose:function(){this.detachEventHandlers();
this.engine.dispose();
},_findHandler:function(h,f){var g=this._highlightResult(function(i){return i.find(f.get_find(),f.get_backwards());
});
this._scrollToHightlighted();
this.showMessage(g);
},_scrollToHightlighted:function(){var f=a(this.editor.get_contentArea()).find(".__reTextHighlight:last").get(0);
if(f&&f.scrollIntoView){f.scrollIntoView();
}},_replaceHandler:function(h,f){var g=this._highlightResult(function(i){return i.replace(f.get_find(),f.get_replace(),f.get_backwards());
});
this._scrollToHightlighted();
this.showMessage(g);
},_replaceAllHandler:function(h,f){var g=this._highlightResult(function(i){return i.replaceAll(f.get_find(),f.get_replace(),f.get_backwards());
});
this.showReplaceAllMessage(g);
},_highlightResult:function(f){this.highlighter.remove();
var g=f(this.engine);
this.highlighter.highlight();
return g;
},_settingsHandler:function(i,f){var g=this.editor;
var h=this.engine;
g.showDialog("FindReplaceSettings",{},function(m,j){var l=j.value;
h.set_caseSensitive(l.matchCase);
var k=c.FindReplaceMode.Find;
if(l.mode=="replace"){k=c.FindReplaceMode.FindAndReplace;
}i.set_mode(k);
});
},_selectionChangeHandler:function(g,f){if(this.isVisible()){this.highlighter.remove();
}},showReplaceAllMessage:function(f){if(f.message){d(String.format(this._localize(f.message),f.replaceCount));
}else{this.showMessage(f);
}},showMessage:function(f){if(f){f=this._localize(f);
d(f);
}},_localize:function(f){var g=this.options.localization;
return g["find_"+f.toLowerCase()]||f;
}};
function d(f){if(f){window.alert(f);
}}})($telerik.$);
(function(a,e){Type.registerNamespace("Telerik.Web.UI.Editor");
var b=Telerik.Web.UI;
var d=b.Editor;
var c=Function.createDelegate;
d.FindReplaceMobile=function(f){d.FindReplaceMobile.initializeBase(this,[f]);
this._mode=d.FindReplaceMode.Find;
};
d.FindReplaceMobile.prototype={initialize:function(){this.attachEventHandlers();
},get_mode:function(){return this._mode;
},set_mode:function(i){var f=this._mode=i;
var h=this.get_rows();
var g=(f==d.FindReplaceMode.Find)?"none":"";
h[1].style.display=g;
},get_rows:function(){return a(this.get_element()).find(".t-hbox");
},attachEventHandlers:function(){this._findPreviousDelegate=c(this,this._findPreviousHandler);
this._findNextDelegate=c(this,this._findNextHandler);
this._settingsDelegate=c(this,this._settingsHandler);
this._replaceDelegate=c(this,this._replaceHandler);
this._replaceAllDelegate=c(this,this._replaceAllHandler);
this.get_findPreviousBtn().add_clicked(this._findPreviousDelegate);
this.get_findNextBtn().add_clicked(this._findNextDelegate);
this.get_settingsBtn().add_clicked(this._settingsDelegate);
$telerik.onEvent(this.get_replaceLink(),"click",this._replaceDelegate);
$telerik.onEvent(this.get_replaceAllLink(),"click",this._replaceAllDelegate);
},detachEventHandlers:function(){this.get_findPreviousBtn().remove_clicked(this._findPreviousDelegate);
this.get_findNextBtn().remove_clicked(this._findNextDelegate);
this.get_settingsBtn().remove_clicked(this._settingsDelegate);
$telerik.offEvent(this.get_replaceLink(),"click",this._replaceDelegate);
$telerik.offEvent(this.get_replaceAllLink(),"click",this._replaceAllDelegate);
this._findPreviousDelegate=e;
this._findNextDelegate=e;
this._settingsDelegate=e;
this._replaceDelegate=e;
this._replaceAllDelegate=e;
},dispose:function(){this.detachEventHandlers();
d.FindReplaceMobile.callBaseMethod(this,"dispose");
},_findPreviousHandler:function(){var f=this._createEventArgs(true);
this.raiseEvent("find",f);
},_findNextHandler:function(){var f=this._createEventArgs(false);
this.raiseEvent("find",f);
},_settingsHandler:function(){this.raiseEvent("settings");
},_replaceHandler:function(){var f=this._createEventArgs(false);
this.raiseEvent("replace",f);
},_replaceAllHandler:function(){var f=this._createEventArgs(false);
this.raiseEvent("all",f);
},_createEventArgs:function(f){var g=(this.get_mode()==d.FindReplaceMode.FindAndReplace);
var h={find:this.get_findInput().value,replace:g?this.get_replaceInput().value:"",backwards:f};
return new d.FindReplaceEventArgs(h);
}};
a.registerControlProperties(d.FindReplaceMobile,{findInput:null,replaceInput:null,findPreviousBtn:null,findNextBtn:null,settingsBtn:null,replaceLink:null,replaceAllLink:null});
a.registerControlEvents(d.FindReplaceMobile,["find","replace","all","settings"]);
d.FindReplaceMobile.registerClass("Telerik.Web.UI.Editor.FindReplaceMobile",b.RadWebControl);
})($telerik.$);
(function(a,b){Type.registerNamespace("Telerik.Web.UI.Editor");
a.registerEnum(Telerik.Web.UI.Editor,"FindReplaceMode",{Find:0,FindAndReplace:1});
})($telerik.$);
