'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ListAuthenticationProvider

    '''<summary>
    '''DVmenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVmenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HYPaddProvider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPaddProvider As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''MLVprofiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVprofiles As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWlist As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''RPTproviders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTproviders As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''DVpageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpageSize As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBpagesize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBpagesize As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLpage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLpage As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PGgrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PGgrid As Global.Comunita_OnLine.UC_PagerControl

    '''<summary>
    '''DVproviderInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVproviderInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBproviderDisplayInfoDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBproviderDisplayInfoDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLinfoProvider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLinfoProvider As Global.Comunita_OnLine.UC_InfoProvider

    '''<summary>
    '''BTNcloseProviderDisplayInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNcloseProviderDisplayInfo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AdminPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AdminPortal)
        End Get
    End Property
End Class
