'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PreviewCall
    
    '''<summary>
    '''CTRLheader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLheader As Global.Comunita_OnLine.UC_CallHeader
    
    '''<summary>
    '''CTRLmodalPlayerHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmodalPlayerHeader As Global.Comunita_OnLine.UC_ModalPlayerHeader
    
    '''<summary>
    '''UC_TextAreaEditorHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_TextAreaEditorHeader As Global.Comunita_OnLine.UC_TextAreaEditorHeader
    
    '''<summary>
    '''MLVpreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVpreview As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''VIWempty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWempty As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''LBpreviewMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBpreviewMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''VIWcall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWcall As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''HYPlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPlist As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''BTNvirtualDeleteSubmission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNvirtualDeleteSubmission As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BTNsaveSubmissionTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNsaveSubmissionTop As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BTNsubmitSubmissionTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNsubmitSubmissionTop As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DVsubmittersLoader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVsubmittersLoader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LBsubmitterSelector_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsubmitterSelector_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DDLsubmitters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLsubmitters As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''FStagContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FStagContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LBcallTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcallTags As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RPTtag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTtag As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''LBcallDescriptionTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcallDescriptionTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LTcallDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcallDescription As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LBtimeValidity_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtimeValidity_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBstartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBstartDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBendDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBendDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBwinnerinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBwinnerinfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FLDpartecipants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FLDpartecipants As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LTsubmitterTypesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsubmitterTypesTitle As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LTpreviewSubmittersMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTpreviewSubmittersMessage As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''RBLsubmitters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBLsubmitters As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RPTattachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTattachments As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''RPTsections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTsections As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''RPTrequiredFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTrequiredFiles As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''DVbottomBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVbottomBox As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''BTNsaveSubmissionBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNsaveSubmissionBottom As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LTsaveBottomExplanation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsaveBottomExplanation As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''BTNsubmitSubmissionBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNsubmitSubmissionBottom As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LTsaveAndSubmitBottomExplanation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsaveAndSubmitBottomExplanation As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.ExternalService
        Get
            Return CType(MyBase.Master,Comunita_OnLine.ExternalService)
        End Get
    End Property
End Class
