'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_GlossaryImportTerms
    
    '''<summary>
    '''LBcommunityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcommunityName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBmapTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBmapTo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBMappedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBMappedTo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBChooseToCommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBChooseToCommunity As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LTSelectedCommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTSelectedCommunity As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LTControlId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTControlId As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''SWHcommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SWHcommunity As Global.Comunita_OnLine.UC_Switch
    
    '''<summary>
    '''RPTGlossaries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTGlossaries As Global.System.Web.UI.WebControls.Repeater
End Class
