'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_GlossaryShareState
    
    '''<summary>
    '''MLVglossaryShare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVglossaryShare As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''VIWglossarySharePending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWglossarySharePending As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''LTsharedFrom_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsharedFrom_t As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LTcommunityFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcommunityFrom As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LTshareState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTshareState As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LBsharedStatus_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsharedStatus_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LTshareState2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTshareState2 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''PNLRefuse1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PNLRefuse1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LBallowGlossarySharing_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBallowGlossarySharing_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LNBshareAccept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBshareAccept As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LBorRefuseIt_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBorRefuseIt_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LNBshareRefuse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBshareRefuse As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LTpermission_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTpermission_t As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''CBXaddTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBXaddTerm As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''LBaddTerm_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBaddTerm_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CBXdeleteTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBXdeleteTerm As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''LBdeleteTerm_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdeleteTerm_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CBXeditTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBXeditTerm As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''LBeditTerm_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBeditTerm_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LTglossaryDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTglossaryDescription As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''VIWglossaryShareEnabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWglossaryShareEnabled As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''LTsharedFrom2_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsharedFrom2_t As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LTcommunityFrom2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcommunityFrom2 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LTshareState3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTshareState3 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LBsharedStatus2_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsharedStatus2_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LTshareState4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTshareState4 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LTpermission2_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTpermission2_t As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''CBXaddTerm2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBXaddTerm2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''LBaddTerm2_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBaddTerm2_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CBXdeleteTerm2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBXdeleteTerm2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''LBdeleteTerm2_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdeleteTerm2_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CBXeditTerm2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBXeditTerm2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''LBeditTerm2_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBeditTerm2_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LTglossaryDescription2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTglossaryDescription2 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LBvisibiltyStatus2_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBvisibiltyStatus2_t As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SWHshareEnabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SWHshareEnabled As Global.Comunita_OnLine.UC_Switch
    
    '''<summary>
    '''PNLRefuse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PNLRefuse As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LTpermanentDiscard2_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTpermanentDiscard2_t As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LNBrefuse2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBrefuse2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''VIWglossaryShareRefused control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWglossaryShareRefused As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''VIWglossaryShareEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWglossaryShareEmpty As Global.System.Web.UI.WebControls.View
End Class
