'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_HelpEpRole

    '''<summary>
    '''IMGhelpRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IMGhelpRole As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LbPermissionTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LbPermissionTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBpartecipantTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBpartecipantTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBstatviewerTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBstatviewerTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''THeval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents THeval As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''LBevaluatorTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBevaluatorTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBmanagerTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBmanagerTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPpermission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPpermission As Global.System.Web.UI.WebControls.Repeater
End Class
