'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_HelpVisibility

    '''<summary>
    '''LBvisibilityHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBvisibilityHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''IMGswitchOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IMGswitchOn As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LBswitchOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBswitchOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''IMGswitchOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IMGswitchOff As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LBswitchOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBswitchOff As Global.System.Web.UI.WebControls.Label
End Class
