'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_SelectPathUsersForMessageService

    '''<summary>
    '''LBselectUsersFrom_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBselectUsersFrom_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLselectFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLselectFrom As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBselectMessages_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBselectMessages_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LNBselectMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBselectMessages As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LBselectMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBselectMessages As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBsearchUserByFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsearchUserByFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLsearchUserBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLsearchUserBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXBsearchBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBsearchBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBcommunityAgencyFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcommunityAgencyFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLcommunityAgencies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLcommunityAgencies As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''MLVfilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVfilters As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWempty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWempty As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''VIWparticipantFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWparticipantFilters As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBsubmissionStatusFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsubmissionStatusFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLsubmissionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLsubmissionStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBsubmissionTypeFilter_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsubmissionTypeFilter_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLsubmitterTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLsubmitterTypes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DVletters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVletters As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CTRLalphabetSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLalphabetSelector As Global.Comunita_OnLine.UC_AlphabetSelector

    '''<summary>
    '''BTNapplyFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNapplyFilters As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RPTitems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTitems As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''TBfooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBfooter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TDfooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TDfooter As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''RPTlegend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTlegend As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''PGgrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PGgrid As Global.Comunita_OnLine.UC_PagerControl

    '''<summary>
    '''DVdialogMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdialogMessages As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CTRLselectMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLselectMessages As Global.Comunita_OnLine.UC_SelectMessage

    '''<summary>
    '''BTNcloseMessageSelectorWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNcloseMessageSelectorWindow As Global.System.Web.UI.WebControls.Button
End Class
