'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class UC_FileDetail

    '''<summary>
    '''MLVdetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVdetails As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWitem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWitem As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBcommunity_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcommunity_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBcommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcommunity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBpath_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBpath_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBpath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBpath As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBname_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBname_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBcreatedOn_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcreatedOn_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBcreatedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcreatedOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TRdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRdescription As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LBdescription_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdescription_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TRtype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRtype As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LBtype_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtype_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBtype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtype As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TRdownloaded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRdownloaded As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LBdownloaded_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdownloaded_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBdownloaded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdownloaded As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBvisibleTo_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBvisibleTo_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBvisibleTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBvisibleTo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TRallow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRallow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LBallow_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBallow_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBallow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBallow As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DVallowRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVallowRoles As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBallowRoles_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBallowRoles_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBallowRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBallowRoles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DVallowPersons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVallowPersons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBallowPersons_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBallowPersons_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBallowPersons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBallowPersons As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TRdeny control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRdeny As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LBdeny_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdeny_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBdeny control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdeny As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DVdenyRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdenyRoles As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBdenyRoles_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdenyRoles_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBdenyRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdenyRoles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DVdenyPersons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdenyPersons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBdenyPersons_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdenyPersons_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBdenyPersons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdenyPersons As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VIWerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWerror As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBitemNotFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBitemNotFound As Global.System.Web.UI.WebControls.Label
End Class
