(function(b,a){a(["./kendo.dom","./kendo.touch","./kendo.draganddrop","./kendo.columnsorter","./kendo.datetimepicker","./kendo.editable"],b);
})(function(){(function(a){var j=window.kendo;
var k=j.dom;
var l=k.element;
var m=k.text;
var c=j.support.browser;
var q=j.support.mobileOS;
var u=j.ui;
var v=u.Widget;
var g=a.extend;
var p=a.map;
var i=a.isFunction;
var n=j.keys;
var t={title:"Title",start:"Start Time",end:"End Time",percentComplete:"% Done",parentId:"Predecessor ID",id:"ID",orderId:"Order ID"};
var s="string";
var r=".kendoGanttList";
var d="click";
var f=".";
var o={wrapper:"k-treelist k-grid k-widget",header:"k-header",alt:"k-alt",editCell:"k-edit-cell",group:"k-treelist-group",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",gridContentWrap:"k-grid-content",selected:"k-state-selected",icon:"k-icon",iconCollapse:"k-i-collapse",iconExpand:"k-i-expand",iconHidden:"k-i-none",iconPlaceHolder:"k-icon k-i-none",input:"k-input",dropPositions:"k-insert-top k-insert-bottom k-add k-insert-middle",dropTop:"k-insert-top",dropBottom:"k-insert-bottom",dropAdd:"k-add",dropMiddle:"k-insert-middle",dropDenied:"k-denied",dragStatus:"k-drag-status",dragClue:"k-drag-clue",dragClueText:"k-clue-text"};
function e(z){var A=[];
var w=z.className;
for(var x=0,y=z.level;
x<y;
x++){A.push(l("span",{className:w}));
}return A;
}function b(){var w=j._activeElement();
if(w.nodeName.toLowerCase()!=="body"){a(w).blur();
}}var h=u.GanttList=v.extend({init:function(w,x){v.fn.init.call(this,w,x);
if(this.options.columns.length===0){this.options.columns.push("title");
}this.dataSource=this.options.dataSource;
this._columns();
this._layout();
this._domTrees();
this._header();
this._sortable();
this._editable();
this._selectable();
this._draggable();
this._attachEvents();
this._adjustHeight();
},_adjustHeight:function(){this.content.height(this.element.height()-this.header.parent().outerHeight());
},destroy:function(){v.fn.destroy.call(this);
if(this._reorderDraggable){this._reorderDraggable.destroy();
}if(this._tableDropArea){this._tableDropArea.destroy();
}if(this._contentDropArea){this._contentDropArea.destroy();
}if(this.touch){this.touch.destroy();
}this.content.off(r);
this.header=null;
this.content=null;
this.levels=null;
j.destroy(this.element);
},options:{name:"GanttList",selectable:true,editable:true},_attachEvents:function(){var x=this;
var w=h.styles;
x.content.on(d+r,"td > span."+w.icon+":not(."+w.iconHidden+")",function(y){var z=a(this);
var A=x._modelFromElement(z);
A.set("expanded",!A.get("expanded"));
y.stopPropagation();
});
},_domTrees:function(){this.headerTree=new k.Tree(this.header[0]);
this.contentTree=new k.Tree(this.content[0]);
},_columns:function(){var x=this.options.columns;
var w;
var y=function(){this.field="";
this.title="";
this.editable=false;
this.sortable=false;
};
this.columns=p(x,function(z){z=typeof z==="string"?{field:z,title:t[z]}:z;
return g(new y(),z);
});
},_layout:function(){var w=this.element;
var x=h.styles;
w.addClass(x.wrapper).append("<div class='"+x.gridHeader+"'><div class='"+x.gridHeaderWrap+"'></div></div>").append("<div class='"+x.gridContentWrap+"'></div>");
this.header=w.find(f+x.gridHeaderWrap);
this.content=w.find(f+x.gridContent);
},_header:function(){var x=this.headerTree;
var w;
var z;
var y;
w=l("colgroup",null,this._cols());
z=l("thead",{role:"rowgroup"},[l("tr",{role:"row"},this._ths())]);
y=l("table",{style:{"min-width":this.options.listWidth+"px"},role:"grid"},[w,z]);
x.render([y]);
},_render:function(y){var w;
var z;
var x;
this.levels=[{field:null,value:0}];
w=l("colgroup",null,this._cols());
z=l("tbody",{role:"rowgroup"},this._trs(y));
x=l("table",{style:{"min-width":this.options.listWidth+"px"},tabIndex:0,role:"treegrid"},[w,z]);
this.contentTree.render([x]);
this.trigger("render");
},_ths:function(){var y=this.columns;
var x;
var w;
var B=[];
for(var z=0,A=y.length;
z<A;
z++){x=y[z];
w={"data-field":x.field,"data-title":x.title,className:h.styles.header,role:"columnheader"};
B.push(l("th",w,[m(x.title)]));
}return B;
},_cols:function(){var y=this.columns;
var x;
var B;
var C;
var w=[];
for(var z=0,A=y.length;
z<A;
z++){x=y[z];
C=x.width;
if(C&&parseInt(C,10)!==0){B={style:{width:typeof C===s?C:C+"px"}};
}else{B=null;
}w.push(l("col",B,[]));
}return w;
},_trs:function(E){var D;
var C=[];
var w;
var x=[];
var A;
var B=h.styles;
for(var y=0,z=E.length;
y<z;
y++){D=E[y];
A=this._levels({idx:D.parentId,id:D.id,summary:D.summary});
w={"data-uid":D.uid,"data-level":A,role:"row"};
if(D.summary){w["aria-expanded"]=D.expanded;
}if(y%2!==0){x.push(B.alt);
}if(D.summary){x.push(B.group);
}if(x.length){w.className=x.join(" ");
}C.push(this._tds({task:D,attr:w,level:A}));
x=[];
}return C;
},_tds:function(B){var w=[];
var y=this.columns;
var x;
for(var z=0,A=y.length;
z<A;
z++){x=y[z];
w.push(this._td({task:B.task,column:x,level:B.level}));
}return l("tr",B.attr,w);
},_td:function(B){var w=[];
var C=this.options.resourcesField;
var A=h.styles;
var D=B.task;
var x=B.column;
var E=D.get(x.field)||[];
var y;
if(x.field==C){y=[];
for(var z=0;
z<E.length;
z++){y.push(j.format("{0} [{1}]",E[z].get("name"),E[z].get("formatedValue")));
}y=y.join(", ");
}else{y=x.format?j.format(x.format,E):E;
}if(x.field==="title"){w=e({level:B.level,className:A.iconPlaceHolder});
w.push(l("span",{className:A.icon+" "+(D.summary?(D.expanded?A.iconCollapse:A.iconExpand):A.iconHidden)}));
}w.push(l("span",null,[m(y)]));
return l("td",{role:"gridcell"},w);
},_levels:function(C){var B=this.levels;
var A;
var D=C.summary;
var y=C.idx;
var x=C.id;
for(var w=0,z=B.length;
w<z;
w++){A=B[w];
if(A.field==y){if(D){B.push({field:x,value:A.value+1});
}return A.value;
}}},_sortable:function(){var C=this.options.resourcesField;
var z=this.columns;
var y;
var D;
var x=this.header.find("th");
var w;
for(var A=0,B=x.length;
A<B;
A++){y=z[A];
if(y.sortable&&y.field!==C){w=x.eq(A);
D=w.data("kendoColumnSorter");
if(D){D.destroy();
}w.attr("data-"+j.ns+"field",y.field).kendoColumnSorter({dataSource:this.dataSource});
}}x=null;
},_selectable:function(){var x=this;
var w=this.options.selectable;
if(w){this.content.on(d+r,"tr",function(y){var z=a(this);
if(!y.ctrlKey){x.select(z);
}else{x.clearSelection();
}});
}},select:function(y){var w=this.content.find(y);
var x=h.styles.selected;
if(w.length){w.siblings(f+x).removeClass(x).attr("aria-selected",false).end().addClass(x).attr("aria-selected",true);
this.trigger("change");
return;
}return this.content.find(f+x);
},clearSelection:function(){var w=this.select();
if(w.length){w.removeClass(h.styles.selected);
this.trigger("change");
}},_setDataSource:function(w){this.dataSource=w;
},_editable:function(){var A=this;
var y=h.styles;
var x="span."+y.icon+":not("+y.iconHidden+")";
var w=function(){if(A.editable&&A.editable.end()){A._closeCell();
}};
var z=function(C){var B=a(C.currentTarget);
if(!B.hasClass(y.editCell)){b();
}};
if(!this.options.editable){return;
}this._startEditHandler=function(C){var D=C.currentTarget?a(C.currentTarget):C;
var B=A._columnFromElement(D);
if(A.editable){return;
}if(B.editable){A._editCell({cell:D,column:B});
}};
A.content.on("focusin"+r,function(){clearTimeout(A.timer);
A.timer=null;
}).on("focusout"+r,function(){A.timer=setTimeout(w,1);
}).on("keydown"+r,function(C){var D=C.keyCode;
var B;
var E;
switch(D){case n.ENTER:b();
w();
break;
case n.ESC:if(A.editable){B=A._editableContainer;
E=A._modelFromElement(B);
if(!A.trigger("cancel",{model:E,cell:B})){A._closeCell(true);
}}break;
}});
if(!q){A.content.on("mousedown"+r,"td",function(B){z(B);
}).on("dblclick"+r,"td",function(B){if(!a(B.target).is(x)){A._startEditHandler(B);
}});
}else{A.touch=A.content.kendoTouch({filter:"td",touchstart:function(B){z(B.touch);
},doubletap:function(B){if(!a(B.touch.initialTouch).is(x)){A._startEditHandler(B.touch);
}}}).data("kendoTouch");
}},_editCell:function(G){var H=this.options.resourcesField;
var D=h.styles;
var y=G.cell;
var z=G.column;
var E=this._modelFromElement(y);
var F=this.dataSource._createNewModel(E.toJSON());
var C=F.fields[z.field]||F[z.field];
var I=C.validation;
var A=j.attr("type");
var x=j.attr("bind");
var w={name:z.field,required:C.validation?C.validation.required===true:false};
var B;
if(z.field===H){z.editor(y,F);
return;
}this._editableContent=y.children().detach();
this._editableContainer=y;
y.data("modelCopy",F);
if((C.type==="date"||a.type(C)==="date")&&/H|m|s|F|g|u/.test(z.format)){if(z.field==="start"){delete C.validation.dateCompare;
}w[x]="value:"+z.field;
w[A]="date";
B=function(J,K){a('<input type="text"/>').attr(w).appendTo(J).kendoDateTimePicker({format:K.format});
};
}this.editable=y.addClass(D.editCell).kendoEditable({fields:{field:z.field,format:z.format,editor:z.editor||B},model:F,clearContainer:false}).data("kendoEditable");
if(I&&I.dateCompare&&i(I.dateCompare)&&I.message){a("<span "+j.attr("for")+'="'+z.field+'" class="k-invalid-msg"/>').hide().appendTo(y);
y.find("[name="+z.field+"]").attr(j.attr("dateCompare-msg"),I.message);
}if(this.trigger("edit",{model:E,cell:y})){this._closeCell(true);
}},_closeCell:function(w){var B=h.styles;
var x=this._editableContainer;
var C=this._modelFromElement(x);
var y=this._columnFromElement(x);
var A=y.field;
var z=x.data("modelCopy");
var D={};
D[A]=z.get(A);
x.empty().removeData("modelCopy").removeClass(B.editCell).append(this._editableContent);
this.editable.destroy();
this.editable=null;
this._editableContainer=null;
this._editableContent=null;
if(!w){if(A==="start"){D.end=new Date(D.start.getTime()+C.duration());
}this.trigger("update",{task:C,updateInfo:D});
}},_draggable:function(){var H=this;
var B=null;
var C=true;
var D;
var E=h.styles;
var F="tr["+j.attr("level")+" = 0]:last";
var w={};
var y=function(){B=null;
D=null;
C=true;
w={};
};
var x=function(J){var I=J;
while(I){if(B.get("id")===I.get("id")){C=false;
break;
}I=H.dataSource.taskParent(I);
}};
var A=function(){var I=a(D).height();
var J=j.getOffset(D).top;
g(D,{beforeLimit:J+I*0.25,afterLimit:J+I*0.75});
};
var z=function(K){var M=K.location;
var I=E.dropAdd;
var J="add";
var L=parseInt(D.attr(j.attr("level")),10);
var N;
if(M<=D.beforeLimit){N=D.prev();
I=E.dropTop;
J="insert-before";
}else{if(M>=D.afterLimit){N=D.next();
I=E.dropBottom;
J="insert-after";
}}if(N&&parseInt(N.attr(j.attr("level")),10)===L){I=E.dropMiddle;
}w.className=I;
w.command=J;
};
var G=function(){return H._reorderDraggable.hint.children(f+E.dragStatus).removeClass(E.dropPositions);
};
if(!this.options.editable){return;
}this._reorderDraggable=this.content.kendoDraggable({distance:10,holdToDrag:q,group:"listGroup",filter:"tr[data-uid]",ignore:f+E.input,hint:function(I){return a('<div class="'+E.header+" "+E.dragClue+'"/>').css({width:300,paddingLeft:I.css("paddingLeft"),paddingRight:I.css("paddingRight"),lineHeight:I.height()+"px",paddingTop:I.css("paddingTop"),paddingBottom:I.css("paddingBottom")}).append('<span class="'+E.icon+" "+E.dragStatus+'" /><span class="'+E.dragClueText+'"/>');
},cursorOffset:{top:-20,left:0},container:this.content,dragstart:function(I){if(H.editable){I.preventDefault();
}B=H._modelFromElement(I.currentTarget);
this.hint.children(f+E.dragClueText).text(B.get("title"));
},drag:function(I){if(C){z(I.y);
G().addClass(w.className);
}},dragend:function(I){y();
},dragcancel:function(I){y();
}}).data("kendoDraggable");
this._tableDropArea=this.content.kendoDropTargetArea({distance:0,group:"listGroup",filter:"tr[data-uid]",dragenter:function(I){D=I.dropTarget;
x(H._modelFromElement(D));
A();
G().toggleClass(E.dropDenied,!C);
},dragleave:function(I){C=true;
G();
},drop:function(I){var K=H._modelFromElement(D);
var J=K.orderId;
var L={parentId:K.parentId};
if(C){switch(w.command){case"add":L.parentId=K.id;
break;
case"insert-before":if(K.parentId===B.parentId&&K.orderId>B.orderId){L.orderId=J-1;
}else{L.orderId=J;
}break;
case"insert-after":if(K.parentId===B.parentId&&K.orderId>B.orderId){L.orderId=J;
}else{L.orderId=J+1;
}break;
}H.trigger("update",{task:B,updateInfo:L});
}}}).data("kendoDropTargetArea");
this._contentDropArea=this.element.kendoDropTargetArea({distance:0,group:"listGroup",filter:f+E.gridContent,drop:function(I){var K=H._modelFromElement(H.content.find(F));
var J=K.orderId;
var L={parentId:null,orderId:B.parentId!==null?J+1:J};
H.trigger("update",{task:B,updateInfo:L});
}}).data("kendoDropTargetArea");
},_modelFromElement:function(w){var y=w.closest("tr");
var x=this.dataSource.getByUid(y.attr(j.attr("uid")));
return x;
},_columnFromElement:function(w){var y=w.closest("td");
var z=y.parent();
var x=z.children().index(y);
return this.columns[x];
}});
g(true,u.GanttList,{styles:o});
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
