(function(b,a){a(["./kendo.dom","./kendo.touch","./kendo.draganddrop"],b);
})(function(){(function(a){var J=kendo.ui.Widget;
var o=kendo.dom.element;
var p=kendo.dom.text;
var m=a.isPlainObject;
var i=a.extend;
var z=a.proxy;
var c=kendo.support.browser;
var s=kendo.support.mobileOS;
var n=false;
var r=kendo.keys;
var A=kendo.data.Query;
var x=".kendoGanttTimeline";
var d="click";
var f="dblclick";
var w="mousemove";
var u="mouseenter";
var v="mouseleave";
var q="keydown";
var h=".";
var E=kendo.template("#=kendo.toString(start, 't')#");
var e=kendo.template("#=kendo.toString(start, 'ddd M/dd')#");
var I=kendo.template("#=kendo.toString(start, 'ddd M/dd')# - #=kendo.toString(kendo.date.addDays(end, -1), 'ddd M/dd')#");
var t=kendo.template("#=kendo.toString(start, 'MMM')#");
var K=kendo.template("#=kendo.toString(start, 'yyyy')#");
var B=kendo.template('<div class="#=styles.marquee#"><div class="#=styles.marqueeColor#"></div></div>');
var C=kendo.template('<div style="z-index: 100002;" class="#=styles.tooltipWrapper#"><div class="#=styles.tooltipContent#"><div>#=messages.start#: #=kendo.toString(start, format)#</div><div>#=messages.end#: #=kendo.toString(end, format)#</div></div></div>');
var y=kendo.template('<div style="z-index: 100002;" class="#=styles.tooltipWrapper#" ><div class="#=styles.tooltipContent#">#=text#%</div><div class="#=styles.tooltipCallout#" style="left:13px;"></div></div>');
var D=kendo.template('<div class="#=styles.taskDetails#"><strong>#=task.title#</strong><div class="#=styles.taskDetailsPercent#">#=kendo.toString(task.percentComplete, "p0")#</div><ul class="#=styles.reset#"><li>#=messages.start#: #=kendo.toString(task.start, "h:mm tt ddd, MMM d")#</li><li>#=messages.end#: #=kendo.toString(task.end, "h:mm tt ddd, MMM d")#</li></ul></div>');
var g={day:{type:"kendo.ui.GanttDayView"},week:{type:"kendo.ui.GanttWeekView"},month:{type:"kendo.ui.GanttMonthView"},year:{type:"kendo.ui.GanttYearView"}};
function G(L){delete L.name;
delete L.prefix;
delete L.views;
return L;
}function l(M){var N=[];
var L=M.workWeekStart;
N.push(L);
while(M.workWeekEnd!=L){if(L>6){L-=7;
}else{L++;
}N.push(L);
}return N;
}function b(){var L=kendo._activeElement();
if(L.nodeName.toLowerCase()!=="body"){a(L).blur();
}}var H={alt:"k-alt",reset:"k-reset",nonWorking:"k-nonwork-hour",header:"k-header",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",tasksWrapper:"k-gantt-tables",rowsTable:"k-gantt-rows",columnsTable:"k-gantt-columns",tasksTable:"k-gantt-tasks",dependenciesWrapper:"k-gantt-dependencies",resource:"k-resource",resourceAlt:"k-resource k-alt",task:"k-task",taskSingle:"k-task-single",taskMilestone:"k-task-milestone",taskSummary:"k-task-summary",taskWrap:"k-task-wrap",taskMilestoneWrap:"k-milestone-wrap",resourcesWrap:"k-resources-wrap",taskDot:"k-task-dot",taskDotStart:"k-task-start",taskDotEnd:"k-task-end",taskDragHandle:"k-task-draghandle",taskContent:"k-task-content",taskTemplate:"k-task-template",taskActions:"k-task-actions",taskDelete:"k-task-delete",taskComplete:"k-task-complete",taskDetails:"k-task-details",taskDetailsPercent:"k-task-pct",link:"k-link",icon:"k-icon",iconDelete:"k-si-close",taskResizeHandle:"k-resize-handle",taskResizeHandleWest:"k-resize-w",taskResizeHandleEast:"k-resize-e",taskSummaryProgress:"k-task-summary-progress",taskSummaryComplete:"k-task-summary-complete",line:"k-line",lineHorizontal:"k-line-h",lineVertical:"k-line-v",arrowWest:"k-arrow-w",arrowEast:"k-arrow-e",dragHint:"k-drag-hint",dependencyHint:"k-dependency-hint",tooltipWrapper:"k-widget k-tooltip k-popup k-group k-reset",tooltipContent:"k-tooltip-content",tooltipCallout:"k-callout k-callout-s",callout:"k-callout",marquee:"k-marquee k-gantt-marquee",marqueeColor:"k-marquee-color"};
var k=kendo.ui.GanttView=J.extend({init:function(L,M){J.fn.init.call(this,L,M);
this.title=this.options.title||this.options.name;
this.header=this.element.find(h+k.styles.gridHeader);
this.content=this.element.find(h+k.styles.gridContent);
this.contentWidth=this.content.width();
this._workDays=l(this.options);
this._headerTree=M.headerTree;
this._taskTree=M.taskTree;
this._dependencyTree=M.dependencyTree;
this._taskCoordinates={};
this._currentTime();
},destroy:function(){J.fn.destroy.call(this);
clearTimeout(this._tooltipTimeout);
this.headerRow=null;
this.header=null;
this.content=null;
this._dragHint=null;
this._resizeHint=null;
this._resizeTooltip=null;
this._taskTooltip=null;
this._percentCompleteResizeTooltip=null;
this._headerTree=null;
this._taskTree=null;
this._dependencyTree=null;
},options:{showWorkHours:false,showWorkDays:false,workDayStart:new Date(1980,1,1,8,0,0),workDayEnd:new Date(1980,1,1,17,0,0),workWeekStart:1,workWeekEnd:5,hourSpan:1,slotSize:100,currentTimeMarker:{updateInterval:10000}},renderLayout:function(){this._slots=this._createSlots();
this._tableWidth=this._calculateTableWidth();
this.createLayout(this._layout());
this._slotDimensions();
this._adjustHeight();
this.content.find(h+k.styles.dependenciesWrapper).width(this._tableWidth);
},_adjustHeight:function(){this.content.height(this.element.height()-this.header.outerHeight());
},createLayout:function(O){var N=this._headers(O);
var L=this._colgroup();
var Q=this._headerTree;
var M=o("thead",null,N);
var P=o("table",{style:{width:this._tableWidth+"px"}},[L,M]);
Q.render([P]);
this.headerRow=this.header.find("table:first tr").last();
},_slotDimensions:function(){var M=this.headerRow[0].children;
var Q=this._timeSlots();
var P;
var L;
for(var N=0,O=M.length;
N<O;
N++){L=M[N];
P=Q[N];
P.offsetLeft=L.offsetLeft;
P.offsetWidth=L.offsetWidth;
}},render:function(R){var Q=R.length;
var P=k.styles;
var M;
var O=this._rowsTable(Q);
var L=this._columnsTable(Q);
var S=this._tasksTable(R);
var N=this.options.currentTimeMarker;
this._taskTree.render([O,L,S]);
M=this.content.find(h+P.rowsTable);
this._contentHeight=M.height();
this._rowHeight=this._contentHeight/M.find("tr").length;
this.content.find(h+P.columnsTable).height(this._contentHeight);
if(N!==false&&N.updateInterval!==undefined){this._renderCurrentTime();
}},_rowsTable:function(O){var P=[];
var N;
var Q=k.styles;
var L=[null,{className:Q.alt}];
for(var M=0;
M<O;
M++){N=o("tr",L[M%2],[o("td",null,[p("\u00a0")])]);
P.push(N);
}return this._createTable(1,P,{className:Q.rowsTable});
},_columnsTable:function(P){var M=[];
var O;
var U=k.styles;
var R=this._timeSlots();
var S=R.length;
var Q;
var T;
var V=0;
var L;
for(var N=0;
N<S;
N++){Q=R[N];
L={};
T=Q.span;
V+=T;
if(T!==1){L.colspan=T;
}if(Q.isNonWorking){L.className=U.nonWorking;
}M.push(o("td",L,[p("\u00a0")]));
}O=o("tr",null,M);
return this._createTable(V,[O],{className:U.columnsTable});
},_tasksTable:function(ad){var Y=[];
var X;
var M;
var S;
var ab;
var aa=k.styles;
var O=this._taskCoordinates={};
var Z=this._calculateMilestoneWidth();
var R=Math.round(Z.width);
var T=this.options.resourcesField;
var N=[aa.resource,aa.resourceAlt];
var V;
var U=this._calculateResourcesMargin();
var ac=this._calculateTaskBorderWidth();
var W;
var L=function(ae){var af;
var ag;
af=S.left;
ag=af+S.width;
if(ab.isMilestone()){af-=R/2;
ag=af+R;
}O[ab.id]={start:af,end:ag,rowIndex:ae};
};
for(var P=0,Q=ad.length;
P<Q;
P++){ab=ad[P];
S=this._taskPosition(ab);
S.borderWidth=ac;
X=o("tr",null);
M=o("td",null,[this._renderTask(ad[P],S)]);
if(ab[T]&&ab[T].length){if(n){V=this._tableWidth-S.left;
}else{V=Math.max((S.width||Z.clientWidth),0)+S.left;
}W={width:(this._tableWidth-(V+U))+"px"};
W[n?"right":"left"]=V+"px";
M.children.push(o("div",{className:aa.resourcesWrap,style:W},this._renderResources(ab[T],N[P%2])));
}X.children.push(M);
Y.push(X);
L(P);
}return this._createTable(1,Y,{className:k.styles.tasksTable});
},_createTable:function(N,P,Q){var M=[];
var L;
var R;
for(var O=0;
O<N;
O++){M.push(o("col"));
}L=o("colgroup",null,M);
R=o("tbody",null,P);
if(!Q.style){Q.style={};
}Q.style.width=this._tableWidth+"px";
return o("table",Q,[L,R]);
},_calculateTableWidth:function(){var P=this._timeSlots();
var O=0;
var R=0;
var L;
var Q;
for(var M=0,N=P.length;
M<N;
M++){L=P[M].span;
R+=L;
if(L>O){O=L;
}}Q=Math.round((R*this.options.slotSize)/O);
return Q;
},_calculateMilestoneWidth:function(){var O;
var M=k.styles.task+" "+k.styles.taskMilestone;
var N=a("<div class='"+M+"' style='visibility: hidden; position: absolute'>");
var L;
this.content.append(N);
L=N[0].getBoundingClientRect();
O={width:L.right-L.left,clientWidth:N[0].clientWidth};
N.remove();
return O;
},_calculateResourcesMargin:function(){var L;
var M=a("<div class='"+k.styles.resourcesWrap+"' style='visibility: hidden; position: absolute'>");
this.content.append(M);
L=parseInt(M.css(n?"margin-right":"margin-left"),10);
M.remove();
return L;
},_calculateTaskBorderWidth:function(){var O;
var L=k.styles.task+" "+k.styles.taskSingle;
var N=a("<div class='"+L+"' style='visibility: hidden; position: absolute'>");
var M;
this.content.append(N);
M=kendo.getComputedStyles(N[0],["border-left-width"]);
O=parseFloat(M["border-left-width"],10);
N.remove();
return O;
},_renderTask:function(Q,N){var T;
var R;
var M=this.options.editable;
var O;
var S=N.left;
var P=k.styles;
var U=P.taskWrap;
var L={};
if(Q.summary){R=this._renderSummary(Q,N);
}else{if(Q.isMilestone()){R=this._renderMilestone(Q,N);
U+=" "+P.taskMilestoneWrap;
}else{R=this._renderSingleTask(Q,N);
}}T=o("div",{className:U,style:{left:S+"px"}},[R]);
if(M){T.children.push(o("div",{className:P.taskDot+" "+P.taskDotStart}));
T.children.push(o("div",{className:P.taskDot+" "+P.taskDotEnd}));
}if(!Q.summary&&!Q.isMilestone()&&M){O=Math.round(N.width*Q.percentComplete);
L[n?"right":"left"]=O+"px";
T.children.push(o("div",{className:P.taskDragHandle,style:L}));
}return T;
},_renderSingleTask:function(Q,N){var P=k.styles;
var O=Math.round(N.width*Q.percentComplete);
var L=o("div",{className:P.taskContent},[o("div",{className:P.taskTemplate},[p(Q.title)])]);
if(this.options.editable){L.children.push(o("span",{className:P.taskActions},[o("a",{className:P.link+" "+P.taskDelete,href:"#"},[o("span",{className:P.icon+" "+P.iconDelete})])]));
L.children.push(o("span",{className:P.taskResizeHandle+" "+P.taskResizeHandleWest}));
L.children.push(o("span",{className:P.taskResizeHandle+" "+P.taskResizeHandleEast}));
}var M=o("div",{className:P.task+" "+P.taskSingle,"data-uid":Q.uid,style:{width:Math.max((N.width-N.borderWidth*2),0)+"px"}},[o("div",{className:P.taskComplete,style:{width:O+"px"}}),L]);
return M;
},_renderMilestone:function(O,M){var N=k.styles;
var L=o("div",{className:N.task+" "+N.taskMilestone,"data-uid":O.uid});
return L;
},_renderSummary:function(P,M){var O=k.styles;
var N=Math.round(M.width*P.percentComplete);
var L=o("div",{className:O.task+" "+O.taskSummary,"data-uid":P.uid,style:{width:M.width+"px"}},[o("div",{className:O.taskSummaryProgress,style:{width:N+"px"}},[o("div",{className:O.taskSummaryComplete,style:{width:M.width+"px"}})])]);
return L;
},_renderResources:function(Q,M){var L=[];
var P;
for(var N=0,O=Q.length;
N<O;
N++){P=Q[N];
L.push(o("span",{className:M,style:{color:P.get("color")}},[p(P.get("name"))]));
}if(n){L.reverse();
}return L;
},_taskPosition:function(O){var M=Math.round;
var N=M(this._offset(n?O.end:O.start));
var L=M(this._offset(n?O.start:O.end));
return{left:N,width:L-N};
},_offset:function(L){var P=this._timeSlots();
var M;
var R;
var N;
var O=0;
var Q;
if(!P.length){return 0;
}Q=this._slotIndex("start",L);
M=P[Q];
if(M.end<L){O=M.offsetWidth;
}else{if(M.start<=L){R=L-M.start;
N=M.end-M.start;
O=(R/N)*M.offsetWidth;
}}if(n){O=(M.offsetWidth+1)-O;
}return M.offsetLeft+O;
},_slotIndex:function(M,R,O){var P=this._timeSlots();
var Q=0;
var L=P.length-1;
var N;
if(O){P=[].slice.call(P).reverse();
}do{N=Math.ceil((L+Q)/2);
if(P[N][M]<R){Q=N;
}else{if(N===L){N--;
}L=N;
}}while(Q!==L);
if(O){Q=(P.length-1)-Q;
}return Q;
},_timeByPosition:function(R,P,Q){var N=this._slotByPosition(R);
if(P){return Q?N.end:N.start;
}var M=R-a(h+k.styles.tasksTable).offset().left;
var L=N.end-N.start;
var O=M-N.offsetLeft;
if(n){O=N.offsetWidth-O;
}return new Date(N.start.getTime()+(L*(O/N.offsetWidth)));
},_slotByPosition:function(N){var L=N-a(h+k.styles.tasksTable).offset().left;
var M=this._slotIndex("offsetLeft",L,n);
return this._timeSlots()[M];
},_renderDependencies:function(L){var M=[];
var P=this._dependencyTree;
for(var N=0,O=L.length;
N<O;
N++){M.push.apply(M,this._renderDependency(L[N]));
}P.render(M);
},_renderDependency:function(L){var Q=this._taskCoordinates[L.predecessorId];
var R=this._taskCoordinates[L.successorId];
var M;
var P;
if(!Q||!R){return[];
}P="_render"+["FF","FS","SF","SS"][n?3-L.type:L.type];
M=this[P](Q,R);
for(var N=0,O=M.length;
N<O;
N++){M[N].attr["data-uid"]=L.uid;
}return M;
},_renderFF:function(L,N){var M=this._dependencyFF(L,N,false);
M[M.length-1].children[0]=this._arrow(true);
return M;
},_renderSS:function(L,N){var M=this._dependencyFF(N,L,true);
M[0].children[0]=this._arrow(false);
return M.reverse();
},_renderFS:function(L,N){var M=this._dependencyFS(L,N,false);
M[M.length-1].children[0]=this._arrow(false);
return M;
},_renderSF:function(L,N){var M=this._dependencyFS(N,L,true);
M[0].children[0]=this._arrow(true);
return M.reverse();
},_dependencyFF:function(Q,ab,X){var aa=this;
var U=[];
var T=0;
var ac=0;
var ae=0;
var S=0;
var P=X?"start":"end";
var O;
var W=2;
var N=1;
var Y=this._rowHeight;
var V=10;
var R=Q.rowIndex*Y+Math.floor(Y/2)-1;
var ad=ab.rowIndex*Y+Math.floor(Y/2)-1;
var Z=k.styles;
var L=function(){U.push(aa._line(Z.line+" "+Z.lineHorizontal,{left:T+"px",top:ac+"px",width:ae+"px"}));
};
var M=function(){U.push(aa._line(Z.line+" "+Z.lineVertical,{left:T+"px",top:ac+"px",height:S+"px"}));
};
T=Q[P];
ac=R;
ae=V;
O=ab[P]-Q[P];
if((O)>0!==X){ae=Math.abs(O)+V;
}if(X){T-=ae;
ae-=N;
L();
}else{L();
T+=ae-W;
}if(ad<ac){S=ac-ad;
S+=W;
ac=ad;
M();
}else{S=ad-ac;
S+=W;
M();
ac+=(S-W);
}ae=Math.abs(T-ab[P]);
if(!X){ae-=N;
T-=ae;
}L();
return U;
},_dependencyFS:function(P,ac,Y){var ab=this;
var T=[];
var S=0;
var ad=0;
var af=0;
var R=0;
var Z=this._rowHeight;
var V=Math.floor(Z/2);
var W=10;
var U=2*W;
var O=ac.start-P.end;
var X=2;
var N=1;
var Q=P.rowIndex*Z+Math.floor(Z/2)-1;
var ae=ac.rowIndex*Z+Math.floor(Z/2)-1;
var aa=k.styles;
var L=function(){T.push(ab._line(aa.line+" "+aa.lineHorizontal,{left:S+"px",top:ad+"px",width:af+"px"}));
};
var M=function(){T.push(ab._line(aa.line+" "+aa.lineVertical,{left:S+"px",top:ad+"px",height:R+"px"}));
};
S=P.end;
ad=Q;
af=W;
if(Y){S+=N;
if(O>U){af=O-(W-X);
}af-=N;
}L();
S+=af-X;
if((O)<=U){R=Y?Math.abs(ae-Q)-V:V;
if(ae<Q){ad-=R;
R+=X;
M();
}else{M();
ad+=R;
}af=(P.end-ac.start)+U;
if(af<W){af=W;
}S-=af-X;
L();
}if(ae<Q){R=ad-ae;
ad=ae;
R+=X;
M();
}else{R=ae-ad;
M();
ad+=R;
}af=ac.start-S;
if(!Y){af-=N;
}L();
return T;
},_line:function(L,M){return o("div",{className:L,style:M});
},_arrow:function(L){return o("span",{className:L?k.styles.arrowWest:k.styles.arrowEast});
},_colgroup:function(){var Q=this._timeSlots();
var M=Q.length;
var L=[];
for(var N=0;
N<M;
N++){for(var O=0,P=Q[N].span;
O<P;
O++){L.push(o("col"));
}}return o("colgroup",null,L);
},_createDragHint:function(L){this._dragHint=L.clone().addClass(k.styles.dragHint).css("cursor","move");
L.parent().append(this._dragHint);
},_updateDragHint:function(M){var L=this._offset(M);
this._dragHint.css({left:L});
},_removeDragHint:function(){this._dragHint.remove();
this._dragHint=null;
},_createResizeHint:function(O){var N=k.styles;
var P=this._taskCoordinates[O.id].rowIndex*this._rowHeight;
var Q;
var R;
var M=this.options;
var L=M.messages;
this._resizeHint=a(B({styles:N})).css({top:0,height:this._contentHeight});
this.content.append(this._resizeHint);
this._resizeTooltip=a(C({styles:N,start:O.start,end:O.end,messages:L.views,format:M.resizeTooltipFormat})).css({top:0,left:0});
this.content.append(this._resizeTooltip);
this._resizeTooltipWidth=this._resizeTooltip.outerWidth();
Q=this._resizeTooltip.outerHeight();
R=P-Q;
if(R<0){R=P+this._rowHeight;
}this._resizeTooltipTop=R;
},_updateResizeHint:function(R,L,P){var M=this._offset(n?L:R);
var Q=this._offset(n?R:L);
var W=Q-M;
var U=(P!==n)?M:Q;
var T=this._tableWidth-kendo.support.scrollbar();
var V=this._resizeTooltipWidth;
var O=this.options;
var N=O.messages;
var S=a(h+k.styles.tasksTable).offset().left-a(h+k.styles.tasksWrapper).offset().left;
if(n){M+=S;
}this._resizeHint.css({left:M,width:W});
if(this._resizeTooltip){this._resizeTooltip.remove();
}U-=Math.round(V/2);
if(U<0){U=0;
}else{if(U+V>T){U=T-V;
}}if(n){U+=S;
}this._resizeTooltip=a(C({styles:k.styles,start:R,end:L,messages:N.views,format:O.resizeTooltipFormat})).css({top:this._resizeTooltipTop,left:U,"min-width":V}).appendTo(this.content);
},_removeResizeHint:function(){this._resizeHint.remove();
this._resizeHint=null;
this._resizeTooltip.remove();
this._resizeTooltip=null;
},_updatePercentCompleteTooltip:function(R,N,O){this._removePercentCompleteTooltip();
var P=this._percentCompleteResizeTooltip=a(y({styles:k.styles,text:O})).appendTo(this.element);
var Q=Math.round(P.outerWidth()/2);
var L=P.find(h+k.styles.callout);
var M=Math.round(L.outerWidth()/2);
P.css({top:R-(P.outerHeight()+M),left:N-Q});
L.css("left",Q-M);
},_removePercentCompleteTooltip:function(){if(this._percentCompleteResizeTooltip){this._percentCompleteResizeTooltip.remove();
}this._percentCompleteResizeTooltip=null;
},_updateDependencyDragHint:function(L,M,N){this._removeDependencyDragHint();
if(N){this._creteVmlDependencyDragHint(L,M);
}else{this._creteDependencyDragHint(L,M);
}},_creteDependencyDragHint:function(O,Q){var P=k.styles;
var M=Q.x-O.x;
var N=Q.y-O.y;
var R=Math.sqrt(M*M+N*N);
var L=Math.atan(N/M);
if(M<0){L+=Math.PI;
}a("<div class='"+P.line+" "+P.lineHorizontal+" "+P.dependencyHint+"'></div>").css({top:O.y,left:O.x,width:R,"transform-origin":"0% 0","-ms-transform-origin":"0% 0","-webkit-transform-origin":"0% 0",transform:"rotate("+L+"rad)","-ms-transform":"rotate("+L+"rad)","-webkit-transform":"rotate("+L+"rad)"}).appendTo(this.content);
},_creteVmlDependencyDragHint:function(L,N){var M=a("<kvml:line class='"+k.styles.dependencyHint+"' style='position:absolute; top: 0px; left: 0px;' strokecolor='black' strokeweight='2px' from='"+L.x+"px,"+L.y+"px' to='"+N.x+"px,"+N.y+"px'></kvml:line>").appendTo(this.content);
M[0].outerHTML=M[0].outerHTML;
},_removeDependencyDragHint:function(){this.content.find(h+k.styles.dependencyHint).remove();
},_createTaskTooltip:function(W,P,R){var V=k.styles;
var S=this.options;
var L=this.content;
var M=L.offset();
var O=L.width();
var N=L.scrollLeft();
var T=a(P).parents("tr").first();
var U=T.offset();
var X=(S.tooltip&&S.tooltip.template)?kendo.template(S.tooltip.template):D;
var Q=R-(M.left-L.scrollLeft());
var aa=(U.top+T.outerHeight()-M.top)+L.scrollTop();
var Y=this._taskTooltip=a('<div style="z-index: 100002;" class="'+V.tooltipWrapper+'" ><div class="'+V.taskContent+'"></div></div>');
var Z;
Y.css({left:Q,top:aa}).appendTo(L).find(h+V.taskContent).append(X({styles:V,task:W,messages:S.messages.views}));
if(Y.outerHeight()<U.top-M.top){Y.css("top",((U.top-M.top)-Y.outerHeight())+L.scrollTop());
}Z=Y.outerWidth();
if((Z+Q)-N>O){Q-=Z;
if(Q<N){Q=(N+O)-(Z+17);
}Y.css("left",Q);
}},_removeTaskTooltip:function(){if(this._taskTooltip){this._taskTooltip.remove();
}this._taskTooltip=null;
},_scrollTo:function(T){var U=T.offset().left;
var W=T.width();
var V=U+W;
var X=T.closest("tr");
var aa=X.offset().top;
var Z=X.height();
var Y=aa+Z;
var L=this.content;
var P=L.offset();
var R=P.top;
var N=L.height();
var M=R+N;
var O=P.left;
var S=L.width();
var Q=O+S;
var ab=kendo.support.scrollbar();
if(aa<R){L.scrollTop(L.scrollTop()+(aa-R));
}else{if(Y>M){L.scrollTop(L.scrollTop()+(Y+ab-M));
}}if(U<O&&W>S&&V<Q||V>Q&&W<S){L.scrollLeft(L.scrollLeft()+(V+ab-Q));
}else{if(V>Q&&W>S&&U>O||U<O&&W<S){L.scrollLeft(L.scrollLeft()+(U-O));
}}},_timeSlots:function(){if(!this._slots||!this._slots.length){return[];
}return this._slots[this._slots.length-1];
},_headers:function(O){var U=[];
var R;
var P;
var L;
var Q;
var V=k.styles;
for(var T=0,S=O.length;
T<S;
T++){R=O[T];
P=[];
for(var N=0,M=R.length;
N<M;
N++){L=R[N];
Q=p(L.text);
P.push(o("th",{colspan:L.span,className:V.header+(L.isNonWorking?(" "+V.nonWorking):"")},[Q]));
}U.push(o("tr",null,P));
}return U;
},_hours:function(S,L){var Q;
var R=[];
var P=this.options;
var U=P.workDayStart.getHours();
var T=P.workDayEnd.getHours();
var O;
var M;
var N=P.hourSpan;
S=new Date(S);
L=new Date(L);
while(S<L){Q=new Date(S);
M=Q.getHours();
O=M>=U&&M<T;
Q.setHours(Q.getHours()+N);
if(M==Q.getHours()){Q.setHours(Q.getHours()+2*N);
}if(!P.showWorkHours||O){R.push({start:S,end:Q,isNonWorking:!O,span:1});
}S=Q;
}return R;
},_days:function(P,L){var N;
var O=[];
var M;
P=new Date(P);
L=new Date(L);
while(P<L){N=kendo.date.nextDay(P);
M=this._isWorkDay(P);
if(!this.options.showWorkDays||M){O.push({start:P,end:N,isNonWorking:!M,span:1});
}P=N;
}return O;
},_weeks:function(R,M){var O;
var P=[];
var N=this.calendarInfo().firstDay;
var L;
var Q;
R=new Date(R);
M=new Date(M);
while(R<M){O=kendo.date.dayOfWeek(kendo.date.addDays(R,1),N,1);
if(O>M){O=M;
}L=this._days(R,O);
Q=L.length;
if(Q>0){P.push({start:L[0].start,end:L[Q-1].end,span:Q});
}R=O;
}return P;
},_months:function(Q,M){var N;
var O=[];
var L;
var P;
Q=new Date(Q);
M=new Date(M);
while(Q<M){N=new Date(Q);
N.setMonth(N.getMonth()+1);
L=this._days(Q,N);
P=L.length;
if(P>0){O.push({start:L[0].start,end:L[P-1].end,span:P});
}Q=N;
}return O;
},_years:function(O,L){var M;
var N=[];
O=new Date(O);
L=new Date(L);
while(O<L){M=new Date(O);
M.setFullYear(M.getFullYear()+1);
N.push({start:O,end:M,span:12});
O=M;
}return N;
},_slotHeaders:function(P,Q){var L=[];
var O;
for(var M=0,N=P.length;
M<N;
M++){O=P[M];
L.push({text:Q(O),isNonWorking:!!O.isNonWorking,span:O.span});
}return L;
},_isWorkDay:function(L){var M=L.getDay();
var P=this._workDays;
for(var N=0,O=P.length;
N<O;
N++){if(P[N]===M){return true;
}}return false;
},calendarInfo:function(){return kendo.getCulture().calendars.standard;
},_renderCurrentTime:function(){var L=this._getCurrentTime();
var Q=this._offset(L);
var M=a("<div class='k-current-time'></div>");
var R=k.styles;
var O=a(h+R.tasksWrapper);
var P=a(h+R.tasksTable);
var N;
if(!this.content||!this._timeSlots().length){return;
}this.content.find(".k-current-time").remove();
N=this._timeSlots()[this._slotIndex("start",L)];
if(L<N.start||L>N.end){return;
}if(O.length&&P.length){Q+=P.offset().left-O.offset().left;
}M.css({left:Q+"px",top:"0px",width:"1px",height:this._contentHeight+"px"}).appendTo(this.content);
},_getCurrentTime:function(){return new Date();
},_currentTime:function(){var L=this.options.currentTimeMarker;
if(L!==false&&L.updateInterval!==undefined){this._renderCurrentTime();
this._currentTimeUpdateTimer=setInterval(z(this._renderCurrentTime,this),L.updateInterval);
}}});
i(true,k,{styles:H});
kendo.ui.GanttDayView=k.extend({name:"day",options:{timeHeaderTemplate:E,dayHeaderTemplate:e,resizeTooltipFormat:"h:mm tt ddd, MMM d"},range:function(L){this.start=kendo.date.getDate(L.start);
this.end=kendo.date.getDate(L.end);
if(kendo.date.getMilliseconds(L.end)>0||this.end.getTime()===this.start.getTime()){this.end=kendo.date.addDays(this.end,1);
}},_createSlots:function(){var M;
var L;
var O;
var N;
var R=[];
M=this._days(this.start,this.end);
O=[];
for(var P=0,Q=M.length;
P<Q;
P++){L=M[P];
N=this._hours(L.start,L.end);
L.span=N.length;
O.push.apply(O,N);
}R.push(M);
R.push(O);
return R;
},_layout:function(){var M=[];
var L=this.options;
M.push(this._slotHeaders(this._slots[0],kendo.template(L.dayHeaderTemplate)));
M.push(this._slotHeaders(this._slots[1],kendo.template(L.timeHeaderTemplate)));
return M;
}});
kendo.ui.GanttWeekView=k.extend({name:"week",options:{dayHeaderTemplate:e,weekHeaderTemplate:I,resizeTooltipFormat:"h:mm tt ddd, MMM d"},range:function(N){var L=this.calendarInfo();
var M=L.firstDay;
var O=N.end;
if(M===O.getDay()){O.setDate(O.getDate()+7);
}this.start=kendo.date.getDate(kendo.date.dayOfWeek(N.start,M,-1));
this.end=kendo.date.getDate(kendo.date.dayOfWeek(O,M,1));
},_createSlots:function(){var L=[];
L.push(this._weeks(this.start,this.end));
L.push(this._days(this.start,this.end));
return L;
},_layout:function(){var M=[];
var L=this.options;
M.push(this._slotHeaders(this._slots[0],kendo.template(L.weekHeaderTemplate)));
M.push(this._slotHeaders(this._slots[1],kendo.template(L.dayHeaderTemplate)));
return M;
}});
kendo.ui.GanttMonthView=k.extend({name:"month",options:{weekHeaderTemplate:I,monthHeaderTemplate:t,resizeTooltipFormat:"dddd, MMM d, yyyy"},range:function(L){this.start=kendo.date.firstDayOfMonth(L.start);
this.end=kendo.date.addDays(kendo.date.getDate(kendo.date.lastDayOfMonth(L.end)),1);
},_createSlots:function(){var L=[];
L.push(this._months(this.start,this.end));
L.push(this._weeks(this.start,this.end));
return L;
},_layout:function(){var M=[];
var L=this.options;
M.push(this._slotHeaders(this._slots[0],kendo.template(L.monthHeaderTemplate)));
M.push(this._slotHeaders(this._slots[1],kendo.template(L.weekHeaderTemplate)));
return M;
}});
kendo.ui.GanttYearView=k.extend({name:"year",options:{yearHeaderTemplate:K,monthHeaderTemplate:t,resizeTooltipFormat:"dddd, MMM d, yyyy"},range:function(L){this.start=kendo.date.firstDayOfMonth(new Date(L.start.setMonth(0)));
this.end=kendo.date.firstDayOfMonth(new Date(L.end.setMonth(12)));
},_createSlots:function(){var M=[];
var L=this._months(this.start,this.end);
a(L).each(function(N,O){O.span=1;
});
M.push(this._years(this.start,this.end));
M.push(L);
return M;
},_layout:function(){var M=[];
var L=this.options;
M.push(this._slotHeaders(this._slots[0],kendo.template(L.yearHeaderTemplate)));
M.push(this._slotHeaders(this._slots[1],kendo.template(L.monthHeaderTemplate)));
return M;
}});
var F={wrapper:"k-timeline k-grid k-widget",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",gridContentWrap:"k-grid-content",tasksWrapper:"k-gantt-tables",dependenciesWrapper:"k-gantt-dependencies",task:"k-task",line:"k-line",taskResizeHandle:"k-resize-handle",taskResizeHandleWest:"k-resize-w",taskDragHandle:"k-task-draghandle",taskComplete:"k-task-complete",taskDelete:"k-task-delete",taskWrapActive:"k-task-wrap-active",taskWrap:"k-task-wrap",taskDot:"k-task-dot",taskDotStart:"k-task-start",taskDotEnd:"k-task-end",hovered:"k-state-hover",selected:"k-state-selected",origin:"k-origin"};
var j=kendo.ui.GanttTimeline=J.extend({init:function(L,M){J.fn.init.call(this,L,M);
if(!this.options.views||!this.options.views.length){this.options.views=["day","week","month"];
}n=kendo.support.isRtl(L);
this._wrapper();
this._domTrees();
this._views();
this._selectable();
this._draggable();
this._resizable();
this._percentResizeDraggable();
this._createDependencyDraggable();
this._attachEvents();
this._tooltip();
},options:{name:"GanttTimeline",messages:{views:{day:"Day",week:"Week",month:"Month",year:"Year",start:"Start",end:"End"}},snap:true,selectable:true,editable:true},destroy:function(){J.fn.destroy.call(this);
if(this._currentTimeUpdateTimer){clearInterval(this._currentTimeUpdateTimer);
}this._unbindView(this._selectedView);
if(this._moveDraggable){this._moveDraggable.destroy();
}if(this._resizeDraggable){this._resizeDraggable.destroy();
}if(this._percentDraggable){this._percentDraggable.destroy();
}if(this._dependencyDraggable){this._dependencyDraggable.destroy();
}if(this.touch){this.touch.destroy();
}this._headerTree=null;
this._taskTree=null;
this._dependencyTree=null;
this.wrapper.off(x);
kendo.destroy(this.wrapper);
},_wrapper:function(){var L=j.styles;
this.wrapper=this.element.addClass(L.wrapper).append("<div class='"+L.gridHeader+"'><div class='"+L.gridHeaderWrap+"'></div></div>").append("<div class='"+L.gridContentWrap+"'><div class='"+L.tasksWrapper+"'></div><div class='"+L.dependenciesWrapper+"'></div></div>");
},_domTrees:function(){var L=j.styles;
var M=kendo.dom.Tree;
var N=this.wrapper;
this._headerTree=new M(N.find(h+L.gridHeaderWrap)[0]);
this._taskTree=new M(N.find(h+L.tasksWrapper)[0]);
this._dependencyTree=new M(N.find(h+L.dependenciesWrapper)[0]);
},_views:function(){var S=this.options.views;
var R;
var N;
var P;
var L;
var Q;
this.views={};
for(var M=0,O=S.length;
M<O;
M++){R=S[M];
N=m(R);
if(N&&R.selectable===false){continue;
}P=N?((typeof R.type!=="string")?R.title:R.type):R;
L=g[P];
if(L){if(N){R.type=L.type;
}L.title=this.options.messages.views[P];
}R=i({title:P},L,N?R:{});
if(P){this.views[P]=R;
if(!Q||R.selected){Q=P;
}}}if(Q){this._selectedViewName=Q;
}},view:function(L){if(L){this._selectView(L);
this.trigger("navigate",{view:L,action:"changeView"});
}return this._selectedView;
},_selectView:function(L){if(L&&this.views[L]){if(this._selectedView){this._unbindView(this._selectedView);
}this._selectedView=this._initializeView(L);
this._selectedViewName=L;
}},_viewByIndex:function(L){var M;
var N=this.views;
for(M in N){if(!L){return M;
}L--;
}},_initializeView:function(L){var N=this.views[L];
if(N){var M=N.type;
if(typeof M==="string"){M=kendo.getter(N.type)(window);
}if(M){N=new M(this.wrapper,G(i(true,{headerTree:this._headerTree,taskTree:this._taskTree,dependencyTree:this._dependencyTree},N,this.options)));
}else{throw new Error("There is no such view");
}}return N;
},_unbindView:function(L){if(L){L.destroy();
}},_range:function(P){var O={field:"start",dir:"asc"};
var M={field:"end",dir:"desc"};
if(!P||!P.length){return{start:new Date(),end:new Date()};
}var N=new A(P).sort(O).toArray()[0].start||new Date();
var L=new A(P).sort(M).toArray()[0].end||new Date();
return{start:new Date(N),end:new Date(L)};
},_render:function(M){var N=this.view();
var L=this._range(M);
this._tasks=M;
N.range(L);
N.renderLayout();
N.render(M);
},_renderDependencies:function(L){this.view()._renderDependencies(L);
},_taskByUid:function(P){var O=this._tasks;
var M=O.length;
var N;
for(var L=0;
L<M;
L++){N=O[L];
if(N.uid===P){return N;
}}},_draggable:function(){var S=this;
var N;
var R;
var M;
var P;
var O=this.options.snap;
var Q=j.styles;
var L=function(){S.view()._removeDragHint();
if(N){N.css("opacity",1);
}N=null;
R=null;
S.dragInProgress=false;
};
if(!this.options.editable){return;
}this._moveDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:h+Q.task,holdToDrag:kendo.support.mobileOS,ignore:h+Q.taskResizeHandle});
this._moveDraggable.bind("dragstart",function(T){var U=S.view();
N=T.currentTarget.parent();
R=S._taskByUid(T.currentTarget.attr("data-uid"));
if(S.trigger("moveStart",{task:R})){T.preventDefault();
return;
}M=R.start;
P=U._timeByPosition(T.x.location,O)-M;
U._createDragHint(N);
N.css("opacity",0.5);
clearTimeout(S._tooltipTimeout);
S.dragInProgress=true;
}).bind("drag",kendo.throttle(function(U){if(!S.dragInProgress){return;
}var W=S.view();
var T=new Date(W._timeByPosition(U.x.location,O)-P);
var V=T;
if(!S.trigger("move",{task:R,start:T})){M=T;
if(n){V=new Date(M.getTime()+R.duration());
}W._updateDragHint(V);
}},15)).bind("dragend",function(T){S.trigger("moveEnd",{task:R,start:M});
L();
}).bind("dragcancel",function(T){L();
}).userEvents.bind("select",function(T){b();
});
},_resizable:function(){var T=this;
var O;
var S;
var N;
var M;
var P;
var Q=this.options.snap;
var R=j.styles;
var L=function(){T.view()._removeResizeHint();
O=null;
S=null;
T.dragInProgress=false;
};
if(!this.options.editable){return;
}this._resizeDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:h+R.taskResizeHandle,holdToDrag:false});
this._resizeDraggable.bind("dragstart",function(U){P=U.currentTarget.hasClass(R.taskResizeHandleWest);
if(n){P=!P;
}O=U.currentTarget.closest(h+R.task);
S=T._taskByUid(O.attr("data-uid"));
if(T.trigger("resizeStart",{task:S})){U.preventDefault();
return;
}N=S.start;
M=S.end;
T.view()._createResizeHint(S);
clearTimeout(T._tooltipTimeout);
T.dragInProgress=true;
}).bind("drag",kendo.throttle(function(V){if(!T.dragInProgress){return;
}var W=T.view();
var U=W._timeByPosition(V.x.location,Q,!P);
if(P){if(U<M){N=U;
}else{N=M;
}}else{if(U>N){M=U;
}else{M=N;
}}if(!T.trigger("resize",{task:S,start:N,end:M})){W._updateResizeHint(N,M,P);
}},15)).bind("dragend",function(U){T.trigger("resizeEnd",{task:S,resizeStart:P,start:N,end:M});
L();
}).bind("dragcancel",function(U){L();
}).userEvents.bind("select",function(U){b();
});
},_percentResizeDraggable:function(){var U=this;
var R;
var S;
var T;
var V;
var P;
var O;
var M;
var X;
var W;
var Q=j.styles;
var N;
var L=function(){U.view()._removePercentCompleteTooltip();
S=null;
R=null;
U.dragInProgress=false;
};
var Y=function(Z){S.find(h+Q.taskComplete).width(Z).end().siblings(h+Q.taskDragHandle).css(n?"right":"left",Z);
};
if(!this.options.editable){return;
}this._percentDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:h+Q.taskDragHandle,holdToDrag:false});
this._percentDraggable.bind("dragstart",function(Z){S=Z.currentTarget.siblings(h+Q.task);
R=U._taskByUid(S.attr("data-uid"));
M=R.percentComplete;
T=S.offset();
V=this.element.offset();
P=S.find(h+Q.taskComplete).width();
O=S.outerWidth();
clearTimeout(U._tooltipTimeout);
U.dragInProgress=true;
}).bind("drag",kendo.throttle(function(aa){if(!U.dragInProgress){return;
}N=n?-aa.x.initialDelta:aa.x.initialDelta;
var Z=Math.max(0,Math.min(O,P+N));
M=Math.round((Z/O)*100);
Y(Z);
X=T.top-V.top;
W=T.left+Z-V.left;
if(n){W+=(O-2*Z);
}U.view()._updatePercentCompleteTooltip(X,W,M);
},15)).bind("dragend",function(Z){U.trigger("percentResizeEnd",{task:R,percentComplete:M/100});
L();
}).bind("dragcancel",function(Z){Y(P);
L();
}).userEvents.bind("select",function(Z){b();
});
},_createDependencyDraggable:function(){var S=this;
var O;
var M=a();
var N=a();
var P;
var Q;
var U=c.msie&&c.version<9;
var R=j.styles;
var L=function(){O.css("display","").removeClass(R.hovered);
O.parent().removeClass(R.origin);
O=null;
T(false);
N=a();
M=a();
S.view()._removeDependencyDragHint();
S.dragInProgress=false;
};
var T=function(V){if(!N.hasClass(R.origin)){N.find(h+R.taskDot).css("display",V?"block":"");
M.toggleClass(R.hovered,V);
}};
if(!this.options.editable){return;
}if(U&&document.namespaces){document.namespaces.add("kvml","urn:schemas-microsoft-com:vml","#default#VML");
}this._dependencyDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:h+R.taskDot,holdToDrag:false});
this._dependencyDraggable.bind("dragstart",function(V){O=V.currentTarget.css("display","block").addClass(R.hovered);
O.parent().addClass(R.origin);
var W=O.offset();
var X=a(h+R.tasksWrapper).offset();
P=Math.round(W.left-X.left+(O.outerHeight()/2));
Q=Math.round(W.top-X.top+(O.outerWidth()/2));
clearTimeout(S._tooltipTimeout);
S.dragInProgress=true;
}).bind("drag",kendo.throttle(function(X){if(!S.dragInProgress){return;
}S.view()._removeDependencyDragHint();
var Z=a(kendo.elementUnderCursor(X));
var Y=a(h+R.tasksWrapper).offset();
var V=X.x.location-Y.left;
var W=X.y.location-Y.top;
S.view()._updateDependencyDragHint({x:P,y:Q},{x:V,y:W},U);
T(false);
M=(Z.hasClass(R.taskDot))?Z:a();
N=Z.closest(h+R.taskWrap);
T(true);
},15)).bind("dragend",function(V){if(M.length){var W=O.hasClass(R.taskDotStart);
var Z=M.hasClass(R.taskDotStart);
var aa=W?(Z?3:2):(Z?1:0);
var X=S._taskByUid(O.siblings(h+R.task).attr("data-uid"));
var Y=S._taskByUid(M.siblings(h+R.task).attr("data-uid"));
if(X!==Y){S.trigger("dependencyDragEnd",{type:aa,predecessor:X,successor:Y});
}}L();
}).bind("dragcancel",function(V){L();
}).userEvents.bind("select",function(V){b();
});
},_selectable:function(){var M=this;
var L=j.styles;
if(this.options.selectable){this.wrapper.on(d+x,h+L.task,function(N){N.stopPropagation();
if(!N.ctrlKey){M.trigger("select",{uid:a(this).attr("data-uid")});
}else{M.trigger("clear");
}}).on(d+x,h+L.tasksWrapper,function(N){if(M.selectDependency().length>0){M.clearSelection();
}else{M.trigger("clear");
}}).on(d+x,h+L.line,function(N){N.stopPropagation();
M.selectDependency(this);
});
}},select:function(N){var L=this.wrapper.find(N);
var M=j.styles;
if(L.length){this.clearSelection();
L.addClass(M.selected);
if(kendo.support.mobileOS){L.parent().addClass(M.taskWrapActive);
}return;
}return this.wrapper.find(h+M.task+h+M.selected);
},selectDependency:function(O){var L=this.wrapper.find(O);
var N;
var M=j.styles;
if(L.length){this.clearSelection();
this.trigger("clear");
N=a(L).attr("data-uid");
this.wrapper.find(h+M.line+"[data-uid='"+N+"']").addClass(M.selected);
return;
}return this.wrapper.find(h+M.line+h+M.selected);
},clearSelection:function(){var L=j.styles;
this.wrapper.find(h+L.selected).removeClass(L.selected);
if(kendo.support.mobileOS){this.wrapper.find(h+L.taskWrapActive).removeClass(L.taskWrapActive);
}},_attachEvents:function(){var M=this;
var L=j.styles;
if(this.options.editable){this._tabindex();
this.wrapper.on(d+x,h+L.taskDelete,function(N){M.trigger("removeTask",{uid:a(this).closest(h+L.task).attr("data-uid")});
N.stopPropagation();
N.preventDefault();
}).on(q+x,function(N){var O;
if(N.keyCode===r.DELETE){O=M.selectDependency();
if(O.length){M.trigger("removeDependency",{uid:O.attr("data-uid")});
M.clearSelection();
}}});
if(!s){this.wrapper.on(f+x,h+L.task,function(N){M.trigger("editTask",{uid:a(this).attr("data-uid")});
N.stopPropagation();
N.preventDefault();
});
}else{this.touch=this.wrapper.kendoTouch({filter:h+L.task,doubletap:function(N){M.trigger("editTask",{uid:a(N.touch.currentTarget).attr("data-uid")});
}}).data("kendoTouch");
}}},_tooltip:function(){var O=this;
var P=this.options.tooltip;
var N=j.styles;
var L;
var M=function(Q){L=Q.clientX;
};
if(P&&P.visible===false){return;
}this.wrapper.on(u+x,h+N.task,function(Q){var R=this;
var S=O._taskByUid(a(this).attr("data-uid"));
if(O.dragInProgress){return;
}O._tooltipTimeout=setTimeout(function(){O.view()._createTaskTooltip(S,R,L);
},800);
a(this).on(w,M);
}).on(v+x,h+N.task,function(Q){clearTimeout(O._tooltipTimeout);
O.view()._removeTaskTooltip();
a(this).off(w,M);
});
}});
i(true,j,{styles:F});
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
