'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_DashboardDaySurvey

    '''<summary>
    '''DVdaySurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdaySurvey As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBdaySurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdaySurvey As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LNBviewDaySurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBviewDaySurvey As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LBisNewSurvay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBisNewSurvay As Global.System.Web.UI.WebControls.Label
End Class
