'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_TagsList

    '''<summary>
    '''CTRLmessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmessages As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''DVfilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVfilters As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTsearchTagFiltersTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsearchTagFiltersTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SPNexpand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPNexpand As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBspanExpandList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBspanExpandList As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBspanCollapseList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBspanCollapseList As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLfilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLfilters As Global.Comunita_OnLine.UC_Filters

    '''<summary>
    '''BTNreloadItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNreloadItems As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LNBapplyTagsFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBapplyTagsFilters As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''DVstatistics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVstatistics As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBtagsStatistics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtagsStatistics As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBcommunitiesWithNoTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcommunitiesWithNoTags As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBcommunitiesWithNoTags_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcommunitiesWithNoTags_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HYPcommunitiesWithNoTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPcommunitiesWithNoTags As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LBtagsNotTranslated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtagsNotTranslated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBtagsNotTranslated_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtagsNotTranslated_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DVlanguageSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVlanguageSelector As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBdisplayLanguageSelectorDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdisplayLanguageSelectorDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBdisplayLanguageSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdisplayLanguageSelected As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPTdisplayLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTdisplayLanguage As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''LTthName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTthName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LNBorderByNameUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBorderByNameUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBorderByNameDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBorderByNameDown As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LTthUsedInCommunities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTthUsedInCommunities As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LNBorderByUsedByUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBorderByUsedByUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBorderByUsedByDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBorderByUsedByDown As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LTthTranslations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTthTranslations As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTthModifiedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTthModifiedOn As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LNBorderByModifiedOnUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBorderByModifiedOnUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBorderByModifiedOnDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBorderByModifiedOnDown As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LTthModifiedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTthModifiedBy As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LNBorderByModifiedByUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBorderByModifiedByUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBorderByModifiedByDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBorderByModifiedByDown As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LBactions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBactions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPTtags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTtags As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''DVpager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVpager As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PGgridBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PGgridBottom As Global.Comunita_OnLine.UC_PagerControl

    '''<summary>
    '''DVlegend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVlegend As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBtableLegend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtableLegend As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LTdraftItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTdraftItem As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTdefaultItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTdefaultItem As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CTRLedit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLedit As Global.Comunita_OnLine.UC_TagEdit

    '''<summary>
    '''LTcssClassSelectBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassSelectBy As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassActive As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassDraft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassDraft As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassDefault As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassInfoToDo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassInfoToDo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassInfoWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassInfoWarning As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcssClassInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcssClassInfo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTtemplateLegendItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtemplateLegendItem As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTtemplateMessageDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtemplateMessageDetails As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTtemplateMessageDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtemplateMessageDetail As Global.System.Web.UI.WebControls.Literal
End Class
