(function(b,a){a(["./kendo.core","./kendo.drawing"],b);
})(function(){(function(a,a2){var O=document,al=window.kendo,a6=al.util,d=a6.append,L=a6.defined,am=a6.last,ao=a6.limitValue,a7=a6.valueOrDefault,D=al.dataviz,V=D.geometry,P=D.drawing,ax=P.util.measureText,av=V.Matrix,t=al.Class,aV=al.template,at=a.map,aB=a.noop,af=a.inArray,a1=a.trim,au=Math,G=al.deepExtend;
var B="k-";
var c=10,h="axisLabelClick",j=1,k="#000",l="bottom",q="center",w=3,u="clip",s="circle",A="cross",H="12px sans-serif",I=400,J=6,K=600,M=au.PI/180,R="fadeIn",U=/\{\d+:?/,aa="height",ac="k",ab=1000,ad=10000,x=100000,ag=600,ai="inside",an="left",ap="linear",aw=Number.MAX_VALUE,ay=-Number.MAX_VALUE,aA="none",aD="noteClick",aE="noteHover",aH="outside",aJ="radial",aM="right",aU="swing",aZ="top",a0="triangle",a3="undefined",a5=/([A-Z])/g,a9="width",a8="#fff",ba="x",bb="y",bc=0.2;
function Z(bd,X){var Y={top:0,right:0,bottom:0,left:0};
X=X||0;
if(typeof(bd)==="number"){Y[aZ]=Y[aM]=Y[l]=Y[an]=bd;
}else{Y[aZ]=bd[aZ]||X;
Y[aM]=bd[aM]||X;
Y[l]=bd[l]||X;
Y[an]=bd[an]||X;
}return Y;
}var aI=function(Y,bd){var X=this;
if(!(X instanceof aI)){return new aI(Y,bd);
}X.x=Y||0;
X.y=bd||0;
};
aI.fn=aI.prototype={clone:function(){var X=this;
return new aI(X.x,X.y);
},equals:function(X){return X&&X.x===this.x&&X.y===this.y;
},rotate:function(X,bf){var bg=this,bi=bf*M,Y=au.cos(bi),bh=au.sin(bi),bd=X.x,be=X.y,bj=bg.x,bk=bg.y;
bg.x=aQ(bd+(bj-bd)*Y+(bk-be)*bh,w);
bg.y=aQ(be+(bk-be)*Y-(bj-bd)*bh,w);
return bg;
},multiply:function(X){var Y=this;
Y.x*=X;
Y.y*=X;
return Y;
},distanceTo:function(bd){var X=this.x-bd.x,Y=this.y-bd.y;
return au.sqrt(X*X+Y*Y);
}};
aI.onCircle=function(Y,X,bd){X*=M;
return new aI(Y.x-bd*au.cos(X),Y.y-bd*au.sin(X));
};
var m=function(Y,be,bd,bf){var X=this;
if(!(X instanceof m)){return new m(Y,be,bd,bf);
}X.x1=Y||0;
X.x2=bd||0;
X.y1=be||0;
X.y2=bf||0;
};
m.fn=m.prototype={width:function(){return this.x2-this.x1;
},height:function(){return this.y2-this.y1;
},translate:function(Y,bd){var X=this;
X.x1+=Y;
X.x2+=Y;
X.y1+=bd;
X.y2+=bd;
return X;
},move:function(be,bf){var X=this,Y=X.height(),bd=X.width();
if(L(be)){X.x1=be;
X.x2=X.x1+bd;
}if(L(bf)){X.y1=bf;
X.y2=X.y1+Y;
}return X;
},wrap:function(Y){var X=this;
X.x1=au.min(X.x1,Y.x1);
X.y1=au.min(X.y1,Y.y1);
X.x2=au.max(X.x2,Y.x2);
X.y2=au.max(X.y2,Y.y2);
return X;
},wrapPoint:function(X){this.wrap(new m(X.x,X.y,X.x,X.y));
return this;
},snapTo:function(bd,X){var Y=this;
if(X==ba||!X){Y.x1=bd.x1;
Y.x2=bd.x2;
}if(X==bb||!X){Y.y1=bd.y1;
Y.y2=bd.y2;
}return Y;
},alignTo:function(bh,X){var bd=this,bf=bd.height(),bj=bd.width(),Y=X==aZ||X==l?bb:ba,bg=Y==bb?bf:bj;
if(X===q){var bi=bh.center();
var be=bd.center();
bd.x1+=bi.x-be.x;
bd.y1+=bi.y-be.y;
}else{if(X===aZ||X===an){bd[Y+1]=bh[Y+1]-bg;
}else{bd[Y+1]=bh[Y+2];
}}bd.x2=bd.x1+bj;
bd.y2=bd.y1+bf;
return bd;
},shrink:function(bd,Y){var X=this;
X.x2-=bd;
X.y2-=Y;
return X;
},expand:function(Y,X){this.shrink(-Y,-X);
return this;
},pad:function(Y){var X=this,bd=Z(Y);
X.x1-=bd.left;
X.x2+=bd.right;
X.y1-=bd.top;
X.y2+=bd.bottom;
return X;
},unpad:function(Y){var X=this,bd=Z(Y);
bd.left=-bd.left;
bd.top=-bd.top;
bd.right=-bd.right;
bd.bottom=-bd.bottom;
return X.pad(bd);
},clone:function(){var X=this;
return new m(X.x1,X.y1,X.x2,X.y2);
},center:function(){var X=this;
return new aI(X.x1+X.width()/2,X.y1+X.height()/2);
},containsPoint:function(Y){var X=this;
return Y.x>=X.x1&&Y.x<=X.x2&&Y.y>=X.y1&&Y.y<=X.y2;
},points:function(){var X=this;
return[new aI(X.x1,X.y1),new aI(X.x2,X.y1),new aI(X.x2,X.y2),new aI(X.x1,X.y2)];
},getHash:function(){var X=this;
return[X.x1,X.y1,X.x2,X.y2].join(",");
},overlaps:function(X){return !(X.y2<this.y1||this.y2<X.y1||X.x2<this.x1||this.x2<X.x1);
},rotate:function(bk){var X=this;
var bl=X.width();
var bf=X.height();
var Y=X.center();
var bd=Y.x;
var be=Y.y;
var bg=aP(0,0,bd,be,bk);
var bh=aP(bl,0,bd,be,bk);
var bi=aP(bl,bf,bd,be,bk);
var bj=aP(0,bf,bd,be,bk);
bl=au.max(bg.x,bh.x,bi.x,bj.x)-au.min(bg.x,bh.x,bi.x,bj.x);
bf=au.max(bg.y,bh.y,bi.y,bj.y)-au.min(bg.y,bh.y,bi.y,bj.y);
X.x2=X.x1+bl;
X.y2=X.y1+bf;
return X;
},toRect:function(){return new V.Rect([this.x1,this.y1],[this.width(),this.height()]);
},hasSize:function(){return this.width()!==0&&this.height()!==0;
},align:function(bi,Y,X){var bd=this,be=Y+1,bf=Y+2,bh=Y===ba?a9:aa,bg=bd[bh]();
if(ae(X,[an,aZ])){bd[be]=bi[be];
bd[bf]=bd[be]+bg;
}else{if(ae(X,[aM,l])){bd[bf]=bi[bf];
bd[be]=bd[bf]-bg;
}else{if(X==q){bd[be]=bi[be]+(bi[bh]()-bg)/2;
bd[bf]=bd[be]+bg;
}}}}};
var aN=t.extend({init:function(Y,bd,be,bg,X){var bf=this;
bf.c=Y;
bf.ir=bd;
bf.r=be;
bf.startAngle=bg;
bf.angle=X;
},clone:function(){var X=this;
return new aN(X.c,X.ir,X.r,X.startAngle,X.angle);
},middle:function(){return this.startAngle+this.angle/2;
},radius:function(Y,X){var bd=this;
if(X){bd.ir=Y;
}else{bd.r=Y;
}return bd;
},point:function(X,be){var bh=this,bf=X*M,Y=au.cos(bf),bd=au.sin(bf),bg=be?bh.ir:bh.r,bi=aQ(bh.c.x-(Y*bg),w),bj=aQ(bh.c.y-(bd*bg),w);
return new aI(bi,bj);
},adjacentBox:function(Y,bk,bd){var bj=this.clone().expand(Y),bg=bj.middle(),bh=bj.point(bg),bf=bk/2,be=bd/2,bl=bh.x-bf,bm=bh.y-be,bi=au.sin(bg*M),X=au.cos(bg*M);
if(au.abs(bi)<0.9){bl+=bf*-X/au.abs(X);
}if(au.abs(X)<0.9){bm+=be*-bi/au.abs(bi);
}return new m(bl,bm,bl+bk,bm+bd);
},containsPoint:function(bj){var bl=this,X=bl.c,bi=bl.ir,bk=bl.r,bm=bl.startAngle,bf=bl.startAngle+bl.angle,bd=bj.x-X.x,be=bj.y-X.y,bp=new aI(bd,be),bn=bl.point(bm),bo=new aI(bn.x-X.x,bn.y-X.y),bg=bl.point(bf),bh=new aI(bg.x-X.x,bg.y-X.y),Y=aQ(bd*bd+be*be,w);
return(bo.equals(bp)||v(bo,bp))&&!v(bh,bp)&&Y>=bi*bi&&Y<=bk*bk;
},getBBox:function(){var bj=this,bd=new m(aw,aw,ay,ay),bk=aQ(bj.startAngle%360),be=aQ((bk+bj.angle)%360),bh=bj.ir,X=[0,90,180,270,bk,be].sort(aG),bl=af(bk,X),bf=af(be,X),Y,bg,bi;
if(bk==be){Y=X;
}else{if(bl<bf){Y=X.slice(bl,bf+1);
}else{Y=[].concat(X.slice(0,bf+1),X.slice(bl,X.length));
}}for(bg=0;
bg<Y.length;
bg++){bi=bj.point(Y[bg]);
bd.wrapPoint(bi);
bd.wrapPoint(bi,bh);
}if(!bh){bd.wrapPoint(bj.c);
}return bd;
},expand:function(X){this.r+=X;
return this;
}});
var aR=aN.extend({init:function(Y,bd,be,X){aN.fn.init.call(this,Y,0,bd,be,X);
},expand:function(X){return aN.fn.expand.call(this,X);
},clone:function(){var X=this;
return new aR(X.c,X.r,X.startAngle,X.angle);
},radius:function(X){return aN.fn.radius.call(this,X);
},point:function(X){return aN.fn.point.call(this,X);
}});
var aS=function(){};
aS.fn=aS.prototype={createRing:function(bj,bg){var bk=bj.startAngle+180;
var bd=bj.angle+bk;
var Y=new V.Point(bj.c.x,bj.c.y);
var bi=au.max(bj.r,0);
var bf=au.max(bj.ir,0);
var X=new V.Arc(Y,{startAngle:bk,endAngle:bd,radiusX:bi,radiusY:bi});
var bh=P.Path.fromArc(X,bg).close();
if(bf){X.radiusX=X.radiusY=bf;
var be=X.pointAt(bd);
bh.lineTo(be.x,be.y);
bh.arc(bd,bk,bf,bf,true);
}else{bh.lineTo(Y.x,Y.y);
}return bh;
}};
aS.current=new aS();
var r=t.extend({init:function(Y){var X=this;
X.children=[];
X.options=G({},X.options,Y);
},reflow:function(bg){var be=this,Y=be.children,X,bf,bd;
for(bf=0;
bf<Y.length;
bf++){bd=Y[bf];
bd.reflow(bg);
X=X?X.wrap(bd.box):bd.box.clone();
}be.box=X||bg;
},destroy:function(){var Y=this,X=Y.children,be=Y.getRoot(),bd;
if(this.animation){this.animation.destroy();
}for(bd=0;
bd<X.length;
bd++){X[bd].destroy();
}},getRoot:function(){var X=this.parent;
return X?X.getRoot():null;
},translateChildren:function(bd,be){var bf=this,X=bf.children,Y=X.length,bg;
for(bg=0;
bg<Y;
bg++){X[bg].box.translate(bd,be);
}},append:function(){d(this.children,arguments);
for(var X=0;
X<arguments.length;
X++){arguments[X].parent=this;
}},renderVisual:function(){if(this.options.visible===false){return;
}this.createVisual();
this.addVisual();
this.renderChildren();
this.createAnimation();
this.renderComplete();
},addVisual:function(){if(this.visual){this.visual.chartElement=this;
if(this.parent){this.parent.appendVisual(this.visual);
}}},renderChildren:function(){var X=this.children;
for(var Y=0;
Y<X.length;
Y++){X[Y].renderVisual();
}},createVisual:function(){this.visual=new D.drawing.Group({zIndex:this.options.zIndex,visible:a7(this.options.visible,true)});
},createAnimation:function(){if(this.visual){this.animation=P.Animation.create(this.visual,this.options.animation);
}},appendVisual:function(X){if(!X.chartElement){X.chartElement=this;
}if(X.options.noclip){this.clipRoot().visual.append(X);
}else{if(L(X.options.zIndex)){this.stackRoot().stackVisual(X);
}else{if(this.visual){this.visual.append(X);
}else{this.parent.appendVisual(X);
}}}},clipRoot:function(){if(this.parent){return this.parent.clipRoot();
}return this;
},stackRoot:function(){if(this.parent){return this.parent.stackRoot();
}return this;
},stackVisual:function(X){var bg=X.options.zIndex||0;
var bf=this.visual.children;
for(var bd=0;
bd<bf.length;
bd++){var be=bf[bd];
var Y=a7(be.options.zIndex,0);
if(Y>bg){break;
}}this.visual.insertAt(X,bd);
},traverse:function(X){var bd=this.children;
for(var be=0;
be<bd.length;
be++){var Y=bd[be];
X(Y);
if(Y.traverse){Y.traverse(X);
}}},closest:function(Y){var X=this;
var bd=false;
while(X&&!bd){bd=Y(X);
if(!bd){X=X.parent;
}}if(bd){return X;
}},renderComplete:a.noop,hasHighlight:function(){var X=(this.options||{}).highlight;
return !(!this.createHighlight||(X&&X.visible===false));
},toggleHighlight:function(bf){var bg=this;
var Y=bg._highlight;
var be=(bg.options||{}).highlight;
var X=(be||{}).visual;
if(!Y){var bd={fill:{color:a8,opacity:0.2},stroke:{color:a8,width:1,opacity:0.2}};
if(X){Y=bg._highlight=X(G(bg.highlightVisualArgs(),{createVisual:function(){return bg.createHighlight(bd);
},series:bg.series,dataItem:bg.dataItem,category:bg.category,value:bg.value,percentage:bg.percentage,runningTotal:bg.runningTotal,total:bg.total}));
if(!Y){return;
}}else{Y=bg._highlight=bg.createHighlight(bd);
}Y.options.zIndex=bg.options.zIndex;
bg.appendVisual(Y);
}Y.visible(bf);
},createGradientOverlay:function(X,bd,Y){var be=new P.Path(G({stroke:{color:aA},fill:this.createGradient(Y),closed:X.options.closed},bd));
be.segments.elements(X.segments.elements());
return be;
},createGradient:function(X){if(this.parent){return this.parent.createGradient(X);
}}});
var aO=r.extend({init:function(X){var Y=this;
Y.gradients={};
r.fn.init.call(Y,X);
},options:{width:K,height:I,background:a8,border:{color:k,width:0},margin:Z(5),zIndex:-2},reflow:function(){var bf=this,be=bf.options,X=bf.children,Y=new m(0,0,be.width,be.height);
bf.box=Y.unpad(be.margin);
for(var bd=0;
bd<X.length;
bd++){X[bd].reflow(Y);
Y=n(Y,X[bd].box);
}},createVisual:function(){this.visual=new P.Group();
this.createBackground();
},createBackground:function(){var be=this.options;
var Y=be.border||{};
var bd=this.box.clone().pad(be.margin).unpad(Y.width);
var X=P.Path.fromRect(bd.toRect(),{stroke:{color:Y.width?Y.color:"",width:Y.width,dashType:Y.dashType},fill:{color:be.background,opacity:be.opacity},zIndex:-10});
this.visual.append(X);
},getRoot:function(){return this;
},createGradient:function(bg){var be=this.gradients;
var bf=a6.objectKey(bg);
var Y=D.Gradients[bg.gradient];
var X;
if(be[bf]){X=be[bf];
}else{var bd=G({},Y,bg);
if(Y.type=="linear"){X=new P.LinearGradient(bd);
}else{if(bg.innerRadius){bd.stops=ah(bd);
}X=new P.RadialGradient(bd);
X.supportVML=Y.supportVML!==false;
}be[bf]=X;
}return X;
}});
var o=r.extend({options:{align:an,vAlign:aZ,margin:{},padding:{},border:{color:k,width:0},background:"",shrinkToFit:false,width:0,height:0,visible:true},reflow:function(bp){var bf=this,Y,be,bl=bf.options,bq=bl.width,bh=bl.height,bg=bq&&bh,bo=bl.shrinkToFit,bk=Z(bl.margin),bm=Z(bl.padding),X=bl.border.width,bd=bf.children,bi,bj;
function bn(){bf.align(bp,ba,bl.align);
bf.align(bp,bb,bl.vAlign);
bf.paddingBox=Y.clone().unpad(bk).unpad(X);
}be=bp.clone();
if(bg){be.x2=be.x1+bq;
be.y2=be.y1+bh;
}if(bo){be.unpad(bk).unpad(X).unpad(bm);
}r.fn.reflow.call(bf,be);
if(bg){Y=bf.box=m(0,0,bq,bh);
}else{Y=bf.box;
}if(bo&&bg){bn();
be=bf.contentBox=bf.paddingBox.clone().unpad(bm);
}else{be=bf.contentBox=Y.clone();
Y.pad(bm).pad(X).pad(bk);
bn();
}bf.translateChildren(Y.x1-be.x1+bk.left+X+bm.left,Y.y1-be.y1+bk.top+X+bm.top);
for(bi=0;
bi<bd.length;
bi++){bj=bd[bi];
bj.reflow(bj.box);
}},align:function(bd,Y,X){this.box.align(bd,Y,X);
},hasBox:function(){var X=this.options;
return X.border.width||X.background;
},createVisual:function(){r.fn.createVisual.call(this);
var X=this.options;
if(X.visible&&this.hasBox()){this.visual.append(P.Path.fromRect(this.paddingBox.toRect(),this.visualStyle()));
}},visualStyle:function(){var Y=this,bd=Y.options,X=bd.border||{};
return{stroke:{width:X.width,color:X.color,opacity:a7(X.opacity,bd.opacity),dashType:X.dashType},fill:{color:bd.background,opacity:bd.opacity},cursor:bd.cursor};
}});
var aW=r.extend({init:function(X,Y){var bd=this;
r.fn.init.call(bd,Y);
bd.content=X;
bd.reflow(m());
},options:{font:H,color:k,align:an,vAlign:""},reflow:function(be){var bf=this,Y=bf.options,bd,X;
bd=Y.size=ax(bf.content,{font:Y.font});
bf.baseline=bd.baseline;
bf.box=m(be.x1,be.y1,be.x1+bd.width,be.y1+bd.height);
},createVisual:function(){var X=this.options;
this.visual=new P.Text(this.content,this.box.toRect().topLeft(),{font:X.font,fill:{color:X.color,opacity:X.opacity},cursor:X.cursor});
}});
var S=r.extend({init:function(X){r.fn.init.call(this,X);
this._initDirection();
},_initDirection:function(){var X=this.options;
if(X.vertical){this.groupAxis=ba;
this.elementAxis=bb;
this.groupSizeField=a9;
this.elementSizeField=aa;
this.groupSpacing=X.spacing;
this.elementSpacing=X.vSpacing;
}else{this.groupAxis=bb;
this.elementAxis=ba;
this.groupSizeField=aa;
this.elementSizeField=a9;
this.groupSpacing=X.vSpacing;
this.elementSpacing=X.spacing;
}},options:{vertical:true,wrap:true,vSpacing:0,spacing:0},reflow:function(X){this.box=X.clone();
this.reflowChildren();
},reflowChildren:function(){var bj=this;
var X=bj.box;
var by=bj.options;
var bh=bj.elementSpacing;
var bu=bj.groupSpacing;
var bd=bj.elementAxis;
var bl=bj.groupAxis;
var bg=bj.elementSizeField;
var bt=bj.groupSizeField;
var bq=bj.groupOptions();
var br=bq.groups;
var bs=br.length;
var bv=X[bl+1]+bj.alignStart(bq.groupsSize,X[bt]());
var bw=bv;
var bi;
var bo;
var bk;
var bm;
var bn;
var bx;
var bp;
var Y;
var be;
var bf;
if(bs){for(bp=0;
bp<bs;
bp++){bk=br[bp];
bm=bk.groupElements;
bn=bm.length;
bi=X[bd+1];
for(bx=0;
bx<bn;
bx++){Y=bm[bx];
bf=bj.elementSize(Y);
bo=bw+bj.alignStart(bf[bt],bk.groupSize);
be=m();
be[bl+1]=bo;
be[bl+2]=bo+bf[bt];
be[bd+1]=bi;
be[bd+2]=bi+bf[bg];
Y.reflow(be);
bi+=bf[bg]+bj.elementSpacing;
}bw+=bk.groupSize+bj.groupSpacing;
}X[bl+1]=bv;
X[bl+2]=bv+bq.groupsSize;
X[bd+2]=X[bd+1]+bq.maxGroupElementsSize;
}},alignStart:function(bd,Y){var be=0;
var X=this.options.align;
if(X==aM||X==l){be=Y-bd;
}else{if(X==q){be=(Y-bd)/2;
}}return be;
},groupOptions:function(){var bi=this;
var X=bi.box;
var Y=bi.children;
var bd=Y.length;
var bg=this.elementSizeField;
var bn=this.groupSizeField;
var bh=this.elementSpacing;
var bo=this.groupSpacing;
var bs=aQ(X[bg]());
var bq=0;
var bm=0;
var bf;
var be;
var bk=0;
var bp=0;
var bl=[];
var bj=[];
var br=0;
for(bq=0;
bq<bd;
bq++){be=Y[bq];
if(!be.box){be.reflow(X);
}bf=this.elementSize(be);
if(bi.options.wrap&&aQ(bk+bh+bf[bg])>bs){bl.push({groupElements:bj,groupSize:bm,groupElementsSize:bk});
br=au.max(br,bk);
bp+=bo+bm;
bm=0;
bk=0;
bj=[];
}bm=au.max(bm,bf[bn]);
if(bk>0){bk+=bh;
}bk+=bf[bg];
bj.push(be);
}bl.push({groupElements:bj,groupSize:bm,groupElementsSize:bk});
br=au.max(br,bk);
bp+=bm;
return{groups:bl,groupsSize:bp,maxGroupElementsSize:br};
},elementSize:function(X){return{width:X.box.width(),height:X.box.height()};
},createVisual:aB});
var aX=o.extend({ROWS_SPLIT_REGEX:/\n|\\n/m,init:function(X,Y){var bd=this;
bd.content=X;
o.fn.init.call(bd,Y);
bd._initContainer();
bd.reflow(m());
},_initContainer:function(){var bh=this;
var bd=bh.options;
var bf=(bh.content+"").split(bh.ROWS_SPLIT_REGEX);
var X=new S({vertical:true,align:bd.align,wrap:false});
var bi=G({},bd,{opacity:1,animation:null});
var Y=bh.hasBox();
var bg;
var be;
bh.container=X;
bh.append(X);
for(be=0;
be<bf.length;
be++){bg=new aW(a1(bf[be]),bi);
X.append(bg);
}},reflow:function(bg){var bh=this;
var be=bh.options;
var bi=be.visual;
var X=be.align;
var bf=be.rotation;
bh.container.options.align=X;
if(bi&&!bh._boxReflow&&bg.hasSize()){bh.visual=bi({text:bh.content,rect:bg.toRect(),options:bh.visualOptions(),createVisual:function(){bh._boxReflow=true;
bh.reflow(bg);
bh._boxReflow=false;
return bh.getDefaultVisual();
}});
var bj=bg;
if(bh.visual){bj=aK(bh.visual.clippedBBox()||new V.Rect());
}bh.box=bh.contentBox=bh.paddingBox=bj;
}else{o.fn.reflow.call(bh,bg);
if(bf){var bd=be.margin;
var Y=bh.box.unpad(bd);
bh.normalBox=Y.clone();
Y.rotate(bf);
Y.pad(bd);
bh.align(bg,ba,X);
bh.align(bg,bb,be.vAlign);
}}},createVisual:function(){var Y=this.options;
if(!Y.visible){return;
}this.visual=new D.drawing.Group({transform:this.rotationTransform(),zIndex:Y.zIndex,noclip:Y.noclip});
if(this.hasBox()){var X=P.Path.fromRect(this.paddingBox.toRect(),this.visualStyle());
this.visual.append(X);
}},renderVisual:function(){if(this.options.visual){this.addVisual();
}else{o.fn.renderVisual.call(this);
}},visualOptions:function(){var X=this.options;
return{background:X.background,border:X.border,color:X.color,font:X.font,margin:X.margin,padding:X.padding,visible:X.visible};
},getDefaultVisual:function(){this.createVisual();
this.renderChildren();
var X=this.visual;
delete this.visual;
return X;
},rotationTransform:function(){var bf=this.options.rotation;
if(!bf){return null;
}var Y=this.normalBox.center();
var bd=Y.x;
var be=Y.y;
var X=this.box.center();
return V.transform().translate(X.x-bd,X.y-be).rotate(bf,[bd,be]);
},rotationMatrix:function(){var bk=this;
var bj=bk.options;
var bg=bk.normalBox;
var Y=bg.center();
var bd=Y.x;
var be=Y.y;
var X=bk.box.center();
var bh=X.x-bd;
var bi=X.y-be;
var bf=av.translate(bh,bi).times(av.rotate(bj.rotation,bd,be));
return bf;
}});
var aY=r.extend({init:function(X){var Y=this;
r.fn.init.call(Y,X);
X=Y.options;
Y.append(new aX(X.text,G({},X,{vAlign:X.position})));
},options:{color:k,position:aZ,align:q,margin:Z(5),padding:Z(5)},reflow:function(X){var Y=this;
r.fn.reflow.call(Y,X);
Y.box.snapTo(X,ba);
}});
aY.buildTitle=function(Y,bd,X){var be;
if(typeof Y==="string"){Y={text:Y};
}Y=G({visible:true},X,Y);
if(Y&&Y.visible&&Y.text){be=new aY(Y);
bd.append(be);
}return be;
};
var i=aX.extend({init:function(bg,bf,Y,X,be){var bd=this;
bd.text=bf;
bd.value=bg;
bd.index=Y;
bd.dataItem=X;
aX.fn.init.call(bd,bf,be);
},click:function(bd,X){var Y=this;
bd.trigger(h,{element:a(X.target),value:Y.value,text:Y.text,index:Y.index,dataItem:Y.dataItem,axis:Y.parent.options});
}});
function z(X,be){var bf=X.tickX,bg=X.tickY,Y=X.position;
var bd=new P.Path({stroke:{width:be.width,color:be.color}});
if(X.vertical){bd.moveTo(bf,Y).lineTo(bf+be.size,Y);
}else{bd.moveTo(Y,bg).lineTo(Y,bg+be.size);
}b(bd);
return bd;
}function y(bg,Y){var bf=bg.lineStart,be=bg.lineEnd,bh=bg.position,bi,X;
var bd=new P.Path({stroke:{width:Y.width,color:Y.color,dashType:Y.dashType}});
if(bg.vertical){bd.moveTo(bf,bh).lineTo(be,bh);
}else{bd.moveTo(bh,bf).lineTo(bh,be);
}b(bd);
return bd;
}var g=r.extend({init:function(Y){var X=this;
r.fn.init.call(X,Y);
if(!X.options.visible){X.options=G({},X.options,{labels:{visible:false},line:{visible:false},margin:0,majorTickSize:0,minorTickSize:0});
}X.options.minorTicks=G({},{color:X.options.line.color,width:X.options.line.width,visible:X.options.minorTickType!=aA},X.options.minorTicks,{size:X.options.minorTickSize,align:X.options.minorTickType});
X.options.majorTicks=G({},{color:X.options.line.color,width:X.options.line.width,visible:X.options.majorTickType!=aA},X.options.majorTicks,{size:X.options.majorTickSize,align:X.options.majorTickType});
X.createLabels();
X.createTitle();
X.createNotes();
},options:{labels:{visible:true,rotation:0,mirror:false,step:1,skip:0},line:{width:1,color:k,visible:true},title:{visible:true,position:q},majorTicks:{align:aH,size:4,skip:0,step:1},minorTicks:{align:aH,size:3,skip:0,step:1},axisCrossingValue:0,majorTickType:aH,minorTickType:aA,majorGridLines:{skip:0,step:1},minorGridLines:{visible:false,width:1,color:k,skip:0,step:1},margin:5,visible:true,reverse:false,justified:true,notes:{label:{text:""}},_alignLines:true},createLabels:function(){var Y=this,bh=Y.options,X=bh.vertical?aM:q,bf=G({},bh.labels,{align:X,zIndex:bh.zIndex}),bi=bf.step;
Y.labels=[];
if(bf.visible){var bg=Y.labelsCount(),be,bd;
for(bd=bf.skip;
bd<bg;
bd+=bi){be=Y.createAxisLabel(bd,bf);
if(be){Y.append(be);
Y.labels.push(be);
}}}},lineBox:function(){var X=this,bk=X.options,be=X.box,bm=bk.vertical,bh=X.labels,bi=bm?aa:a9,bg=bk.justified,bj=bk.labels.mirror,Y=bj?be.x1:be.x2,bd=bj?be.y2:be.y1,bl=0,bf=bk.line.width;
if(bg&&bh.length>1){bl=bh[0].box[bi]()/2;
bf=am(bh).box[bi]()/2;
}return bm?m(Y,be.y1+bl,Y,be.y2-bf):m(be.x1+bl,bd,be.x2-bf,bd);
},createTitle:function(){var X=this,Y=X.options,be=G({rotation:Y.vertical?-90:0,text:"",zIndex:1,visualSize:true},Y.title),bd;
if(be.visible&&be.text){bd=new aX(be.text,be);
X.append(bd);
X.title=bd;
}},createNotes:function(){var X=this,bi=X.options,bg=bi.notes,be=bg.data||[],bh,Y,bj,bd,bf;
X.notes=[];
for(Y=0;
Y<be.length;
Y++){bd=G({},bg,be[Y]);
bd.value=X.parseNoteValue(bd.value);
bf=new aC(bd.value,bd.label.text,null,null,null,bd);
if(bf.options.visible){if(L(bf.options.position)){if(bi.vertical&&!ae(bf.options.position,[an,aM])){bf.options.position=bi.reverse?an:aM;
}else{if(!bi.vertical&&!ae(bf.options.position,[aZ,l])){bf.options.position=bi.reverse?l:aZ;
}}}else{if(bi.vertical){bf.options.position=bi.reverse?an:aM;
}else{bf.options.position=bi.reverse?l:aZ;
}}X.append(bf);
X.notes.push(bf);
}}},parseNoteValue:function(X){return X;
},renderVisual:function(){r.fn.renderVisual.call(this);
this.createPlotBands();
},createVisual:function(){r.fn.createVisual.call(this);
this.createBackground();
this.createLine();
},gridLinesVisual:function(){var X=this._gridLines;
if(!X){X=this._gridLines=new P.Group({zIndex:-2});
this.appendVisual(this._gridLines);
}return X;
},createTicks:function(be){var X=this,bh=X.options,bd=X.lineBox(),bg=bh.labels.mirror,bf=bh.majorTicks.visible?bh.majorUnit:0,bk={vertical:bh.vertical},bj,Y;
function bi(bp,bo,bn){var bm,bl=bp.length;
if(bo.visible){for(bm=bo.skip;
bm<bl;
bm+=bo.step){if(L(bn)&&(bm%bn===0)){continue;
}bk.tickX=bg?bd.x2:bd.x2-bo.size;
bk.tickY=bg?bd.y1-bo.size:bd.y1;
bk.position=bp[bm];
be.append(z(bk,bo));
}}}bi(X.getMajorTickPositions(),bh.majorTicks);
bi(X.getMinorTickPositions(),bh.minorTicks,bf/bh.minorUnit);
},createLine:function(){var X=this,bg=X.options,bd=bg.line,be=X.lineBox(),bf;
if(bd.width>0&&bd.visible){var bh=new P.Path({stroke:{width:bd.width,color:bd.color,dashType:bd.dashType}});
bh.moveTo(be.x1,be.y1).lineTo(be.x2,be.y2);
if(bg._alignLines){b(bh);
}var Y=this._lineGroup=new P.Group();
Y.append(bh);
this.visual.append(Y);
this.createTicks(Y);
}},getActualTickSize:function(){var X=this,Y=X.options,bd=0;
if(Y.majorTicks.visible&&Y.minorTicks.visible){bd=au.max(Y.majorTicks.size,Y.minorTicks.size);
}else{if(Y.majorTicks.visible){bd=Y.majorTicks.size;
}else{if(Y.minorTicks.visible){bd=Y.minorTicks.size;
}}}return bd;
},createBackground:function(){var X=this,be=X.options,Y=be.background,bd=X.box;
if(Y){X._backgroundPath=P.Path.fromRect(bd.toRect(),{fill:{color:Y},stroke:null});
this.visual.append(X._backgroundPath);
}},createPlotBands:function(){var Y=this,bf=Y.options,bh=bf.plotBands||[],bm=bf.vertical,bg=Y.plotArea,bj,bk,bd,bl;
if(bh.length===0){return;
}var be=this._plotbandGroup=new P.Group({zIndex:-1});
var X=a.grep(Y.pane.axes,function(bn){return bn.options.vertical!==Y.options.vertical;
})[0];
var bi=this.range();
a.each(bh,function(bp,bq){bd=a7(bq.from,ay);
bl=a7(bq.to,aw);
var bo=[];
if(ak(bd,bi)||ak(bl,bi)){if(bm){bj=(X||bg.axisX).lineBox();
bk=Y.getSlot(bq.from,bq.to,true);
}else{bj=Y.getSlot(bq.from,bq.to,true);
bk=(X||bg.axisY).lineBox();
}var bn=new V.Rect([bj.x1,bk.y1],[bj.width(),bk.height()]);
var br=P.Path.fromRect(bn,{fill:{color:bq.color,opacity:bq.opacity},stroke:null});
be.append(br);
}});
Y.appendVisual(be);
},createGridLines:function(X){var Y=this,bl=Y.options,bd=X.options.line.visible,bi=bl.majorGridLines,bk=bi.visible?bl.majorUnit:0,bo=bl.vertical,bf=X.lineBox(),bh=bf[bo?"y1":"x1"],bg={lineStart:bf[bo?"x1":"y1"],lineEnd:bf[bo?"x2":"y2"],vertical:bo},bm,bj=[];
var be=this.gridLinesVisual();
function bn(bt,bq,bs){var bp=bt.length,br;
if(bq.visible){for(br=bq.skip;
br<bp;
br+=bq.step){bm=aQ(bt[br]);
if(!ae(bm,bj)){if(br%bs!==0&&(!bd||bh!==bm)){bg.position=bm;
be.append(y(bg,bq));
bj.push(bm);
}}}}}bn(Y.getMajorTickPositions(),bl.majorGridLines);
bn(Y.getMinorTickPositions(),bl.minorGridLines,bk/bl.minorUnit);
return be.children;
},reflow:function(Y){var X=this,bj=X.options,bm=bj.vertical,bg=X.labels,bd=bg.length,bk=X.getActualTickSize()+bj.margin,bh=0,bi=0,bl=X.title,bf,be;
for(be=0;
be<bd;
be++){bf=bg[be];
bh=au.max(bh,bf.box.height());
bi=au.max(bi,bf.box.width());
}if(bl){if(bm){bi+=bl.box.width();
}else{bh+=bl.box.height();
}}if(bm){X.box=m(Y.x1,Y.y1,Y.x1+bi+bk,Y.y2);
}else{X.box=m(Y.x1,Y.y1,Y.x2,Y.y1+bh+bk);
}X.arrangeTitle();
X.arrangeLabels();
X.arrangeNotes();
},arrangeLabels:function(){var X=this,br=X.options,bi=X.labels,bj=!br.justified,bu=br.vertical,bn=X.lineBox(),bp=br.labels.mirror,bt=X.getMajorTickPositions(),bg=X.getActualTickSize()+br.margin,bf,bm,bd;
for(bd=0;
bd<bi.length;
bd++){var be=bi[bd],bs=be.index,bk=bu?be.box.height():be.box.width(),bh=bt[bs]-(bk/2),Y,bq,bo,bl;
if(bu){if(bj){Y=bt[bs];
bq=bt[bs+1];
bo=Y+(bq-Y)/2;
bh=bo-(bk/2);
}bl=bn.x2;
if(bp){bl+=bg;
}else{bl-=bg+be.box.width();
}bf=be.box.move(bl,bh);
}else{if(bj){Y=bt[bs];
bq=bt[bs+1];
}else{Y=bh;
bq=bh+bk;
}bm=bn.y1;
if(bp){bm-=bg+be.box.height();
}else{bm+=bg;
}bf=m(Y,bm,bq,bm+be.box.height());
}be.reflow(bf);
}},arrangeTitle:function(){var X=this,bd=X.options,Y=bd.labels.mirror,bf=bd.vertical,be=X.title;
if(be){if(bf){be.options.align=Y?aM:an;
be.options.vAlign=be.options.position;
}else{be.options.align=be.options.position;
be.options.vAlign=Y?aZ:l;
}be.reflow(X.box);
}},arrangeNotes:function(){var X=this,Y,bd,be,bf;
for(Y=0;
Y<X.notes.length;
Y++){bd=X.notes[Y];
bf=bd.options.value;
if(L(bf)){if(X.shouldRenderNote(bf)){bd.show();
}else{bd.hide();
}be=X.getSlot(bf);
}else{bd.hide();
}bd.reflow(be||X.lineBox());
}},alignTo:function(be){var X=this,Y=be.lineBox(),bf=X.options.vertical,bd=bf?bb:ba;
X.box.snapTo(Y,bd);
if(bf){X.box.shrink(0,X.lineBox().height()-Y.height());
}else{X.box.shrink(X.lineBox().width()-Y.width(),0);
}X.box[bd+1]-=X.lineBox()[bd+1]-Y[bd+1];
X.box[bd+2]-=X.lineBox()[bd+2]-Y[bd+2];
},axisLabelText:function(bf,X,Y){var bd=bf;
if(Y.template){var be=aV(Y.template);
bd=be({value:bf,dataItem:X,format:Y.format,culture:Y.culture});
}else{if(Y.format){if(Y.format.match(U)){bd=al.format(Y.format,bf);
}else{bd=al.toString(bf,Y.format,Y.culture);
}}}return bd;
},slot:function(X,bd){var Y=this.getSlot(X,bd);
if(Y){return Y.toRect();
}}});
var aC=o.extend({init:function(bh,bg,Y,X,bf,be){var bd=this;
o.fn.init.call(bd,be);
bd.value=bh;
bd.text=bg;
bd.dataItem=Y;
bd.category=X;
bd.series=bf;
bd.render();
},options:{icon:{visible:true,type:s},label:{position:ai,visible:true,align:q,vAlign:q},line:{visible:true},visible:true,position:aZ,zIndex:2},hide:function(){this.options.visible=false;
},show:function(){this.options.visible=true;
},render:function(){var bg=this,bi=bg.options,be=bi.label,bk=bg.text,bd=bi.icon,bj=bd.size,X=m(),bf,bl,Y,bh;
if(bi.visible){if(L(be)&&be.visible){if(be.template){bh=aV(be.template);
bk=bh({dataItem:bg.dataItem,category:bg.category,value:bg.value,text:bk,series:bg.series});
}else{if(be.format){bk=e(be.format,bk);
}}bg.label=new aX(bk,G({},be));
if(be.position===ai){if(bd.type===s){bj=au.max(bg.label.box.width(),bg.label.box.height());
}else{bl=bg.label.box.width();
Y=bg.label.box.height();
}X.wrap(bg.label.box);
}}bd.width=bl||bj;
bd.height=Y||bj;
bf=new aT(G({},bd));
bg.marker=bf;
bg.append(bf);
if(bg.label){bg.append(bg.label);
}bf.reflow(m());
bg.wrapperBox=X.wrap(bf.box);
}},reflow:function(bl){var bi=this,bj=bi.options,Y=bl.center(),bm=bi.wrapperBox,bf=bj.line.length,bk=bj.position,be=bi.label,bh=bi.marker,bg,X,bd;
if(bj.visible){if(ae(bk,[an,aM])){if(bk===an){bd=bm.alignTo(bl,bk).translate(-bf,bl.center().y-bm.center().y);
if(bj.line.visible){bg=[au.floor(bl.x1),Y.y];
bi.linePoints=[bg,[au.floor(bd.x2),Y.y]];
X=bd.clone().wrapPoint(bg);
}}else{bd=bm.alignTo(bl,bk).translate(bf,bl.center().y-bm.center().y);
if(bj.line.visible){bg=[au.floor(bl.x2),Y.y];
bi.linePoints=[bg,[au.floor(bd.x1),Y.y]];
X=bd.clone().wrapPoint(bg);
}}}else{if(bk===l){bd=bm.alignTo(bl,bk).translate(bl.center().x-bm.center().x,bf);
if(bj.line.visible){bg=[au.floor(Y.x),au.floor(bl.y2)];
bi.linePoints=[bg,[au.floor(Y.x),au.floor(bd.y1)]];
X=bd.clone().wrapPoint(bg);
}}else{bd=bm.alignTo(bl,bk).translate(bl.center().x-bm.center().x,-bf);
if(bj.line.visible){bg=[au.floor(Y.x),au.floor(bl.y1)];
bi.linePoints=[bg,[au.floor(Y.x),au.floor(bd.y2)]];
X=bd.clone().wrapPoint(bg);
}}}if(bh){bh.reflow(bd);
}if(be){be.reflow(bd);
if(bh){if(bj.label.position===aH){be.box.alignTo(bh.box,bk);
}be.reflow(be.box);
}}bi.contentBox=bd;
bi.targetBox=bl;
bi.box=X||bd;
}},createVisual:function(){o.fn.createVisual.call(this);
if(this.options.visible){this.createLine();
}},renderVisual:function(){var be=this;
var Y=be.options;
var X=Y.visual;
if(Y.visible&&X){var bd=be.targetPoint;
be.visual=X({dataItem:be.dataItem,category:be.category,value:be.value,text:be.text,series:be.series,rect:be.targetBox.toRect(),options:{background:Y.background,border:Y.background,icon:Y.icon,label:Y.label,line:Y.line,position:Y.position,visible:Y.visible},createVisual:function(){be.createVisual();
be.renderChildren();
var bf=be.visual;
delete be.visual;
return bf;
}});
be.addVisual();
}else{o.fn.renderVisual.call(be);
}},createLine:function(){var X=this.options.line;
if(this.linePoints){var Y=P.Path.fromPoints(this.linePoints,{stroke:{color:X.color,width:X.width,dashType:X.dashType}});
this.visual.append(Y);
}},click:function(bd,Y){var X=this.eventArgs(Y);
if(!bd.trigger(aD,X)){Y.preventDefault();
}},hover:function(bd,Y){var X=this.eventArgs(Y);
if(!bd.trigger(aE,X)){Y.preventDefault();
}},leave:function(X){X._unsetActivePoint();
},eventArgs:function(X){var Y=this,bd=Y.options;
return{element:a(X.target),text:L(bd.label)?bd.label.text:"",dataItem:Y.dataItem,series:Y.series,value:Y.value,category:Y.category};
}});
var aT=o.extend({init:function(X,Y){this.pointData=Y;
o.fn.init.call(this,X);
},options:{type:s,align:q,vAlign:q},getElement:function(){var bg=this,bh=bg.options,bl=bh.type,bj=bh.rotation,X=bg.paddingBox,bd,Y=X.center(),be=X.width()/2,bi,bf;
if(!bh.visible||!bg.hasBox()){return;
}var bk=bg.visualStyle();
if(bl===s){bd=new P.Circle(new V.Circle([aQ(X.x1+be,w),aQ(X.y1+X.height()/2,w)],be),bk);
}else{if(bl===a0){bd=P.Path.fromPoints([[X.x1+be,X.y1],[X.x1,X.y2],[X.x2,X.y2]],bk).close();
}else{if(bl===A){bd=new P.MultiPath(bk);
bd.moveTo(X.x1,X.y1).lineTo(X.x2,X.y2);
bd.moveTo(X.x1,X.y2).lineTo(X.x2,X.y1);
}else{bd=P.Path.fromRect(X.toRect(),bk);
}}}if(bj){bd.transform(V.transform().rotate(-bj,[Y.x,Y.y]));
}bd.options.zIndex=this.options.zIndex;
return bd;
},createElement:function(){var bd=this;
var X=bd.options.visual;
var Y=bd.pointData||{};
var be;
if(X){be=X({value:Y.value,dataItem:Y.dataItem,series:Y.series,category:Y.category,rect:bd.paddingBox.toRect(),options:bd.visualOptions(),createVisual:function(){return bd.getElement();
}});
}else{be=bd.getElement();
}return be;
},visualOptions:function(){var X=this.options;
return{background:X.background,border:X.border,margin:X.margin,padding:X.padding,type:X.type,size:X.width,visible:X.visible};
},createVisual:function(){this.visual=this.createElement();
}});
var aF=g.extend({init:function(bf,be,bd){var X=this,Y=X.initDefaults(bf,be,bd);
g.fn.init.call(X,Y);
},startValue:function(){return 0;
},options:{type:"numeric",min:0,max:1,vertical:true,majorGridLines:{visible:true,width:1,color:k},zIndex:1},initDefaults:function(bj,bi,bh){var be=this,bg=bh.narrowRange,Y=be.autoAxisMin(bj,bi,bg),X=be.autoAxisMax(bj,bi,bg),bf=f(Y,X),bd={majorUnit:bf},bk;
if(bh.roundToMajorUnit!==false){if(Y<0&&aL(Y,bf,1/3)){Y-=bf;
}if(X>0&&aL(X,bf,1/3)){X+=bf;
}}bd.min=T(Y,bf);
bd.max=p(X,bf);
if(bh){bk=L(bh.min)||L(bh.max);
if(bk){if(bh.min===bh.max){if(bh.min>0){bh.min=0;
}else{bh.max=1;
}}}if(bh.majorUnit){bd.min=T(bd.min,bh.majorUnit);
bd.max=p(bd.max,bh.majorUnit);
}else{if(bk){bh=G(bd,bh);
bd.majorUnit=f(bh.min,bh.max);
}}}bd.minorUnit=(bh.majorUnit||bd.majorUnit)/5;
return G(bd,bh);
},range:function(){var X=this.options;
return{min:X.min,max:X.max};
},autoAxisMax:function(be,bd,bf){var X,Y;
if(!be&&!bd){return 1;
}if(be<=0&&bd<=0){bd=be==bd?0:bd;
Y=au.abs((bd-be)/bd);
if(bf===false||(!bf&&Y>bc)){return 0;
}X=au.min(0,bd-((be-bd)/2));
}else{be=be==bd?0:be;
X=bd;
}return X;
},autoAxisMin:function(be,bd,bf){var X,Y;
if(!be&&!bd){return 0;
}if(be>=0&&bd>=0){be=be==bd?0:be;
Y=(bd-be)/bd;
if(bf===false||(!bf&&Y>bc)){return 0;
}X=au.max(0,be-((bd-be)/2));
}else{bd=be==bd?0:bd;
X=be;
}return X;
},getDivisions:function(bd){if(bd===0){return 1;
}var X=this.options,Y=X.max-X.min;
return au.floor(aQ(Y/bd,w))+1;
},getTickPositions:function(br,bo){var X=this,bh=X.options,bs=bh.vertical,bl=bh.reverse,bf=X.lineBox(),bg=bs?bf.height():bf.width(),bk=bh.max-bh.min,bm=bg/bk,bq=br*bm,bn=0,bd=X.getDivisions(br),Y=(bs?-1:1)*(bl?-1:1),bp=Y===1?1:2,bi=bf[(bs?bb:ba)+bp],bj=[],be;
if(bo){bn=bo/br;
}for(be=0;
be<bd;
be++){if(be%bn!==0){bj.push(aQ(bi,w));
}bi=bi+bq*Y;
}return bj;
},getMajorTickPositions:function(){var X=this;
return X.getTickPositions(X.options.majorUnit);
},getMinorTickPositions:function(){var X=this;
return X.getTickPositions(X.options.minorUnit);
},getSlot:function(X,bd,bf){var Y=this,bj=Y.options,bm=bj.reverse,bq=bj.vertical,bp=bq?bb:ba,bg=Y.lineBox(),bi=bg[bp+(bm?2:1)],bh=bq?bg.height():bg.width(),be=bm?-1:1,bo=be*(bh/(bj.max-bj.min)),bk,bl,bn=new m(bg.x1,bg.y1,bg.x1,bg.y1);
if(!L(X)){X=bd||0;
}if(!L(bd)){bd=X||0;
}if(bf){X=au.max(au.min(X,bj.max),bj.min);
bd=au.max(au.min(bd,bj.max),bj.min);
}if(bq){bk=bj.max-au.max(X,bd);
bl=bj.max-au.min(X,bd);
}else{bk=au.min(X,bd)-bj.min;
bl=au.max(X,bd)-bj.min;
}bn[bp+1]=au.max(au.min(bi+bo*(bm?bl:bk),x),-x);
bn[bp+2]=au.max(au.min(bi+bo*(bm?bk:bl),x),-x);
return bn;
},getValue:function(bk){var X=this,bj=X.options,bl=bj.reverse,bq=bj.vertical,bg=bj.max*1,bh=bj.min*1,bo=bq?bb:ba,bd=X.lineBox(),bf=bd[bo+(bl?2:1)],be=bq?bd.height():bd.width(),Y=bl?-1:1,bi=Y*(bk[bo]-bf),bm=(bg-bh)/be,bp=bi*bm,bn;
if(bi<0||bi>be){return null;
}bn=bq?bg-bp:bh+bp;
return aQ(bn,J);
},translateRange:function(Y){var X=this,bf=X.options,bd=X.lineBox(),bk=bf.vertical,bh=bf.reverse,bj=bk?bd.height():bd.width(),bg=bf.max-bf.min,bi=bj/bg,be=aQ(Y/bi,J);
if((bk||bh)&&!(bk&&bh)){be=-be;
}return{min:bf.min+be,max:bf.max+be};
},scaleRange:function(Y){var X=this,be=X.options,bd=-Y*be.majorUnit;
return{min:be.min-bd,max:be.max+bd};
},labelsCount:function(){return this.getDivisions(this.options.majorUnit);
},createAxisLabel:function(Y,bd){var X=this,be=X.options,bg=aQ(be.min+(Y*be.majorUnit),J),bf=X.axisLabelText(bg,null,bd);
return new i(bg,bf,Y,null,bd);
},shouldRenderNote:function(Y){var X=this.range();
return X.min<=Y&&Y<=X.max;
}});
var ar=g.extend({init:function(bd,Y,X){this.options=this._initOptions(bd,Y,X);
g.fn.init.call(this,X);
},startValue:function(){return this.options.min;
},options:{type:"log",majorUnit:10,minorUnit:1,axisCrossingValue:1,vertical:true,majorGridLines:{visible:true,width:1,color:k},zIndex:1},getSlot:function(X,bd,bg){var Y=this,bm=Y.options,bp=bm.reverse,bt=bm.vertical,bs=bt?bb:ba,bh=Y.lineBox(),bj=bh[bs+(bp?2:1)],bi=bt?bh.height():bh.width(),bf=bp?-1:1,be=bm.majorUnit,bl=Y.logMin,bk=Y.logMax,br=bf*(bi/(bk-bl)),bn,bo,bq=new m(bh.x1,bh.y1,bh.x1,bh.y1);
if(!L(X)){X=bd||1;
}if(!L(bd)){bd=X||1;
}if(X<=0||bd<=0){return;
}if(bg){X=au.max(au.min(X,bm.max),bm.min);
bd=au.max(au.min(bd,bm.max),bm.min);
}X=aq(X,be);
bd=aq(bd,be);
if(bt){bn=bk-au.max(X,bd);
bo=bk-au.min(X,bd);
}else{bn=au.min(X,bd)-bl;
bo=au.max(X,bd)-bl;
}bq[bs+1]=bj+br*(bp?bo:bn);
bq[bs+2]=bj+br*(bp?bn:bo);
return bq;
},getValue:function(bl){var X=this,bk=X.options,bm=bk.reverse,bs=bk.vertical,be=X.lineBox(),Y=bk.majorUnit,bi=X.logMin,bh=X.logMax,bd=bs===bm?1:-1,bn=bd===1?1:2,bf=bs?be.height():be.width(),bo=((bh-bi)/bf),bq=bs?bb:ba,bg=be[bq+bn],bj=bd*(bl[bq]-bg),br=bj*bo,bp;
if(bj<0||bj>bf){return null;
}bp=bi+br;
return aQ(au.pow(Y,bp),J);
},range:function(){var X=this.options;
return{min:X.min,max:X.max};
},scaleRange:function(bd){var X=this,bf=X.options,Y=bf.majorUnit,be=-bd;
return{min:au.pow(Y,X.logMin-be),max:au.pow(Y,X.logMax+be)};
},translateRange:function(bd){var X=this,bi=X.options,Y=bi.majorUnit,be=X.lineBox(),bm=bi.vertical,bj=bi.reverse,bl=bm?be.height():be.width(),bg=X.logMin,bf=X.logMax,bk=bl/(X.logMax-X.logMin),bh=aQ(bd/bk,J);
if((bm||bj)&&!(bm&&bj)){bh=-bh;
}return{min:au.pow(Y,X.logMin+bh),max:au.pow(Y,X.logMax+bh)};
},labelsCount:function(){var X=this,bd=au.floor(X.logMax),Y=au.floor(bd-X.logMin)+1;
return Y;
},getMajorTickPositions:function(){var X=this,Y=[];
X.traverseMajorTicksPositions(function(bd){Y.push(bd);
},{step:1,skip:0});
return Y;
},createTicks:function(be){var X=this,bm=[],bi=X.options,bd=X.lineBox(),bh=bi.labels.mirror,bf=bi.majorTicks,bg=bi.minorTicks,bl={vertical:bi.vertical},bk,Y;
function bj(bo,bn){bl.tickX=bh?bd.x2:bd.x2-bn.size;
bl.tickY=bh?bd.y1-bn.size:bd.y1;
bl.position=bo;
be.append(z(bl,bn));
}if(bf.visible){X.traverseMajorTicksPositions(bj,bf);
}if(bg.visible){X.traverseMinorTicksPositions(bj,bg);
}return bm;
},createGridLines:function(X){var Y=this,bk=Y.options,bd=X.options.line.visible,bh=bk.majorGridLines,bj=bk.minorGridLines,bn=bk.vertical,bf=X.lineBox(),bg={lineStart:bf[bn?"x1":"y1"],lineEnd:bf[bn?"x2":"y2"],vertical:bn},bl,bi=[];
var be=this.gridLinesVisual();
function bm(bp,bo){if(!ae(bp,bi)){bg.position=bp;
be.append(y(bg,bo));
bi.push(bp);
}}if(bh.visible){Y.traverseMajorTicksPositions(bm,bh);
}if(bj.visible){Y.traverseMinorTicksPositions(bm,bj);
}return be.children;
},traverseMajorTicksPositions:function(Y,bk){var X=this,bd=X._lineOptions(),be=bd.lineStart,bj=bd.step,bg=X.logMin,bf=X.logMax,bi,bh;
for(bi=au.ceil(bg)+bk.skip;
bi<=bf;
bi+=bk.step){bh=aQ(be+bj*(bi-bg),J);
Y(bh,bk);
}},traverseMinorTicksPositions:function(bd,bs){var X=this,bo=X.options,bf=X._lineOptions(),bg=bf.lineStart,bh=bf.step,Y=bo.majorUnit,bj=X.logMin,bi=X.logMax,br=au.floor(bj),bk=bo.max,bl=bo.min,bn=bo.minorUnit,bq,bt,bp,bm;
for(bq=br;
bq<bi;
bq++){bm=X._minorIntervalOptions(bq);
for(var be=bs.skip;
be<bn;
be+=bs.step){bt=bm.value+be*bm.minorStep;
if(bt>bk){break;
}if(bt>=bl){bp=aQ(bg+bh*(aq(bt,Y)-bj),J);
bd(bp,bs);
}}}},createAxisLabel:function(Y,bd){var X=this,be=X.options,bf=au.ceil(X.logMin+Y),bh=Math.pow(be.majorUnit,bf),bg=X.axisLabelText(bh,null,bd);
return new i(bh,bg,Y,null,bd);
},shouldRenderNote:function(Y){var X=this.range();
return X.min<=Y&&Y<=X.max;
},_throwNegativeValuesError:function(){throw new Error("Non positive values cannot be used for a logarithmic axis");
},_initOptions:function(bj,bi,bh){var X=this,Y=G({},X.options,{min:bj,max:bi},bh),bg=Y.min,bf=Y.max,bd=Y.majorUnit,be;
if(Y.axisCrossingValue<=0){X._throwNegativeValuesError();
}if(!L(bh.max)){be=aQ(aq(bf,bd),J)%1;
if(bf<=0){bf=bd;
}else{if(be!==0&&(be<0.3||be>0.9)){bf=au.pow(bd,aq(bf,bd)+0.2);
}else{bf=au.pow(bd,au.ceil(aq(bf,bd)));
}}}else{if(bh.max<=0){X._throwNegativeValuesError();
}}if(!L(bh.min)){if(bg<=0){bg=bf<=1?au.pow(bd,-2):1;
}else{if(!bh.narrowRange){bg=au.pow(bd,au.floor(aq(bg,bd)));
}}}else{if(bh.min<=0){X._throwNegativeValuesError();
}}X.logMin=aQ(aq(bg,bd),J);
X.logMax=aQ(aq(bf,bd),J);
Y.max=bf;
Y.min=bg;
Y.minorUnit=bh.minorUnit||aQ(bd-1,J);
return Y;
},_minorIntervalOptions:function(bf){var X=this.options.majorUnit,bg=au.pow(X,bf),be=au.pow(X,bf+1),Y=be-bg,bd=Y/this.options.minorUnit;
return{value:bg,minorStep:bd};
},_lineOptions:function(){var X=this,bg=X.options,bh=bg.reverse,bl=bg.vertical,bk=bl?bb:ba,bd=X.lineBox(),Y=bl===bh?1:-1,bi=Y===1?1:2,be=bl?bd.height():bd.width(),bj=Y*(be/(X.logMax-X.logMin)),bf=bd[bk+bi];
return{step:bj,lineStart:bf,lineBox:bd};
}});
D.Gradients={glass:{type:ap,rotation:0,stops:[{offset:0,color:a8,opacity:0},{offset:0.25,color:a8,opacity:0.3},{offset:1,color:a8,opacity:0}]},sharpBevel:{type:aJ,stops:[{offset:0,color:a8,opacity:0.55},{offset:0.65,color:a8,opacity:0},{offset:0.95,color:a8,opacity:0.25}]},roundedBevel:{type:aJ,stops:[{offset:0.33,color:a8,opacity:0.06},{offset:0.83,color:a8,opacity:0.2},{offset:0.95,color:a8,opacity:0}]},roundedGlass:{type:aJ,supportVML:false,stops:[{offset:0,color:a8,opacity:0},{offset:0.5,color:a8,opacity:0.3},{offset:0.99,color:a8,opacity:0}]},sharpGlass:{type:aJ,supportVML:false,stops:[{offset:0,color:a8,opacity:0.2},{offset:0.15,color:a8,opacity:0.15},{offset:0.17,color:a8,opacity:0.35},{offset:0.85,color:a8,opacity:0.05},{offset:0.87,color:a8,opacity:0.15},{offset:0.99,color:a8,opacity:0}]}};
var Q={extend:function(X,Y){if(!X.exportVisual){throw new Error("Mixin target has no exportVisual method defined.");
}X.exportSVG=this.exportSVG;
X.exportImage=this.exportImage;
X.exportPDF=this.exportPDF;
if(!Y){X.svg=this.svg;
X.imageDataURL=this.imageDataURL;
}},exportSVG:function(X){return P.exportSVG(this.exportVisual(),X);
},exportImage:function(X){return P.exportImage(this.exportVisual(),X);
},exportPDF:function(X){return P.exportPDF(this.exportVisual(),X);
},svg:function(){if(P.svg.Surface){return P.svg._exportGroup(this.exportVisual());
}else{throw new Error("SVG Export failed. Unable to export instantiate kendo.drawing.svg.Surface");
}},imageDataURL:function(){if(!al.support.canvas){return null;
}if(P.canvas.Surface){var X=a("<div />").css({display:"none",width:this.element.width(),height:this.element.height()}).appendTo(document.body);
var bd=new P.canvas.Surface(X);
bd.draw(this.exportVisual());
var Y=bd._rootElement.toDataURL();
bd.destroy();
X.remove();
return Y;
}else{throw new Error("Image Export failed. Unable to export instantiate kendo.drawing.canvas.Surface");
}}};
function f(bd,Y){var X=aQ(Y-bd,J-1);
if(X===0){if(Y===0){return 0.1;
}X=au.abs(Y);
}var bf=au.pow(10,au.floor(au.log(X)/au.log(10))),be=aQ((X/bf),J),bg=1;
if(be<1.904762){bg=0.2;
}else{if(be<4.761904){bg=0.5;
}else{if(be<9.523809){bg=1;
}else{bg=2;
}}}return aQ(bf*bg,J);
}function W(bd){var X=[];
for(var Y in bd){X.push(Y+bd[Y]);
}return X.sort().join(" ");
}function aP(bf,bg,Y,bd,X){var be=X*M;
return new aI(Y+(bf-Y)*au.cos(be)+(bg-bd)*au.sin(be),bd-(bf-Y)*au.sin(be)+(bg-bd)*au.cos(be));
}function n(bj,bl){if(bj.x1==bl.x1&&bj.y1==bl.y1&&bj.x2==bl.x2&&bj.y2==bl.y2){return bl;
}var X=au.min(bj.x1,bl.x1),Y=au.max(bj.x1,bl.x1),bd=au.min(bj.x2,bl.x2),be=au.max(bj.x2,bl.x2),bf=au.min(bj.y1,bl.y1),bg=au.max(bj.y1,bl.y1),bh=au.min(bj.y2,bl.y2),bi=au.max(bj.y2,bl.y2),bk=[];
bk[0]=m(Y,bf,bd,bg);
bk[1]=m(X,bg,Y,bh);
bk[2]=m(bd,bg,be,bh);
bk[3]=m(Y,bh,bd,bi);
if(bj.x1==X&&bj.y1==bf||bl.x1==X&&bl.y1==bf){bk[4]=m(X,bf,Y,bg);
bk[5]=m(bd,bh,be,bi);
}else{bk[4]=m(bd,bf,be,bg);
bk[5]=m(X,bh,Y,bi);
}return a.grep(bk,function(bm){return bm.height()>0&&bm.width()>0;
})[0];
}function ae(Y,X){return af(Y,X)!=-1;
}function p(Y,X){return aQ(au.ceil(Y/X)*X,J);
}function T(Y,X){return aQ(au.floor(Y/X)*X,J);
}function aQ(bd,Y){var X=au.pow(10,Y||0);
return au.round(bd*X)/X;
}function aq(Y,X){return au.log(Y)/au.log(X);
}function aL(bf,X,Y){var bd=aQ(au.abs(bf%X),J),be=X*(1-Y);
return bd===0||bd>be;
}function aj(bd,X,Y){return aQ(bd+(X-bd)*Y,w);
}function aG(X,Y){return X-Y;
}function a4(X,be,bf){var Y,bd=X.length;
for(Y=0;
Y<bd;
Y++){X[Y][be]=bf;
}}function e(X,Y){if(X.match(U)){return al.format.apply(this,arguments);
}return al.toString(Y,X);
}function N(X){var Y=X.parentNode;
while(Y&&Y.parentNode){Y=Y.parentNode;
}return Y!==O;
}function v(X,Y){return -X.x*Y.y+X.y*Y.x<0;
}function E(X,Y){if(X&&Y){return X.getTime()-Y.getTime();
}return 0;
}var C=function(X){this.closed=X;
};
C.prototype=C.fn={WEIGHT:0.333,EXTREMUM_ALLOWED_DEVIATION:0.01,process:function(bf){var bq=this,X=bq.closed,bn=bf.slice(0),bj=bn.length,bo=[],bk,bl,bm,Y,bh,bi,bp;
if(bj>2){bq.removeDuplicates(0,bn);
bj=bn.length;
}if(bj<2||(bj==2&&bn[0].equals(bn[1]))){return bo;
}bk=bn[0];
bl=bn[1];
bm=bn[2];
bo.push(new P.Segment(bk));
while(bk.equals(bn[bj-1])){X=true;
bn.pop();
bj--;
}if(bj==2){bp=bq.tangent(bk,bl,ba,bb);
am(bo).controlOut(bq.firstControlPoint(bp,bk,bl,ba,bb));
bo.push(new P.Segment(bl,bq.secondControlPoint(bp,bk,bl,ba,bb)));
return bo;
}if(X){bk=bn[bj-1];
bl=bn[0];
bm=bn[1];
Y=bq.controlPoints(bk,bl,bm);
bh=Y[1];
bi=Y[0];
}else{bp=bq.tangent(bk,bl,ba,bb);
bh=bq.firstControlPoint(bp,bk,bl,ba,bb);
}var bd=bh;
for(var bg=0;
bg<=bj-3;
bg++){bq.removeDuplicates(bg,bn);
bj=bn.length;
if(bg+3<=bj){bk=bn[bg];
bl=bn[bg+1];
bm=bn[bg+2];
Y=bq.controlPoints(bk,bl,bm);
am(bo).controlOut(bd);
bd=Y[1];
var be=Y[0];
bo.push(new P.Segment(bl,be));
}}if(X){bk=bn[bj-2];
bl=bn[bj-1];
bm=bn[0];
Y=bq.controlPoints(bk,bl,bm);
am(bo).controlOut(bd);
bo.push(new P.Segment(bl,Y[0]));
am(bo).controlOut(Y[1]);
bo.push(new P.Segment(bm,bi));
}else{bp=bq.tangent(bl,bm,ba,bb);
am(bo).controlOut(bd);
bo.push(new P.Segment(bm,bq.secondControlPoint(bp,bl,bm,ba,bb)));
}return bo;
},removeDuplicates:function(X,Y){while(Y[X].equals(Y[X+1])||Y[X+1].equals(Y[X+2])){Y.splice(X+1,1);
}},invertAxis:function(bd,be,bf){var bg=this,X,bh,Y=false;
if(bd.x===be.x){Y=true;
}else{if(be.x===bf.x){if((be.y<bf.y&&bd.y<=be.y)||(bf.y<be.y&&be.y<=bd.y)){Y=true;
}}else{X=bg.lineFunction(bd,be);
bh=bg.calculateFunction(X,bf.x);
if(!(bd.y<=be.y&&bf.y<=bh)&&!(be.y<=bd.y&&bf.y>=bh)){Y=true;
}}}return Y;
},isLine:function(Y,bd,be){var bf=this,X=bf.lineFunction(Y,bd),bg=bf.calculateFunction(X,be.x);
return(Y.x==bd.x&&bd.x==be.x)||aQ(bg,1)===aQ(be.y,1);
},lineFunction:function(bd,be){var X=(be.y-bd.y)/(be.x-bd.x),Y=bd.y-X*bd.x;
return[Y,X];
},controlPoints:function(bf,bg,bh){var bn=this,bo=ba,bp=bb,bi=false,bl=false,bm,bd,Y,bj,X=bn.EXTREMUM_ALLOWED_DEVIATION;
if(bn.isLine(bf,bg,bh)){bm=bn.tangent(bf,bg,ba,bb);
}else{bd={x:bn.isMonotonicByField(bf,bg,bh,ba),y:bn.isMonotonicByField(bf,bg,bh,bb)};
if(bd.x&&bd.y){bm=bn.tangent(bf,bh,ba,bb);
bi=true;
}else{if(bn.invertAxis(bf,bg,bh)){bo=bb;
bp=ba;
}if(bd[bo]){bm=0;
}else{var bk;
if((bh[bp]<bf[bp]&&bf[bp]<=bg[bp])||(bf[bp]<bh[bp]&&bg[bp]<=bf[bp])){bk=bn.sign((bh[bp]-bf[bp])*(bg[bo]-bf[bo]));
}else{bk=-bn.sign((bh[bo]-bf[bo])*(bg[bp]-bf[bp]));
}bm=X*bk;
bl=true;
}}}bj=bn.secondControlPoint(bm,bf,bg,bo,bp);
if(bl){var be=bo;
bo=bp;
bp=be;
}Y=bn.firstControlPoint(bm,bg,bh,bo,bp);
if(bi){bn.restrictControlPoint(bf,bg,bj,bm);
bn.restrictControlPoint(bg,bh,Y,bm);
}return[bj,Y];
},sign:function(X){return X<=0?-1:1;
},restrictControlPoint:function(Y,bd,X,be){if(Y.y<bd.y){if(bd.y<X.y){X.x=Y.x+(bd.y-Y.y)/be;
X.y=bd.y;
}else{if(X.y<Y.y){X.x=bd.x-(bd.y-Y.y)/be;
X.y=Y.y;
}}}else{if(X.y<bd.y){X.x=Y.x-(Y.y-bd.y)/be;
X.y=bd.y;
}else{if(Y.y<X.y){X.x=bd.x+(Y.y-bd.y)/be;
X.y=Y.y;
}}}},tangent:function(X,Y,bf,bh){var bd,be=Y[bf]-X[bf],bg=Y[bh]-X[bh];
if(be===0){bd=0;
}else{bd=bg/be;
}return bd;
},isMonotonicByField:function(Y,bd,be,X){return(be[X]>bd[X]&&bd[X]>Y[X])||(be[X]<bd[X]&&bd[X]<Y[X]);
},firstControlPoint:function(bg,Y,bd,bi,bj){var bh=this,be=Y[bi],bf=bd[bi],X=(bf-be)*bh.WEIGHT;
return bh.point(be+X,Y[bj]+X*bg,bi,bj);
},secondControlPoint:function(bg,Y,bd,bi,bj){var bh=this,be=Y[bi],bf=bd[bi],X=(bf-be)*bh.WEIGHT;
return bh.point(bf-X,bd[bj]-X*bg,bi,bj);
},point:function(bd,bf,Y,be){var X=new V.Point();
X[Y]=bd;
X[be]=bf;
return X;
},calculateFunction:function(X,bf){var be=0,bd=X.length;
for(var Y=0;
Y<bd;
Y++){be+=Math.pow(bf,Y)*X[Y];
}return be;
}};
function az(Y){var bd=Y.originalEvent,X=0;
if(bd.wheelDelta){X=-bd.wheelDelta/120;
X=X>0?au.ceil(X):au.floor(X);
}if(bd.detail){X=aQ(bd.detail/3);
}return X;
}function F(Y){if(!Y||!Y.indexOf||Y.indexOf("&")<0){return Y;
}else{var X=F._element;
X.innerHTML=Y;
return X.textContent||X.innerText;
}}function ak(Y,X){return Y>=X.min&&Y<=X.max;
}function b(Y){if(!al.support.vml){for(var X=0;
X<Y.segments.length;
X++){Y.segments[X].anchor().round(0).translate(0.5,0.5);
}}return Y;
}function ah(bg){var bd=this,bh=bg.stops,bi=((bg.innerRadius/bg.radius)*100),be,bf=bh.length,X,Y=[];
for(be=0;
be<bf;
be++){X=G({},bh[be]);
X.offset=(X.offset*(100-bi)+bi)/100;
Y.push(X);
}return Y;
}function aK(bd){var Y=bd.origin;
var X=bd.bottomRight();
return new m(Y.x,Y.y,X.x,X.y);
}F._element=document.createElement("span");
G(al.dataviz,{AXIS_LABEL_CLICK:h,COORD_PRECISION:w,DEFAULT_PRECISION:J,DEFAULT_WIDTH:K,DEFAULT_HEIGHT:I,DEFAULT_FONT:H,INITIAL_ANIMATION_DURATION:ag,NOTE_CLICK:aD,NOTE_HOVER:aE,CLIP:u,Axis:g,AxisLabel:i,Box2D:m,BoxElement:o,ChartElement:r,CurveProcessor:C,ExportMixin:Q,FloatElement:S,LogarithmicAxis:ar,Note:aC,NumericAxis:aF,Point2D:aI,Ring:aN,RootElement:aO,Sector:aR,ShapeBuilder:aS,ShapeElement:aT,Text:aW,TextBox:aX,Title:aY,alignPathToPixel:b,autoFormat:e,autoMajorUnit:f,boxDiff:n,dateComparer:E,decodeEntities:F,getSpacing:Z,inArray:ae,interpolateValue:aj,mwDelta:az,rectToBox:aK,rotatePoint:aP,round:aQ,ceil:p,floor:T});
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
