'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddTask

    '''<summary>
    '''LBtitoloSuperiore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtitoloSuperiore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MLVaddProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVaddProject As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWaddProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWaddProject As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''WZRaddTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WZRaddTask As Global.System.Web.UI.WebControls.Wizard

    '''<summary>
    '''WSTselectParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WSTselectParent As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''LBselectParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBselectParent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLselectTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLselectTask As Global.Comunita_OnLine.UC_SelectTask

    '''<summary>
    '''WSTtaskDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WSTtaskDetail As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''LBtaskProperties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtaskProperties As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBtaskPropertiesChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtaskPropertiesChild As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DIVtaskDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIVtaskDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CTRLdetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLdetail As Global.Comunita_OnLine.UC_TaskDetail

    '''<summary>
    '''WSTmanageResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WSTmanageResource As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''LBmanageResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBmanageResource As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBmangeResourceParentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBmangeResourceParentName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBmanagerError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBmanagerError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLmanageChildrenResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmanageChildrenResource As Global.Comunita_OnLine.UC_ReallocateResourcesOnNodes

    '''<summary>
    '''WSTaddUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WSTaddUser As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''LBaddUsersTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBaddUsersTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBaddUserTaskName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBaddUserTaskName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLaddVirtualAssignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLaddVirtualAssignment As Global.Comunita_OnLine.UC_AddVirtualTaskAssignments

    '''<summary>
    '''WSTresume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WSTresume As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''LBresume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBresume As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBresumeParentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBresumeParentName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLresumeChildrenResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLresumeChildrenResource As Global.Comunita_OnLine.UC_ReallocateResourcesOnNodes

    '''<summary>
    '''VIWerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWerror As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''HYPreturnToTaskList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPreturnToTaskList As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LBerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBerror As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AjaxPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AjaxPortal)
        End Get
    End Property
End Class
