'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReallocateUser

    '''<summary>
    '''LBtitoloSuperiore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtitoloSuperiore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MLVreallocateUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVreallocateUsers As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWstepWizard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWstepWizard As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''WZRreallocateUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WZRreallocateUsers As Global.System.Web.UI.WebControls.Wizard

    '''<summary>
    '''WSTselectResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WSTselectResource As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''LBselectResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBselectResource As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBtaskNameSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtaskNameSelect As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLresourceEditable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLresourceEditable As Global.Comunita_OnLine.UC_ReallocateResourcesOnNodes

    '''<summary>
    '''WSTconfirmResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WSTconfirmResource As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''LBresumeUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBresumeUsers As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBtaskNameResume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtaskNameResume As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLresourceResume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLresourceResume As Global.Comunita_OnLine.UC_ReallocateResourcesOnNodes

    '''<summary>
    '''VIWerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWerror As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''HYPreturnToTaskList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPreturnToTaskList As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LBerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBerror As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AjaxPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AjaxPortal)
        End Get
    End Property
End Class
