'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_AddVirtualTaskAssignments

    '''<summary>
    '''LBrole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrole As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLrole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLrole As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DIV1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CTRLsearchUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLsearchUser As Global.Comunita_OnLine.UC_SearchUserByCommunities
End Class
