'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_ExternalTopBar

    '''<summary>
    '''LTwelcome_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTwelcome_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''HYPuser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPuser As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LTmanage_m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmanage_m As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''HYPuserSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPuserSettings As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPlist As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPadd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPadd As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPlanguageCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPlanguageCurrent As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''RPTlanguages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTlanguages As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''LKBlogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKBlogout As Global.System.Web.UI.WebControls.LinkButton
End Class
