'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_PasswordChange

    '''<summary>
    '''LBoldPwd_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBoldPwd_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TXBoldPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBoldPwd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBnewPwd_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBnewPwd_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TXBnewPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBnewPwd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBrenewPwd_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrenewPwd_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TXBrenewPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBrenewPwd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CTRLactionMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLactionMsg As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''LNBchangePwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBchangePwd As Global.System.Web.UI.WebControls.LinkButton
End Class
