'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_TicketUpload

    '''<summary>
    '''DVdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTdescription As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CTRLinternalUploader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLinternalUploader As Global.Comunita_OnLine.UC_ModuleInternalFileMultipleUploader

    '''<summary>
    '''CTRLrepositoryUploader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLrepositoryUploader As Global.Comunita_OnLine.UC_AjaxMultipleFileUploader

    '''<summary>
    '''CTRLlinkItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLlinkItems As Global.Comunita_OnLine.UC_OtherModuleLinkRepositoryItems

    '''<summary>
    '''DVcommands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVcommands As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BTNaddAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNaddAttachment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LNBcloseAttachmentWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBcloseAttachmentWindow As Global.System.Web.UI.WebControls.LinkButton
End Class
