'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_TicketUserSettings

    '''<summary>
    '''LTmyNotification_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmyNotification_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTmyNotificationDesc_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmyNotificationDesc_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTtitleUser_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtitleUser_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''UCswitchUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCswitchUser As Global.Comunita_OnLine.UC_Switch

    '''<summary>
    '''LTusrDeacription_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTusrDeacription_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBusrMailSet_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBusrMailSet_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UCmailUsrSett control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCmailUsrSett As Global.Comunita_OnLine.UC_MailSettingsNew

    '''<summary>
    '''LKBgetUsrGlobalSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKBgetUsrGlobalSettings As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LKBsaveSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKBsaveSettings As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''DVextraInfoUsr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVextraInfoUsr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBextraInfoUsr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBextraInfoUsr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PNLmanager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PNLmanager As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LTtitleManager_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtitleManager_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''UCswitchMan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCswitchMan As Global.Comunita_OnLine.UC_Switch

    '''<summary>
    '''LTmanDescription_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmanDescription_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBmanMailSet_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBmanMailSet_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UCmailManSett control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCmailManSett As Global.Comunita_OnLine.UC_MailSettingsNew

    '''<summary>
    '''LKBgetManGlobalSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKBgetManGlobalSettings As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''DVextraInfoMan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVextraInfoMan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBextraInfoMan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBextraInfoMan As Global.System.Web.UI.WebControls.Label
End Class
