'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditSkin1

    '''<summary>
    '''LTtitle_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtitle_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''HYPbackUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPbackUrl As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LKBexportPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKBexportPDF As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LKBexportRTF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKBexportRTF As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HYPlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPlist As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPGoToAdvance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPGoToAdvance As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPGoToSimple control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPGoToSimple As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LKBundo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKBundo As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LKBsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKBsave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''CTRLsteps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLsteps As Global.Comunita_OnLine.UC_EditSteps

    '''<summary>
    '''MLVtemplatePart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVtemplatePart As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VWskin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VWskin As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''UCskin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCskin As Global.Comunita_OnLine.UC_SkinSelector

    '''<summary>
    '''VWproperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VWproperty As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''UCsettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCsettings As Global.Comunita_OnLine.UC_EditSettings

    '''<summary>
    '''VWbody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VWbody As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''UCbody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCbody As Global.Comunita_OnLine.UC_EditBody

    '''<summary>
    '''VWsignatures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VWsignatures As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''UCsignatures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCsignatures As Global.Comunita_OnLine.UC_EditSignatures

    '''<summary>
    '''HDNdownloadTokenValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDNdownloadTokenValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AjaxPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AjaxPortal)
        End Get
    End Property
End Class
