'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.832
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''helpDomandaNumerica classe.
'''</summary>
'''<remarks>
'''Classe generata automaticamente.
'''</remarks>
Partial Public Class helpDomandaNumerica

    '''<summary>
    '''Head1 controllo.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per apportare la modifica spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''aspnetForm controllo.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per apportare la modifica spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents aspnetForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''LBTitolo controllo.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per apportare la modifica spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents LBTitolo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTesto1 controllo.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per apportare la modifica spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents LBTesto1 As Global.System.Web.UI.WebControls.Label
End Class
