'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditTile

    '''<summary>
    '''CTRLbaseHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLbaseHeader As Global.Comunita_OnLine.UC_BaseTileHeader

    '''<summary>
    '''CTRLheader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLheader As Global.Comunita_OnLine.UC_AsyncUploadHeader

    '''<summary>
    '''LNBenableTileTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBenableTileTop As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBdisableTileTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBdisableTileTop As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBvirtualDeleteTileTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBvirtualDeleteTileTop As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBvirtualUndeleteTileTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBvirtualUndeleteTileTop As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBsaveTileTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBsaveTileTop As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HYPgoTo_TileListTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPgoTo_TileListTop As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''CTRLmessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmessages As Global.Comunita_OnLine.UC_ActionMessages

    '''<summary>
    '''CTRLedit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLedit As Global.Comunita_OnLine.UC_EditTile

    '''<summary>
    '''DVmenuBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVmenuBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LNBenableTileBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBenableTileBottom As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBdisableTileBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBdisableTileBottom As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBvirtualDeleteTileBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBvirtualDeleteTileBottom As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBvirtualUndeleteTileBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBvirtualUndeleteTileBottom As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LNBsaveTileBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNBsaveTileBottom As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HYPgoTo_TileListBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPgoTo_TileListBottom As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AjaxPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AjaxPortal)
        End Get
    End Property
End Class
