'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_GestioneListe

    '''<summary>
    '''PNLContenitore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PNLContenitore As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LBL_NewLista_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_NewLista_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TXB_NewListaName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXB_NewListaName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTN_AddNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_AddNew As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GRVListe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GRVListe As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BTN_Inserisci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Inserisci As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LBLMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLMessage As Global.System.Web.UI.WebControls.Label
End Class
