'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_ModuleAttachmentJqueryHeaderCommands

    '''<summary>
    '''LTdialogTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTdialogTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTdialogTitleTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTdialogTitleTemplate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CTRLheader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLheader As Global.Comunita_OnLine.UC_ModuleInternalUploaderHeader

    '''<summary>
    '''LTaddurltomoduleitemWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTaddurltomoduleitemWindow As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTaddurltomoduleitemandcommunityWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTaddurltomoduleitemandcommunityWindow As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTuploadtomoduleitemandcommunityWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTuploadtomoduleitemandcommunityWindow As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTcloseScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcloseScripts As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CTRLscripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLscripts As Global.Comunita_OnLine.UC_OpenDialogHeaderScripts

    '''<summary>
    '''LTaddurltomoduleitem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTaddurltomoduleitem As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTaddurltomoduleitemandcommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTaddurltomoduleitemandcommunity As Global.System.Web.UI.WebControls.Literal
End Class
